doc/architecture.rst
Found this by refering to the documentation for https://github.com/owncloud/core/issues/13005
cc @RealRancor
=> fix link and add slash as bad character

src/gui/CMakeLists.txt, src/gui/application.cpp, src/gui/application.h, src/gui/folderman.cpp, src/gui/folderman.h, src/gui/sharedialog.cpp, src/gui/sharedialog.h, src/gui/sharedialog.ui, src/gui/socketapi.cpp, src/gui/socketapi.h
Initial pull request for filebrowser intergration sharing.
A lot of stuff still needs to be tested and verified.
=> Filebrowser integration

src/gui/owncloudgui.cpp
=> Fix for issue #2703

src/gui/owncloudgui.cpp
=> Resepct theming when no syncs are configure

src/gui/sharedialog.cpp, src/gui/sharedialog.h
Some code cleanup. Moved some stuff that we did everytime for each OcsShareJob into OcsShareJob. For example setting of the json format.
=> Sharedialog fixes

src/gui/sharedialog.cpp, src/gui/sharedialog.h
Since owncloud 8 is out this is the PR for thumbnails as described in #2726
=> Sharedialog: retrive thumbnail from server for shares

src/gui/sharedialog.cpp, src/gui/sharedialog.ui
Added button to explicitly set the password (makes is clear the user has to do
something!). Patch for #2812
=> Added push button to sharedialog to set password

src/gui/folderwizard.cpp, src/gui/logbrowser.cpp, src/gui/owncloudsetupwizard.cpp, src/gui/sharedialog.cpp, src/gui/sharedialog.ui, src/libsync/owncloudpropagator.cpp, src/libsync/propagateremotedelete.cpp, src/libsync/propagateremotemkdir.cpp, src/libsync/propagateremotemove.cpp, src/libsync/propagatorjobs.cpp, src/libsync/syncengine.cpp
Also remove trailingspaces which are not visible by translators on Transifex.
=> some typos, grammar and sentence fixes

cmake/modules/MacOSXBundleInfo.plist.in
Otherwise the copyright meta-info of the application shows 2014
=> Bump Copyright year to 2015

shell_integration/nautilus/syncstate.py
The print statement needs brackets.
=> fix python3 syntax errors

doc/autoupdate.rst, doc/installing.rst
Re https://github.com/owncloud/enterprise/issues/600, context menu not visible without Windows restart
=> add note to restart windows after update

doc/conffile.rst
see https://github.com/owncloud/core/issues/6543
=> Clarify the remotePollInterval variable 

src/libsync/utility_win.cpp
=> Use dynamic library loading for detecting the correct path for links

doc/architecture.rst
https://doc.owncloud.org/desktop/1.8/architecture.html#ignored-files
=> Fix wrong word in doc

translations/.tx/config, translations/client_nb_NO.ts
This is to add Norwegian translation of the desktop client.
=> Adding Norwegian translation to Client

doc/troubleshooting.rst
1. Bullet was missing
2. Wrong indents
=> Fix syntax issues in troubleshooting docs

doc/troubleshooting.rst
=> Backport #3279 to 1.8

doc/troubleshooting.rst
=> Backport #3279 to 1.7

doc/architecture.rst, doc/troubleshooting.rst
=> Backport #3004 and #2978 to 1.7

doc/architecture.rst, doc/troubleshooting.rst
=> Backport #3004 and #2978 to 1.8

README.md
=> Add CI job state

src/gui/accountsettings.cpp, src/gui/accountsettings.h, src/gui/accountstate.cpp, src/gui/accountstate.h, src/gui/quotainfo.cpp, src/gui/quotainfo.h
=> QuotaInfo: only request the quota when the UI is visible

src/gui/application.cpp, src/gui/application.h
Fixes https://github.com/owncloud/client/issues/2702
Now the behavious is similar to how 'ls' works.
@MorrisJobke @guruz what you think?
=> clear error hint went wrongly use command line options

src/gui/folder.cpp, src/gui/generalsettings.cpp, src/gui/generalsettings.ui, src/libsync/configfile.cpp, src/libsync/configfile.h
=> Confirm feature: Add an option for it

src/gui/updater/ocupdater.cpp
=> Win32: Do not silent-update if the application is already up-to-date

src/gui/application.cpp, src/gui/application.h, src/gui/generalsettings.cpp, src/gui/updater/ocupdater.cpp, src/gui/updater/ocupdater.h, src/gui/updater/updater.cpp, src/gui/updater/updater.h, src/libsync/configfile.cpp, src/libsync/configfile.h
This pull requests enables that the update checker to check regularly for available updates, reading the frequency value from the config file.
@danimo please.
=> Regular update check

shell_integration/nautilus/syncstate.py
Fixes #2775 for the nautilus plugin, plus another bugfix for files with colons in it.
=> Fix nautilus plugin

src/gui/ignorelisteditor.ui
Issue raised by user 'kant' in Transifex on the 1st of August.
=> Minor typo: Ingored -> Ignored

src/libsync/utility_win.cpp
Reverts owncloud/client#2920 because of a missing CLA
=> Revert "Use dynamic library loading for detecting the correct path for links #2920"

src/libsync/owncloudtheme.cpp
No need to have an additional redirect
=> Use HTTPS links

src/gui/folderstatusmodel.cpp
fixes the unicode issue #3753
I don't know much CPP and Qt but after some google research I found this http://wiki.qt.io/Strings_and_encodings_in_Qt
it does mention trUtf8() that has done the trick for me on Linux with Gnome 3.16.
Haven't tested it on other systems
=> fix unicode issue #3753

src/gui/folderman.cpp, src/gui/folderstatusdelegate.cpp
Proposed wording for issue
https://github.com/owncloud/client/issues/3757
=> Coin the term 'folder sync connection'

CMakeLists.txt, CONTRIBUTING.md, OWNCLOUD.cmake, cmake/modules/DefineCompilerFlags.cmake, cmake/modules/NSIS.template.in, cmake/modules/UseDoxygen.cmake, cmake/scripts/generate_lib_file, csync/ChangeLog, csync/INSTALL, csync/README
Just some random stuff I noticed while looking at how this beast is put
together.
=> Minor build etc typos

src/cmd/CMakeLists.txt, src/cmd/cmd.cpp, src/crashreporter/CMakeLists.txt
=> cmd and crashreporter minor typos

test/scripts/README.rst, test/testfilesystem.h, test/testplan.txt
Note: I am not sure that nostoredpasswd even exists in the current
version. Maybe the stuff in testplan.txt is old and not relevant anyway?
=> Minor typos in client test section

src/cmd/cmd.cpp, src/gui/socketapi.cpp, src/gui/wizard/owncloudsetuppage.cpp, src/libsync/account.cpp, src/libsync/account.h, src/libsync/discoveryphase.cpp, src/libsync/owncloudpropagator.cpp, src/libsync/owncloudpropagator.h, src/libsync/theme.cpp, src/libsync/theme.h
@ogoffart and @danimo could you please review this?
=> Branding option: Alternative WebDAV URL

shell_integration/MacOSX/OwnCloudFinder/ContentManager.m, shell_integration/MacOSX/OwnCloudFinder/RequestManager.m, shell_integration/MacOSX/OwnCloudInjector/OwnCloudInjector.m, shell_integration/MacOSX/common/SyncClientProxy.m, shell_integration/dolphin/README, shell_integration/dolphin_kf5/README, shell_integration/nautilus/syncstate.py, shell_integration/windows/OCOverlays/OverlayConstants.h
all in comments or other places that have no effect on the user.
=> Minor shell integration typos

doc/visualtour.rst
Noticed while looking at commit https://github.com/owncloud/client/commit/5f660bf080a57172bab091007e0be0146b4ec918
Note: This whole doc needs review and updating of text and screen shots for 2.0 multi-account client.
=> Adjust log out description

doc/architecture.rst
=> Backport #3916 to 2.0

src/gui/CMakeLists.txt, src/gui/accountmanager.h, src/gui/application.cpp, src/gui/creds/shibbolethcredentials.cpp, src/gui/creds/shibbolethcredentials.h, src/gui/folder.cpp, src/gui/folderman.cpp, src/gui/folderman.h, src/gui/folderstatusdelegate.cpp, src/gui/folderstatusmodel.cpp, src/gui/folderstatusmodel.h, src/gui/folderwatcher.cpp, src/gui/folderwatcher.h, src/gui/logbrowser.cpp, src/gui/owncloudgui.cpp, src/gui/owncloudsetupwizard.cpp, src/gui/proxyauthhandler.h, src/gui/quotainfo.cpp, src/gui/quotainfo.h, src/gui/selectivesyncdialog.cpp, src/gui/selectivesyncdialog.h, src/gui/settingsdialog.cpp, src/gui/settingsdialogmac.cpp, src/gui/sharedialog.cpp, src/gui/socketapi.cpp, src/gui/updater/ocupdater.cpp, src/gui/updater/ocupdater.h, src/gui/wizard/owncloudadvancedsetuppage.cpp
This is a resubmit of what was in https://github.com/owncloud/client/pull/3812
Now it seems work on master has started again, and that old PR was against 2.0 and had a bunch of merge things in it anyway.
This is a cleaner single commit for master.
=> GUI comment and message typos for master

doc/navigating.rst
This menu in 2.0.* now has 4 options.
The small screenshot needs updating also. @carlaschroder it is probably best if you take a new screen shot from whatever client version you have been using for screen shots. That way they will all have a consistent look.
=> Update "..." menu documentation for 2.0

doc/navigating.rst
Reverts owncloud/client#3931
PR references testing 2.0.2 version
=> Revert "Update "..." menu documentation for 2.0"

src/gui/folder.cpp
=> Folder: Do not create the sync folder if it does not exist #3692

src/cmd/cmd.cpp
=> Make returncode 0 for --version and --help

csync/src/csync_update.c, src/libsync/discoveryphase.cpp, translations/client_zh_TW.ts
@ogoffart and @ckamm what do you think about this?
=> Fix hidden detection

src/libsync/capabilities.cpp, src/libsync/capabilities.h, src/libsync/owncloudpropagator.cpp, src/libsync/ownsql.cpp, src/libsync/ownsql.h, src/libsync/propagatedownload.cpp, src/libsync/propagatedownload.h, src/libsync/propagateupload.cpp, src/libsync/propagateupload.h, src/libsync/propagatorjobs.h, src/libsync/syncengine.cpp, src/libsync/syncfileitem.h, src/libsync/syncjournaldb.cpp, src/libsync/syncjournaldb.h, src/libsync/syncjournalfilerecord.cpp, src/libsync/syncjournalfilerecord.h, src/libsync/transmissionchecksumvalidator.cpp, src/libsync/transmissionchecksumvalidator.h, test/testsyncjournaldb.h, test/testtranschecksumvalidator.h
Store the checksums in the db during up and downloads.
=> Checksums work for #3735

ChangeLog
Hopefully the last place I need to submit this again :)
=> ChangeLog typos that reverted in merge from 2.0

shell_integration/nautilus/syncstate.py
- Adds an *"Initializing owncloud-client-nautilus extension"* message, as any other Nautilus extension have one (Dropbox, nautilus-terminal, etc).
- Few µ-typos on printed message.
- Improved style slightly.
=> Reviewing, improved style, and a initializing message

doc/autoupdate.rst, doc/installing.rst, doc/introduction.rst
A few small tweaks. Please to merge.
@danimo 
@dragotin
=> some doc fixes & updates

doc/autoupdate.rst
=> Backport #4052 to 2.0

src/gui/shareusergroupwidget.cpp, src/gui/shareusergroupwidget.h, src/gui/shareusergroupwidget.ui, src/gui/sharewidget.ui
As described in https://github.com/owncloud/client/issues/3737#issuecomment-156036279
=> [Sharedialog] Fix UI stuff

src/gui/accountstate.h
Improve this to say what I think it means.
=> tagLastSuccessfullETagRequest comment wording

src/gui/shareusergroupwidget.cpp
=> [Sharing] Files should not have create permissions

src/gui/sharelinkwidget.cpp, src/gui/sharelinkwidget.h
Fixes https://github.com/owncloud/client/issues/4227
=> [Sharing] Do not allow users to uset the password if it is enforced

doc/navigating.rst
Please review @danimo @ogoffart @dragotin 
Reference: https://github.com/owncloud/core/issues/7009
=> add note re mtime syncing

cmake/modules/MacOSXBundleInfo.plist.in
My yearly contribution to the client :wink:
=> Bump year to 2016

doc/building.rst
Please review @danimo @dragotin
=> improve client build instructions

src/gui/sharedialog.cpp, src/gui/socketapi.cpp, src/libsync/theme.cpp, src/libsync/theme.h
Fixes #4325 
To test I just modified the settings in theme.cpp.
Is there anyway to test this?
CC: @Dianafg76 @rperezb @MTRichards
=> Add theming options control sharing operations

src/gui/owncloudgui.cpp, src/gui/sharedialog.cpp, src/gui/sharedialog.h
Fixes #4185 
And probably also #4484
@Dianafg76 please verify this
=> Disable sharing dialog if account state is not connected

src/gui/shareusergroupwidget.cpp
See https://github.com/owncloud/core/issues/22122#issuecomment-185637344
Fixes #4481 
This patch makes sure we have the same behaviour on the client as on the server with regards to federated shares.
CC: @Dianafg76
=> Do not send reshare permissions when creating a federated share

src/gui/accountmanager.cpp, src/gui/accountmanager.h, src/gui/accountstate.cpp, src/gui/accountstate.h, src/gui/folder.cpp, src/gui/folder.h, src/gui/folderman.cpp, src/gui/folderstatusmodel.cpp, src/gui/owncloudgui.cpp, src/gui/owncloudgui.h, src/libsync/account.cpp, src/libsync/account.h, test/stub.cpp
It's a patch for #3829 plus some improvements to how accounts are written to and read from settings.
=> Account pausing #3829

src/gui/shareusergroupwidget.cpp
Fixes #3737
The rest of the sharing stuff I consider new enhancements and/or bugfixes.
CC: @guruz @ckamm @dragotin
=> Add spinner to show we are creating the share

src/gui/folder.cpp
=> Add account name to warning message boxes in Folder

src/libsync/checksums.cpp, src/libsync/checksums.h, src/libsync/propagatedownload.cpp, src/libsync/propagatedownload.h, src/libsync/propagateupload.cpp
=> Enable content checksums #4375

cmake/modules/NSIS.template.in
=> NSIS: Force uninstall before install #4543

src/gui/CMakeLists.txt, src/gui/accountsettings.cpp, src/gui/folderstatusdelegate.cpp, src/gui/folderstatusmodel.cpp, src/gui/owncloudgui.cpp, src/gui/tooltipupdater.cpp, src/gui/tooltipupdater.h, src/libsync/utility.cpp, src/libsync/utility.h, test/testutility.h
(note: says "Synchronizing with local folder" instead now)
For #3403 and #4562. @jancborchardt already said this was a step in the right direction.
@dragotin @ogoffart @jturcotte review?
=> Progress layout adjustments

shell_integration/MacOSX/CMakeLists.txt, shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/FinderSync.m, shell_integration/MacOSX/OwnCloudFinderSync/OwnCloudFinderSync.xcodeproj/project.pbxproj
This works for both plain ownCloud and themed clients.
=> OS X: Use app icon for "Share with ..." Finder menu #4472

src/gui/folder.cpp, src/gui/folder.h, src/libsync/progressdispatcher.cpp, src/libsync/syncfileitem.h
This pull request shows a tray message if conflicts happened. fixes #3222
=> Bubble up conflicts

src/gui/activitywidget.cpp, src/gui/activitywidget.h, src/gui/protocolwidget.cpp, src/gui/protocolwidget.h
This pull request adds the number of not synced items to the "not synced" tab
=> ProtocolWidget: Show number of non synced files in tab label.

src/gui/folderwatcher_win.cpp, src/gui/folderwatcher_win.h
This fixes crashes on sync folder removal on windows for me. See #4620.
=> Graceful termination of folderwatcher_win #4620

src/libsync/owncloudpropagator.cpp, src/libsync/propagateremotemove.cpp, src/libsync/propagatorjobs.cpp, src/libsync/syncengine.cpp, src/libsync/syncjournaldb.cpp, src/libsync/syncjournaldb.h
More fixes to handle the case that a database connect was lost because of hibernation and removeable disks.
@ogoffart pls review.
=> Close journal fix

shell_integration/dolphin/CMakeLists.txt
=> Dolphin Plugin: rename the files to the branded name #4669

shell_integration/nautilus/syncstate.py, src/gui/folderman.cpp, src/gui/socketapi.cpp
@jturcotte @ckamm 
I think this will remove a bit of performance problems.
=> Less socket api updates

csync/src/csync_update.c, src/libsync/discoveryphase.cpp
Also related https://github.com/owncloud/core/issues/23468
=> Discovery: Be more explicit about files with unknown size #4573

src/3rdparty/qtokenizer/qtokenizer.h, src/3rdparty/qtokenizer/qtokenizer.pro, src/3rdparty/qtokenizer/test/test.pro, src/3rdparty/qtokenizer/test/tst_qtokenizer.cpp, src/cmd/CMakeLists.txt, src/cmd/netrcparser.cpp, src/cmd/netrcparser.h, test/CMakeLists.txt, test/testnetrcparser.cpp
=> Use QTokenizer to properly parse netrc

translations/.tx/config
The new project on transifex - https://www.transifex.com/owncloud-org/owncloud/client-desktop/
=> Adding new resource for the desktop.ini file

src/gui/sharedialog.cpp
Apparently I did not push the correct final version to https://github.com/owncloud/client/pull/4687 :speak_no_evil: 
Here it is...
=> Only 1 : between namespace and property

doc/navigating.rst
@owncloud/desktop-developers please check if that is common understanding.
@MTRichards does that reflect your understanding of the overlay icons 
@carlaschroder draft input for the docs, please do whatever you want with it ;-)
=> Doc: Draft overlay icons

src/gui/main.cpp
=> Workaround ubuntu 16.04 systemtray bug (#4693)

csync/src/vio/csync_vio_local_win.c
shouldn't we relax the attributes a bit?
=> vio for windows: Use more graceful create file params.

shell_integration/windows/OCUtil/RemotePathChecker.cpp, src/gui/socketapi.cpp
=> Disambiguate socket API pathes on Windows with user name

shell_integration/windows/OCUtil/RemotePathChecker.cpp, src/gui/socketapi.cpp
=> Revert "Disambiguate socket API pathes on Windows with user name"

src/gui/creds/shibbolethcredentials.cpp
For https://github.com/owncloud/enterprise/issues/1034
=> Shibboleth: Load username from config for UI

src/gui/shareusergroupwidget.cpp, src/gui/shareusergroupwidget.h, src/gui/shareusergroupwidget.ui
Fixed #4740
When searching for sharees we should display a loading spinner.
Easy one
CC: @ckamm @guruz @dragotin
=> Add spinner during sharee search

shell_integration/nautilus/syncstate.py
=> Fix nautilus and nemo plugin branding strings.

src/gui/folderstatusmodel.cpp, src/gui/folderwizard.cpp, src/gui/selectivesyncdialog.cpp, src/libsync/utility.cpp, src/libsync/utility.h
Still need to test building against Qt4.
=> Use natural sorting for filenames if available #4859

src/libsync/propagateupload.cpp
=> Remember to upload files that are locked during a sync run

src/libsync/syncfilestatustracker.cpp
normalization to NFC is still required. Mac OS API will not take care of that
by default.
Resolves #4884
=> Undo regression caused by 727e73d

src/gui/updater/ocupdater.cpp
=> Fix memleak in updater

src/gui/folderwatcher_mac.cpp
I got syncs triggered for even opening a file by double clicking it in Finder
and having launched Preview.app (e.g. for JPEG files).
=> OS X filewatcher fix

doc/building.rst
ref: https://github.com/owncloud/client/pull/4851
=> [Doc] fix win install instructions: build path and docker image name

src/gui/accountsettings.cpp
@ckamm, @guruz 
There was a syntax error. Please check if this is the intended semantics now.
=> Update accountsettings.cpp fixing the tray-patch

Jenkinsfile
backport of https://github.com/owncloud/client/pull/5091
=> [2.2] Jenkinsfile: Add win32 build (#5091)

shell_integration/dolphin/ownclouddolphinpluginhelper.cpp
do not hardcode owncloud here.
This should fix #5165
=> Dolphin Plugin: Use the Application name for the socket path

src/cmd/cmd.cpp
=> add server capabilities to owncloudcmd

src/libsync/discoveryphase.cpp
From https://github.com/owncloud/core/pull/26145
@PVince81 @mmattel @butonic @ogoffart
=> 503: Also parse other server error message

src/libsync/syncjournaldb.cpp
=> SyncJournalDB: check the return value of the prepare statements in checkConnect

doc/building.rst
@carlaschroder please check. 
I had a user here who was struggling with the description because he did not have the source repos enabled on Ubuntu.
=> Add a note that the source repositories need to be enabled.

src/libsync/owncloudpropagator.cpp, src/libsync/propagateupload.h
Fix for https://github.com/owncloud/client/issues/4986#issuecomment-227071801
This is before we have bundling at some point.
=> Propagator: Also upload more in parallel

src/libsync/configfile.cpp
=> OS X: Use monochrome tray icon by default

src/gui/CMakeLists.txt, src/gui/manifest-mingw.rc, src/gui/owncloud.exe.manifest-mingw
Added RT_MANIFEST resource on Windows to make the application UAC aware. This disables UAC virtualization which caused problems on my machine.
=> Add manifest file on Windows to make the application UAC aware.

src/libsync/owncloudpropagator.cpp
=> libsync: Clear the upload info after several retries

doc/building.rst
Reported in the doc repo owncloud/documentation#1618
This version as suggested by @jturcotte
=> Fix Mac PATH command

src/libsync/progressdispatcher.cpp
=> Increase initial bandwidth estimates #4428 #5390

src/libsync/syncjournaldb.cpp
=> DB: Also migrate -shm and -wal to new name #3764 #5045

sync-exclude.lst
Avoid to upload the "System Volume Information" folder
=> Ignoring "System Volume Information"

src/libsync/owncloudpropagator.cpp, src/libsync/owncloudpropagator.h, src/libsync/propagatedownload.cpp, src/libsync/propagateremotedelete.cpp, src/libsync/propagateremotemkdir.cpp, src/libsync/propagateremotemove.cpp, src/libsync/propagateupload.cpp, src/libsync/propagateupload.h, src/libsync/propagateuploadng.cpp, src/libsync/propagateuploadv1.cpp, src/libsync/propagatorjobs.cpp
=> Remove PropagatorJob::_propagator use and pointer

src/libsync/syncengine.cpp
=> Sync Engine: Specify what chars are not syncable in the error message

src/gui/folder.cpp, src/gui/owncloudgui.cpp
Part of code originally by @SamuAlfageme
=> Message Boxes: Force to be more on top #5503

src/gui/sslbutton.cpp
Regression since 7bfe0613827aa7cee93a77ccbedab9b07ea9ca78
Issue: #5573
=> SslButton: Remove additional ')'

src/gui/activitylistmodel.cpp
Backtrace from the crash reporter:
Crash: EXCEPTION_ACCESS_VIOLATION_READ at 0x401
File "moc_activitylistmo_M5OEXJ7XGJYTWT.cpp", line 92, in OCC::ActivityListModel::qt_static_metacall
File "qobject.cpp", line 3730, in QMetaObject::activate
File "moc_networkjobs_7AMNCW4BBANVRK.cpp", line 1342, in OCC::JsonApiJob::jsonReceived
File "networkjobs.cpp", line 714, in OCC::JsonApiJob::finished
File "abstractnetworkjob.cpp", line 207, in OCC::AbstractNetworkJob::slotFinished
File "moc_abstractnetwor_PFI2TXGQHRE33H.cpp", line 98, in OCC::AbstractNetworkJob::qt_static_metacall
File "qobject.cpp", line 3730, in QMetaObject::activate
File "moc_qnetworkreply.cpp", line 367, in QNetworkReply::finished
File "qnetworkreplyhttpimpl.cpp", line 2100, in QNetworkReplyHttpImplPrivate::finished
File …
=> ActivityListModel: fix possible crash in slotActivitiesReceived

src/gui/application.cpp
* Add git revision, if available
* Add SSL runtime/compiletime version
* Add compiletime Qt version
=> Add more versions to --version #5592

src/gui/creds/httpcredentialsgui.cpp, src/gui/sharedialog.cpp, src/gui/sharemanager.cpp, src/gui/shareusergroupwidget.cpp, src/gui/socketapi.cpp, src/libsync/account.cpp, src/libsync/account.h, src/libsync/propagatedownload.cpp, src/libsync/propagateuploadv1.cpp, src/libsync/syncengine.cpp
See also owncloud/core#27360
Create Account::makeServerVersion() along the way, to avoid
version literals like 0x0A0000.
=> HttpCreds: Update app passwords url #5605

doc/CMakeLists.txt
remove doc-man target in doc/CMakeLists.txt https://github.com/owncloud/client/issues/2153
=> doc/CMakeLists.txt no more doc-man

src/gui/accountstate.cpp, src/libsync/propagatedownload.cpp
A few crashes from the crash reporter.
See the commit message for details
=> Fix crashes

src/libsync/propagateuploadng.cpp
For https://github.com/owncloud/core/issues/26988
=> Chunking NG: Also send OC-Total-Length on MOVE

src/cmd/cmd.cpp
=> owncloudcmd: return code depend on sync result

src/gui/accountsettings.cpp, src/gui/accountsettings.h
As suggested in #5666
The first commit simplifies related code first.
=> Add a "force re-scanning" key sequence

src/libsync/ownsql.cpp, src/libsync/utility.h
=> SqlDatabase: Ask freeSpace for directory, fix for Windows

src/libsync/syncengine.cpp
=> Better words for the error message when one cannot create the database.

src/gui/accountstate.cpp, src/gui/creds/shibbolethcredentials.cpp, src/libsync/connectionvalidator.cpp, src/libsync/connectionvalidator.h, src/libsync/creds/abstractcredentials.cpp, src/libsync/creds/abstractcredentials.h, src/libsync/creds/dummycredentials.cpp, src/libsync/creds/httpcredentials.cpp, src/libsync/creds/tokencredentials.cpp
And as a side effect: don't ask for user password when we can't
connect to the server in the first place.
I've gone through a lot of test cases, but still review carefully please.
=> Credentials: Simplify credential flow #5728

src/gui/sharedialog.cpp
@SamuAlfageme: Could you test whether the layout problems you observed on Win and OSX are gone?
=> Sharing layout

src/gui/sharedialog.cpp, src/gui/sharelinkwidget.cpp
=> Share link dialog tweaks

src/gui/CMakeLists.txt, src/gui/creds/httpcredentialsgui.cpp, src/gui/creds/httpcredentialsgui.h, src/gui/creds/oauth.cpp, src/gui/creds/oauth.h, src/gui/owncloudsetupwizard.cpp, src/gui/wizard/owncloudoauthcredspage.cpp, src/gui/wizard/owncloudoauthcredspage.h, src/gui/wizard/owncloudsetuppage.cpp, src/gui/wizard/owncloudwizard.cpp, src/gui/wizard/owncloudwizard.h, src/gui/wizard/owncloudwizardcommon.h, src/libsync/creds/httpcredentials.cpp, src/libsync/creds/httpcredentials.h, src/libsync/theme.cpp, src/libsync/theme.h
When the OAuth2 app (https://github.com/owncloud/oauth2) is enabled,
We will open a browser and perform the OAuth2 authentication
Issue: #4798 and https://github.com/owncloud/platform/issues/17
=> Authentication with OAuth2

src/gui/accountsettings.cpp, src/gui/owncloudgui.cpp
=> AccountSettings: Triggering log in re-ask about previously rejected vertificates #5819

src/gui/creds/oauth.cpp
Requires https://github.com/owncloud/oauth2/pull/45
This commit moves the reply after we got the token reply from
the server, that allows to reply with an error to the browser
if the login does not work.
=> OAuth: Redirects to the server in case of sucessfull login

src/gui/CMakeLists.txt, src/gui/elidedlabel.cpp, src/gui/elidedlabel.h, src/gui/folder.cpp, src/gui/folder.h, src/gui/folderstatusmodel.cpp, src/gui/issueswidget.cpp, src/gui/issueswidget.h, src/gui/issueswidget.ui, src/gui/owncloudgui.cpp, src/libsync/owncloudpropagator.cpp, src/libsync/owncloudpropagator.h, src/libsync/progressdispatcher.cpp, src/libsync/progressdispatcher.h, src/libsync/propagatedownload.cpp, src/libsync/propagateupload.cpp, src/libsync/propagateupload.h, src/libsync/propagateuploadng.cpp, src/libsync/propagateuploadv1.cpp, src/libsync/syncengine.cpp, src/libsync/syncengine.h, src/libsync/syncjournaldb.cpp, src/libsync/syncjournaldb.h, src/libsync/syncjournalfilerecord.cpp, src/libsync/syncjournalfilerecord.h
Various improvements to the issues tab and to local and remote insufficient storage errors.
=> Error handling improvements

admin/win/docker/Dockerfile
=> Broken URL fixed in Dockerfile

src/gui/accountsettings.cpp, src/gui/accountsettings.h, src/gui/accountstate.cpp, src/gui/accountstate.h, src/gui/application.cpp, src/gui/creds/httpcredentialsgui.cpp, src/gui/creds/httpcredentialsgui.h, src/gui/creds/oauth.cpp, src/gui/creds/oauth.h
When the browser is open, ad a link in the ui to re-open
the browser.
Issue #5893
=> OAuth2: Have a link to the browser in the owncloud UI

src/cmd/cmd.cpp
https://github.com/owncloud/client/issues/5692
=> Fix for issue number 5692

src/gui/creds/oauth.cpp
Issues: #5897, https://github.com/owncloud/oauth2/issues/48
To go with https://github.com/owncloud/oauth2/pull/60
=> OAuth: Add the user in the authorize call

src/libsync/discoveryphase.cpp, src/libsync/syncfilestatus.cpp, src/libsync/syncfilestatus.h, src/libsync/syncfilestatustracker.cpp, test/syncenginetestutils.h, test/testsyncfilestatustracker.cpp
This reverts commit efa7821dd28491ad0b93fec53be6d4ad0f94f19f.
This reverts the revert, but also add a check that the server version
is bigger than 10.0
Issue #4788
=> Revert "Revert "Discovery: consider also the "shared by me" as shared""

src/gui/accountsettings.cpp, src/gui/generalsettings.ui
=> Fix external storage nofification ui issues

src/gui/accountsettings.cpp, src/gui/owncloudsetupwizard.cpp
Not only in the account wizard.
=> Sync Folder: Add file manager favorite also in folder wizard #455

doc/faq.rst
### Relates To 
https://github.com/owncloud/documentation/issues/3354
=> Fix broken images in FAQ

doc/installing.rst
https://github.com/owncloud/documentation/issues/3354.
=> Fix link to download the ownCloud client

src/gui/creds/httpcredentialsgui.cpp, src/gui/owncloudsetupwizard.cpp, src/gui/owncloudsetupwizard.h, src/gui/wizard/owncloudoauthcredspage.cpp, src/gui/wizard/owncloudsetuppage.cpp, src/gui/wizard/owncloudsetuppage.h, src/gui/wizard/owncloudwizard.cpp, src/gui/wizard/owncloudwizard.h, src/gui/wizard/owncloudwizardcommon.h, src/libsync/creds/httpcredentials.cpp, src/libsync/creds/httpcredentials.h, src/libsync/networkjobs.cpp, src/libsync/networkjobs.h
* Move it to networkjobs
* Minor adjustments to its logic
* Fixes redirect handling for oauth/basic http auth check #6003
=> Use DetermineAuthTypeJob in HttpCredentials

src/gui/folder.cpp
Maybe more things were happening on the server?
See #4116
=> Folder: Check etag again after active sync #4116

test/syncenginetestutils.h
To help with finding space issues https://github.com/owncloud/enterprise/issues/2202
=> ChunkingNgTest: CI debuggability #6015

src/gui/creds/oauth.cpp
To reproduce, log in and click "authorize" on the browser, then close
the browser before the client has replied, (but after redirected to localhost,
i.e. when the client is asking the server for the token)
The problem is that socket can be destroyed so we don't need to answer on a
destroyed socket.
=> OAuth: Fix crash when closing the browser while identifying

src/common/utility.cpp, src/gui/syncrunfilelog.cpp, src/libsync/cookiejar.cpp, src/libsync/logger.cpp, src/libsync/owncloudpropagator.cpp, src/libsync/propagatedownload.cpp, src/libsync/propagateupload.cpp, src/libsync/syncengine.cpp, src/libsync/syncresult.cpp, test/mockserver/httpserver.cpp, test/syncenginetestutils.h, test/testsyncengine.cpp
QDateTime::currentDateTime is terribly slow.
=> Use QDateTime::currentDateTimeUtc instead of the non utc version

src/gui/creds/oauth.h, test/CMakeLists.txt, test/syncenginetestutils.h, test/testoauth.cpp
=> Test OAuth2

src/gui/accountsettings.cpp, src/gui/accountstate.cpp, src/gui/accountstate.h, src/gui/settingsdialog.cpp, src/gui/settingsdialog.h, src/libsync/account.cpp, src/libsync/account.h, src/libsync/connectionvalidator.cpp
refs https://github.com/owncloud/oauth2/issues/74#issuecomment-319914664
=> Use display-name from the ocs call in the settings dialog

src/libsync/propagatedownload.cpp, src/libsync/propagatorjobs.h, test/syncenginetestutils.h, test/testsyncengine.cpp
=> PropagateDownload: Read Content-md5 header

src/libsync/capabilities.cpp, src/libsync/capabilities.h, src/libsync/syncengine.cpp, test/testsyncengine.cpp
=> Sync: Add capability for invalid filename regexes

.github/release_template.md
Copied 3 items from https://github.com/owncloud/client/issues/5889
(more items needed to copy??)
=> Adding post-release checks to template

src/gui/sharedialog.cpp, src/gui/socketapi.cpp, src/libsync/account.cpp, src/libsync/account.h, src/libsync/connectionvalidator.cpp, src/libsync/connectionvalidator.h
=> Private link fixes

src/libsync/theme.cpp
=> Theme: Update the wizard size on high dpi screen

ChangeLog
Web equivalent PR: https://github.com/owncloud/owncloud.org/pull/1318
=> Changelog Updated with latest changes

src/gui/sharelinkwidget.cpp, src/gui/sharelinkwidget.h
Also add the "Delete" action to the "..." menu.
See  #6163
=> Share links: Confirm deletion explicitly

.github/release_template.md
this fixes https://github.com/owncloud/client/issues/5836
@SamuAlfageme plese review for possible automated test
@guruz please review for feasability
=> post release checks added

src/gui/creds/shibbolethcredentials.cpp
If the server support both Shibboleth and OAuth2, upgrades to OAuth2
Issue #6198
=> Shibboleth: Upgrade to OAuth2 When the server supports it

Jenkinsfile
Just to find out what's the problem on the CI
=> Attempt to fix Jenkins

src/libsync/owncloudpropagator.h
Sentry:
https://sentry.io/owncloud/desktop-win-and-mac/issues/427476987/
=> Fix potential crash in Composite job destruction

src/csync/csync_exclude.cpp
My benchmarks show no performance difference.
As suggested in the last PR.
=> Exclude regex: Use named captures

src/gui/issueswidget.cpp, src/gui/protocolwidget.cpp, src/gui/protocolwidget.h
=> Nicer protocol item accessors and correct sorting by size

shell_integration/dolphin/ownclouddolphinactionplugin.cpp, shell_integration/dolphin/ownclouddolphinpluginhelper.cpp, shell_integration/dolphin/ownclouddolphinpluginhelper.h, shell_integration/nautilus/syncstate.py, shell_integration/windows/OCContextMenu/OCClientInterface.cpp, shell_integration/windows/OCContextMenu/OCClientInterface.h, shell_integration/windows/OCContextMenu/OCContextMenu.cpp, shell_integration/windows/OCContextMenu/OCContextMenu.h, shell_integration/windows/OCUtil/StringUtil.h, src/gui/socketapi.cpp, src/gui/socketapi.h
By making it dynamic.
So far only the nautilus and dolphin shell extension have been ported
=> SocketAPI: Make it easier to add or remove item in the action menu

src/gui/folderman.cpp, src/gui/folderman.h, src/gui/folderstatusmodel.cpp, src/gui/owncloudgui.cpp, src/libsync/syncresult.h
=> Tray: Change icon for unresolved conflicts

src/cmd/cmd.cpp
https://github.com/owncloud/enterprise/issues/2391
=> owncloudcmd: Do not do the capability call when --nonshib is passed

ChangeLog, src/gui/settingsdialog.cpp, src/gui/settingsdialog.h, src/gui/settingsdialogmac.cpp, src/gui/settingsdialogmac.h
Analog to settingsdialog.cpp (which is for linux/windows)
=> Notifications bug fixes / improvements

src/libsync/propagatedownload.h, src/libsync/propagatedownloadzsync.cpp, test/syncenginetestutils.h, test/testzsync.cpp
=> Delta-sync GET-range bug fix and small test improvements

src/libsync/discoveryphase.cpp, src/libsync/discoveryphase.h
This is potentially too aggressive? What do you think @ogoffart?
See #6317
=> Discovery: Error if properties are missing

src/csync/csync.cpp, src/csync/csync_private.h, src/csync/csync_update.cpp, src/csync/vio/csync_vio.cpp, src/gui/folder.cpp, src/gui/folder.h, src/gui/folderstatusmodel.cpp, src/gui/issueswidget.cpp, src/gui/issueswidget.h, src/gui/owncloudgui.cpp, src/gui/protocolwidget.cpp, src/gui/protocolwidget.h, src/gui/syncrunfilelog.cpp, src/libsync/discoveryphase.cpp, src/libsync/progressdispatcher.cpp, src/libsync/progressdispatcher.h, src/libsync/syncengine.cpp, src/libsync/syncengine.h, src/libsync/syncresult.cpp, src/libsync/syncresult.h, test/testsyncengine.cpp
See #6226 
I still have to investigate some other errors that can be shown in the issues tab.
=> Make sure ignored and conflict files show up in the issues tab even with partial local discovery

appveyor.ini
=> Use Qt 5.10 on Windows

shell_integration/nautilus/syncstate.py
The problem was that plain encode()/decode() in python2 use ascii
encoding, not utf8.
See  #6393
=> Fix nautilus/nemo shell integration encoding issues

README.md
* Update list of maintainers
* Fix link to binary downloads
@jturcotte @dragotin @danimo @cryptomilk Let me know if you don't want to appear like this, and if you'd like your email addresses updated!
=> Update list of maintainers, add section for past maintainers

src/libsync/syncengine.cpp, src/libsync/syncengine.h, test/CMakeLists.txt, test/testblacklist.cpp
For #6411 and as a follow up to #6412
=> Add a unit test for blacklist behavior

src/common/syncjournaldb.h, src/common/syncjournalfilerecord.h, src/common/utility.cpp, test/testchunkingng.cpp, test/testexcludedfiles.cpp, test/testsyncconflict.cpp, test/testsyncmove.cpp
From "_conflict-user-yyyymmdd-hhmmss"
to   " (Conflict user yyyy-mm-dd hhmmss)"
See  #6365
=> Conflicts: Change tags to be more user friendly

src/gui/folder.cpp, src/gui/folder.h
=> Notify if an explicitly excluded folder is created

src/libsync/propagatecommonzsync.cpp
=> Deltasync: Use native API for opening files on Windows 

doc/conflicts.rst, doc/index.rst
I wrote some text that explains conflict files and how to resolve them. It's dense but hopefully understandable. Feel free to make lots of "a non-technical person wouldn't undestand that!" comments!
For #6396
=> Doc: Explaining conflict files and resolving them

shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/FinderSync.h, shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/FinderSync.m, shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/SyncClientProxy.h, shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/SyncClientProxy.m, src/gui/socketapi.cpp
@SamuAlfageme I've only tested this with my local building, but it should also be tested with a build from rotor. 
Sorry for the whitespace mess, XCode is doing that :-(
FYI @jturcotte
=> macOS: Implement new dynamic Finder menu items #6328

src/libsync/propagateuploadng.cpp, test/testchunkingng.cpp
=> Upload: Add more chunk resuming unit tests

src/gui/activitydata.h, src/gui/notificationwidget.cpp
=> Notifications: Also have clickable link #6236

test/syncenginetestutils.h, test/testzsync.cpp
Similar to the one for uploads, to test these corner cases more.
@ahmedammar
=> Deltasync: Add growth/shrink unittest for downloads

doc/installing.rst
into master, into 2.4.0 branch?
=> update supported linux platforms

src/gui/issueswidget.cpp, src/gui/issueswidget.h, src/gui/issueswidget.ui, src/libsync/theme.cpp, src/libsync/theme.h
The link url is themed.
For #6396
Only merge once we can check that the link will actually work. Currently it's a 404: https://doc.owncloud.org/desktop/2.5/conflicts.html
=> Issues: Show link to conflicts doc if there are some

src/gui/sharelinkwidget.cpp, src/gui/sharelinkwidget.h, src/gui/sharemanager.cpp
=> ShareLink: Preserve password when unrelated ui changes

src/gui/folderwizard.cpp, src/gui/wizard/owncloudadvancedsetuppage.ui, src/gui/wizard/owncloudwizard.cpp, src/libsync/syncengine.cpp
See code changes for concrete strings.
=> Rename "placeholder" feature

src/common/syncjournaldb.cpp
For #6049 
Needs cherry-pick to 2.4 after merge.
=> macOS: Don't use WAL for sqlite3 in /Volumes

src/gui/CMakeLists.txt, src/gui/generalsettings.cpp, src/gui/generalsettings.h, src/gui/generalsettings.ui, src/gui/updater/ocupdater.cpp, src/gui/updater/ocupdater.h, src/gui/updater/sparkleupdater.h, src/gui/updater/sparkleupdater_mac.mm, src/gui/updater/updater.cpp, src/gui/updater/updater.h, src/libsync/configfile.cpp, src/libsync/configfile.h
@guruz unfortunately there was a significant conflict in one of the patches and I need you to double-check it still works on osx...
=> Introduce a release channel selector in 2.4

man/CMakeLists.txt
=> Fix make doc-man in shadow build

src/csync/csync_reconcile.cpp, test/testsyncvirtualfiles.cpp
With thanks to @ogoffart for spotting the problem.
=> Virtual files: Only remove virtual file once on download

src/libsync/propagatedownload.cpp, test/testsyncvirtualfiles.cpp
Otherwise a interrupted or unsuccessful download would mean that the
download-intend was forgotten. The next sync would reestablish the
virtual file instead.
=> Virtual files: Wipe virtual after download completes, not before

src/common/syncjournaldb.cpp, src/common/syncjournaldb.h, src/gui/folder.cpp, src/gui/folder.h, src/gui/socketapi.cpp, test/testsyncvirtualfiles.cpp
=> Virtual Files: Allow to download a folder recursively from the socketAPI

src/gui/settingsdialog.cpp, src/gui/settingsdialogmac.cpp
(I don't know if mac needs also a similar change)
=> SettingsDialog: Show the page for the newly created account

src/gui/generalsettings.cpp
=> GeneralSettings: Hide update channel for other themes

src/gui/wizard/owncloudadvancedsetuppage.cpp, src/gui/wizard/owncloudadvancedsetuppage.ui, src/gui/wizard/owncloudwizardcommon.cpp
Another attempt at #6546
How about this?
=> Wizard errors in a scroll area 

src/gui/updater/ocupdater.cpp
=> MSI: Always with logfile #6609

src/gui/updater/ocupdater.cpp
=> OCUpdater: Set correct state on network error

appveyor.ini, appveyor.yml, test/testoauth.cpp
I will fix this later in a less fragile way finally ... for now I wanna check if AppVeyor still builds at all...
=> Use Qt 5.11 in Craft

doc/options.rst
https://github.com/owncloud/documentation/issues/3436
desktop client: Document --logdebug switch that outputs even more information in the log
=> added logdebug

src/gui/wizard/owncloudoauthcredspage.cpp
Relates to https://github.com/owncloud/enterprise/issues/2600
=> Wizard OAuth2 Page: add a context menu to copy the link

src/gui/application.cpp
But add a line of spaces to make sure it is wide enough otherwise the
default messagebox size is way too small.
Issue #6644
=> Help Text: wrap the text

src/gui/application.cpp
Found by @hurradieweltgehtunter
=> Settings: Fix rename issue on old macOS

src/common/filesystembase.cpp
=> Windows: Release handle/fd when file open fails 

mirall.desktop.in, src/gui/owncloud.xml.in
As reported in https://github.com/owncloud/client/issues/6717#issuecomment-413703567
=> Virtual Files Mime Type: use "vnd." prefix instead of "x-"

src/libsync/propagatedownload.cpp, test/testsyncvirtualfiles.cpp
Note: When the server mtime is modified, the mtime of the file is not updated
Issue #6727
=> Virtual Files: Set the mtime of the virtual file to that of the server

src/gui/activityitemdelegate.cpp, src/gui/activitywidget.cpp
=> Activity: Handle the fact that the username can contain a '@'

src/gui/accountsettings.cpp, src/gui/folderstatusdelegate.cpp, src/gui/folderstatusdelegate.h
=> Account Settings: the info text should not be clickable

src/common/syncjournaldb.cpp, src/common/syncjournalfilerecord.h, src/libsync/owncloudpropagator.cpp, src/libsync/propagatedownload.cpp, src/libsync/propagateupload.cpp, src/libsync/syncengine.cpp, test/testsyncconflict.cpp
To make clearer that this path is not unlikely to be outdated.
Amends #6709
=> Conflicts: Rename BasePath to InitialBasePath

src/gui/socketapi.cpp, src/gui/socketapi.h
=> Socket API: add an option to replace existing files with virtual files

src/gui/accountsettings.cpp, src/gui/folderstatusmodel.cpp
=> Virtual files: Don't show selective sync

src/libsync/discoveryphase.cpp
https://github.com/owncloud/client/issues/6724#issuecomment-417368475
=> Virtual files: don't check for new big folders

src/common/syncjournalfilerecord.cpp, src/common/syncjournalfilerecord.h, src/gui/owncloudgui.cpp, src/gui/protocolwidget.cpp, src/gui/socketapi.cpp, test/testsyncjournaldb.cpp
=> Private links: improve legacy fileid derivation

src/gui/accountsettings.cpp
=> AccountSettings: Force sync should wipe the blacklist

doc/faq.rst
like #6773, but for the correct branch :) @tboerger can you merge and deploy the docs?
=> Documented: unsupported server version warning message -> 2.5

src/csync/csync_reconcile.cpp, src/csync/csync_update.cpp, src/libsync/propagateremotemove.cpp, test/testsyncvirtualfiles.cpp
=> Virtual files: Renames propagate

src/gui/accountsettings.cpp, src/gui/folder.cpp, src/gui/folder.h
=> Account Settings: Add a context menu entry to enable or disable virtual files

src/cmd/cmd.cpp
=> owncloudcmd: Read the server version from the capabilities

src/libsync/propagateupload.h, src/libsync/propagateuploadng.cpp, src/libsync/propagateuploadv1.cpp
=> PropagateUpload: Fix UploadDevice leak

src/gui/generalsettings.cpp, src/gui/generalsettings.h, src/gui/generalsettings.ui, src/gui/owncloudgui.h, src/gui/settingsdialog.cpp, src/gui/settingsdialogmac.cpp, src/libsync/theme.cpp, src/libsync/theme.h
=> Settings: Bring back version and copyright

src/gui/sslbutton.cpp
Reported in https://github.com/nextcloud/desktop/issues/871
=> SSLButton: do not hardcode the background color

src/libsync/vfs/suffix/CMakeLists.txt
=> Fix installation of vfs suffix plugin

src/gui/main.cpp
=> Gui: do not show the settings when opening a virtual file

src/gui/application.cpp
=> Allow to open log window via command line to already running client

src/gui/accountsettings.cpp
from the selective sync context menu
Issue: #6471
=> AccountSettings: add an item to open the folder in the browser

src/common/syncjournaldb.cpp, src/common/syncjournaldb.h, src/gui/socketapi.cpp, src/gui/socketapi.h, test/testsyncjournaldb.cpp
Still way to go (submenu, icons, checked items etc) but already nicer. 
Depends on #6935 which should merge first.
For #6815
=> UI improvements for VFS directory and file pinning

ChangeLog, src/gui/owncloudsetupwizard.cpp, src/gui/wizard/owncloudsetuppage.cpp, src/gui/wizard/owncloudsetuppage.h
See #6911 
Please review carefully since it touches the wizard. I tested with my server, my server+ssl cert and demo.owncloud.com.
=> Wizard: Fix setting up accounts with ssl client certificates

src/libsync/discoveryphase.cpp, src/libsync/discoveryphase.h, src/libsync/syncengine.cpp
=> Discovery: Ensure selective sync lists are sorted

src/gui/accountsettings.cpp, src/gui/folder.cpp, src/gui/folder.h, src/gui/folderstatusmodel.cpp, src/gui/wizard/owncloudwizard.cpp, src/libsync/progressdispatcher.h, src/libsync/syncengine.cpp, src/libsync/syncengine.h
Depends on https://github.com/owncloud/client/pull/6954 which must merge first.
See #6936
=> Switch vfs state only when no sync is running / fix discovery aborts

src/gui/socketapi.cpp
Seeing "Currently available online only" for a currently hydrated file
was odd. It makes sense since current hydration status and pin state are
independent.
The new text will say something like "Currently available, but marked
online only" to better indicate that the file might be dehydrated later
since it wasn't pinned.
FYI @michaelstingl. (This will become easier for users once there are file icons; essentially there are three states: "pinned & hydrated", "unpinned & hydrated", "unpinned & dehydrated".)
=> vfs: Update pinning context menu to be less confusing

src/libsync/discovery.cpp, src/libsync/discoveryphase.cpp, src/libsync/discoveryphase.h, src/libsync/owncloudpropagator.cpp, src/libsync/owncloudpropagator.h, src/libsync/propagateremotemove.cpp, src/libsync/propagatorjobs.cpp, test/testsyncmove.cpp
Fix issue #6694 and some other move problems.
=> Fix a couple of issue with move of nested directories

src/common/syncjournaldb.cpp
Maybe a fix for @jnweiger's observation of present -wal/-shm files even though I couldn't reproduce it. #6881
Your code had a "must be done before synchonous mode is set" note - I couldn't see why, please check.
=> Db: Move drop-index to after pragmas are set 

src/gui/connectionvalidator.cpp, src/gui/creds/httpcredentialsgui.cpp, src/gui/creds/httpcredentialsgui.h, src/gui/owncloudsetupwizard.cpp, src/libsync/theme.cpp, src/libsync/theme.h
For https://github.com/owncloud/enterprise/issues/2951
=> Add a noPreFlight branding option

src/gui/folderman.cpp
=> Folder wizard: Fix infinite loop for bad paths

docs/Makefile
Referencing: [owncloud/docs#616](https://github.com/owncloud/docs/pull/616)
@tboerger @settermjd
=> fix shell used in makefile

docs/modules/ROOT/pages/building.adoc
[Rendered](https://github.com/owncloud/client/blob/windows-build-doc/docs/modules/ROOT/pages/building.adoc#windows-development-build-with-kde-craft)
=> Update windows build instructions

shell_integration/windows/OCContextMenu/OCContextMenu.cpp
Previously it'd handle all verbs as if they were our own.
For #7004, #7023
=> Windows: Fix context menu handling only own verbs

src/gui/accountmanager.cpp
=> AccountManager: load the cookies

docs/modules/ROOT/pages/automatic_updater.adoc
The location in windows FS was missing, so I added it.
=> location for owncloud.cfg added

src/gui/folder.cpp
There was a period of time between local discovery of a new folder and
the folder receiving a filesystem watcher. Any changes to its contents
during that time were missing, leading to misbehaviors.
For #7068
Note: I'm working on a nicer solution on the folderwatcher level, but that may be too large or not in time for 2.5.4.
=> FolderWatcher: Work around missing notifications on linux 

docs/modules/ROOT/pages/faq.adoc
=> Doc: Add faq entry for changing server url 

docs/modules/ROOT/pages/troubleshooting.adoc
This fixes https://github.com/owncloud/docs/issues/603 and also cleans up the file so that it renders correctly.
=> [#603] - Remove merge conflict markers in the troubleshooting appendix

docs/modules/ROOT/nav.adoc
added a reference to the document describing removing the remnants of the windows client
=> added removing the client

src/gui/folder.cpp, src/libsync/discovery.cpp, src/libsync/propagatedownload.cpp, test/testsyncvirtualfiles.cpp
=> Improve notification wording for hydrating vfs files

src/3rdparty/sqlite3/sqlite3.h
Mostly PRed to check compiles.
=> Sqlite: Update to 3.27.2

src/libsync/theme.cpp
For  #7137, see screenshot there
=> About: Add remark about vfs plugin that's in use

src/common/pinstate.h, src/common/syncjournaldb.cpp, src/common/syncjournaldb.h, src/common/vfs.cpp, src/common/vfs.h, src/gui/accountsettings.cpp, src/gui/guiutility.cpp, src/gui/guiutility.h, src/gui/socketapi.cpp, test/testsyncvirtualfiles.cpp
For #7143 .
Requires updates to winvfs plugin, so let me merge.
=> Improvements to vfs availability actions and text

admin/osx/macdeployqt.py, cmake/modules/NSIS.template.in
Can't test win32 build currently because of the other failures (CC @ckamm ) but let's assume it works..?
=> WebKit: Remove more from macOS and NSIS builds #6451

src/gui/application.cpp, src/gui/application.h, src/gui/logbrowser.cpp, src/gui/logbrowser.h, src/libsync/configfile.cpp, src/libsync/configfile.h, src/libsync/logger.cpp, src/libsync/logger.h
=> LogWindow: Option to disable automatic deletion

src/libsync/propagateuploadng.cpp, test/syncenginetestutils.h, test/testchunkingng.cpp
=> Chunked upload: Fix percent encoding in If header 

src/gui/creds/oauth.cpp, src/libsync/abstractnetworkjob.cpp, test/testoauth.cpp
This does not fix a bug, just was found while spotting a bug that was no bug.
For https://github.com/owncloud/enterprise/issues/2951
=> OAuth2: Better error logging

src/gui/addcertificatedialog.ui
A bug in QFormLayout causes the widget to be too small
Issue: #7184
=> Add Certificate dialog: fix layout

src/libsync/discovery.cpp, test/testremotediscovery.cpp
=> Discovery: Do not abort the sync in case of error 404 (or 500)

src/libsync/accessmanager.cpp
This Qt version fixes QTBUG-73947 and along with the resend workaround
for #7174 HTTP2 should work more reliably.
See  #7092
=> HTTP2: Enable if using Qt >=5.12.4

src/gui/sharelinkwidget.cpp, src/gui/sharelinkwidget.h
=> Sharing: Use the default expiration setting more

test/testsyncvirtualfiles.cpp
For #7279 and all the automatic test runners in the world.
=> Vfs: Make test pass with different suffix 

docs/modules/ROOT/pages/advanced_usage/environment_variables.adoc
@michaelstingl @HanaGemela @jnweiger @patrickjahns FYI!
=> Doc: List most environment variables

src/gui/folderwatcher.cpp
=> FolderWatcher: Disable test on OSX

src/libsync/propagatedownload.cpp, test/testsyncvirtualfiles.cpp
=> Vfs: Preserve pin state on hydration

src/gui/socketapi.cpp
=> Shares: Show creation dialog if silent creation fails

src/libsync/logger.cpp
=> LogDir: Compress last logfile on restart

src/gui/updater/ocupdater.cpp, src/gui/updater/ocupdater.h
Fixing smaller issues discovered during testing of #7217
=> Windows updater improvements

ChangeLog
=> Update 2.6.0 changelog

src/gui/ignorelisteditor.cpp
=> Ignore editor: Expand description

src/gui/updater/ocupdater.cpp
=> Updater: Improve logging for version comparison

src/libsync/vfs/CMakeLists.txt
This simplifies ci and local builds
=> CMake VFS: Enable us to provided vfs plugins from an external directory

CMakeLists.txt, cmake/modules/DefineCompilerFlags.cmake, config.h.in, src/gui/accountsettings.cpp, src/gui/accountsettings.h, src/gui/accountstate.h, src/gui/settingsdialog.cpp, src/gui/settingsdialog.h, src/gui/socketapi.cpp, src/gui/socketapi.h, src/gui/socketapi_p.h, src/gui/wizard/owncloudwizard.cpp, src/libsync/account.h
This is still WIP but by now it feels like it's worth a first round of reviewing.
The implementation of the command parser is still fragile (splitting by | is not exactly error-proof)
I'm not completely settled on the commands we want to support: this largely depends on feedback from @SamuAlfageme 
As most of it is hidden inside the `SocketApi` class, it should not affect any other part of the application with only one excception:
We just need to give a few widgets names to be able to find them, are you fine with that?
Also let me know if the code does not speak for itself enough and you need any explanation.
=> GUI Testing

src/libsync/owncloudpropagator.cpp, src/libsync/owncloudpropagator.h
To not starve the event loop.
(Idea by @ogoffart )
=> Propagator: Make sure we schedule only one job #7439

src/libsync/discovery.cpp, src/libsync/discovery.h, src/libsync/discoveryphase.h, src/libsync/owncloudpropagator.h, src/libsync/syncengine.cpp, test/syncenginetestutils.h, test/testpermissions.cpp, test/testsyncengine.cpp
=> Restore source when move to target fails

src/libsync/owncloudpropagator.cpp
Possible avoids "Not responding"
=> Propagator: Delay job execution a bit #7439

src/libsync/syncengine.cpp
I have verified that the 'Insert sorted' part is "instant".
Before the big sorting took quite some time -> https://github.com/owncloud/client/issues/7445#issuecomment-528816224
=> Reconcile: Sort already during discovery #7445

src/libsync/discovery.cpp, src/libsync/discovery.h, src/libsync/discoveryphase.cpp, src/libsync/discoveryphase.h, test/testsyncengine.cpp
Like in 2.5 and older (but this time with more threads instead of 1 background thread)
FYI @jnweiger
=> Discovery: List local directories from thread #7456 #7439

src/libsync/discovery.cpp, src/libsync/discoveryphase.h
Again thanks to @jnweiger for testing and stack traces.
=> Fix issues with threaded local discovery

src/gui/wizard/owncloudsetuppage.cpp
=> Ensure the url is complete before we validate it

OWNCLOUD.cmake, src/gui/issueswidget.cpp, src/gui/libcloudproviders/libcloudproviders.h, src/gui/protocolwidget.cpp, src/libsync/discovery.cpp
See commit messages for details
=> Fix a bunch of warnings.

docs/yarn.lock
This change should correct the repo's current security alerts
https://github.com/owncloud/client/network/alerts.
=> Update docs JavaScript dependencies

src/gui/settingsdialog.cpp
Issue: #7512
(I only tested on linux where it makes no difference. But that should solve the problem described in #7512)
=> Fix too low contrast when tab is selected

src/libsync/discovery.cpp, src/libsync/discoveryphase.cpp, src/libsync/syncfileitem.h, test/testpermissions.cpp
=> When moving is allowed but deleting is not, do not restore moved items

src/gui/owncloudsetupwizard.cpp, src/libsync/syncengine.cpp, src/libsync/syncengine.h
This set appears in the memory profiling.
=> Save a bit of memory by not keeping a set of all filename

src/gui/notificationwidget.ui
=> Notifications: Remove do-nothing "OK" button 

admin/osx/macdeployqt.py
=> [Mac] Fix deployment of vfs plugin on mac

src/gui/ocssharejob.cpp
=> Sharing: Ask reshares=true only where it makes sense

src/gui/sharelinkwidget.ui
Renaming
"Download / View / Upload"
to
"Download / View / Edit"
for #7357 and owncloud/enterprise#3464
=> Link shares: Rename permission

src/common/result.h, src/common/vfs.h, src/libsync/propagatedownload.cpp, src/libsync/syncengine.cpp, src/libsync/vfs/suffix/vfs_suffix.cpp, src/libsync/vfs/suffix/vfs_suffix.h, test/testsyncvirtualfiles.cpp
=> VFS: use absolute path for the plugins

src/gui/activityitemdelegate.cpp, src/gui/activitylistmodel.cpp, src/libsync/account.cpp
And some other fixup in the activity tab (relate to issue #6728)
=> Change account name

docs/modules/ROOT/pages/advanced_usage/options.adoc, src/gui/application.cpp, src/gui/application.h
=> Application: add an option to start with the settings visible

src/gui/owncloudgui.cpp
=> About Dialog: Don't put a too big icon

src/gui/connectionvalidator.cpp, src/gui/creds/httpcredentialsgui.cpp, src/gui/creds/httpcredentialsgui.h, src/gui/owncloudsetupwizard.cpp, src/libsync/theme.cpp, src/libsync/theme.h
This reverts commit c47af368328e0cbacde7d6abeda4b6f4291cc86f.
It turned out to be a dead end.
=> Revert "Add a noPreFlight branding option"

src/libsync/accessmanager.cpp
Related issue: https://github.com/owncloud/client/issues/7610
=> Disable http2 support for now

src/gui/owncloudgui.cpp, src/libsync/capabilities.cpp, src/libsync/capabilities.h
=> Fix "Default sharing permissions are ignored"

src/libsync/logger.cpp
This fixes the flodded sys log.
Fixes: #7453
=> [Logger] Correctly handle message priority

src/gui/owncloudgui.cpp
=> [GUI] Limit about dialog image size to 1/4 of the screen

src/common/utility.cpp
What do you think in general about this?
=> [Core] Include more information about the OS in the user agent

.drone.star
Depends on https://github.com/owncloud-ci/client/pull/2
=> [CI] Enable clazy

.drone.star
=> Fix changelog in master

changelog/unreleased/7709, changelog/unreleased/7710, src/gui/accountsettings.cpp, src/gui/folderwizard.cpp, src/gui/wizard/owncloudadvancedsetuppage.cpp, src/gui/wizard/owncloudwizard.cpp, src/gui/wizard/owncloudwizard.h
@HanaGemela did I fix the correct issue with the fix for #7710
=> Fix vfs wizard issues

changelog/unreleased/7247, changelog/unreleased/7313, changelog/unreleased/7700, changelog/unreleased/7709, changelog/unreleased/7710
=> Changelog: make sure the title is short enough

src/CMakeLists.txt
See https://github.com/owncloud/client/pull/7730
Ci will fail until we update our dependencies.
=> Reuqire qt 5.12

.drone.star, changelog/CHANGELOG.tmpl
This is a backport from master.
=> Run changelog ci on 2.6

src/gui/socketapi.cpp
The issue was introduced with https://github.com/owncloud/client/pull/5682
=> [SocketApi] Ensure listener still exists

changelog/unreleased/7774, src/gui/owncloudgui.cpp
=> [Gui] Implement raiseDialog on Windows

changelog/unreleased/7799, src/libsync/discoveryphase.cpp, test/syncenginetestutils.h, test/testsyncmove.cpp
=> Fix vfs sync crash

docs/modules/ROOT/pages/advanced_usage/environment_variables.adoc
@TheOneRing reading the source, can you confirm, that this should disable chunking?
=> document how to disable chunking

src/gui/socketapi.cpp
Load the plugin file before we load the plugin by its id.
=> Fix order of pluginkit commands and modernise

changelog/unreleased/7874, src/gui/accountsettings.cpp, src/gui/generalsettings.cpp, src/gui/wizard/owncloudwizard.cpp
=> Fix usage of QMessageBox

src/gui/accountsettings.cpp
https://github.com/owncloud/client/commit/150a5b4d06600d140ddf05383fb74cda6ae6e941#diff-29ad999698e087a443d0cd76499838cbL617 ...
=> Fix 150a5b4d06600d140ddf05383fb74cda6ae6e941

changelog/unreleased/7748, src/gui/accountsettings.cpp, src/gui/navigationpanehelper.cpp
=> VFS: Prevent duplicated navigation panel icon

src/gui/accountsettings.cpp, src/gui/accountsettings.ui, src/gui/creds/httpcredentialsgui.cpp, src/gui/creds/httpcredentialsgui.h, src/gui/wizard/owncloudoauthcredspage.cpp, src/gui/wizard/owncloudsetuppage.cpp, src/gui/wizard/owncloudwizard.cpp, src/libsync/creds/httpcredentials.h, src/libsync/creds/oauth.cpp, src/libsync/networkjobs.cpp, src/libsync/networkjobs.h, test/syncenginetestutils.h
=> OAuth: Fix reopening the browser from the account page

src/common/vfs.h, src/gui/folder.cpp
This allows us to decide on the presentation of the account
=> VFS: Tell the vfs plugin whether we have multiple accounts

changelog/unreleased/7920, src/gui/wizard/owncloudadvancedsetuppage.ui
Instead of using a fixed size grid layout use a dynamic layout.
Fixes: #7920
=> Wizard: Improve layout

changelog/unreleased/pr-7509
What changed https://github.com/owncloud/client/compare/v2.6.1...master
=> [WIP]Add previously missing changelog entries

src/gui/application.cpp
=> Gui: Don't try to display the wizard during shutdown

changelog/unreleased/7920, src/gui/accountsettings.ui, src/gui/activitywidget.ui, src/gui/addcertificatedialog.ui, src/gui/folderwizardsourcepage.ui, src/gui/folderwizardtargetpage.ui, src/gui/ignorelisteditor.ui, src/gui/issueswidget.ui, src/gui/networksettings.ui, src/gui/protocolwidget.ui, src/gui/proxyauthdialog.ui, src/gui/sharedialog.cpp, src/gui/sharedialog.ui, src/gui/sharelinkwidget.cpp, src/gui/sharelinkwidget.ui, src/gui/sslerrordialog.ui, src/gui/wizard/owncloudadvancedsetuppage.cpp, src/gui/wizard/owncloudadvancedsetuppage.ui, src/gui/wizard/owncloudconnectionmethoddialog.ui, src/gui/wizard/owncloudhttpcredspage.ui, src/gui/wizard/owncloudsetupnocredspage.ui
The first few changes include src changes so they should be reviewed with a bit more care.
I know that is impossible to review ui files
=> Get rid of gridlayout

src/gui/ignorelisteditor.cpp, src/gui/ignorelisteditor.ui
The lable had no size and no content in the designer so it got lost...
=> Fix layout after a9185fbc1d6db5742fa4d779f906c103fa0fcea3

src/libsync/propagateupload.cpp, src/libsync/propagateuploadtus.cpp
=> Fix progress report with tus

translations/client_cs.ts, translations/client_de.ts, translations/client_el.ts, translations/client_es.ts, translations/client_fa.ts, translations/client_fr.ts, translations/client_gl.ts, translations/client_it.ts, translations/client_ja.ts, translations/client_nb_NO.ts, translations/client_nl.ts, translations/client_pl.ts, translations/client_pt.ts, translations/client_pt_BR.ts, translations/client_ru.ts, translations/client_sl.ts, translations/client_sv.ts, translations/client_th.ts, translations/client_tr.ts, translations/client_zh_CN.ts
This reverts commit 14a897efe9d20db54ef303facf2aaf8d965b9908.
The translations job was running on two branches and thngs got messed up
=> Revert "[tx] updated client translations from transifex"

src/libsync/propagateuploadtus.cpp
=> Fix overflow of offset

test/testsyncengine.cpp
=> Skip test if Qt is build without support for plain ASCII

changelog/unreleased/8018, src/gui/wizard/owncloudadvancedsetuppage.cpp, src/gui/wizard/owncloudadvancedsetuppage.ui
=> Advances Wizard: Move choose what to sync to Sync everything

changelog/unreleased/8020, src/gui/generalsettings.cpp, src/gui/generalsettings.ui, src/gui/ignorelisteditor.cpp, src/gui/ignorelisteditor.h, src/gui/ignorelisteditor.ui
=> Move sync hidden files to advanced settings

src/gui/generalsettings.ui
=> Make update channel settings less prominent

src/gui/generalsettings.ui
=> Move version banner to the right

changelog/unreleased/8042, src/crashreporter/main.cpp
=> Crashreporter: Apply the same hdpi settings as to the main gui

changelog/unreleased/8066, src/libsync/propagateupload.cpp, src/libsync/propagateuploadtus.cpp
=> Fix missing permissions on db entry

changelog/unreleased/8051, src/gui/wizard/owncloudadvancedsetuppage.cpp, src/gui/wizard/owncloudsetuppage.cpp, src/gui/wizard/owncloudsetuppage.h, src/gui/wizard/owncloudwizard.cpp, src/gui/wizard/owncloudwizard.h
=> Fix back button on the advanced setup page

src/cmd/cmd.cpp, src/gui/connectionvalidator.cpp
https://github.com/owncloud/product/issues/181#issuecomment-689661673
=> No display name

src/libsync/httplogger.cpp
```
09-14 12:26:58:917 [ info sync.httplogger ]:	"0dff93f9-4678-4dc1-8fa6-5da32ecd390f: Response: GET 302 https://demo.owncloud.com/.well-known/openid-configuration Header: { Cache-Control: no-store, no-cache, must-revalidate, Content-Length: 0, Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *, Content-Type: text/html; charset=UTF-8, Date: Mon, 14 Sep 2020 10:27:01 GMT, Expires: Thu, 19 Nov 1981 08:52:00 GMT, Location: https://demo.owncloud.com/login, Pragma: no-cache, Referrer-Policy: strict-origin-when-cross-origin, Server: Apache, Set-Cookie: ocvvmpc7oy6p=hjm1j06k7ua2qvb2lj092343uf; path=/; secure; …
```
=> Log http status

src/libsync/propagateuploadtus.cpp
=> Include _remoteFolder in tus upload destination

src/cmd/cmd.cpp, src/csync/csync_exclude.cpp, test/csync/std_tests/check_std_c_jhash.c
Depends on https://github.com/owncloud/client/pull/8009
=> Remove usage of goto statements

src/common/vfs.cpp, src/gui/folderwizard.cpp
=> Use winvfs by default when adding folder sync connection

changelog/unreleased/8085, src/gui/activitydata.h, src/gui/activitywidget.cpp
=> Remove notifications when account was removed

docs/modules/ROOT/pages/advanced_usage/environment_variables.adoc, src/libsync/capabilities.cpp
=> Allow to disable tus uploads by setting OWNCLOUD_NO_TUS

.github/patch_release_template.md
…bringing template from internal handbook to public repo…
=> Update release templates

src/libsync/creds/oauth.cpp, src/libsync/theme.cpp, src/libsync/theme.h
=> Introduce opeIdConnectScopes bradnding option

src/gui/updater/updateinfo.cpp
https://github.com/owncloud/enterprise/issues/4227
=> Don't scare users with critical parser log messages

changelog/unreleased/8104, src/libsync/account.cpp
=> Account display name `servername (username) -> username@servername`

docs/modules/ROOT/pages/installing.adoc
=> Clarify System Requirements for Win & Mac

src/gui/generalsettings.ui
=> Gui: Mark non vfs settings explicitly

src/gui/accountmanager.cpp, src/gui/owncloudsetupwizard.cpp
=>     Ensure that we always have a display name ready when we register a folder

changelog/unreleased/7749, src/gui/CMakeLists.txt, src/gui/aboutdialog.cpp, src/gui/aboutdialog.h, src/gui/aboutdialog.ui, src/gui/generalsettings.cpp, src/gui/generalsettings.ui, src/gui/owncloudgui.cpp, src/libsync/theme.cpp, src/libsync/theme.h
See https://github.com/owncloud/enterprise/issues/3787#issuecomment-595759522
=> [Gui]Redesign AboutDialog and unify version info.

src/gui/owncloudgui.cpp, src/gui/owncloudgui.h
=> Raise the about dialog

src/gui/wizard/owncloudadvancedsetuppage.cpp
=> Fix vfs condition on advanced wizard page

src/gui/activityitemdelegate.cpp, src/gui/activityitemdelegate.h
=> Make activity delegate rtl aware

src/gui/application.cpp
Initialization of the plugins is needed to print their availability
=> Improve handling of cmd swtiches

src/gui/application.cpp
=> Always append a newline to the help text

changelog/unreleased/8131, src/common/vfs.cpp, src/common/vfs.h, src/gui/accountsettings.cpp, src/gui/folder.cpp, src/gui/folder.h, src/gui/folderstatusmodel.cpp, src/gui/folderwizard.cpp, src/gui/socketapi.cpp, src/gui/wizard/owncloudadvancedsetuppage.cpp
=> VirtualFiles: Ensure the target location supports vfs

changelog/unreleased/8170, src/gui/accountsettings.cpp, src/gui/accountsettings.h, src/gui/folder.cpp, src/gui/folder.h, src/gui/wizard/owncloudadvancedsetuppage.cpp, src/libsync/syncengine.cpp, src/libsync/syncengine.h, test/syncenginetestutils.h, test/testallfilesdeleted.cpp
Remaining blocking dialogs are the ssl dialog which turned out to be quite complicated...
And an error dialog during initialization...
=> Make dialogs non blocking

src/gui/logbrowser.ui
=> Fix logbrowser text not properly displayed

src/libsync/creds/httpcredentials.cpp
Fixes: #8188, Fixes: #8122, Fixes: #8186
=> Oauth: Reset login state on error

changelog/unreleased/8187, src/common/utility.h, src/common/utility_win.cpp, src/gui/folderman.cpp
=> Fix folder permission check on NTFS

changelog/unreleased/8169, src/gui/activitylistmodel.cpp, src/gui/connectionvalidator.cpp, src/gui/connectionvalidator.h, src/gui/settingsdialog.cpp, src/gui/shareusergroupwidget.cpp, src/gui/shareusergroupwidget.h, src/libsync/account.cpp, src/libsync/account.h, src/libsync/networkjobs.cpp, src/libsync/networkjobs.h, test/testfolderman.cpp
We should probably wait for 2.7.1 and also add a changelog entry.
=> display avatar in activity

docs/modules/ROOT/pages/building.adoc
tested, but zsh is giving me and error
checked and `-` is missing
=> fixing parameter typo

src/libsync/theme.cpp
Depends on https://github.com/owncloud/ocis/pull/788
=> Set the default oidc promt to 'select_account consent'

translations/Makefile
c.f. https://github.com/transifex/transifex-client/issues/233
=> Force pull transifex translations to avoid problems with timestamps.

changelog/unreleased/8229, src/gui/folder.cpp, src/gui/folderman.cpp
The issue was introduced in https://github.com/owncloud/client/issues/7779 https://github.com/owncloud/client/pull/7969
=> Fix usePlaceholders migration

changelog/unreleased/8258, src/gui/generalsettings.cpp, src/gui/generalsettings.h
=> Bugfix: Update "Sync hidden files" button

docs/modules/ROOT/pages/advanced_usage/environment_variables.adoc
Please also check for other new variables that should go here.
=> document QT_LOGGING_RULES

src/gui/accountstate.cpp, src/gui/accountstate.h, src/gui/folder.cpp, src/gui/folder.h, src/libsync/abstractnetworkjob.cpp, src/libsync/discovery.h, src/libsync/discoveryphase.cpp, src/libsync/discoveryphase.h, src/libsync/networkjobs.cpp, src/libsync/networkjobs.h, src/libsync/syncengine.cpp, src/libsync/syncengine.h, test/syncenginetestutils.cpp, test/syncenginetestutils.h, test/testasyncop.cpp
not when it was processed by the client, to determine the quality of the connection.
Depends on https://github.com/owncloud/client/pull/8278
=> Use time the request was sent,..

changelog/unreleased/7672, src/common/utility_win.cpp, src/gui/generalsettings.cpp
=> Update windows launch on start binary location

src/common/asserts.h, src/common/vfs.h
Depends on https://github.com/owncloud/client/pull/8309/files
=> OC_REQUIRED_RESULT

changelog/unreleased/8313, src/gui/CMakeLists.txt, src/gui/accountsettings.cpp, src/gui/application.h, src/gui/creds/httpcredentialsgui.cpp, src/gui/folder.cpp, src/gui/owncloudgui.cpp, src/gui/owncloudsetupwizard.cpp, src/gui/updater/ocupdater.cpp, test/owncloud_add_test.cmake
=> Properly display parent Window when displaying a dialog

src/libsync/accessmanager.cpp, src/libsync/accessmanager.h, test/syncenginetestutils.cpp
This allow better debugging of the tests
=> Use the http logger with the unittests

changelog/unreleased/8390, src/libsync/creds/oauth.cpp
=> Fix OIDC display

docs/modules/ROOT/pages/advanced_usage/environment_variables.adoc
I was not able to change the base branch from master (#8410) to 2.7 --> new PR
This is an improvement of the environment variable document.
The content renders now much better, some text has been improved and added.
When you do a build or render it with a browser antora plugin, it now looks much more professional
Backport to 2.6 and master
=> Improve Environment Variable Document

docs/modules/ROOT/pages/advanced_usage/low_disk_space.adoc
I was not able to change the base branch from master (#8414) to 2.7 --> new PR
This is an improvement of the low disk space document.
The content renders now much better, some text has been improved and added.
When you do a build or render it with a browser antora plugin, it now looks much more professional
Backport to 2.6 and master
=> Improve Low Disk Space Document

test/CMakeLists.txt, test/testlongpath.cpp
Depends on https://github.com/owncloud/client/pull/8434
=>     Add test for csync_vio_local_stat with long path

docs/modules/ROOT/pages/troubleshooting.adoc
on Windows you need to open a powershell
on Linux just a standard terminal
Just a quick addition to the docs. Wording can probably be improved
=> additional logging option: CLI

changelog/unreleased/7838, src/libsync/discovery.cpp
=> Fix url for etag request

changelog/unreleased/7838, src/libsync/discovery.cpp
Fixes: #7838
Discovered in https://github.com/owncloud/client/pull/8456
=> Fix another url for etag request

src/gui/application.cpp, src/libsync/theme.cpp, src/libsync/theme.h
'ownCloud 2.8.0git  Mar  1 2021 15:11:36 Libraries Qt 5.12.10, OpenSSL 1.1.1g  21 Apr 2020 Using virtual files plugin: wincfapi windows-10.0.21286'
=> Include full version string in log header

src/crashreporter/main.cpp
Depends on https://github.com/dschmidt/libcrashreporter-qt/pull/24
=> Send crash log as comment

src/gui/socketapi/socketapi.cpp, src/gui/socketapi/socketapi.h, src/gui/socketapi/socketapi_p.h, src/gui/socketapi/socketuploadjob.cpp, src/gui/socketapi/socketuploadjob.h
Depends on: https://github.com/owncloud/client/pull/8437
In an async scenario the listener can disconnect before we answer
=> Don't crash when the listener disconnected

docs/modules/ROOT/pages/index.adoc
https://github.com/owncloud/client/pull/8485
=> updated complete changelog link

test/gui/shared/steps/steps.py, test/gui/tst_addAccount/test.feature, test/gui/tst_syncing/test.feature
These are all minor changes to wording of test steps etc.
=> [tests-only] Minor changes from review of 8287 BDD UI tests

changelog/unreleased/8484, src/gui/folder.cpp
=> Bugfix: We fixed an issue with the promptDeleteAllFiles setting

src/libsync/creds/httpcredentials.cpp, src/libsync/creds/httpcredentials.h, src/libsync/creds/httpcredentials_p.h
~Depends on https://github.com/owncloud/client/pull/8397~
=> Port http credentials to the new credential manager

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/conflicts.adoc
This is a small improvement for the conflict page.
I hope that the base branch 2.7 is right ...
=> [DOCS] Improve Conflict Text

src/libsync/creds/oauth.cpp
=> Dynamic registration: Correctly handle 0 expire date

src/common/utility.cpp, src/common/utility.h, src/csync/csync_exclude.cpp, src/csync/csync_exclude.h, src/libsync/discovery.cpp, test/testexcludedfiles.cpp
Depends on https://github.com/owncloud/client/pull/8500
=> Use more stringref

src/common/asserts.h
03-25 14:20:01:023 [ fatal default ]:ENFORCE: "1 == 0" in file C:\CraftRoot\build\_\30b36579\owncloud-client\src\gui\application.cpp:void __cdecl OCC::Application::slotCrashEnforce(void), line 473
=> Include function signature in assert

src/libsync/abstractnetworkjob.cpp
The assert only makes sense in makeDavUrl
Fixes: #8490
=> Remove assert in makeAccountUrl

src/common/asserts.h
IDE's expect something like file line...
=> Make asserts parseable by ide's again

src/common/utility.h, src/libsync/syncfilestatustracker.cpp, src/libsync/syncfilestatustracker.h
I know you don't like local statics, but I guess this is a compromise and an improvement to what we had before.
=> Don't duplicate fsCasePreserving

test/gui/shared/scripts/names.py, test/gui/shared/steps/steps.py, test/gui/tst_sharing/test.feature
This PR adds tests for sharing file using public link.
https://github.com/owncloud/client/issues/8501
=> [tests-only]added tests for public link

changelog/unreleased/8437, changelog/unreleased/8539, src/gui/application.cpp, src/gui/folder.cpp, src/gui/owncloudgui.cpp, src/gui/owncloudgui.h, src/gui/settingsdialog.cpp, src/gui/socketapi/socketuploadjob.cpp, src/gui/socketapi/socketuploadjob.h, src/gui/systray.cpp, src/gui/systray.h, src/libsync/logger.cpp, src/libsync/logger.h
The quality of the image would be better if that would be a proper toast notification and not a legacy popup.
=> Backup notification

test/gui/shared/steps/steps.py, test/gui/tst_addAccount/test.feature, test/gui/tst_sharing/test.feature, test/gui/tst_syncing/test.feature
This PR removes unwanted values from py string while setting up client
- Fixes https://github.com/owncloud/client/issues/8552
=> [Tests-Only]Refactor step for setting up client

test/gui/tst_sharing/test.feature, test/gui/tst_syncing/test.feature
This PR adds tests for sharing folder using public link with expiration date and changing the date.
https://github.com/owncloud/client/issues/8501
=> [tests-only]public link share for folder expiration date

src/gui/accountstate.cpp
This fixes issues with some middleware
=> Clear cookies before we validate the server state

test/gui/shared/steps/steps.py, test/gui/tst_sharing/test.feature
This PR  adds tests for sharing folder using public link with various permissions
#8501
=> [tests-only]public link share for folder with different permissions

src/libsync/abstractnetworkjob.cpp, src/libsync/abstractnetworkjob.h, src/libsync/accessmanager.cpp, src/libsync/networkjobs.cpp, src/libsync/propagateupload.cpp
Add an additional header to track reuests that had to be restarted
=> Introduce X-Original-Request-ID

src/gui/socketapi/socketuploadjob.cpp, src/gui/socketapi/socketuploadjob.h
Issue: https://github.com/owncloud/files_backup/issues/29
=> Mark completed backups with the finished tag

changelog/unreleased/8158, src/common/fixedsizeringbuffer.h, src/gui/CMakeLists.txt, src/gui/activitylistmodel.cpp, src/gui/activitylistmodel.h, src/gui/activitywidget.cpp, src/gui/activitywidget.h, src/gui/folderman.cpp, src/gui/issueswidget.cpp, src/gui/issueswidget.h, src/gui/issueswidget.ui, src/gui/models.cpp, src/gui/models.h, src/gui/protocolitem.cpp, src/gui/protocolitem.h, src/gui/protocolitemmodel.cpp, src/gui/protocolitemmodel.h, src/gui/protocolwidget.cpp, src/gui/protocolwidget.h, src/gui/protocolwidget.ui, src/gui/settingsdialog.cpp, src/gui/settingsdialog.h, test/modeltests/CMakeLists.txt, test/modeltests/testactivitymodel.cpp, test/modeltests/testprotocolmodel.cpp
Depends on #8524
Some parts are still missing and will be handled in a follow up
=> Refactor protocol and issue widget

test/gui/shared/steps/steps.py, test/gui/tst_sharing/test.feature
This PR refactors test `simple sharing of folder by public link with different roles` to use data table in `When` step.
=> [tests-only]refactor tests to use scenario outline

test/gui/shared/steps/steps.py
make `davUserName` to take first name only in lower case.
=> [Tests-Only]Fix user name in dav_user and http_user

src/libsync/logger.cpp
With the recent changes to the logger, Qt creator stopped printing the output if a debugger was attached.
=> Windows: Write to debug if a debugger is attached

src/gui/accountmanager.cpp, src/gui/creds/httpcredentialsgui.h, src/gui/wizard/owncloudoauthcredspage.cpp, src/libsync/creds/httpcredentials.cpp, src/libsync/creds/httpcredentials.h
Issue was introduced in 3d878bae27ba22ecdf07313725b085b84c62af1a
=> Fix ouath credential loading

test/gui/shared/scripts/names.py, test/gui/shared/steps/steps.py, test/gui/tst_syncing/test.feature
This PR fixes failing test for file sync after the recent redesign of desktop-client.
- fixes https://github.com/owncloud/client/issues/8614
=> [tests-only] repair file sync failing test

test/gui/shared/steps/steps.py, test/gui/shared/verificationPoints/publicLinkPasswordProgressIndicatorInvisible, test/gui/tst_sharing/test.feature
for now we are expecting this step to fail because of #7459
squish has a way of defining tests(assertions) that are expected to fail, so using that and do not implement a expected to fail parser
=> use expected to fail system

changelog/unreleased/8609, src/libsync/owncloudpropagator.cpp, src/libsync/owncloudpropagator.h, src/libsync/propagatedownload.cpp, src/libsync/propagatorjobs.cpp
=> Display local file name in case clash warning
