owncloud/client

- src/gui/owncloudgui.cpp
- src/libsync/progressdispatcher.cpp
- src/libsync/progressdispatcher.h
This small patch hides ignored files in the recent changes context menu. It is a potential fix for issue #1865, but still needs to be tested thoroughly.
> Hide Ignored files in context menu

- src/gui/owncloudgui.cpp
We are using a QHash to store all the folder objects. This does not allow for
easy sorting and looks weird to the user. Now they are first inserted into a
temp QMap to sort them properly.
This should (at least partly) solve #1529
> Manged folder list in the tray icon is now sorted

- src/gui/sharedialog.cpp
When we try to get the shares for a file/dir that has no shares yet 404 is an
acceptable response from the server.
> Sharedialog: 404 is also an acceptable response when retriving shares

- src/gui/CMakeLists.txt
- src/gui/wizard/owncloudconnectionmethoddialog.cpp
- src/gui/wizard/owncloudconnectionmethoddialog.h
- src/gui/wizard/owncloudconnectionmethoddialog.ui
- src/gui/wizard/owncloudsetuppage.cpp
- src/gui/wizard/owncloudsetuppage.h
When connecting to a https:// URL fails, present the user with three choices:
* Try again with a http:// URL
* Configure client-side TLS certificates
* Go back and enter a different URL
This allows users connecting with an ownCloud server secured with client-side TLS certificates to start the certificate import wizard manually instead of relying on a custom server error message.
#69 introduces support for client-side TLS certificates, but relies on the server to return an error message `SSL handshake failed`. However, it is not always possible or desirable to modify the server's error messages (e.g., when the TLS-layer is handled by a proxy server serving as a gateway for several hosted services).
This seems to work.
That said, this is the first time I've touched software written in …
> Add dialog to connection wizard for client-side TLS certificates

- src/gui/sharedialog.cpp
- src/gui/sharedialog.h
The copy button in the sharedialog was still empty and not connect. This commit fixes that.
> Sharedialog: add copy button text and actually connect the button

- test/testfolderwatcher.h
on some systems touch(1) is in /bin, not /usr/bin.
instead hardcoding another path, take it from $PATH, like other commands used here (rm, echo)
> use touch from path

- src/gui/sharedialog.cpp
One tiny statement missing from 4849c31addc1d1c6b9a45a5487c22511d5cac83c
When a user deletes a public link and then recreates it and password sharing is enforced things did not go as expected. They do now.
> Reset _public_share_id after we delete the share

- src/libsync/filesystem.cpp
Fix to make the client compile with Qt-4.8 again.
> static member QFileInfo::exists is not available on 4.8

- src/mirall/filesystem.cpp
- src/mirall/filesystem.h
- src/mirall/propagator_qnam.cpp
for testing env variable OWNCLOUD_CHECKSUM_TYPE may be set to Adler32, otherwise default is MD5
This aligns better with the protocol specified in: https://github.com/cernbox/smashbox/blob/master/protocol/checksum.md
> added adler32 implementation; use OC-Checksum header instead of OC-MD5

- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderman.cpp
- src/gui/socketapi.cpp
When the local sync target is just a drive letter (e.g. "X:\"), neither
the display of the sync status via file icon overlay, nor the creation of a
share link works. In the latter case no pop-up comes up and no server
request is done.
[QDir::cleanPath() usually removes trailing slashes, but not if the path to
be cleaned is just "X:\" and the OS it is running on is Windows](http://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/io/qdir.cpp?id=9ae7e33f28f972ec566d62ab110e173ebe933520#n2167). In that case the trailing slash is kept.
Addendum: I tried to keep number of changes as small as possible. But the change to `Folder::path()` was necessary, so that the local sync target `X:\` would not end up as `X:\/`. [Which would result in the construction of a wrong remote path for a …
> Windows Explorer: fix issues when syncing whole drive.

- csync/src/csync_log.h
- csync/src/httpbf/src/httpbf.c
- csync/tests/csync_tests/check_csync_log.c
this fixes the error and makes complete oCC compile with GCC 5.
error: ISO C does not support '`__FUNCTION__`' predefined identifier [-Wpedantic]
According to the porting guide:
The fix is either to use the standard predefined identifier `__func__` (since C99), or to use the `__extension__` keyword
> Compile with GCC 5

- src/libsync/networkjobs.cpp
This fix solves #3256 by adding 'Content-Length: 0' to the MKCOL request. It does not violate the [WebDAV spec](http://www.webdav.org/specs/rfc2518.html#METHOD_MKCOL) and it is compatible with Apache. It works on the Linux client. The Windows client is being tested as we speak.
> Add 'Content-Length: 0' header to MKCOL request; fixes #3256

- doc/troubleshooting.rst
Really wonder why no one ever considered such problems caused by on-access virus scanners.
Source: https://forum.owncloud.org/viewtopic.php?f=14&t=17477&p=79098#p79073
> Add note for on-access virus scanner solutions

- src/libsync/account.cpp
This is supposed to fix bug #3283
> Abort the request and reset the QNAM if user does not ACK a new cert.

- csync/src/csync_private.h
- csync/src/csync_update.c
- src/cmd/cmd.cpp
- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderman.cpp
- src/gui/selectivesyncdialog.cpp
- src/gui/socketapi.cpp
- src/libsync/discoveryphase.cpp
- src/libsync/discoveryphase.h
- src/libsync/networkjobs.cpp
- src/libsync/ownsql.cpp
- src/libsync/syncengine.cpp
- src/libsync/syncengine.h
- src/libsync/syncjournaldb.cpp
- src/libsync/syncjournaldb.h
The idea is that the UI would set SyncEngine->setNewSharedFolderSizeLimit and listen to the newSharedFolder signal.  It would then add the new folder in the blacklist, and the unconfirmed list.  Then from the UI we can move the unconfirmed item to the white list when the selective sync dialog is closed.
> Confirm feature (sync engine part only)

- .travis.yml
All things pushed to the "coverity_scan" branch will now get build by Travis and the resulting binary is pushed to Coverity and analyzed automatically.
Since Coverity has a fair usage policy which allows us up to 8 builds per week with a maximum of 2 builds per day we cannot run this automatedly on every push. Which also doesn't make that much sense.
Currently this can be used by reating a "coverity_scan" branch and force-pushing the new code to analyze. If all went well the Travis build should pass and Coverity should display the new information (give it some time to process the build though). In Coverity the SHA of the processed build will be used as version number as well as descriptive text.
(we can automate this though in the future as well if we want that too)
This will fail at the …
> Add travis file for coverity_scan branch

- src/gui/folderstatusmodel.cpp
- src/gui/owncloudgui.cpp
- src/libsync/utility.cpp
- src/libsync/utility.h
- test/testutility.h
To fix https://github.com/owncloud/client/issues/2672 just need translations
@danimo is that how to solve it?
(It builds and shows the time string still properly in English)
> make the remaining time string translatable and support plural forms

- csync/src/csync.h
- csync/src/csync_private.h
- csync/src/csync_update.c
- csync/src/vio/csync_vio_local.c
- csync/tests/csync_tests/check_csync_update.c
- csync/tests/ownCloud/t4.pl
- src/libsync/syncengine.cpp
There is no reason to ignore them. Downloading a file that is hardlinked
will break the link.
Will solve syncing NTFS directories #3241
> csync: Do not ignore hard links anymore

- src/gui/sharedialog.cpp
If we have a slow connection we do now want to show the share checkbox until we
have retrieved the shares (so we know the state). Else we might try to enable
sharing on an already shared file.
Fix for #3002
> Wait until we retrieved shares before showing checkbox

- src/gui/sharedialog.cpp
- src/gui/sharedialog.h
Basically another go at #2805
The last time this code was removed since the endpoint might still change. (CC: @dragotin) however, to my knowledge the mobile clients also use this endpoint. So after a quick chat with @DeepDiver1975 he said to just do it :)
> Sharedialog show thumbnail of file (if available)

- src/gui/socketapi.cpp
Sharing the root folder is not possible so don't allow the user to do this. Fixes #3482 and #3483 
Note that this is just a quick fix.
For better UX we should have a way to tell the plugins that the registered path is the root folder. That way they can simply grey out the menu item on the root folder.
> Don't allow sharing of the root folder

- src/gui/sharedialog.cpp
To avoid us having to construct the URL for public shares just rely on the server to do it.
This makes it easier to maintain. For example if (in the not do distant future) the index.php part is removed the server would just server this new url.
Pretty simple fix, and should not break for people not on 8.2 since then the url element is simply not present.
> If the OCS Share API returns an url use that

- src/gui/sharedialog.cpp
- src/libsync/CMakeLists.txt
- src/libsync/account.cpp
- src/libsync/account.h
- src/libsync/capabilities.cpp
- src/libsync/capabilities.h
Replaces #2943
Should fix: #2815
By making use of the capabilities provided by the server we can provide a better UX.
1. Do not allow a user to remove expire date/password if the admin enforces it
2. Require a password from the user if this is enforced.
> Use server capabilities

- src/gui/CMakeLists.txt
Change the installation target for the translations and the .desktop file to the architecture-independent DATADIR.
> [Unix] Install architecture-independent files to DATADIR.

- src/libsync/discoveryphase.cpp
This should allow for the case when a user has set the limit to 0 and a new empty folder appears on the server. The folder will have size 0 (no files in it). Doing the >= test here will mean that the user will be prompted about the new folder, which I think is the behaviour they would expect.
The side-effect of this change is that if the user has a limit of, for example, 10,000,000 bytes (10 MB) and a new folder comes along with exactly 10,000,000 bytes of content then they will now be prompted about it. Before the change such a new folder would have been auto-synced without prompting the user. I do not think this is a big deal - I cannot believe that users will be counting exact bytes for this limit, they are just setting a rough number of MB at the UI.
Should fix …
> Notify of big folders that are greater than or equal to the limit

- src/libsync/utility.cpp
- test/testutility.h
SI units make more sens because users are used to compute with powers of 10
> Utility: use SI units for the sizes in bytes

- src/gui/CMakeLists.txt
SHAREDIR is used in src/gui/application.cpp and should also use that in
CMakeLists.txt.
> Use SHAREDIR for i18n dir

- doc/navigating.rst
Some "downloading" that should be "uploading".
Some bullet points with "code" items were rendering with bold, italics on the published page. These seemed to be bullet points that had 3 spaces at the start of their 2nd line of text. Other bullet points that rendered correctly had only 2 spaces. So I removed the extra space. I hope it renders nicely in the published form - it is a bit hard to know in the GitHub Preview, because that is trying to show change-sidebars and differences also.
> Navigating doc typos 2.0

- doc/autoupdate.rst
A space at the start of the bullet point about "Locate and open the following file" seems to be causing that bullet point to not line up nicely on the rendered page.
> Autoupdate Doc bullet point rendering 2.0

- shell_integration/nautilus/syncstate.py
check if its a folder (ends with an /), if yes add a "/" otherwise it will not find the entry in the socketConnect.nautilusVFSFile_table
This should fix the issue #3556
> checking if file or folder is to be shared to fix issue #3556

- shell_integration/nautilus/syncstate.py
Top level folders cannot be shared. If you try you receive an 403 error.
So we should not show the "Share with Owncloud" menu item for them
back-port of #3663 
fixes #3662
> [2.0] don't show share menu item for top level folders

- doc/autoupdate.rst
Should be stated clearly that there are no alternative 32- / 64-bit-ownCloud-Clients, but just a 32-bit-ownCloud-Client that is treated differently in 32- / 64-bit-Windows
> /doc/autoupdate.rst: "32-/64-bit" => "32-/64-bit-Windows"

- src/gui/accountsettings.cpp
Since the context menu text was changed to "Remove Account" it seems sensible to also change the title of this message box to match.
https://github.com/owncloud/client/issues/3793
> Adjust message box text for account removal

- src/gui/updater/ocupdater.h
Make it say something understandable. Looking at previous versions with git blame, the word "not" fits here.
Issue #3809
> OCUpdater description text

- src/gui/accountsettings.cpp
Since the context menu text was changed to "Remove Sync" it seems sensible to also change the title of this message box to match.
https://github.com/owncloud/client/issues/3745
> Adjust message box text for sync removal

- doc/architecture.rst
Typo causing a broken link in https://doc.owncloud.org/desktop/2.0/architecture.html#synchronization-by-time-versus-etag
> Fix linkname in architecture.rst.

- cmake/modules/GNUInstallDirs.cmake
Simplification taken from upstream cmake to make the ocsync library behave correctly on Debian and Ubuntu multiarch systems.
> fix multiarch library path for Debian/Ubuntu

- src/gui/sharedialog.cpp
- src/gui/socketapi.cpp
- src/gui/socketapi.h
- src/libsync/capabilities.cpp
- src/libsync/capabilities.h
For #3879
The socketAPI `SHARE_STATUS` allows to retrieve the share status for the current file. So can it be shared or not. And if it can how (UserGroup, Link).
We will need additional fixes in the shell_intergration stuff.
CC: @dragotin
> Provide information about share availablity for files

- src/gui/sharedialog.cpp
- src/gui/sharedialog.h
- src/gui/sharedialog.ui
- src/libsync/capabilities.cpp
- src/libsync/capabilities.h
Fixes #3551
Allow users to set write access on link shares if this is enabled by the server.
Will require the 8.2 (current master) on the server to expose the capability.
> Allow setting of public upload on link shares

- src/gui/CMakeLists.txt
- src/gui/ocsjob.cpp
- src/gui/ocsjob.h
- src/gui/ocssharejob.cpp
- src/gui/ocssharejob.h
- src/gui/sharedialog.cpp
- src/gui/sharedialog.h
- src/gui/thumbnailjob.cpp
- src/gui/thumbnailjob.h
In preparation of the full desktop sharing (https://github.com/owncloud/client/issues/3737) the sharedialog code had to be somewhat unentangled.
There now is more code in libsync and the gui is cleaned up a bit.
* OCSJob class added. To allow a nice abstraction also for the new sharee endpoint code (which is required)
* OcsShareJob class is now in libsync and has more generic functions like createShare, setPassword etc. So the GUI part can just say do this.
* ShareDialog is cleaned up
My tests show that everything still works as expected but please run your own tests to make sure I did not break anything!
CC: @dragotin @guruz @ogoffart and others that want to test!
> Split sharedialog code

- ChangeLog
These changes were committed to 2.0.2-rc1 branch https://github.com/owncloud/client/pull/3957/files https://github.com/owncloud/client/commit/6da2139a1bc4069f1cd1dfb017502f089c3af26f but that branch was never merged up into 2.0 (or 2.0.2-rc2) so the changes never went anywhere.
These changes could also be applied on 2.0.2-rc2 and 2.0.2 branch for completeness - then they would be in every branch in which they have appeared.
> ChangeLog 2.0.2 minor typos for 2.0 branch

- src/gui/CMakeLists.txt
- src/gui/ocsjob.cpp
- src/gui/ocsjob.h
- src/gui/ocssharejob.cpp
- src/gui/ocssharejob.h
- src/gui/share.cpp
- src/gui/share.h
- src/gui/sharedialog.cpp
- src/gui/sharedialog.h
Step closer to https://github.com/owncloud/client/issues/3737
Pretty big PR (I'm sorry... I'll promise to do better).
Basically this introduces the abstraction I want. And which should help significantly in making the user/group sharing easier to implement.
There is now a ShareManager, this is the entry point to do anything with shares. Be it creating, or fetching.
Then there is the Share class which represents a generic share and there is the LinkShare class. Since link shares are just like regular shares but slightly different :P. Share objects allow for interaction with the object. E.g. setting the password etc. 
The sharedialog code is converted to use the new code and still works for me so far. And is a lot simpler.
TODO:
@guruz @dragotin @ckamm please have a look. More commits will …
> Add share manager and the share objects

- doc/autoupdate.rst
Currently only looks like this:
``HKEY_LOCAL_MACHINESoftwarePoliciesownCloudownCloud``
https://doc.owncloud.org/desktop/2.0/autoupdate.html#preventing-automatic-updates-in-windows-environments
> Make registry key a code block in autoupdate docs.

- src/gui/wizard/owncloudhttpcredspage.cpp
If a user enters a server URL in the form of https://user:pass@example.com/, this will pre-populate the following credentials page with those values. This streamlines the setup process in the case where the URL already has the credentials.
To test:
1. Start the client and set up a new account. Use `https://user:pass@example.com` for the server URL. Click Next.
2. See `user` pre-populated for the username. See four dots pre-populated for the password.
3. Click Next and check that `user` and `pass` were used for authentication.
> Populate account setup credentials from server URL

- src/gui/accountsettings.cpp
- src/gui/accountsettings.h
- src/gui/accountsettings.ui
- src/gui/generalsettings.cpp
- src/gui/generalsettings.h
- src/gui/generalsettings.ui
Also move the 'Add Account' button from the General Tab, where it
is not properly found, to the new account toolbox.
This results in a look like that:
Also note the Add-Account functionality, that moved from the General tab to here. 
@jancborchardt how is that? @phil-davis as we talked about in the other issue #4134
> AccountSettings: Add a toolbox button for the account specific actions.

- src/gui/CMakeLists.txt
- src/gui/accountmanager.cpp
- src/gui/accountmanager.h
- src/gui/activityitemdelegate.cpp
- src/gui/activityitemdelegate.h
- src/gui/activitywidget.cpp
- src/gui/activitywidget.h
- src/gui/activitywidget.ui
- src/gui/folderman.cpp
- src/gui/folderman.h
- src/gui/generalsettings.cpp
- src/gui/generalsettings.h
- src/gui/generalsettings.ui
- src/gui/owncloudgui.cpp
- src/gui/protocolwidget.cpp
- src/gui/protocolwidget.h
- src/gui/protocolwidget.ui
- src/gui/settingsdialog.cpp
- src/gui/settingsdialog.h
- src/gui/synclogdialog.cpp
- src/gui/synclogdialog.h
- src/gui/synclogdialog.ui
- src/libsync/networkjobs.cpp
- src/libsync/networkjobs.h
- src/libsync/utility.cpp
- src/libsync/utility.h
I'd like to create this pull request already to discuss the changes done here as early as possible.
This branch changes the way we display the sync activity in the former client releases and adds three new views to the Activity-tab in the client.
1. **Server Activiity**
This displays the server activity list. Currently it is pulled from the server and displayed if the server is reachable. 
2. **Sync Protocol**
Very similar to the former list of synced files, but without the ignored and error files in between. It's a plain positive list now.
3. **Not Synced**
A list of files that were not successfully synced because they were ignored (by user intention or because of other reasons) Later on we can also handle the blacklisting here more user friendly.
Some Screenshots:
Please give me your …
> New Activity View

- src/gui/shareusergroupwidget.cpp
- src/gui/shareusergroupwidget.h
- src/gui/sharewidget.ui
As discusses with jan.
* Detailed permissions displayed in qtoolboxmenu
* Made share rows slightly smaller
Bug fix:
* Do not show delete permissions for file shares
> [Sharing] Permissions now in dropdown menu

- src/gui/sharee.cpp
Now against 2.1 :)
Problem found by danimo and investigated by me: searching for LDAP users was buggy. They only appeared, when the search started with the userid.
Server works correctly.
Turns out, displayname variable was not used.
@danimo @rullzer
> show displaynames of users in share dialog instead of userid

- src/libsync/capabilities.cpp
Required to fix sharing for pre 8.1 servers
I hope this Fixes https://github.com/owncloud/client/issues/4218
CC: @Dianafg76 @dragotin
> [Sharing] Default capabilitie for link sharing

- src/gui/socketapi.cpp
Before we attemt any sharing make sure the file is synced to the server.
We should make sure actually that non of the file browser plugins tries to share a file if it does not have to proper status.
> [Sharing] Make sure the file is actually synced to the server

- doc/building.rst
I am using :: lists, as the ``  versions mangle multi-line commands all in one long line.
The cmake command should just end in .., not in ../client
@Kawohl this should also work in your Dockerfile.
> improved linux build instructions.

- src/gui/settingsdialog.cpp
Fixing bug in opening Activity log from tray icon menu 'Recent Changes/Details...'.
such that Settings dialog shows Activity tab, but highlighted tab could be different.
the problem fixed in settingsdialog.cpp.
settingsdialogmac.cpp checked, doesn't have the problem.
> Fixing bug in opening Activity log from tray icon menu 'Recent Changes/Details...'

- csync/src/csync_update.c
This fixes a  compatibility issue with the definitions of the type members within the two used structs.
> Fix enum csync

- cmake/modules/AddCMockaTest.cmake
- csync/tests/CMakeLists.txt
Neither tests nor the libcmocka needs to be installed globally.
ctest still works.
> Don't install tests and cmocka lib

- doc/conffile.rst
Fixes https://github.com/owncloud/client/issues/4468
Ref: https://github.com/owncloud/client/issues/4354#issuecomment-171947435 and https://github.com/owncloud/client/blob/v2.1.1/src/libsync/configfile.cpp#L127
> Add chunkSize config to documentation

- src/libsync/propagatedownload.cpp
Backtrace seen from the crash reporter where reply() is null.
> PropagatorDownload: fix possible crash

- src/gui/shareusergroupwidget.cpp
This prevents accidentally sharing with the same sharee multiple times.
Because creating shares is not instance.
Fixes #4469
CC: @Dianafg76
> Lock the sharee input when sharing

- src/libsync/networkjobs.cpp
- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- src/libsync/propagatedownload.cpp
- src/libsync/propagatedownload.h
- src/libsync/propagateremotedelete.cpp
- src/libsync/propagateremotedelete.h
- src/libsync/propagateremotemkdir.cpp
- src/libsync/propagateremotemkdir.h
- src/libsync/propagateremotemove.cpp
- src/libsync/propagateupload.cpp
Helps with small file sync #331
When I benchmarked this, it went up to 6 parallelism and
was about 1/3 faster than the previous fixed 3 parallelism.
Doing more than 6 is dangerous because QNAM limits to 6 TCP
connections and also the server might become a bottleneck.
Should also help for #4081
> Propagator: Pump in more requests if we think current ones are quick

- src/gui/accountmanager.cpp
- src/gui/accountsettings.cpp
- src/gui/application.cpp
- src/gui/folderman.cpp
- src/gui/folderman.h
- src/gui/owncloudgui.cpp
- src/gui/owncloudgui.h
- src/libsync/account.cpp
- src/libsync/account.h
- src/libsync/connectionvalidator.cpp
* A tray message on every start up
* Red message in account settings
* Folders are paused when the server version switches to
an unsupported one
> Add warnings for old server versions #4523

- src/gui/activitywidget.cpp
- src/gui/activitywidget.h
If the ownCloud server does not have the activity app enabled,
it returns 999 as status code. If all the configured accounts
do that, this code hides the entire tab with the server
activities.
This is supposed to fix #4533
> Activities: Hide if non of the accounts has the app enabled.

- src/libsync/syncengine.cpp
`ExcludedFiles::~ExcludedFiles` calls `c_strlist_destroy()`, so it must be run before `csync_destroy()`; field destructors are run after the destructor body, so we cannot use a smart pointer for `SyncEngine::_excludedFiles`.
> Fix crash due to destruction order

- src/gui/accountmanager.h
- src/gui/accountsettings.cpp
- src/gui/accountstate.h
- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderman.cpp
- src/gui/folderman.h
- src/gui/owncloudgui.cpp
- src/gui/owncloudgui.h
- src/gui/selectivesyncdialog.cpp
- src/gui/socketapi.cpp
- src/gui/socketapi.h
- src/libsync/CMakeLists.txt
- src/libsync/accountfwd.h
- src/libsync/excludedfiles.cpp
- src/libsync/excludedfiles.h
- src/libsync/progressdispatcher.h
- src/libsync/syncengine.cpp
- src/libsync/syncengine.h
- src/libsync/syncfilestatus.cpp
- src/libsync/syncfilestatus.h
- src/libsync/syncfilestatustracker.cpp
- src/libsync/syncfilestatustracker.h
- src/libsync/utility.cpp
- src/libsync/utility.h
- test/testfolderman.h
- Make the SyncEngine persistent in the Folder, in order to be able to move backed logic into libsync
- Move any backend logic from SocketApi into a new SyncFileStatusTracker in libsync
- Refactor SyncFileStatusTracker to simplify the logic, make it match 100% the status of files in the UI and support bubbling up error statuses to parent folders as a warning
- Blacklisted files are now kept marked as error in the overlay icons even though they are a simple information in the activity log
Next step is to try adding auto tests for this, but this branch was tested manually during development and can land without.
> Socket API refactor

- src/cmd/cmd.cpp
- src/gui/accountsettings.cpp
- src/gui/folder.cpp
- src/gui/folderstatusmodel.cpp
- src/gui/selectivesyncdialog.cpp
- src/gui/selectivesyncdialog.h
- src/libsync/syncengine.cpp
- src/libsync/syncjournaldb.cpp
- src/libsync/syncjournaldb.h
If there is a read error from the database while trying to get
the list from database, make sure to not behave badly because
the list is empty.
Supposed to fix #4633
> SelectiveSync: Verify if the list could be read from journal.

- doc/troubleshooting.rst
Follow-up of: https://github.com/owncloud/documentation/issues/1981
Warnings currently looks like seen here: https://doc.owncloud.org/server/9.0/admin_manual/issues/code_signing.html#errors
> Change note to warning in documentation

- csync/src/csync.c
- src/gui/folder.cpp
- src/gui/folderwatcher_linux.cpp
There were two issues:
* With the refactoring of how Folder and SyncEngine relate, the
ignore_hidden_files flag on the CSync context was reset after
each sync run and not updated from the configuration again.
* The folder watcher failed to enumerate hidden folders and thus
didn't watch for changes inside them. (linux only)
> Fix hidden file handling #4655

- src/gui/ocssharejob.cpp
- src/gui/ocssharejob.h
- src/gui/owncloudgui.cpp
- src/gui/share.cpp
- src/gui/share.h
- src/gui/sharedialog.cpp
- src/gui/sharedialog.h
- src/gui/sharelinkwidget.cpp
- src/gui/sharelinkwidget.h
- src/gui/sharepermissions.h
- src/gui/shareusergroupwidget.cpp
- src/gui/shareusergroupwidget.h
Users can't reshare with more permissions than they have themselves.
> Disable unavailable sharing permissions #4383

- csync/src/csync_update.c
I don't see a reason we should not allow this. We detect
a "failed stat reply" in other ways. Maybe this was a legacy
csync decision somewhow that is not valid anymore?
> CSync: Allow files with 0 mtime #1603

- src/gui/sharedialog.cpp
See https://github.com/owncloud/core/pull/24017
This was done since other services we want to intergrate with don't use
the ownCloud namespace.
Once https://github.com/owncloud/core/pull/24017 is in. Pleae give it a quick test.
> The share-permissions namespace was moved

- src/gui/share.cpp
- src/gui/share.h
- src/gui/sharelinkwidget.cpp
If an app modifies the expiration date (for example the password policy
app) then on more recent versions of the server we will get the share
object back REST style. We should use that info!
Fixes #4409
> Use expireDate if returned by the OCS Share API

- src/libsync/capabilities.cpp
- src/libsync/capabilities.h
- src/libsync/checksums.cpp
- src/libsync/checksums.h
- src/libsync/configfile.cpp
- src/libsync/configfile.h
- src/libsync/owncloudpropagator.cpp
- src/libsync/propagatedownload.cpp
- src/libsync/propagateupload.cpp
- src/libsync/theme.cpp
- src/libsync/theme.h
The server may send invalid checksums when files change on disk,
see owncloud/core#23783.
Introduces a new validateChecksumOnDownload configuration and
branding option.
> Disable validation of transmission checksums by default #4638

- shell_integration/nautilus/syncstate.py
- src/gui/socketapi.cpp
- src/libsync/syncfilestatustracker.cpp
- src/libsync/syncfilestatustracker.h
This uses some  heuristics to estimate the root status. Not complete as it completely neglects the database items, but maybe a start.
@jturcotte @ckamm please.
> SyncFileStatusTracker: Add a method to handle the root item.

- src/gui/quotainfo.cpp
- src/libsync/theme.cpp
- src/libsync/theme.h
As discussed on issue #4460
Having the quote to be queried on subfolder is wrong in the generic case,
so add a branding option to configure it.
This partially reverts commit ff4cdc3161ddbb74a0fe10f969043ff898fbb93a
> Quota: Add branding option for the base folder

- shell_integration/nautilus/syncstate.py
This avoids an extra socketapi call after invalidate_extension_info
is called from a STATUS message.
> Overlay icons: Fix invalidation with nautilus #3249

- src/gui/accountsettings.cpp
- src/gui/folderman.cpp
- src/gui/folderman.h
- src/gui/owncloudsetupwizard.cpp
Before commit 1a51b6718a345f1e5f28dd1f4e0c04bdaeeb5357, the wizard was
making sure folder had an alias but this is no longer the case.
So generate still an unique alias.
Alias is not used in the UI any longer, it's just use for internal purposes.
For issue #4737
> Accountsettings: Generate an alias for new folders

- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderman.cpp
- src/libsync/syncfilestatustracker.cpp
- src/libsync/syncfilestatustracker.h
This uses the file watcher to keep track of files that were modified
in order to assign them the blue icon.
This is transient state that's not persisted across restarts.
> Overlay icons: Track touched files #4730

- csync/tests/ownCloud/t6.pl
As t6 uses curl to run, and curl is not installed by default, it's better to check at the beginning and abort then, with a meaningful message, than later in the script, with an obscure one.
> Adding CURL check in t6.pl

- src/gui/sharelinkwidget.cpp
- src/gui/sharelinkwidget.ui
- src/gui/shareusergroupwidget.ui
Do the visual stuff from designer.
The previous code that was ment to change the color in red did not work
and changed it to gray instead.
Also I don't see why there should be a frame.
Issue #4773
> ShareDialog: show the error message in red

- src/gui/socketapi.cpp
- src/libsync/syncfilestatustracker.cpp
- src/libsync/syncfilestatustracker.h
Since the windows implementation first does cache lookups using the
path string, directories need to be passed identically as through
RETRIEVE_FILE_STATUS.
Change the convention to never have a trailing slash for directories
in the protocol. This allows the convention to be applied without
having to access the disk (since we'd need to know if the path is
represented by a directory) and also matches the convention of the
rest of the sync engine. Individual file manager plugins are then
responsible of handling pushed paths as not ending with a trailing
slash.
This also:
- Moves the trailing slash removal logic from the SyncFileStatusTracker
to the SocketApi class
- Remove the unneeded QString::normalized call in fileStatus, since
this should already be done by the FolderWatcher and plugins
> [shell/windows] Fix the windows status push not working

- src/libsync/syncfilestatustracker.cpp
The assert was there to make sure that this case wasn't happening
to eventually be properly tested. Remove the assert for now but this
codepath should eventually be unit tested using this specific situation.
> Fix assert on restore after propagation

- test/testutility.cpp
f.ex. a valid verson nr: 2.2.0
-> fist \d+ = 2
-> second \d+ = 2
-> the last \d+ = 0
-> .+ in not matching, because there is nothing to match
> A final release version number breaks regex

- src/libsync/progressdispatcher.cpp
These directory SyncFileItems are necessary for bookkeeping
but should not influence the progress display at all.
> Progress: Don't count dirs without propagation jobs #4856

- src/gui/owncloudsetupwizard.cpp
- src/libsync/account.cpp
- src/libsync/account.h
Previously rejecting any kind of certificate meant that the user
was never asked again, even if the certificate changed.
Now we keep track of which certificates were rejected and ask again
if the ones mentioned in the ssl errors change.
mitmproxy is excellent for testing this.
> Certs: Re-ask for different cert after rejection #4898

- src/gui/main.cpp
This seems to be broken. Worst case users can still set it manually
Addresses #4840
> Don't try to determine pixel ratio with Qt < 5.6.0

- src/libsync/owncloudpropagator.h
Since a signal is protected in Qt4 and we are triggering a signal from upload as well now this is required to unbreak Qt4 builds.
> Fix Qt4 build

- src/gui/shareusergroupwidget.cpp
Also allows searching on attributes other than displayname in ldap configurations. Search results match web and mobile apps.
> Search results are filtered by server. Don't filter a second time.

- src/gui/main.cpp
Setting the Environment variable only for owncloud makes in inconsistant with
other Qt application running at the same time.
The users can still set it themself for the whole desktop if they wish.
Addresses #4840
> GUI: don't force the environment variable for high DPI on linux.

- src/gui/folder.cpp
FolderDefinition::save and load escapes the alias. We also need to escape
it when we remove it.
New folder can't be created with alias that needs escaping, but old folder
from old config may still exist, and we must allow user to delete them.
> Folder: fix removing folder with escaped characters

- src/libsync/filesystem.cpp
No need to allocate (and initialize to 0) a 10 MiB buffer for each files, even
when most files are much smaller than that.
So make sure the buffer that we allocate is not bigger than the file size.
And Also 10 MiB is a bit big for a buffer. 500 KiB should be more than enough.
(Too big allocations can cause problem because of memory fragmentation and such)
> Checksum speedup.

- src/libsync/syncfilestatustracker.cpp
- src/libsync/syncfilestatustracker.h
The FolderWatcher inserts files to be marked as SYNC and we
currently assume that all file statuses will be updated by the
following sync. It's however possible that the FolderWatcher
notify us of a change that csync won't consider necessary to
propagate, in which case a new status wouldn't be pushed and
the file manager would continue showing this file as syncing.
Re-push the file status when emptying the dirty files list
before propagating to avoid this issue, most likely the OK
status.
> SocketAPI: Push new status of dirty files regardless when not synced

- csync/src/csync_exclude.c
Otherwise we have the log line even though the pattern was not logged.
> excludes: Only log if the pattern was really logged.

- src/gui/application.cpp
- src/gui/folder.cpp
We were missing some csync related log output during startup.
Discovered in #4967
> Setup csync logging earlier

- csync/src/csync_statedb.c
- csync/src/csync_update.c
- csync/src/vio/csync_vio_file_stat.c
- csync/src/vio/csync_vio_local_unix.c
* For csync_file_stat_t and csync_vio_file_stat_t
* Add original_name to the vio file stat destructor
> csync: Use the full file stat destructors

- src/gui/shareusergroupwidget.cpp
This disables the workaround 487e1fdca5ee04fc98c1ed77898df70d740967c8
for servers that are new enough to support fine grained permissions
on federated shares.
The consequence is that the 'reshare' permission is now granted by
default and that users can edit permissions on the usual fine-grained
level again.
The way the client deals with servers <9.1 is unchanged.
> Share: Permissions for federated shares on servers >=9.1 #4996

- shell_integration/windows/OCUtil/CommunicationSocket.cpp
- src/gui/socketapi.cpp
Named pipe names that contain backslashes sometimes lead to problems.
> SocketAPI: Use different pipe name #4977

- src/libsync/discoveryphase.cpp
Since the SyncEngine now quits and waits for the discovery thread,
the main thread can enter a deadlock where the discovery thread waits
for its directory result.
Add a 2 seconds timer to the discovery thread wait condition
to limit the deadlock time.
> Fix a deadlock when shutting down during discovery

- src/gui/main.cpp
This was removed in 0194ebb2229adc33f5b9790231a3384b46474bde
because it breaks on Linux. However, it looks like it is correct
for Windows. In the meantime the surrounding ifdef has changed
from !Q_OS_MAC to Q_OS_WIN, so reverting it makes sense.
> Fix windows HiDPI #4994

- src/gui/owncloudgui.cpp
Attach the accout menu QAction to the menu rather than the
ownCloudGui since it should be destroyed when the context
menu is cleared.
> Fix a QAction leak

- src/gui/creds/httpcredentialsgui.cpp
- src/gui/creds/httpcredentialsgui.h
- src/gui/owncloudsetupwizard.cpp
- src/gui/owncloudsetupwizard.h
- src/gui/wizard/owncloudhttpcredspage.cpp
- src/gui/wizard/owncloudhttpcredspage.ui
If owncloud >= 9.1 is detexted:
instead of "Password:" ask for "Password or Token"
and add a link to the ownCloud page that allow to add device token
Issue #4877
> GUI: Show link to the page that allow to add a new token

- src/libsync/capabilities.cpp
> Only accept notification API Capability if endpoint is OCS-enabled

- csync/src/vio/csync_vio_local_win.c
Fixes an accidental behavior change introduced in
055c2ef73f84b68ebfbe0296fadef438981cba37
Affects #4056 and owncloud/enterprise#1225.
> Windows: Skip symlinks and junctions again #5019

- src/gui/accountmanager.cpp
While loading the account, only override the server url if Theme::forceConfigAuthType
is set. This restore the behavior from the client 2.2.0 for theme that did not
use Theme::forceConfigAuthType.
> AccountManager: Don't force the server URL while loading the config.

- src/gui/creds/shibboleth/shibbolethwebview.cpp
It opens a window and connects to a cipher test
page, showing the output from there, that helps for debugging.
The window is enabled by setting the environment variable
OWNCLOUD_SHIBBOLETH_DEBUG
I wonder if we want that in 2.2 branch to be released with 2.2.3?
> ShibbolethView: Open a debug windows that shows cipher info.

- src/libsync/discoveryphase.cpp
- src/libsync/discoveryphase.h
- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- src/libsync/syncengine.cpp
- src/libsync/syncengine.h
- src/libsync/syncjournaldb.cpp
- src/libsync/syncjournaldb.h
When it changes, assume a backup was recovered, and keep conflict files.
Issues: #2325 and https://github.com/owncloud/enterprise/issues/966
> SyncEngine: Reads the data-fingerprint property

- src/libsync/ownsql.cpp
QByteArray is used for checksum
> ownsql: handle QByteArray without converting to QString

- src/libsync/discoveryphase.cpp
Reverts owncloud/client#4993, could be the cause of #5092 and the cost is higher than the benefit if this is the case. A network request taking more than 30 seconds isn't something unlikely in this world and shouldn't be a good reason to abort. We should try to untangle the threads dependencies to properly fix this if possible instead.
> Revert "Fix a deadlock when shutting down during discovery"

- src/libsync/syncengine.cpp
Once upon a time, the SyncEngine was instantiated once per sync. But now that the SyncEngine is kept between sync, we need to reset all these variable between syncs.
> SyncEngine: Fix detection of backup or full resync

- src/libsync/abstractnetworkjob.cpp
- src/libsync/networkjobs.cpp
- src/libsync/propagatedownload.cpp
This is a move away from the original policy where jobs would only follow
redirects in special cases.
Two restrictions are in place:
1. We do not allow protocol downgrades (https -> http) 
2. We stop redirects after we find them looping (e.g. old = new url, or indirectly when looping 10
times).
This is closer to RFC conforming behavior, although currently we will treat
301 replies like they were 302. This is for a separate commit.
> Always follow redirects in network jobs

- src/gui/owncloudgui.cpp
- src/gui/owncloudgui.h
The tray menu is now only updated when it becomes visible or while
it is visible.
> Tray menu: Update only on demand #4990 #4985

- src/gui/syncrunfilelog.cpp
Adds the rename target to the the sync log that lies around in the sync dir. Helpful to understand nifty problems.
> Show the rename target in the client log file.

- src/gui/folderstatusmodel.cpp
- src/gui/folderstatusmodel.h
I got into a situation where the model would endlessly request the directory
contents from the server because we did not notice yet that the server
is actually in maintenance mode while we were expanding the tree view when
changing the tab to the account or when just expanding it by clicking.
> Selective Sync: Fix request loop and show error in view

- src/libsync/excludedfiles.cpp
Previously, we only checked the hiddenness of the target file and
ignored the hiddenness of the containing folders. This lead to
undesired behavior when people synced their home folders and there
was a folder watcher notification for a non-hidden file in one of
the hidden folders.
I'm not fully sure why, but sometimes notifications for .foo/bar were
already ignored, but notifications for .foo/bar/car were not. This may
be because of how we set up the FolderWatchers on Linux.
The new behavior is to check all path components for hiddenness, up
until the base path (but excluding the base path, so using a hidden
folder as a sync folder will work).
> Excludes: Consider files in hidden folders excluded #5163

- src/gui/owncloudgui.cpp
- src/gui/owncloudgui.h
I even had this issue long before 2.3 that submenus suddenly disappeared.
Now we refrain from updating while visible.
> OS X: Try to fix tray menu not updating correctly #5158

- src/gui/folder.cpp
It was surprising to have a broken symlink return empty for
canonical path.
> Folder/Watcher: Fix up #5174 #5153

- src/libsync/connectionvalidator.cpp
We wwer enot connecting to the right signal from the check server
job, and therefore we were not catching the condition in which the
json was invalid. We would then never terminate the ConnectionValidator job.
Note that instanceNotFound is also emited if there is a network error.
The log looked like this:
10:25:51.247 OCC::CheckServerJob::finished: status.php from server is not valid JSON!
10:25:51.248 OCC::CheckServerJob::finished: status.php returns:  QMap()   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x2b6a790)
10:25:51.248 OCC::CheckServerJob::finished: No proper answer on  QUrl("http://localhost/~owncloud/status.php")
10:26:23.235 OCC::AccountState::checkConnectivity: ConnectionValidator already running, ignoring "owncloud@localhost"
10:26:55.235 …
> ConnectionValidator: properly handle error in status.php

- src/libsync/owncloudpropagator.cpp
- src/libsync/syncengine.cpp
- test/syncenginetestutils.h
- test/testsyncengine.cpp
Two bugs:
- The change filed are not considered as move, they are re-downloaded
but the old file was not removed from the database. The change in
owncloudpropagator.cpp takes care of removing the old entries.
- Next sync would then remove the file in the server in the old folder
This was not a problem until we start reusing the sync engine, and
that the _renamedFolders map is not cleared. We were before deleting
a non-existing file. But now we delete the actual file.
Also improve the tests to be able to do move on the server.
This include support for file id.
Issue #5192
> SyncEngine: Fix renaming of folder when file are changed

- src/cmd/cmd.cpp
We ignored csync log, but we also need to silent Qt debug output.
We need to ignore it at the very begining because there might be
qDebug also in account creation.
Issue #5196
> owncloudcmd: fix --silent

- src/gui/owncloudgui.cpp
- src/gui/owncloudgui.h
* QDBus workaround for Qt 5.5.0 only, there were reports of the tray
working fine with 5.5.1. #5164
* OWNCLOUD_FORCE_QDBUS_TRAY_WORKAROUND to force the workaround on an off
* OWNCLOUD_TRAY_UPDATE_WHILE_VISIBLE to enable or disable updating of
the menu while it's visible
* Track the visibility of the tray menu with aboutToShow/aboutToHide
only on OSX - the aboutToHide signal doesn't trigger reliably on linux
* Refactor such that setupContextMenu is different from updateContextMenu
* Don't use on-demand updating of the tray menu when the qdbus workaround
is active, instead to occasional (30s) updates of the tray menu.
> Tray: Workaround collection

- src/gui/accountsettings.cpp
- src/gui/accountsettings.ui
- src/gui/folderstatusmodel.cpp
- src/gui/folderstatusmodel.h
Instead of using the regular selective-sync UI (where it's unclear what
the "Cancel" button would even mean in this context), provide a
different set of buttons that allow the user to quickly synchronize
all pending big folders, none of them, or perform manual changes
as usual.
> Improve the "new big folder" UI #5202

- src/gui/owncloudsetupwizard.cpp
- src/gui/owncloudsetupwizard.h
- src/libsync/clientproxy.cpp
- src/libsync/clientproxy.h
This is analogous to the code in ConnectionValidator. Otherwise Qt did it internally and blocked the UI.
I had this pending in a branch for another issue.
@danimo Sorry that this might collide with your new wizard code.
> Wizard: Do the system proxy lookup in a thread

- src/gui/owncloudgui.cpp
- src/libsync/theme.cpp
- src/libsync/theme.h
- Use a white icon if the context menu is visible.
This is enables the same behaviour as every other App.
Before:
After:
- Enable `QIcon::setIsMask` if compiled on Qt >= 5.6 to allow automatic macOS color handling
(See [QTBUG-42109](https://bugreports.qt.io/browse/QTBUG-42109))
The monochrome icon now better matches the black tone of all other icons (blending with the background) if used with a white menu bar.
The icon now nicely blends with the other icons even if multiple monitors are connected and this is not the active monitor/desktop.
- No changes if the colored icons are used.
As this is my first contribution, I'm not sure if it is ok to add `#ifdef Q_OS_MAC` or should I create methods in the `Utility` class?
> Improve macOS SysTray/StatusBar monochrome icon

- src/libsync/ownsql.cpp
The crash reporter shows a lot of crashes in sqlite3_clear_bindings
which seems to indicate that _stmt is null. We should guard against
a null value in order to avoid crashing.
This should only happen if the prepare call fails. We don't usually
check the return value of the prepare call, but if _stmt is null, the
exec call should return false, not true. We check the result of the
exec call, so this should then abort the sync with an error, rather
than crashing.
> OwnSQL: avoid crashing in SqlQuery::reset_and_clear_bindings

- csync/src/csync_rename.cc
- csync/src/csync_rename.h
- src/libsync/discoveryphase.cpp
- src/libsync/discoveryphase.h
- src/libsync/propagateremotemove.cpp
- src/libsync/propagateremotemove.h
- src/libsync/propagatorjobs.cpp
- test/syncenginetestutils.h
- test/testsyncengine.cpp
Issue #5224
Two problems:
- In the discovery phase, we need to check the selective sync entries of
the source path in case of renames.
- When the rename is done, we need to actually update the black list in the
database.
> SyncEngine: Fix renaming a folder should keep the selective sync state

- shell_integration/nautilus/CMakeLists.txt
- shell_integration/nautilus/createcajaplugin.sh
Caja is a fork of nautilus maintained by the Mate project.
This adds a script to create a caja plugin from the nautilus plugin.
It replaces all occurences of nautilus with caja (case sensitive).
This is done in the same way the nemo plugin is generated from the nautilus one.
> Add script to create a caja plugin.

- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
This PR solves the problem discussed in this PR https://github.com/owncloud/client/pull/5269, implementing the solution of @ckamm which appears to work :
I did not run in any race condition and manualy tested most of the cases. Hope this will work out
@guruz @ogoffart
> Cache the value of last unfinished job in the PropagateDerectory scheduleNextJob 

- src/libsync/syncengine.cpp
The ownCloud 9.1 server has a data-fingerprint property that the admin must
change in case of backup restoration. When this change, the client understands
that a backup was restored, and will generate conflict files and re-upload
new files.
The heuristics based system checks that there is at least two files wose mtime
is put back in the past and no files that goes forward. In that case we ask the
user before creating the conflicts.
This commit disable the heuristics for newer server that have the data-fingerpint.
And change the heuristics to two hours because we want to avoid false positive due
to some clock error, and that 2 hours of lost due to backup restoration is probably
not so bad.
We only ask the user in the heuristics based aproach so in practice this mean that
the …
> SyncEngine: disable heuristics for backup restoration for server >= 9.1

- csync/tests/ownCloud/t7.pl
- src/libsync/propagatedownload.cpp
Otherwise local conflict files may be overridden in a restore
situation. See ticket for details.
> Conflicts: Use the local mtime for the conflict file name #5273

- shell_integration/nautilus/syncstate.py
Issue #4608
- folder state is either OK or SYNC usually
- this extension does not know about if a folder is shareable
- a OK folder is shareable
- a SYNC folder could be uploaded or not uploaded
- this commit looks into file entries below this folder
- if one exists with state OK or SYNC
this folder must have been uploaded
- better would be if the server (gui) tells us
if the folder is uploaded
> nautilus integration: "share" extension for syncing folders

- src/libsync/discoveryphase.cpp
- src/libsync/syncfilestatus.cpp
- src/libsync/syncfilestatus.h
- src/libsync/syncfilestatustracker.cpp
- test/syncenginetestutils.h
- test/testsyncfilestatustracker.cpp
The "S" in the permission is only for the "Shared with me" files.
It is only used to show the shared status in the overlay icons.
But we also wish to show the shared status for files that are shared
"by" the users. We can find that out using the 'share-types' webdav
property. If set, then we are sharing the object.
We fake a 'S' in the permission as for our purpose, they mean the same.
Issue #4788
> Discovery: consider also the "shared by me" as shared

- csync/src/csync.c
- csync/src/csync.h
- csync/src/csync_private.h
- csync/src/csync_update.c
- csync/tests/csync_tests/check_csync_commit.c
- csync/tests/csync_tests/check_csync_create.c
- csync/tests/csync_tests/check_csync_exclude.c
- csync/tests/csync_tests/check_csync_init.c
- csync/tests/csync_tests/check_csync_log.c
- csync/tests/csync_tests/check_csync_statedb_load.c
- csync/tests/csync_tests/check_csync_statedb_query.c
- csync/tests/csync_tests/check_csync_update.c
- csync/tests/vio_tests/check_vio.c
- csync/tests/vio_tests/check_vio_ext.c
- src/cmd/cmd.cpp
- src/gui/folder.cpp
- src/gui/folderstatusmodel.cpp
- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- src/libsync/propagateremotemove.cpp
- src/libsync/propagateuploadng.cpp
- src/libsync/syncengine.cpp
- src/libsync/syncengine.h
- src/libsync/utility.cpp
- src/libsync/utility.h
- test/syncenginetestutils.h
- test/testutility.cpp
We are going to change the webdav path depending on the capabilities.
But the SyncEngine and csync might have been created before the capabilities
are retrieved.
The main raison why we gave the path to the sync engine was to pass it to csync.
But the thing is that csync don't need anymore this url as everything is done by the
discovery classes in libsync that use the network jobs that use the account for the urls.
So csync do not need the remote URI.
shortenFilename in folderstatusmodel.cpp was useless because the string is the
_file of a SyncFileItem which is the relative file name, that name never
starts with owncloud://.
All the csync test creates the folder because csync use to check if the folder
exists. But we don't need to do that anymore
> libsync: Don't store the remote URI in the csync or in the SyncEngine

- src/gui/activitywidget.cpp
This refers to the message shown when copying the list of unsynced items on the activity tab
> Fixing a typo on a message

- src/gui/accountsettings.cpp
- src/gui/owncloudsetupwizard.cpp
- src/libsync/filesystem.cpp
- src/libsync/filesystem.h
Because on OS X the parent folder might not protect
against access.
> Folder: Make folder only accessible by user #5282

- src/gui/owncloudsetupwizard.cpp
- src/gui/wizard/owncloudsetuppage.cpp
- src/libsync/networkjobs.cpp
This also nicely displays the 'Untrusted domain' message of oC.
The link to add a trusted domain (via web browser) is clickable.
> Wizard: Show if server asks for client certificate #2799 #69

- src/cmd/cmd.cpp
As the URL might be print on the logs.
Also don't change the scheme from http to owncloud.
This was required before when we were using neon through csync, but now that
we use QNAM for everything we don't need it. The credentials from the account
are used.
> owncloudcmd: Don't put the password in the URL

- src/libsync/account.cpp
- src/libsync/capabilities.cpp
- src/libsync/owncloudpropagator.cpp
- src/libsync/propagateuploadng.cpp
The rules to select the webdav url are now:
- If the server reports that the new chunking algorithm is working,
always use remote.php/dav/files/<username>
This capability can be overriden with an environment variable
- Otherwise, use the dav path provided by the theme, which defaults to
remote.php/webdav
This means that with the newer server, the branding can no longer override
the webdav URL. If there is still an usecase for the branding to do so, we
need to find another way to override it. But it is now more complicated to
configure as might need include the username and need different endpoint
depending on the operations (chunks or not)
> libsync: use the new webdav url if the server reports it

- CMakeLists.txt
Currently, if get_git_head_revision() doesn't define GIT_SHA1 (which it doesn't in some cases) it's possible to end up with the following error:
CMake Error at CMakeLists.txt:69 (if):
if given arguments:
"STREQUAL" "GITDIR-NOTFOUND"
Unknown arguments specified
This PR fixes this issue by making sure both left and right hand arguments to STREQUAL are always strings, even if GIT_SHA1 is undefined.
> Correctly handle possible missing GIT_SHA1.

- src/libsync/capabilities.cpp
- src/libsync/capabilities.h
- src/libsync/propagateuploadv1.cpp
Reviewed https://github.com/owncloud/client/pull/5364 needed technical correction and tests
Tested agains oc92 in following scenarios:
- **chunking capability set to true on server**: triggers chunkingNG
- **chunking capability set to false on server**: triggers old chunking with parallel chunk upload
- **chunkingParallelUploadDisabled capability not existing** : triggers old chunking with parallel chunk upload
- **chunkingParallelUploadDisabled set to true**: triggers old chunking without parallel chunk upload
- **chunkingParallelUploadDisabled set to false**: triggers old chunking with parallel chunk upload
- **chunking capability set to false on server and chunkingParallelUploadDisabled set to true**: triggers old chunking without parallel chunk upload
@moscicki @ogoffart
> Add capability to disable parallel chunked upload #5364

- src/gui/owncloudsetupwizard.cpp
Fixes #5408 #5407.
The problem was that cleanup of the credentials page set the
credentials of the account back to dummy, thereby overriding
things like shib usernames.
This should be broken since a932eac832b442cca763197240f036905dd284da.
> Wizard: Detach saved account from wizard

- src/cmd/cmd.cpp
- src/gui/folder.cpp
- src/gui/folderman.cpp
- src/libsync/syncengine.cpp
- src/libsync/syncengine.h
Fix for #5317. If the folder isn't there initially, retry occasionally so users don't have to manually restart.
Note that the case of a folder being there, vanishing and then being there again is very likely still broken. (Does the DB reconnect? Do the FolderWatchers do the right thing?)
> Regularly retry an unavailable folder

- src/libsync/ownsql.cpp
- src/libsync/ownsql.h
This actually happens in low-disk situations.
> Sql: Allow prepare fail for PRAGMA quick_check #5357

- src/gui/owncloudsetupwizard.cpp
It might be that we intentionally don't validate the url before attempting to connect to it. But if there's a connection failure and the url is invalid, the likely cause of the connection failure is the invalid url.
(If we don't intentionally don't validate, checking beforehand would be better!)
> Wizard: Let the user know if url is invalid #5398

- src/libsync/account.cpp
Some custom server use persistent cookies with the auth token. So we should
clear all the cookies when disconnecting.
Account::clearCookieJar is only called from the HTTPCredentials. This funciton
is not used for shibboleth.
There is probably no reasons to keep the HTTP cookie anyway.
Issue #5370
> HTTPCreds: remove all cookies when logging out

- shell_integration/dolphin/ownclouddolphinactionplugin.cpp
- shell_integration/dolphin/ownclouddolphinoverlayplugin.cpp
I use the owncloud client by having a directory `~/.owncloud` which is getting synced and placing symlinks in my home directory `ln -s ~/.owncloud/documents ~/Dokumente`. With the current owncloud client my Dolphin file manager does not show the status of the files when I open the symlinked folders and I cannot use the sharing functionality either.
Therefore, this patch normalizes the directories, to let the plugin know, that the files in the symlinked directories are part of the owncloud sync directory.
> Symlink Support for Dolphin Plugins

- src/libsync/capabilities.cpp
- src/libsync/capabilities.h
- src/libsync/owncloudpropagator.cpp
- src/libsync/propagateupload.cpp
- src/libsync/propagateupload.h
- src/libsync/propagateuploadng.cpp
- src/libsync/propagateuploadv1.cpp
- src/libsync/syncjournalfilerecord.cpp
- test/CMakeLists.txt
- test/syncenginetestutils.h
- test/testuploadreset.cpp
Previously this wasn't happening for errors that were not
NormalErrors because they don't end up in the blacklist.
This revises the resetting logic to be independent of the
error blacklist and make use of UploadInfo::errorCount
instead.
412 errors should reset chunked uploads because they might be
indicative of a checksum error.
Additionally, server bugs might require that additional
errors cause an upload reset. To allow that, a new capability
is added that can be used to advise the client about this.
> Reset stuck chunked uploads eventually #5344

- doc/faq.rst
This PR, as requested in #1067:
- Adds a new entry to the FAQ explaining that there is a directory depth limit, and why it is there.
> Add Sync Client's Directory Depth Limit To FAQ

- doc/autoupdate.rst
As requested in #5431, this PR:
- removes the incorrect MacOS X automatic update instructions
> Update the MacOS automatic update instructions

- doc/building.rst
This addresses the issue only on OS X through homebrew. It should be stated though, that qtwebkit is not part of the qt5core lib and therefore a requirement for the project to build in the rest of the OSS
> Reference to build Qt5 with qtwebkit support in the docs #5129

- src/libsync/syncfilestatustracker.cpp
- src/libsync/syncfilestatustracker.h
- test/testsyncfilestatustracker.cpp
The current logic tried to avoid a DB lookup just to fetch whether
the file is shared or not since that info is already in the
SyncFileItem. The implementation would however need to decrease the
sync count for itself (and parents) before emitting the new status,
thus emitting the OK status for parents before that last child that
ended the propagation for that folder.
Change the implementation to achieve what we want: give the
possibility to decSyncCount to use a pre-fetched sharing state while
still doing the emission for all involved files. This ensures that
the leaf file also gets its status emitted before its parents.
Issue #4797
> StatusTracker: Emit OK for the last child before parents

- src/libsync/propagateupload.h
- src/libsync/propagateuploadng.cpp
- test/syncenginetestutils.h
The server sorts the chunk by name alphabetically. So if we want to keep
the chunk in order, we need to add a few '0' in front of the chunk name
> ChunkingNG: add '0' padding on the filename

- src/gui/creds/shibbolethcredentials.cpp
Previously shib multiaccount didn't work at all because the
session cookie was stored in the same keychain entry.
> Shib: Use different keychain entry per account #5469

- src/libsync/propagateuploadng.cpp
- src/libsync/syncengine.cpp
- src/libsync/syncjournaldb.cpp
- src/libsync/syncjournaldb.h
- test/syncenginetestutils.h
- test/testchunkingng.cpp
Will help for https://github.com/owncloud/core/issues/26981
> Chunking ng cleanup

- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderman.cpp
- src/gui/folderman.h
- src/gui/folderstatusmodel.cpp
- src/gui/protocolwidget.cpp
- src/gui/protocolwidget.h
- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- src/libsync/progressdispatcher.h
- src/libsync/syncengine.cpp
- src/libsync/syncengine.h
- src/libsync/syncfileitem.h
- src/libsync/syncfilestatustracker.cpp
- src/libsync/syncfilestatustracker.h
- src/libsync/syncresult.cpp
- src/libsync/syncresult.h
- test/CMakeLists.txt
- test/benchmarks/benchlargesync.cpp
- test/owncloud_add_test.cmake
- test/syncenginetestutils.h
- test/testsyncengine.cpp
This improves the number of files that can be synced in one shot.
Issue #5237
This depends on #5400 to work properly
> Delete SyncFileItems after propagation

- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- test/testsyncengine.cpp
Delete finished job in the PropagateDerectory scheduleNextJob. 
This should reduce code complexity from https://github.com/owncloud/client/pull/5274 and solve the issue https://github.com/owncloud/client/pull/5269
> Delete finished job in the PropagateDirectory scheduleNextJob. #5269

- src/gui/accountmanager.cpp
- src/gui/wizard/owncloudshibbolethcredspage.cpp
- src/libsync/account.cpp
- src/libsync/account.h
- src/libsync/cookiejar.cpp
- src/libsync/cookiejar.h
> Cookies: Use different DB for different accounts

- src/gui/accountmanager.cpp
- src/gui/accountmanager.h
- src/gui/application.cpp
Previously, we'd try migrating from legacy settings if reading
the settings failed with an error. Now, we try again after a
couple of seconds and eventually give up.
> Settings: Don't migrate settings on access error #5499

- admin/win/docker/Dockerfile
While building a themed client for 2.3 I noticed your Dockerfile was not up to date.
> Update windows docker file to use 2.3 OBS repo

- src/libsync/accessmanager.cpp
If we call
setConfiguration(QNetworkConfiguration());
This sets an invalid configuration on the QNAM.
But later, when we really go online because interfaces are discovered,
QNetworkAccessManagerPrivate::_q_onlineStateChanged is called (with isOnline=true).
And this will set the state to disconnected because customNetworkConfiguration is
true, and the networkConfiguration state is disabled.
The workaround we to fix another bug on Windows in which the default network
configuration was not behaving properly.
The issue on linux is hard to reproduce and only happen in some condition,
but it was reproduced on smashbox when they run two owncloudcmd at the same time.
Issues: #4720 , #3600
> AccessManager: don't set an invalid network configuration on linux

- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- src/libsync/propagateuploadv1.cpp
The test sets OWNCLOUD_MAX_PARALLEL to 1 to disable parallelism.
But since the max amount of parallelism is twice as much, that does not
work.
So change the way we compute the hardMaximumActiveJob: Use the value of
OWNCLOUD_MAX_PARALLEL to maximize this amount and base the maximum amount
of transfer jobs on it instead of the other way.
A result of this change is that, in case of bandwidth limit, we keep the
default of 6 non-transfer jobs in parallel. I believe that's fine since
the short jobs do not really use bandwidth, so we can still keep the same
amount of small jobs.
> Propagator: Fix t8.pl

- doc/architecture.rst
- doc/autoupdate.rst
- doc/building.rst
- doc/introduction.rst
- doc/navigating.rst
- doc/options.rst
- doc/owncloudcmd.1.rst
- doc/owncloudcmd.rst
- doc/troubleshooting.rst
- doc/visualtour.rst
As I was going through the docs to fix #5444, I noticed a number of grammar and spelling issues. This PR sorts out the issues that I found. Also, when attempting to build the docs, it pointed out a number of errors as well. These are also fixed in this PR.
> Fix grammar and spelling errors in the documentation

- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- src/libsync/propagatedownload.cpp
- src/libsync/propagateremotemove.h
- src/libsync/propagateuploadng.cpp
- src/libsync/propagateuploadv1.cpp
- src/libsync/propagatorjobs.cpp
- src/libsync/propagatorjobs.h
- test/testsyncengine.cpp
This is pull request finishes the work to fix TestSyncEngine::abortAfterFailedMkdir by ensuring that we either go down in the job tree (e.g. scheduleNextJob, abort), or up (finished) on a stack to avoid reentrancy.
This is mixed with refactoring to split the subjob logic from PropagateDirectory in a PropagateCompositeJob class to make it easier to add a dynamic creation of item jobs.
> Create PropagateItemJobs on the fly

- doc/building.rst
- doc/introduction.rst
This PR:
- Updates the docs to use the Sphinx-doc `|version|` tag to represent the version, so that it's always interpolated to the latest version, instead of a hard-coded version.
- owncloud/documentation/issues/2848
> Update client version from 2.2 to 2.3

- src/gui/notificationconfirmjob.cpp
- src/gui/ocsjob.cpp
- src/gui/owncloudsetupwizard.cpp
- src/gui/thumbnailjob.cpp
- src/libsync/abstractnetworkjob.cpp
- src/libsync/abstractnetworkjob.h
- src/libsync/account.cpp
- src/libsync/account.h
- src/libsync/networkjobs.cpp
- src/libsync/propagatedownload.cpp
- src/libsync/propagateremotedelete.cpp
- src/libsync/propagateremotemove.cpp
- src/libsync/propagateupload.cpp
- src/libsync/propagateupload.h
- test/syncenginetestutils.h
* For requests:
- reuse the original QNetworkRequest, so headers and attributes
are the same as in the original request
- determine the original http method from the reply and the request
attributes
- keep the original request body around such that it can be sent
again in case the request is redirected
* Simplify the interface that is used for creating new requests in
AbstractNetworkJob.
> AbstractNetworkJob: Improve redirect handling #5555

- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- src/libsync/propagateupload.cpp
It is possible to create files with filenames that differ
only by case in NTFS, but most operations such as stat and
open only target one of these by default.
When that happens, we want to avoid uploading incorrect data
and give up on the file.
Typically this situation should never occurr during normal use
of Windows. It can happen, however, when a NTFS partition is
mounted in another OS.
> Windows/NTFS: Do not attempt to upload inaccessible files #5544

- src/gui/wizard/owncloudconnectionmethoddialog.cpp
This is a possible fix for #3850, applying custom window flags (http://doc.qt.io/qt-5.8/qt.html#WindowType-enum) on the connection method dialog. These avoid resizing the dialog and displaying a maximize button on OS X and context help button on Windows.
<p align="center">
</p>
<p align="center">
</p>
<p align="center">
</p>
And:
<p align="center">
</p>
> Using different window flags on the connection method dialog

- src/libsync/theme.cpp
I didn't want to touch this visible translated string in a
patch release so I just switched the data.
For Qt versions before 5, we continue to show the build-time version
of OpenSSL but it's clearly marked as such.
> About: Show the runtime versions of Qt and OpenSSL #5592

- src/gui/activitylistmodel.cpp
The backtrace seems to indicate that the account is invalid.
I don't know how this can happen, maybe the account's display
name was changed while the app is running?
Backtrace:
Crash: EXC_BAD_ACCESS / KERN_INVALID_ADDRESS at 0x18
Module "owncloud", in OCC::AccountState::account
Module "owncloud", in OCC::ActivityListModel::data
Module "owncloud", in OCC::ActivityItemDelegate::paint
Module "QtWidgets", in QListView::paintEvent
Module "QtWidgets", in QWidget::event
Module "QtWidgets", in QFrame::event
Module "QtWidgets", in QAbstractScrollArea::viewportEvent
Module "QtWidgets", in QAbstractItemView::viewportEvent
Module "QtWidgets", in QAbstractScrollAreaFilter::eventFilter
Module "QtCore", in QCoreApplicationPrivate::sendThroughObjectEventFilters
> ActivityListModel: attempt to fix a crash.

- src/gui/folder.h
- src/gui/folderman.cpp
- src/gui/folderman.h
- src/gui/folderwizard.cpp
- src/gui/owncloudsetupwizard.cpp
- src/gui/wizard/owncloudadvancedsetuppage.cpp
- src/gui/wizard/owncloudadvancedsetuppage.h
- test/testfolderman.cpp
Primarily address #5597: Don't propose existing folders as sync folders in wizards to not cause accidents.
> Improve folder selection in wizards

- doc/advancedusage.rst
- doc/envvars.rst
In particular the `OWNCLOUD_CHUNK_SIZE` as requested per #2449.
I looked through the code and it seems the env vars override the conf file, but I'm not 100 % sure.
The `OWNCLOUD_CRITICAL_FREE_SPACE_BYTES` and `OWNCLOUD_FREE_SPACE_BYTES` are now mentioned in two places.
> Documented the usage of environment variables.

- src/gui/wizard/owncloudwizardresultpage.cpp
Before we would only open the part of the url that the users entered.
Now if the wizardUrlPostfix is used this should be appended to that
when opening the browser on the result page.
> complete url when using themed wizardUrlPostfix

- doc/building.rst
- The duplicate and some typos were introduced in 42aed56a5a92a32b86e2bdd1c6e9d75e27728c8b 
- Also fixes some minor format issues. There's a lot of notes in this docs, we should refactor some.
> Fixing a duplicate in the build instructions

- src/gui/activitywidget.cpp
- src/gui/folderwizard.cpp
- src/gui/owncloudsetupwizard.cpp
- src/libsync/abstractnetworkjob.cpp
- src/libsync/abstractnetworkjob.h
- src/libsync/connectionvalidator.cpp
- src/libsync/networkjobs.cpp
- src/libsync/networkjobs.h
- src/libsync/propagatedownload.cpp
- src/libsync/propagatedownload.h
- src/libsync/propagateremotedelete.cpp
- src/libsync/propagateremotedelete.h
- src/libsync/propagateremotemkdir.cpp
- src/libsync/propagateremotemove.cpp
- src/libsync/propagateremotemove.h
- src/libsync/propagateupload.cpp
- src/libsync/propagateupload.h
- src/libsync/propagateuploadng.cpp
- src/libsync/propagateuploadv1.cpp
By default QNetworkReply::errorString() often produces messages like
`"Error downloading <url> - server replied: <reason>"`
but the "downloading" part invariably confuses people since the
error might very well have been produced by a PUT request.
This commit produces clearer error messages for HTTP errors.
Additionally:
* Remove some unnecessary null checks from slots connected to
network job signals and document that these signals never send
null replies.
* There was a bug where AbstractNetworkJob::_timedout wasn't
set when derived classes overrode slotTimeout. We now ensure
it's always set by disallowing overrides of slotTimeout.
Instead it now calls onTimedOut, which allows custom handling.
* Several subclasses declared errorString, isTimedOut. Move
these to AbstractNetworkJob.
* Unify …
> Improve http error messages; cleanup

- src/cmd/cmd.cpp
I release my code under the MIT license ;-)
> added owncloudcmd  bwlimit 

- src/gui/owncloudgui.cpp
- src/gui/owncloudsetupwizard.cpp
- src/gui/owncloudsetupwizard.h
On my OS X, it might get hidden under other apps while I opened it and then want to quickly
verify something in another app.
> Share Dialog: Bring to top on tray click #5515

- src/gui/folderstatusmodel.cpp
The problem was that split("", SkipEmptyParts) is the empty list.
See
https://sentry.io/owncloud/desktop-win-and-mac/issues/251167186/
> FolderStatusModel: Fix crash for empty relativePath

- src/gui/proxyauthhandler.cpp
- src/libsync/account.cpp
- src/libsync/account.h
See
https://sentry.io/owncloud/desktop-win-and-mac/issues/243433178/activity/
https://sentry.io/owncloud/desktop-win-and-mac/issues/234182688/activity/
The problem was that an account's QNetworkAccessManager can be deleted
when reentering the event loop.
> Fix a crash in ProxyAuthHandler

- src/gui/CMakeLists.txt
- src/gui/ocssharejob.cpp
- src/gui/ocssharejob.h
- src/gui/sharedialog.cpp
- src/gui/sharedialog.ui
- src/gui/sharelinkwidget.cpp
- src/gui/sharelinkwidget.h
- src/gui/sharelinkwidget.ui
- src/gui/sharemanager.cpp
- src/gui/sharemanager.h
- src/gui/shareusergroupwidget.cpp
- src/gui/shareusergroupwidget.h
- src/gui/shareusergroupwidget.ui
- src/gui/shareuserline.ui
See https://github.com/owncloud/client/issues/5655
For servers that support it:
For older servers:
> Multiple link shares and UI adjustments for share dialog

- src/libsync/account.cpp
- src/libsync/propagateupload.cpp
Now that #2558 has been closed there is no point of having to check whether Qt is <5.0.
> Remove all conditional checks for Qt 4.x

- src/gui/generalsettings.cpp
- src/libsync/theme.cpp
- src/libsync/theme.h
Refactor the code to use a separate function to check if mono icons are available.
This could be used in #5229.
Open questions:
- This only checks for a single color (black or white). Should this be changed to check for both?
(macOS currently requires black&white icons, this could also be changed to white only if build on >= Qt 5.6.0).
> Move check for mono icons into separate function

- src/libsync/utility_win.cpp
Fixes https://github.com/owncloud/client/issues/2719
> When creating explorer favorite use more specific windows functions

- src/gui/application.cpp
- src/gui/wizard/owncloudwizard.cpp
Better immediately show the settings dialog where people can see what's going on.
They can go to sync folder or webinterface from there.
> Wizard: Don't show not-so-useful result page #5726

- src/libsync/account.cpp
I'm confident this is unnecessary. The original bug in #3283 was
to call ignoreSslErrors() without an argument in the 'accept'
case, which meant ignoring *all* subsequent SSL errors.
With that fixed, explicitly aborting the reply and resetting QNAM
is not needed since not ignoring the error will lead to the SSL
handshake failing.
See also:
75b38d1a2ffe57d0f1eb3ebb8c5f30b8b2a185e4 (workaround introduced)
89376e14d6135a6f39a6df99d54fde253573575c (real fix)
76ce5adbf02af052ab8d7596b8ded75c7d4d7fcb (cherry-pick of workaround)
> SSL error handling: Remove unnecessary confusing code

- sync-exclude.lst
As per issue #5701, if the server does not support it, let the server
show return an error, but we should not blacklist it localy
> Exclude list: remove .htaccess

- src/gui/sharedialog.cpp
- src/gui/sharelinkwidget.ui
For https://github.com/owncloud/enterprise/issues/1914
> Sharing: Optionally show warning that links are public

- src/gui/accountsettings.cpp
- src/gui/accountstate.cpp
- src/gui/accountstate.h
- src/libsync/connectionvalidator.cpp
- src/libsync/connectionvalidator.h
When we first detect a 503 (probably from a PROPFIND) and enter the
ServiceUnavailable state, we new trigger a status.php query that will
switch the state to MaintenanceMode if necessary.
> Detect maintenance mode #4485

- csync/src/csync_statedb.c
- src/libsync/syncjournaldb.h
- test/testsyncengine.cpp
When a new folder becomes selective-sync excluded, we already mark it
and all its parent folders with _invalid_ etags to force rediscovery.
That's not enough however. Later calls to csync_statedb_get_below_path
could still pull data about the excluded files into the remote tree.
That lead to incorrect behavior, such as uploads happening for folders
that had been explicitly excluded from sync.
To fix the problem, statedb_get_below_path is adjusted to not read the
data about excluded folders from the database.
Currently we can't wipe this data from the database outright because we
need it to determine whether the files in the excluded folder can be
wiped away or not.
See owncloud/enterprise#1965
> Selective sync: Skip excluded folders when reading db

- src/gui/folderman.cpp
This should help clearly delimiting them in the log for multi-account setups.
This information is already available elsewhere in the log in any case.
Issue #5672
> Add the account name and folder when starting the sync

- src/gui/sharelinkwidget.ui
Backport of 3872e060ba33913e43714776a1afce787e772351
> Sharing: Show warning that link shares are public #5785 #5747

- src/gui/accountmanager.cpp
@SamuAlfageme This should do it, I see the keychain-removal code being run on delete now. But I've had some trouble seeing the keychain entries. Testing would be appreciated.
> Account: forget credentials on delete #5752

- src/gui/sharemanager.cpp
Older ownCloud servers like 8.2.0 used to use integer ids.
This broke when switching to QJson because toString() on JSON
values is strict and returns "" for integers.
> Share link: Fix parsing integer ids #5777

- src/libsync/propagatedownload.cpp
See owncloud/enterprise#1966
If the server and the client's database go out of sync, there could be
persistent 404 errors. This change ensures that the problem corrects
itself eventually by triggering a remote discovery of the file's
parent folders.
It does not address the root cause that might have lead to the
divergence.
> Download: Retrigger folder discovery on 404

- src/gui/folderstatusmodel.cpp
Fix an assert that happens in beginInsertRows when opening a folder
and that folder is empty.
This can only be reproduced with a debug build of Qt.
> FolderStatusModel: fix assert in Qt when the list of subfolder is empty

- src/gui/CMakeLists.txt
- src/gui/creds/oauth.cpp
- src/gui/creds/oauth.h
- src/gui/owncloudsetupwizard.cpp
- src/gui/wizard/owncloudoauthcredspage.cpp
- src/gui/wizard/owncloudoauthcredspage.h
- src/gui/wizard/owncloudoauthcredspage.ui
- src/gui/wizard/owncloudwizard.cpp
Show smething sensible if the user click on the owncloud icon, and handle errors
Issues: #5813 and #5811
> OAuth: Wizard page

- src/gui/creds/oauth.cpp
- src/libsync/abstractnetworkjob.cpp
- src/libsync/creds/httpcredentials.cpp
- Add category to the all messages (they did not have it was merged right after
the patch to add category everywhere, but this code did not have it.)
- Make sure there is no warnings in the normal flow. (The wizard does a request
without authentication to determine the auth type)
> OAuth: cleanup debug messages

- csync/src/csync_exclude.c
- csync/tests/csync_tests/check_csync_exclude.c
- src/cmd/cmd.cpp
- src/gui/folder.cpp
- src/gui/folderman.cpp
- src/gui/folderwatcher_linux.cpp
- src/gui/ignorelisteditor.cpp
- src/libsync/syncjournaldb.cpp
- src/libsync/syncjournaldb.h
When synchronizing a folder on a samba share, creating files that begin
with ._ is often forbidden. This prevented the client from creating
its ._sync_abcdef.db file.
Now, it'll check whether the preferred filename is creatable, and if
it isn't it'll use .sync_abcdef.db instead.
The disadvantage is that this alternative path won't be ignored by
older clients - that was the reason for the ._ prefix.
> Journal: Don't use a ._ path if it won't work #5633

- .github/issue_template.md
- src/libsync/owncloudtheme.cpp
Desktop client category was renamed, old link was 404 - see: https://central.owncloud.org/t/new-central-categories-you-decide
> Update central.owncloud.org link (#5862)

- test/testsyncengine.cpp
Checks instruction, direction, size, modtime for three common cases.
> SyncEngine: Add unittest for SyncFileItem properties #5855

- src/libsync/discoveryphase.h
- src/libsync/owncloudpropagator.cpp
- src/libsync/propagateupload.h
- src/libsync/propagateuploadng.cpp
This should solve https://github.com/owncloud/client/issues/5850. 
Please note: we cannot set chunk size of PUT V1 to _chunkSize which is dynamic because PUT V1 will not adjust dynamic chunk size. If we want it, we need to make code adjusting dynamic chunk size both for V1 and NG.
> Classify chunked items correctly. Issue #5850

- src/gui/main.cpp
src/gui/main.cpp:112:9: warning: bool literal returned from 'main' [-Wmain]
Used 1 to keep previous behaviour. I supposed the code was meant
to return success (0), but it does not really matter anyway.
> main.cpp: Fix a compiler warning

- src/gui/protocolwidget.cpp
- src/libsync/owncloudpropagator.cpp
- src/libsync/progressdispatcher.cpp
- src/libsync/syncengine.cpp
- src/libsync/syncfileitem.h
- src/libsync/syncfilestatustracker.cpp
Before, blacklisted errors were set to FileIgnored status and hence
displayed as warnings. Now, they have their own BlacklistedError
category which allows them to appear as errors in the issues list and in
the shell integration icons.
> Blacklist: Don't let errors become warnings #5516

- src/gui/accountstate.cpp
- src/gui/accountstate.h
This only applies when the server was explicitly in maintenance mode or
when it was 503-unavailable.
> AccountState: Add a 1-5min reconnection delay #5872

- src/gui/CMakeLists.txt
- src/gui/accountsettings.cpp
- src/gui/accountsettings.h
- src/gui/activitywidget.cpp
- src/gui/activitywidget.h
- src/gui/folderstatusdelegate.cpp
- src/gui/folderstatusdelegate.h
- src/gui/issueswidget.cpp
- src/gui/issueswidget.h
- src/gui/issueswidget.ui
- src/gui/protocolwidget.cpp
- src/gui/settingsdialog.cpp
- src/gui/settingsdialog.h
- src/gui/settingsdialogmac.cpp
- src/gui/settingsdialogmac.h
* Allow filtering of ignores and warnings to see only important bits.
* Navigate from the folder view to the error view by clicking on the
error list with the red background.
* Move the error list into its own ui file to allow easier extension.
* Fix issue around tab id handling in ActivitySettings.
* Rename "Action" column to "Issue".
Not done:
* Protocol and Issue view probably want to share the same underlying
model.
* Blacklisting of errors currently moves them into the 'ignored file'
category; that should change because then they don't appear as errors
and are easily filtered away.
* How should non-file errors be displayed? (e.g. "not enough disk space
to start the sync!")
> Add a more functional error view #5516

- src/libsync/account.cpp
- src/libsync/account.h
- src/libsync/creds/httpcredentials.cpp
- src/libsync/creds/httpcredentials.h
Calling forgetSensitiveData() on account deletion leads to a timer for
clearQNAMCache() being queued. Then the Account object is deleted. The
Credentials object stays alive for now because it has a deleteLater
deleter.
If the timer calls into a slot on the Credentials object, the _account
pointer will be invalid at this time.
As a workaround, move the target slot to Account - that way it will not
be called as the account object is already destroyed.
However since Account and Credentials are mutually dependent, it would
be much preferable if their lifetimes were linked, avoiding this
category of bugs.
The current behavior was introduced in
d40c56eda561e3a541bf1b23f70fa8d659d3037e and I currently don't
understand why - maybe there's another way of dealing with the problem
that existed then.
> Fix crash on account deletion

- src/gui/creds/shibbolethcredentials.cpp
- src/gui/creds/shibbolethcredentials.h
- src/libsync/account.cpp
- src/libsync/account.h
- src/libsync/creds/abstractcredentials.h
- src/libsync/creds/dummycredentials.cpp
- src/libsync/creds/dummycredentials.h
- src/libsync/creds/httpcredentials.cpp
- src/libsync/creds/httpcredentials.h
- test/syncenginetestutils.h
The QNAM may continue to outlive both.
Rename Credentials::getQNAM() to createQNAM() while we're at it - it's
used to make a new QNAM that will subsequently be owned by the Account
object.
See d01065b9a12e69ca493a232f3a8e8f3d416fed52 for rationale.
Relates to
d40c56eda561e3a541bf1b23f70fa8d659d3037e
147cf798a6f13c9b53a9f1fb2db1ef26c8c63273
> Account/Credentials: Have identical lifetimes

- src/gui/folderman.cpp
- src/gui/issueswidget.cpp
- src/gui/issueswidget.h
- src/gui/issueswidget.ui
And also select the obvious entry if there's only a single possible choice.
> IssuesTab: Hide folder and account filters if they aren't useful

- src/gui/creds/httpcredentialsgui.cpp
- src/gui/creds/oauth.cpp
- src/gui/creds/oauth.h
Since the user is already in the browser, put the error message in the
browser with a message to log out and then log in as the right user.
Issue #5895
> OAuth: Better message when loggin in with the wrong username

- test/owncloud_add_test.cmake
- test/testutility.cpp
No need to do a STR replacement. It actually broke test execution for
Debian.
See https://bugs.debian.org/844937
> Use OWNCLOUD_BIN_DIR directly in C++ code.

- src/libsync/propagateupload.cpp
- src/libsync/propagateupload.h
This was only for Qt <= 5.4, which we don't really support anymore.
And even then, the data corruption is happens very seldomly anyway.
> PropagateUpload: Remove the Qt workaround against data corruption

- src/gui/accountstate.cpp
- src/gui/creds/httpcredentialsgui.cpp
- src/libsync/creds/httpcredentials.cpp
- src/libsync/creds/httpcredentials.h
Before commit d3b00532b1dd9f44cc606e6738b53345c37582cf,
fetchFromKeychain was called everytime we detect that the creds are
invalid (in AccountState::slotInvalidCredentials)
But since that commit, AccountState was calling askFromUser directly,
breaking the refresh of the token.
So I made sure AccountState::slotInvalidCredentials still calls
refreshAccessToken.
Another change that was made was too be sure to clear the cookies
in HttpCredentials::invalidateToken even when we are only clearing the
access_token. That's because the session with a cookie may stay valid
longer than the access_token
> OAuth: Fix refresh of token after expiration

- src/gui/accountstate.cpp
Just to force the logic to re-ask the credenticals, in case we were
already asking them when singin off.
Issue: https://github.com/owncloud/client/issues/5893#issuecomment-316949686
> AccountState: reset _waitingForNewCredentials when signin in

- src/gui/folderwizard.cpp
The Job is a LsColJob, not a MkColJob!
Reproduce by entering a name with invalid character that cause an error 400
in the folder wizard's remote path line edit.
(Relates issue #5924)
> FolderWizard: fix crash in FolderWizardRemotePath::slotHandleLsColNetworkError

- csync/src/csync_exclude.c
- src/libsync/utility_win.cpp
- sync-exclude.lst
By setting the icon in Desktop.ini of the root folder, this adds the icon
both when browsing the folder directly and to the sidebar shortcut.
To avoid overwriting any user setting that could exist in Desktop.ini,
only do this if the file doesn't exist. Editing .ini files on Windows
isn't trivial and isn't worth it given that this file won't exist most
of the time.
Fixes #2446
> Windows: Use the application icon for the sidebar

- doc/navigating.rst
Refs: Issue #5969 (Documentation improvement)
Adding text describing in navigation.rst section Activity Window that you can double click an item to open the corresponding folder.
> Documentation improvement for #5969

- shell_integration/icons/CMakeLists.txt
- shell_integration/nautilus/CMakeLists.txt
- shell_integration/nautilus/createcajaplugin.sh
- shell_integration/nautilus/createnemoplugin.sh
The APPLICATION_SHORTNAME only made it into the nautilus copy of syncstate.py so far.
Now caja and nemo also recieve a branded copy. Correct branding is important for a nemo plugin, because this is part of the socket name that we need for connecting.
> fix branded nemo and caja shell integration

- src/libsync/syncfilestatustracker.cpp
- src/libsync/syncfilestatustracker.h
- test/testsyncfilestatustracker.cpp
Use a custom std::map comparator functor to do all comparisons
on contained QStrings using Qt::CaseInsensitive on macOS and Windows.
Issue #5257
> StatusTracker: Fix different case paths not matching

- src/gui/creds/httpcredentialsgui.cpp
- src/gui/creds/httpcredentialsgui.h
When the GET request from askFromUser is scheduled on the QNAM inside
the slot that handles the QNetworkReply::finished signal, it seems to
not get processed at all.
This workaround moves the sending of the new GET to the event loop,
sidestepping the problem.
> Http credentials: Fix behavior for bad password #5989

- src/CMakeLists.txt
Enable **Data Execution Prevention** (DEP) & **Address space layout randomization** (ASLR) on Windows as exploit mitigation.
See:
https://www.microsoft.com/security/sir/strategy/default.aspx#!section_3_3
https://blogs.technet.microsoft.com/srd/2010/12/08/on-the-effectiveness-of-dep-and-aslr/
> Enable DEP & ASLR on Windows

- src/common/utility_win.cpp
When created from scratch, the owncloud icon won't be picked-up by
explorer unless the right attributes are set on both the sync root and the
Desktop.ini file.
Issue #2446
> Windows: Make sure that the folder and Desktop.ini have the right attributes

- src/gui/creds/httpcredentialsgui.cpp
- src/gui/owncloudsetupwizard.cpp
- src/gui/owncloudsetupwizard.h
- src/gui/wizard/owncloudoauthcredspage.cpp
- src/gui/wizard/owncloudsetuppage.cpp
- src/gui/wizard/owncloudsetuppage.h
- src/gui/wizard/owncloudwizard.cpp
- src/gui/wizard/owncloudwizard.h
- src/gui/wizard/owncloudwizardcommon.h
- src/libsync/abstractnetworkjob.cpp
- src/libsync/abstractnetworkjob.h
- src/libsync/connectionvalidator.cpp
- src/libsync/creds/httpcredentials.cpp
- src/libsync/creds/httpcredentials.h
- src/libsync/networkjobs.cpp
- src/libsync/networkjobs.h
This is the first time the account url may update outside of
account setup.
Summary of redirection handling:
1. During account setup (wizard) - fixes #5954
- status.php gets permanently redirected -> adjust url 
- authed PROPFIND gets *any* redirection -> adjust url
2. During connectivity ping (ConnectionValidator)
- status.php gets permanently redirected -> adjust url (new!)
All other redirections should be followed transparently and
don't update the account url in the settings.
See #5972
> Update server url in case of permanent redirection #5972

- src/libsync/ownsql.cpp
- src/libsync/syncjournaldb.cpp
Also add logging of extended error codes for this IO error, maybe we can
become more specific about which situations should trigger a journal
mode switch.
See #5723
> Journal: Fall back to DELETE on IO error #5723

- src/csync/csync_exclude.cpp
- src/gui/ignorelisteditor.cpp
- sync-exclude.lst
- test/csync/csync_tests/check_csync_exclude.cpp
Otherwise adding patterns that start with # are impossible to add, since
they get treated as comments. Also add this escaping for patterns added
in the ui.
See #6012
> Excludes: Allow escaping # #6012

- src/gui/protocolwidget.cpp
- src/libsync/discoveryphase.h
- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- src/libsync/progressdispatcher.cpp
- src/libsync/propagatedownload.cpp
- src/libsync/propagateupload.cpp
- src/libsync/syncfileitem.h
- src/libsync/syncfilestatustracker.cpp
- test/testsyncengine.cpp
When we see a 507 error, assume that quota is < uploaded size.
> PropagateUpload: Model of remote quota, avoid some uploads #5537

- src/gui/creds/shibbolethcredentials.cpp
- src/gui/creds/shibbolethcredentials.h
- src/libsync/creds/abstractcredentials.cpp
- src/libsync/creds/abstractcredentials.h
- src/libsync/creds/httpcredentials.cpp
- src/libsync/creds/httpcredentials.h
This requires a lot of migration code: the old entries need to be read,
saved to the new locations and then deleted.
See #5830. It's potentially breaking, so please review carefully.
Known side effects of this patch:
* If you go back from 2.4 to 2.3, you'll have to enter the keychain data for your accounts again.
* If you have several accounts pointing to the same url+user, one of them might not have credentials set up on the first start of 2.4.
While working on this I had an idea about an alternate approach: What if we added a "what's the keychain base id" entry to the settings? Then we could add the new account identifier to new accounts and old accounts would work without losing keychain data even when switching between 2.3 and 2.4. The drawback is that we'd never migrate old accounts.
> Credentials: Use per-account keychain entries #5830

- src/gui/creds/oauth.cpp
- src/gui/owncloudsetupwizard.cpp
- src/libsync/abstractnetworkjob.cpp
- src/libsync/creds/httpcredentials.cpp
Grab any permanent redirects from the base url the user entered before attempting to connect to a modified url (with status.php added).
Solves #5954 
Depends on #6016 (for SimpleNetworkJob), only the last commit is new
> Wizard: Handle url-shortener redirects

- doc/navigating.rst
- doc/visualtour.rst
- src/gui/folderstatusmodel.cpp
- src/gui/folderwizard.cpp
... or child folders
There is also no real reason to forbid the user from syncing the same
folder to multiple location on its hardrive.
A real use case is when the user uncheck a big directory using "choose
what to sync", but would still like to sync a folder within this disabled
tree. The user can now do this with the "add folder" feature
Since 2.3, we even support syncing the same local folder to multiple
remote folder, so why not allow syncing the same remote folder several
times?
Relates to issue #3645
> Gui: Allow to add multiple sync folder connection of the same folder

- src/common/syncjournalfilerecord.h
- src/gui/sharedialog.cpp
- src/gui/sharedialog.h
- src/gui/shareusergroupwidget.cpp
- src/gui/shareusergroupwidget.h
- src/gui/socketapi.cpp
- src/gui/socketapi.h
- src/libsync/account.cpp
- src/libsync/account.h
- src/libsync/capabilities.cpp
- src/libsync/capabilities.h
* The sharing ui does a propfind anyway: use that to query the new
property as well!
* For the socket api, asynchronously query the server for the right url
when an action that needs it is triggered.
The old, manually generated URL will be used as fallback in case the
server doesn't support the new property or the property can't be
retrieved for some reason.
Depends on owncloud/core#29021
For #6020
> Private links: Retrieve link through propfind property #6020

- src/common/utility.cpp
- src/common/utility.h
- src/csync/csync_exclude.cpp
- src/csync/csync_update.cpp
- src/libsync/syncengine.cpp
Set OWNCLOUD_UPLOAD_CONFLICT_FILES=1 to trigger this behavior.
Note that this is experimental and unsupported. The real feature is
likely to end up in 2.5.
Uploading conflict files is simply done by removing the pattern from
csync_exclude. The rest here deals with making the conflict notification
ui approximately work.
There are still some concerns about where an uploaded conflict file
appears in the sync protocol and issues list (it should be in both, but
is only in one of them currently!).
See #4557.
> Conflicts: Upload them files if env variable says so

- src/common/common.cmake
- src/common/remotepermissions.cpp
- src/common/remotepermissions.h
- src/common/syncjournaldb.cpp
- src/common/syncjournalfilerecord.h
- src/csync/csync.h
- src/csync/csync_private.h
- src/csync/csync_statedb.cpp
- src/csync/csync_update.cpp
- src/gui/owncloudgui.cpp
- src/libsync/discoveryphase.cpp
- src/libsync/discoveryphase.h
- src/libsync/propagatedownload.cpp
- src/libsync/syncengine.cpp
- src/libsync/syncengine.h
- src/libsync/syncfileitem.h
- src/libsync/syncfilestatustracker.cpp
- test/testsyncjournaldb.cpp
Create a specific type that parses the permissions so we can store
it in a short rather than in a QByteArray
(Note: since most files have the same permissions, i was also wondering if we could not try to "internate" the QByteArray  (storing it into a QSet so they can all be shared.)  But this is Good enough I think.
The other advantage is that we keep all these letters in a centralized place.
> RemotePermissions: Store in a class rather than in a QByteArray to save memory

- src/csync/csync_update.cpp
- src/csync/vio/csync_vio.cpp
- src/csync/vio/csync_vio.h
- src/csync/vio/csync_vio_local_unix.cpp
- src/csync/vio/csync_vio_local_win.cpp
Keep the value stored in the original_path
Saves 15% of the CPU time for csync_update
> csync_vio_local_stat: Try to avoid expensive call to c_utf8_path_to_locale

- src/gui/creds/httpcredentialsgui.cpp
- src/gui/creds/oauth.cpp
- src/libsync/creds/httpcredentials.cpp
We need to use concatPath to avoid possible double '/' in the URLs if the
account url() ends with '/'.
This has become even more of a problem since commit
d1b8370a4ad21c741da507f64a5dbfe82a3fad05 which was resolving the url after
a redirect where most server actually add a '/' if the url is a folder
CC/ @DeepDiver1975
> Fix double slash in URL

- src/csync/csync_private.h
- src/csync/std/c_utf8.cpp
see individual commits:  optimize c_utf8_from_locale and the std::map looking, two of the Three big offender remaining:  https://user-images.githubusercontent.com/959326/30771445-53d4178a-a048-11e7-8668-0c6e43b965c5.png
> optimize csync_update

- src/libsync/bandwidthmanager.cpp
- src/libsync/bandwidthmanager.h
from the destroyed signal, qobject_cast won't work because the object
is already destroyed. One must use reinterpret_cast then
> bandwidthmanager: Fix unregistering devices on delete

- src/libsync/syncengine.cpp
- test/testallfilesdeleted.cpp
I think this fixes a regression.
We don't want to show the delete popup if all metadata change, this might be normal.
> SyncEngine: _hasNoneFiles should be set when there are INSTRUCTION_UPDATE_METADATA

- src/common/syncjournaldb.cpp
quickfix: define the symbol for backwards compat
or FIXME: better solution #ifdef SQLITE_IOERR_SHMMAP where needed...
> support old sqlite before 3.7.7 e.g. CentOS-6

- src/csync/csync_exclude.cpp
- src/csync/csync_exclude.h
- src/csync/csync_private.h
- src/csync/csync_update.cpp
- src/libsync/discoveryphase.cpp
- src/libsync/excludedfiles.cpp
- test/csync/csync_tests/check_csync_exclude.cpp
On my Mac, this halves the time spent in csync_excluded_traversal
when using check_csync_excluded_performance.
On Linux the changes were not so much visible, maybe the fnmatch
there is much faster.
> Excludes: During directory traversal, use QRegularExpression

- src/csync/csync_update.cpp
- test/testsyncengine.cpp
Comparison of file sizes for potential conflicts was added in
0eb9401c624f20a128b46f8eb1fa5a984f9ef61e, but did not extend to checking
the file size in case of potential local moves.
This commit adds this check and adds tests for various move+change
scenarios.
> Rename detection: File size must be equal

- src/gui/owncloudgui.cpp
- src/gui/owncloudgui.h
Previously it could only display synchronization progress or "up to
date". Now it also communicates the same overall state that the icon
shows.
See owncloud/enterprise#2134
> Context menu: More detailed status messages

- src/gui/creds/httpcredentialsgui.cpp
- src/gui/creds/httpcredentialsgui.h
- src/libsync/networkjobs.cpp
This is an ugly solution.
See  #5989
@ogoffart Do you know if timers are stable in this way? I think we'll have to look very carefully at how the credential / account machinery works together in this case.
> HttpCreds: Fix retry after wrong password

- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- src/libsync/propagatedownload.cpp
- src/libsync/propagatedownload.h
- src/libsync/propagateremotedelete.cpp
- src/libsync/propagateremotedelete.h
- src/libsync/propagateremotemkdir.cpp
- src/libsync/propagateremotemkdir.h
- src/libsync/propagateremotemove.cpp
- src/libsync/propagateremotemove.h
- src/libsync/propagateupload.cpp
- src/libsync/propagateupload.h
- src/libsync/propagateuploadng.cpp
- src/libsync/propagateuploadv1.cpp
- test/syncenginetestutils.h
- test/testchunkingng.cpp
@SamuAlfageme can you verify that this fixes issue for ChunkingNG for you? I checked on my local machine and this fixed it.
@guruz I will also add similar thing, but for V1, however there I will check if the file bytes been sent or not. 
Issue #5949
> Fix paused sync file move issue #5949

- src/gui/issueswidget.cpp
- src/gui/issueswidget.ui
- src/gui/protocolwidget.cpp
- src/gui/protocolwidget.h
- src/gui/protocolwidget.ui
The issues tab uses custom ordering where overall and summary sync
issues are displayed first. This ordering is preserved by creating
special sorting logic for the "time" column.
It needed special handling anyway, since sorting by time-string would
have yielded incorrect results.
> Activity: Allow sorting of issues and protocol #6086

- doc/CMakeLists.txt
The old behavior broke builds with other CMake generators like Ninja as it obviously has no concept of $(MAKE)
> Only use $(MAKE) in doc target if make is used as generator

- src/cmd/cmd.cpp
We did not set a log handler so there were no timestamps.
The --debug didn't have an effect, let's use --logdebug like in GUI version.
(Command line always outputs some log)
Found in owncloud/documentation#3436
> owncloudcmd: Fix timestamps, Fix --logdebug

- src/gui/owncloudsetupwizard.cpp
Issue #6105
Dynamically find the browser trough topLevelWidgets instead of
forwarding the call to the relevant page as it would require to break
many abstration layers (OwncloudSetupWizard -> OwncloudWizard ->
AbstractCredentialsWizardPage -> OwncloudShibbolethCredsPage)
And considering that we want to phase shibboleth down, I tought is
was not worth adding an interface for this.
The OAuth page don't have this problem because it shows a label and
allow the user to re-open the browser.
> Shibolleth: raise the browser when clicking on the tray

- src/gui/owncloudsetupwizard.cpp
Clicking on the "Add new Account" from the systray menu should raise
the wizard, even if it is already running.
Relates to issue #6105
> owncloudsetupwizard: Fix "add new account" if the wizard is already visible

- src/gui/owncloudsetupwizard.cpp
- src/gui/owncloudsetupwizard.h
Unfortunately checking the base-url for redirects in all cases lead
to incorrect behavior in some SAML/OAuth2 edge cases.
This new iteration checks the base url for redirects only if the
standard CheckServerJob can't reach the server. That way the 2.3
behavior is only changed in cases that would have lead to errors.
See #5954
> Wizard: Resolve url/ redirects only if url/status.php not found

- doc/conffile.rst
- src/common/syncjournaldb.cpp
- src/common/syncjournaldb.h
- src/csync/csync.cpp
- src/csync/csync_private.h
- src/csync/csync_update.cpp
- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderman.cpp
- src/gui/folderman.h
- src/gui/folderwatcher.cpp
- src/gui/folderwatcher.h
- src/gui/folderwatcher_linux.cpp
- src/gui/folderwatcher_win.cpp
- src/gui/folderwatcher_win.h
- src/libsync/configfile.cpp
- src/libsync/configfile.h
- src/libsync/syncengine.cpp
- src/libsync/syncengine.h
- test/testsyncengine.cpp
Use the data from the db instead and only check the file system when a file watcher event suggests it's necessary.
Since we're not confident that file watcher events are good enough, we still do a full local discovery every hour for now. This also doesn't get rid of the initial sync after client startup. But incremental syncs should be sped up significantly.
See #2297
> Speed up local discovery by not doing it

- src/gui/folder.cpp
- src/gui/sharemanager.cpp
- src/gui/sharemanager.h
- src/libsync/syncengine.cpp
- src/libsync/syncengine.h
- test/testsyncengine.cpp
- test/testsyncfilestatustracker.cpp
See commit message for more information.
The two first commit are just code cleanup
The other commit fix the issue #6098
This include a workaround of the fact that the server don't update the etags.
> Sharing: fix overlay icons directly after sharing a file

- src/gui/owncloudsetupwizard.cpp
For historical reasons CheckServerJob doesn't just check url/ but also
url/owncloud/. However, that means if url/status.php is a 404 and
url/owncloud/status.php is a 404, the user will see the latter url
appear in the error message. That's potentially confusing.
Instead, just show the account url which will be closer to what the
user typed into the account wizard, while being adjusted for protocol
and possible redirects.
> Wizard: Don't report confusing error message #6116

- src/libsync/creds/abstractcredentials.cpp
The application name is prepended to the key. QtKeychain doesn't
do that automatically on the platform.
See #6125 
@SamuAlfageme I'd like to ask you to redo the 2.3 -> 2.4 upgrade tests after this patch hits. It's expected that 2.4alpha credentials won't be found or deleted.
> Credentials: Namespace windows cred keys

- src/common/ownsql.cpp
- src/common/ownsql.h
Surprisingly sqlite3_open_v2() returns ok on readonly files with
SQLITE_OPEN_READWRITE.
See #6050
> Journal: Don't crash if the db file is readonly

- src/libsync/creds/httpcredentials.cpp
- src/libsync/creds/httpcredentials.h
This doesn't do anything about deleting the client cert keychain
entries when the whole account is removed though.
See  #5752
Requested by @SamuAlfageme
> HttpCreds: Don't create empty client cert keychain entries

- src/gui/creds/httpcredentialsgui.cpp
- src/gui/owncloudsetupwizard.cpp
- src/libsync/abstractnetworkjob.cpp
- src/libsync/abstractnetworkjob.h
- src/libsync/networkjobs.cpp
- src/libsync/networkjobs.h
With some firewalls we can't GET /remote.php/webdav/. Here we keep the
GET request to detect shibboleth through the redirect pattern but then
use PROPFIND to figure out the http auth method.
This also restores the fallback behavior of assuming basic auth
when no auth type can be determined.
See  #6135
@SamuAlfageme Could you test with the specific problematic server?
> DetermineAuthType: Adjustments for tight firewalls

- src/csync/csync_update.cpp
- test/testsyncengine.cpp
This bug was introduced when strcmp(a, b) != 0 was accidentally
converted to a == b.
See #6145
> Discovery: Treat files starting with '.' as hidden again

- src/common/ownsql.cpp
The assert was made fatal when looking at asserts for #5429 #5518
without having a particular problem in mind. Recent reports weakly
suggest that this might lead to occasional crashes for users when
sqlite_close fails in ways that look ignorable.
> Sql: db close() failing isn't fatal

- src/gui/creds/httpcredentialsgui.cpp
- src/gui/wizard/owncloudsetuppage.cpp
- src/libsync/networkjobs.cpp
- src/libsync/networkjobs.h
This restores 2.3 behavior. Some servers reply 404 to GETs and PROPFINDs
to the remote.php/webdav/ url and used to work. Being more picky would
break them.
Fixes #6148
> DetermineAuth: Remove concept of Unknown

- src/libsync/abstractnetworkjob.cpp
- src/libsync/abstractnetworkjob.h
- src/libsync/propagatedownload.cpp
- src/libsync/propagatedownload.h
The GET jobs were redirected, but the custom incremental handling
in readyRead didn't propagate to the follow-up job.
> PropagateDownload: Fix GET with redirects #6159

- src/csync/csync_reconcile.cpp
- src/csync/csync_util.cpp
- src/csync/csync_util.h
- src/libsync/propagatedownload.cpp
- test/testsyncengine.cpp
Previously we required matching mtimes but that's actually
unnecessary when the question is about whether to skip the
download. We will still update the downloaded file's metadata.
See #6153
> PropagateDownload: Skip identical files more

- doc/installing.rst
I would like to maintain the System Requirements in the client repo. (Switch planned for 2.4.0 release).
[documentation/admin_manual/installation/system_requirements.rst](https://github.com/owncloud/documentation/blob/master/admin_manual/installation/system_requirements.rst) > [client/doc/installing.rst](https://github.com/owncloud/client/blob/master/doc/installing.rst)
@guruz @settermjd @SamuAlfageme What do you think?
> Add 2.3.3 System Requirements to client repo

- src/gui/accountsettings.cpp
The menu can be open with the keyboard shortcut.
(Fixup for the fix of #5596)
Also use popup instead of exec to show the menu: it's safer as it does
not re-enter the event loop.
> AccountSettings: Use the proper position to show the menu over sub-folder

- src/gui/issueswidget.cpp
- src/gui/issueswidget.h
- src/gui/protocolwidget.cpp
- src/gui/protocolwidget.h
- src/gui/socketapi.cpp
- src/libsync/networkjobs.cpp
- src/libsync/networkjobs.h
To do this conveniently a bunch of functionality that's common to
IssueWidget and ProtocolWidget is moved to ProtocolItem.
Also the convenience function to asynchronously retrieve the private
link url is moved from the socket api to the network jobs.
See #6121
> Protocol: Introduce context menu with "open in browser" action

- src/libsync/account.cpp
- src/libsync/account.h
- src/libsync/connectionvalidator.cpp
- src/libsync/connectionvalidator.h
- src/libsync/creds/tokencredentials.cpp
- src/libsync/creds/tokencredentials.h
- src/libsync/networkjobs.cpp
- src/libsync/networkjobs.h
This means we cannot use QtGui in libsync.
So this mostly disable the avatar from the account and the avatarjob
Note that there is one logic change: in ConnectionValidator::slotUserFetched
we do the avatar job even if the user is empty. Otherwise we would end up in
a invalid state. This restore the 2.3.x behavior that was broken in
commit e05d6bfcdc39b551d0a29c763afcabcadb5d05a6
> libsync: Fix compilation with TOKEN_AUTH_ONLY

- src/gui/folderstatusdelegate.cpp
The problem here is that the QPainter is created on the viewport with is a
QWidget, but QAbstractItemView can have a different font, and the
QStyleOptionViewItem::font is this font. QStyleOptionViewItem::font
was used to compute the sizeHint, and the default font from the QPainter
was used to draw the text, so they could be not in sync.
Fix it by always using the font for QPushButton
Reported in
https://github.com/owncloud/client/issues/6156#issuecomment-346576328
> AccountSettings: Fix the size of the "Add Sync Folder Connection" button

- src/gui/folderwizard.cpp
- src/gui/folderwizard.h
There are several bugs in QWizard that needs to be worked around for the minimum
size of the widget to take effect.
Issue #4280
> FolderWizard: Fix minimum size

- src/gui/accountsettings.cpp
The selective sync selections get reset in this case, while the
big folder warnings will pop up again on reconnection.
> Hide selective sync buttons while disconnected #5809

- src/csync/csync.cpp
- src/csync/csync_reconcile.cpp
- src/csync/csync_rename.cpp
- src/csync/csync_rename.h
- src/libsync/discoveryphase.cpp
- test/testsyncmove.cpp
See #6212 and the commit message of the second commit.
> Make rename detection consistent for duplicate file ids

- doc/autoupdate.rst
- doc/conffile.rst
- src/cmd/simplesslerrorhandler.cpp
- src/gui/application.cpp
- src/libsync/abstractnetworkjob.cpp
- src/libsync/abstractnetworkjob.h
- src/libsync/account.cpp
- src/libsync/capabilities.cpp
- src/libsync/configfile.cpp
- src/libsync/configfile.h
- src/libsync/discoveryphase.h
- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- src/libsync/syncoptions.h
See individual commit.
Relates to issues #6213 #2245 #1601 and #684
One of the change is that it moves the config directory from
~/.local/share/data/ownCloud/ to ~/.config/ownCloud/
It migrates by moving the folder to the new location and creating a symlink.
> Move config and remove most dependencies form the sync engine.

- src/gui/sharelinkwidget.cpp
- src/gui/sharelinkwidget.h
- src/gui/sharelinkwidget.ui
Copying design changes from https://github.com/owncloud/core/pull/29376
Fixes #6192
> Share link: Adjust design of folder sharing permissions #6192

- src/common/syncjournaldb.cpp
- src/common/syncjournaldb.h
- src/csync/csync_reconcile.cpp
- src/libsync/propagateuploadng.cpp
- src/libsync/propagateuploadv1.cpp
- test/syncenginetestutils.h
- test/testchunkingng.cpp
- test/testoauth.cpp
- test/testsyncengine.cpp
- test/testsyncmove.cpp
This can happen if the upload of a file is finished, but we just got
disconnected right before recieving the reply containing the etag.
So nothing was save din the DB, and we are not sure if the server
recieved the file properly or not. Further local update of the file
will cause a conflict.
In order to fix this, store the checksum of the uploading file in
the uploadinfo table of the local db (even if there is no chunking
involved).  And when we have a conflict, check that it is not because
of this situation by checking the entry in the uploadinfo table.
Issue #5106
This goes to master because it is an old issue and the fix is quite intrusive as it even add a row in the database.
> SyncEngine: Recover when the PUT reply (or chunkin's MOVE) is lost

- src/libsync/configfile.cpp
If the application binary is not installed in /usr/bin the client
with this patch considers to check the relative location
`../../etc/owncloud-client/` to find the system exclude.
This is an important bit for AppImage based packages of the client,
as this runs from a temporar mountpoint and the system file can not
be found under /etc.
> Config: Look for exclude file in a relative path.

- src/csync/csync_exclude.cpp
- test/csync/csync_tests/check_csync_exclude.cpp
- test/testexcludedfiles.cpp
fopen does not work well with relative path tand forward slashes on windows
This fix the windows textexcludedfiles test.
And also make the code simpler.
Note that the 'trimmed' might be a behavior change, but i think it is ok
> Exclude: Use Qt to load the exclude file

- src/gui/issueswidget.cpp
- src/gui/issueswidget.h
- src/gui/issueswidget.ui
Since sorting was enabled permanenty the list would be resorted with
each inserted issue. When inserting thousands of ignored files that
would make the whole ui freeze up.
Instead, sorting is disabled for inserts now and is reenabled after some
time has passed. That way users usually see the sorted view without the
lockups. Also, there's now a maximum of 50k issue entries.
See  #6272
> Issues: Speed up insertion and add hard upper limit

- src/csync/csync_exclude.cpp
- src/csync/csync_exclude.h
- test/csync/csync_tests/check_csync_exclude.cpp
Unfortunately matching behaved differently on Windows. This patch
restores the previous matching behavior but still uses the new regular
expression based matching.
Further work will hopefully unify the behavior between platforms without
breaking backwards compatibility.
See  #6245
> Exclude regex: Restore old matching on Windows

- src/gui/folderwizard.cpp
Sentry:
https://sentry.io/owncloud/desktop-win-and-mac/issues/425331770/
> Fix resizing crash when currentPage() is null

- src/csync/csync_update.cpp
- test/testsyncengine.cpp
There's an upstream bug where QTextCodec::canEncode returns true even
though it should be false. This works around that issue and adds a test.
The original work was done in 72809ef5b1aeb578976e4360ed267ac1c4d71ea6
See #6287, #5676, #5719
See https://bugreports.qt.io/browse/QTBUG-6925
> Ignore files that can't be encoded for the filesystem

- src/gui/updater/updater.cpp
We want to change the package suffix of the daily rebuilds.
Please review and find other places where this might have impact.
Backport into all needed branches too.
> deprecate suffix nightly, promote suffix daily

- src/gui/sharelinkwidget.cpp
Eventually there might be server API for default share name generation.
See owncloud/core#29913, #6298
> Link shares: Elide default name to make it <64 chars

- src/csync/csync_exclude.cpp
- src/csync/csync_exclude.h
- test/csync/csync_tests/check_csync_exclude.cpp
Previously we'd use the full regex when the bname triggered a full-path
matching to take place. Now we have a simplified full-traversal regex
for this case that can be significantly faster to apply.
Triggered by #5017 but doesn't actually solve it.
> Exclude matching: Speedup the full-path traversal case

- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- src/libsync/propagatedownload.cpp
- src/libsync/propagatorjobs.cpp
- src/libsync/syncengine.cpp
- test/testsyncconflict.cpp
Previously conflicts with a different type on both ends lead to sync
errors. Now they are handled in the expected way: the local item gets
renamed and the remote item gets propagated downwards.
This also adds a unittest for the TYPE_CHANGE case. That one looks like
parts of it might be unified with CONFLICT cases.
See  #6312
> Sync: Deal with file/folder conflicts

- src/libsync/propagateupload.cpp
- src/libsync/propagateupload.h
- src/libsync/propagateuploadng.cpp
- src/libsync/propagateuploadv1.cpp
For issue #6318
The StopWatch is using memory, and we are not really using it.
> Get rid of the StopWatch in the PropagateUpload job

- src/libsync/logger.cpp
Recent Qt version show way too many debug messages, spamming the console.
So filter only messages that comes from the client.
> Logger: --logdebug only show owncloud's debug message

- src/gui/issueswidget.cpp
- src/gui/protocolwidget.cpp
- src/gui/sharelinkwidget.cpp
- src/libsync/syncfileitem.h
The instruction just indicates a potential conflict. If we can determine
that there's no actual conflict, the activity item shouldn't announce
that a conflict file was created.
The "Downloaded" message is not necessarily technically correct, but
seems less confusing than "It looked like there might be a conflict, but
there didn't end up being one after all".
See #6316
> Activity: Avoid misleading message for INSTRUCTION_CONFLICT

- src/gui/socketapi.cpp
- src/gui/socketapi.h
This adds "Open in browser" entry in the menu (Issue #5903)
Also mark the share entries as disabled when sharing is not allowed
or not available for a given file.
If sharing is disabled globaly in the branding or in the server,
the share entry will not be present.
(Issues #4205 and #4608)
Meta issue #6292
> SocketAPI: "Open in browser" and disable Share entries when sharing is disabled

- src/common/filesystembase.cpp
- src/common/filesystembase.h
- src/libsync/propagatorjobs.cpp
QFileInfo::isSymLink() does detect reparse points that are symlinks but
returns false for junctions. The new function FileSystem::isJunction()
can detect those and is used to not recursively delete files inside
directories that are junctions.
See  #6322
> Don't delete contents behind directory junctions

- src/gui/sharemanager.cpp
The client already computed the valid permissions, there was just a typo
that meant we didn't end up using them.
See  #6346
> Sharing: Use maximum allowed permissions for new share

- src/common/syncjournaldb.cpp
- src/common/syncjournaldb.h
- src/libsync/syncengine.cpp
Before, we only cleared the _avoidReadFromDbOnNextSyncFilter *after* a
sync which meant that we had to sync twice after selective sync setup.
Now, we clear the filter *before* a sync as well which allows the actual
next sync to write the correct etags to the db again - instead of only
the sync after that one.
Also expand on comments and rename _avoidReadFromDbOnNextSyncFilter to
_etagStorageFilter.
> SyncJournal: Clear etag filter before sync

- appveyor.ini
- appveyor.yml
Resubmitting the app veyor fixes without the qt 5.10 version bump as we don't have the right binaries in craft cache yet and building it ourselves takes too long for appveyor.
> Fix appveyor

- src/libsync/syncengine.cpp
It's unlikely that there were interaction effects but still seems safer
to use different conversion state for the path and rename_path.
> SyncEngine: Use separate state for two unicode conversions

- src/common/utility.cpp
- src/common/utility.h
- src/libsync/owncloudpropagator.cpp
- test/testsyncconflict.cpp
- test/testutility.cpp
For the case of uploading conflict files only.
See #6325. Possible issue is too-long-path on windows.
> Conflicts: Add user name to conflict file name

- src/gui/application.cpp
The previous code would disable it when the second account was
configured.
See #6347
> Set launch-on-startup when the first account is set up

- src/gui/folder.cpp
A recent patch that touched the condition for deciding whether a
periodic full local discovery is necessary accidentally inverted the
condition.
> Partial local discovery: Fix scheduling logic

- CMakeLists.txt
- config.h.in
- src/common/utility.cpp
- src/csync/config_csync.h.cmake
- test/testutility.cpp
Since the release package will be build with unit test, we don't
want to query the env variable at every call to fsCasePreserving.
So only test the env variable at startup.
And the testutility can still change the value.
(The env variable is still used from t8.pl and maybe smashbox)
Issue #6318
> Utility::fsCasePreserving: remove UNIT_TESTING ifdef

- src/libsync/propagateupload.h
- src/libsync/propagateuploadng.cpp
- test/syncenginetestutils.h
- test/testzsync.cpp
I still need to add a bunch of unit tests but manual upload tests now pass much more reliably for me.
@mrow4a Possibly rerun your tests with this branch to verify.
@ahmedammar
> Delta-sync upload fixes

- src/libsync/CMakeLists.txt
- src/libsync/propagatecommonzsync.cpp
- src/libsync/propagatecommonzsync.h
Combines with https://github.com/ahmedammar/zsync/pull/1
Note that this is based on https://github.com/owncloud/client/pull/6382 to allow actual testing. This PR has only one commit: https://github.com/owncloud/client/commit/c742b4a9ec35414d360e81651c1e5698dfed96d4
> Use zsyncfile API, remove duplicated code

- src/libsync/propagatecommonzsync.cpp
- src/libsync/propagatecommonzsync.h
- src/libsync/propagatedownloadzsync.cpp
- src/libsync/propagateuploadng.cpp
This PR is based on top of https://github.com/owncloud/client/pull/6389 and has only one commit https://github.com/owncloud/client/commit/15aff7b0dd188bb9bc8d36c9e7d243b56af2697c. It also depends on https://github.com/ahmedammar/zsync/pull/2
@ahmedammar
> zsync: use larger rolling hash size to avoid conflicts

- shell_integration/dolphin/ownclouddolphinpluginhelper.cpp
As per XDG Base Directories specification:
> If $XDG_RUNTIME_DIR is not set applications should fall back
> to a replacement directory [...]
In practice, the ownCloud client has the fallback, but the plugin
helper does not, and if $XDG_RUNTIME_DIR is not set, the plugin
mysteriously does not work.
> Dolphin plugin: fall back if $XDG_RUNTIME_DIR is empty

- doc/architecture.rst
- src/csync/csync_exclude.cpp
- test/csync/csync_tests/check_csync_exclude.cpp
The Desktop.ini exclude was added for 2.4 because we add such a file to
the synced folder on Windows. It doesn't need to cover subdirectories.
See https://github.com/owncloud/documentation/issues/2832
> Excludes: Expand doc, Desktop.ini only in root folder

- src/gui/folderstatusmodel.cpp
- src/gui/folderstatusmodel.h
OCC::FolderStatusModel::slotUpdateDirectories: ASSERT: "parentInfo->_fetching" in file /home/olivier/kdegit/owncloud/mirall/src/gui/folderstatusmodel.cpp, line 599
This can happen if the structure of a folder is change while the user
expands the root folder. In this case, resetSubs() is called which
resets _fetching to false.
Instead, we need to keep a pointer to the job so we can abort it by
deleting it.
> FolderStatusModel: fix potential assert

- shell_integration/nautilus/syncstate.py
The nautilus plugin doesn't actually define get_columns(), so pretending
to be a ColumnProvider lead to a critical warning on startup.
> Nautilus integration: Not a ColumnProvider

- admin/osx/post_install.sh.cmake
Some users have disabled Finder on their systems; the old postinstall script would always reenable Finder; therefore the quick check for Finder status. The postinstall script will only run the osascript reveal command, if Finder is enabled/running.
> macOS postinstall: check if Finder is running

- src/libsync/owncloudtheme.cpp
- src/libsync/owncloudtheme.h
- src/libsync/theme.cpp
- src/libsync/theme.h
The goal is to avoid confusion described in issue #6422 by removing
duplicates between the Theme and owncloudTheme.
- Use the about from ownCloudTheme everywhere
- Create default applicationIcons() and condifFileName() that should work
everywhere
- trayFolderIcon was removed as it is not used
- the helpUrl from the default Theme now points to the owncloud client
documentation. Before there was no help entry by default for branded
client if the function was not overriden.
- Do not merge functions that would otherwise break compatibility with
theme that did not override them. For example colors or customMedia.
> Theme: unify ownCloudTheme and Theme classes

- src/gui/sharelinkwidget.ui
> Share link: Update permission wording

- src/gui/folderstatusmodel.cpp
For  #6277
@ogoffart Would you mind if I went in and refactored our icon usage to not depend on "SyncResult"? I think the icon enum should be separate from the sync result enum.
> Folders: Use "Problem" icon for unresolved conflicts

- src/gui/socketapi.cpp
...and load it on startup.
Fixes #5382
> macOS: Unload the Finder extension on exit #5382 #3819

- src/gui/application.cpp
- src/gui/logbrowser.cpp
- src/gui/logbrowser.h
- src/gui/owncloudgui.cpp
- src/libsync/configfile.cpp
- src/libsync/configfile.h
- src/libsync/logger.cpp
- src/libsync/logger.h
For #6442 
When the checkbox in the logwindow is enabled and no explicit --logfile etc. are passed, we'll log to a dir in `/tmp` by default, with one log per sync run, compressed on switch and expired after four hours.
There was a bunch of talk around logging while discussing feedback from @moscicki - and while we may add more elaborate schemes this was simple to get ready in time for 2.5. My hope is that this can allow power users (@sagamusix ?) to just leave logging on all the time - and then we end up with logs even for the weird and intermittent problems.
Also, when we ask reporters for logs, we no longer have to explain `--logfile` and `--logdebug` -- just "F12 and enable this check box, find logs here, beware that logs have personal data".
@SamuAlfageme @guruz
> Add simple persistent logging option

- src/gui/ocsshareejob.cpp
- src/gui/ocssharejob.h
- src/gui/owncloudgui.cpp
- src/gui/owncloudgui.h
- src/gui/sharedialog.cpp
- src/gui/sharedialog.h
- src/gui/socketapi.cpp
- src/gui/socketapi.h
* The new menu option will fetch shares and create a new link share if
no "context menu share" currently exists.
* Various cleanup of common operations in socketapi happened as well,
in particular there's now FileData::get() that calculates all the
relevant paths that are useful for most socketapi actions.
See  #6356
@SamuAlfageme
> SocketApi/Sharing: Add "copy public link" to menu

- src/gui/networksettings.cpp
- src/gui/networksettings.h
What happens internally is that a proxy without a hostname gets treated
as no proxy.
See  #5885 
@SamuAlfageme This needs testing on OSX because we use a different settings window base class there.
> Network settings: If no proxy host given, show "no proxy"

- CMakeLists.txt
To make themes work that don't define it explicitly.
> CMake: Add a default placeholder_suffix

- src/libsync/abstractnetworkjob.cpp
- src/libsync/abstractnetworkjob.h
- src/libsync/networkjobs.cpp
- src/libsync/propagatedownload.cpp
- src/libsync/propagateremotedelete.cpp
- src/libsync/propagateremotemove.cpp
- src/libsync/propagateupload.h
The old code printed "QNetworkReply::NoError"
> Logging: Avoid the word "Error"

- src/gui/owncloudsetupwizard.cpp
- src/gui/owncloudsetupwizard.h
- src/gui/wizard/owncloudadvancedsetuppage.cpp
- src/gui/wizard/owncloudadvancedsetuppage.h
- src/gui/wizard/owncloudadvancedsetuppage.ui
- src/gui/wizard/owncloudwizard.cpp
- src/gui/wizard/owncloudwizard.h
Issue #3664
The goal is to make it more visible than the button.
An alternative would have been to simply rename the button to "Manual folder configuration", but I feel a radio button works better.
Here is how it looks:
cc/ @michaelstingl
> Wizard: Move the 'Skip folder configuration' in a radio button

- src/gui/owncloudgui.cpp
At least on windows and linux. OSX would need tests first since
the addition was originally supposed to help with OSX problems,
see #3783.
For #6185
> Share dialog: Don't hide account settings before showing

- doc/faq.rst
- src/gui/application.cpp
- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderwatcher.cpp
- src/gui/folderwatcher.h
- src/gui/folderwatcher_linux.cpp
- test/testfolderwatcher.cpp
See #6119 
It's only a tray message. I feel that if we made a message box, we'd need to include a "never show this again" box...
> Show a tray message when a folder watcher becomes unreliable 

- shell_integration/nautilus/syncstate.py
Use b'\n' in the call to rfind, as the _remainder is bytes, not a string.
Remove most of the debug message which happens during normal operation.
They are mostly spamming the nautilus console, and can also cause bug
as they may throw exception in case of wrong encoding.
Issue: #6406
> Nautilus: Fix Python3 and remove many debug

- src/gui/networksettings.cpp
Fixes f6a075ef54a3434e758dcddc6a29b218c4f2a247 for #5885
When no host is given it shouldn't just *appear* that there is no
proxy, there actually shouldn't be a proxy set then.
> Proxy settings: Fix bad behavior with empty host

- doc/navigating.rst
https://github.com/owncloud/documentation/issues/4109.
> Correct incorrect reference to OSX Menu bar

- src/common/syncjournaldb.cpp
- src/common/syncjournalfilerecord.h
- src/gui/syncrunfilelog.cpp
- src/libsync/abstractnetworkjob.cpp
- src/libsync/abstractnetworkjob.h
- src/libsync/owncloudpropagator.cpp
- src/libsync/propagatedownload.cpp
- src/libsync/propagateremotedelete.cpp
- src/libsync/propagateremotemkdir.cpp
- src/libsync/propagateremotemove.cpp
- src/libsync/propagateupload.cpp
- src/libsync/propagateuploadng.cpp
- src/libsync/propagateuploadv1.cpp
- src/libsync/syncfileitem.h
- test/testblacklist.cpp
Issue #6420
Store the X-Request-ID in the SyncFileItem and also in the blacklist.
Note that for consistency reason, the X-Request-ID is also in the
SyncFileItem if the request succeeds.
Currently there is no UI to access it, but it can be queried with sql
commands
> Blacklist: remember the X-Request-ID

- src/common/syncjournaldb.cpp
With WAL mode sqlite seems to occasionally crash when the
underlying filesystem goes away.
Shall be picked to 2.4 afterwards.
> SyncJournal: Check file existence even for open dbs #6049

- src/gui/wizard/owncloudadvancedsetuppage.ui
@jancborchardt 
This will lead to a double parenthesis: "(recommended) (124 MB)". It'd be easy to make it say "(recommended, 124 MB)" if that seems better. (note that the size is not always available)
For #6470
> Wizard: Add a "(recommended)" to the main option

- src/libsync/owncloudpropagator_p.h
Because it sometimes appears in conjunction with server bugs and we
don't want to halt all syncing for other files in these cases.
See  #6516
> Propagation: Connection closed is a normal error

- src/libsync/propagateupload.cpp
- src/libsync/propagateupload.h
- src/libsync/propagateuploadng.cpp
- src/libsync/propagateuploadv1.cpp
Some servers have virus scanners and the like that can delay the
response of the final chunked upload assembly significantly, often
breaking the current 5min (!) timeout. See owncloud/enterprise#2480
for details.
For #6527
> Upload: Adjust timeout for final job based on size

- src/gui/CMakeLists.txt
- src/gui/generalsettings.cpp
- src/gui/generalsettings.h
- src/gui/generalsettings.ui
- src/gui/updater/ocupdater.cpp
- src/gui/updater/ocupdater.h
- src/gui/updater/sparkleupdater.h
- src/gui/updater/sparkleupdater_mac.mm
- src/gui/updater/updater.cpp
- src/gui/updater/updater.h
- src/libsync/configfile.cpp
- src/libsync/configfile.h
Open questions / things this doesn't do:
- Should it ever be hidden when the "Updater" group is shown?
- As a user I'd expect that when I switch the release channel I'll be offered to download the newest version from that channel. I think this important and I'll look at it.
Intended for picking into 2.4 once merged.
For  #6259
> Settings: Add update channel combobox

- src/libsync/creds/httpcredentials.cpp
- src/libsync/creds/httpcredentials.h
When owncloud is restored, at boot time, it might be started before the
crendential manager. So if we detect an error, wait 10 seconds and hopefully
it'd be loaded by then.
Issues: #4274, #6522
> Credentials: Retry fetching from the keychain in case the keychain is still starting

- src/gui/accountmanager.cpp
- src/gui/accountmanager.h
- src/gui/application.cpp
- src/gui/application.h
- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderman.cpp
- src/gui/folderman.h
- src/libsync/configfile.cpp
- src/libsync/configfile.h
For #6504 
* Store placeholder folders differently, so 2.4 clients don't see them at all
* Add mechanism to do backwards compatibility in a smarter way next time
* Remove silly "stub" body of placeholders
Open question:
* Remove the placeholder ignore pattern that was added for backwards compatibility but doesn't really work?
@SamuAlfageme
> Placeholder and general backwards compatibility

- src/gui/sharedialog.cpp
- src/gui/socketapi.cpp
- src/gui/socketapi.h
When sharing a virtual file, we should actually use the original file name
not the virtual file name
Issue: #6461
> Share dialog: use the original name and not the virtual file name

- src/libsync/propagatedownload.cpp
- test/syncenginetestutils.h
We want to keep the body so we can get the message from it
(Issue #6459)
TestDownload::testErrorMessage did not fail because the FakeErrorReply
did not emit readyRead and did not implement bytesAvailable.
> PropagateDownload: Don't discard the body of error message

- src/csync/csync.cpp
- src/csync/csync.h
- src/csync/csync_private.h
- src/csync/csync_update.cpp
- src/csync/vio/csync_vio.cpp
- src/csync/vio/csync_vio.h
- src/gui/folderstatusmodel.cpp
- src/libsync/discoveryphase.cpp
- src/libsync/syncengine.cpp
Fix the crash reported in #6562
Also cleanup another warning reported by valgrind.
See individual commit message for more info.
> Crash fixes and valgrind error fix

- src/gui/accountsettings.cpp
The previous patch did forget about the big-folder-ui which should
also be hidden on disconnect.
See  #5809
> Selective sync: Hide ui on disconnect

- src/libsync/propagatedownload.cpp
- test/syncenginetestutils.h
- test/testdownload.cpp
- test/testsyncengine.cpp
It could happen that readyRead was emitted for incoming data while the
download was not yet finished. Then the network job could finish with
no more data arriving - so readyRead wasn't emitted again.
To fix this, the finished signal also gets connected to the readyRead
slot.
For #6581
> Ensure GETFileJob notices finishing 

- src/gui/accountstate.cpp
This can happen when the client is started and the internet connection
was not enabled. Then we would fetch the credentials, but we would
no do the refresh token step (because network is down).
So next time we try to connect, we would also not refresh the token
because the credentials are not marked as 'ready'
Reported in
https://github.com/owncloud/client/issues/6522#issuecomment-396845167
> OAuth2: Try to refresh the token even if the credentials weren't ready.

- src/libsync/theme.cpp
Issue #6422
Note: there is now a difference with for the non-branded client:  It says "Distributed by ownCloud GmbH" while it did not say that in 2.4.
CC @hodyroff
> Theme: Put back the string as it was in 2.4, for branded clients.

- src/gui/owncloudgui.cpp
- src/gui/owncloudgui.h
* Disentangle the previous 'qdbusWorkarounds' into three different
things
* Make not trusting tray.isVisible() a new workaround
* Introduce env vars for all workaround flags
* Use the workaround flags for OSX
* Determine workaround flags for KDE when the plasma integration plugin
is missing
For #6545
> Tray workarounds

- src/gui/generalsettings.cpp
- src/gui/generalsettings.h
The names in the combobox are being translated, so we need to rely
on the index rather than the text.
> Updater: Fix beta channel for translated clients.

- src/gui/creds/oauth.cpp
- src/gui/wizard/owncloudoauthcredspage.cpp
Issue #6574
When there is an error in the advanced page, OwncloudAdvancedSetupPage::updateStatus
(and others) call completeChanged(), which is connected to
QWizardPrivate::_q_updateButtonStates which will re-enable the back button from the
last page.
When the user click "back" and re-open the browser, the account's credentials
already have a oauth token set. So the call to the API to get a new token fails
because we use the previous token instead of using the client's secret_id.
Fix this with the HttpCredentials::DontAddCredentialsAttribute.
Now, this is still not working because the session cookies are confusing the
server.  So we'll clear the cookies when re-opening the browser
> Wizard + OAuth: Make opening a new browser after clicking back works again

- src/gui/owncloudgui.cpp
- src/gui/owncloudgui.h
* Disentangle the previous 'qdbusWorkarounds' into three different
things
* Make not trusting tray.isVisible() a new workaround
* Introduce env vars for all workaround flags
* Use the workaround flags for OSX
* Determine workaround flags for KDE when the plasma integration plugin
is missing
(cherry picked from commit 99116acdcaba3fb068ba63bdcd759836f2017a92)
(cherry picked from commit ca033b96856662342ef760c827bc4855210868d3)
(cherry picked from commit 8b1d9799a3c05eb4b10c96ee3e5ceca404bec108)
(cherry picked from commit a0d6139505b2c0f2527769a252e199c37d751781)
For  #6545
> Tray workarounds backport for 2.4

- shell_integration/nautilus/setappname.sh
- shell_integration/nautilus/syncstate.py
It appears that several extension can be loaded at the same time, but their
classname for the extension need to be different, otherwise only the last
loaded one would be active.
Issue #6524
> nautilus shell integration: Fix when there are several branded client installed

- src/gui/creds/oauth.cpp
There is no real reason to have a timeout. The connection can stay open
as long as we are not authenticated. The User can still re-open a browser
from the UI at any time.
Issue #6612
> OAuth: Remove the timeout

- src/gui/generalsettings.cpp
- src/gui/generalsettings.ui
- src/gui/owncloudgui.cpp
- src/gui/owncloudgui.h
Can someone check if this looks OK on Windows and Linux too?
Menu entry:
Dialog now not so high:
Every proper application has that!
For decreasing window height in #6075
> Introduce an about dialog

- src/csync/csync_reconcile.cpp
- src/csync/csync_update.cpp
Not having these enabled by default is causing significant extra back
and forth with reporters since they must manually use --logdebug for the
log to be useful.
Cherry pick to 2.4
> Log: Adjust update/reconcile log verbosity

- src/csync/csync_reconcile.cpp
- test/testsyncmove.cpp
Issue https://github.com/owncloud/client/issues/6629#issuecomment-402450691
> Reconcile: When detecting a local move, keep the local mtime

- shell_integration/nautilus/syncstate.py
It seems None gets assigned to 'state' in some paths.
See #6643
> Nautilus: Guard against None state

- src/gui/folderman.cpp
- src/gui/folderman.h
- src/gui/folderwizard.cpp
- test/testfolderman.cpp
Note that we also needed to adjust the server url to contains the user name
in the folder wizard. (As checkPathValidityForNewFolder expect the user name)
Issue #6654
> FolderMan::checkPathValidityForNewFolder: make sure to work with deleted folders

- src/libsync/theme.cpp
This increases the resoluton for e.g. the window icon (and so also the taskbar icon) on Windows.
cc @ChrisEdS @michaelstingl
> Support higher resolution theme icons

- src/libsync/creds/httpcredentials.cpp
The server reply with a code 400 when the token is invalid,
the client was understanding this error as a network error, and was retying
again with the same token.
Instead, we must rely on what the json is saying, even if the reply is
not a 200 code.
Issue https://github.com/owncloud/enterprise/issues/2777
(Need to be backported in 2.4.x)
> OAuth: Fix infinite loop when the refresh token is expired

- src/libsync/discoveryphase.cpp
- src/libsync/syncengine.cpp
- test/syncenginetestutils.h
- test/testallfilesdeleted.cpp
- test/testpermissions.cpp
Add a test to test the data fingerprint feature make me realize it was broken.
The code was relying in the distinction between empty and null QByteArray,
but this was a bad idea as this difference is lost when going through QString.
> Data-Fingerprint: Fix backup detection when fingerprint is empty

- shell_integration/nautilus/syncstate.py
For python2 there was a problem here when using `'{}'.format(u'ä')` - the adjusted code works for python 2 and 3 (though I've tested 3 only indirectly through the interpreter).
Calling `sendCommand()` with a unicode string also is the right thing to do, as it calls `.encode('utf-8')` on it.
For #6643
@jnweiger Thanks for finding this issue - I hadn't tested clicking the file. :/
> nautilus: Fix GET_MENU_ITEMS with utf8 filenames

- src/common/remotepermissions.cpp
- src/common/remotepermissions.h
- src/common/syncjournaldb.cpp
- src/libsync/discoveryphase.cpp
- test/testpermissions.cpp
- test/testsyncjournaldb.cpp
Fixes two bugs that appeared since the introduction of the struct:
- when reading permissions from the journal, null ("") was read as
empty-not-null
- when reading permissinos from the server, empty ("") was read as null
Addresses #4608
> RemotePermissions: Fix empty vs null

- src/gui/activitywidget.cpp
The mingw compiler isn't happy with them.
> C++: Don't use auto parameters in lambdas

- src/libsync/syncengine.cpp
- test/testsyncmove.cpp
Issue #6694
This is not a problem in the `new_discovery_algo` branch, but let's fix that for 2.5
> SyncEngine: Fix renames making hierarchy inversion

- src/csync/csync_update.cpp
- src/libsync/propagatedownload.cpp
- test/testsyncvirtualfiles.cpp
Unfortunately to do this, the local update phase must write to the
database, creating a new side-effect and order dependency (local update
must run before remote update).
For  #6718
> Virtual files: Renaming to virtual doesn't delete data

- .gitmodules
Without this, the HTML documentation isn't able to build successfully, as it fails on the deployment of the generated HTML files to the live server.
> Add the ownCloud documentation theme as a submodule

- src/gui/accountsettings.cpp
- src/gui/owncloudgui.cpp
- src/libsync/account.cpp
- src/libsync/networkjobs.cpp
We want to warn if the server version is not supported and did not get
appropriate QA for this client version.
https://github.com/owncloud/enterprise/issues/2687
> Update the minimum supported version

- src/gui/accountsettings.cpp
- src/gui/accountsettings.h
- src/gui/folder.h
- src/gui/folderstatusmodel.cpp
- src/gui/ignorelisteditor.cpp
- src/gui/selectivesyncdialog.cpp
Since we are now skipping the full local discovery, we also need to
call the method to force a full local discovery while we were making
full remote discovery, for the same reason.
Same applies when applying a selective sync: Normally there should not
be any file or directory with the same same of a blacklisted folder, but
if there is one, it was ignored and now need to be taken in account.
Also make the F6 shortcut do a full local discovery as well.
> Discovery:  Do full local discovery when changing the ignore files

- src/gui/updater/ocupdater.cpp
relates to #6690.
Usually this should not be a problem, but while testing it's easy to mess up your data dir with left over installers.
> Remove unused installers before copying new ones into the appdata dir

- shell_integration/windows/OCContextMenu/OCClientInterface.cpp
Otherwise we can't have operation that has many many filename
As reported in #6780
> Windows Shell Integration: Don't limit the size of the buffer

- src/gui/folderwatcher_linux.cpp
- src/gui/folderwatcher_linux.h
- test/testfolderwatcher.cpp
If a folder was renamed A -> B, the folder watcher for the inode
would be unaware and still report changes for A/foo. Now directory
renames in the watched folders are tracked and paths are updated
accordingly.
For  #6808
> Folderwatcher: On linux, fix paths after dir renames

- src/libsync/syncengine.cpp
- test/testlocaldiscovery.cpp
Regardless of what the file system watcher said
Issue #6804
> Local discovery: always recurse within new directory

- appveyor.ini
It tries to compile LLVM because of qttools. (qdoc)
Compiling llvm takes way to long and is timing out.
We do not need qdoc anyway.
> Attempt to fix appveyor build

- src/libsync/propagateuploadv1.cpp
If the server does not set the mtime, it is not a big problem for the
synchronisation.
The test was used before so we could do a PROPPATCH for server that did not
support this header. But now that all server supports that we don't need to
to the check. (We do not do the PROPPATCH since we got rid of the neon
dependency)
Apparently, it may happen that some backend don't support setting mtime
and this can lead to this error.
https://github.com/owncloud/client/issues/6797
> Upload: Do not error out if the server do not send X-OC-MTime:accepted

- src/csync/csync_update.cpp
Because on windows, all filename can be encoded: The file system uses
UTF-16, regardless of the locale
Issue: #6810
> Discovery: Windows: Don't check if a server file name can be encoded

- src/libsync/abstractnetworkjob.cpp
- src/libsync/abstractnetworkjob.h
- src/libsync/creds/abstractcredentials.h
- src/libsync/creds/httpcredentials.cpp
- src/libsync/creds/httpcredentials.h
- src/libsync/propagatedownload.cpp
- src/libsync/propagatedownload.h
OAuth2 access token typically only has a token valid for 1 hour.
Before this patch, when the token was timing out during the sync, the
sync was aborted, and the ConnectionValidator was then requesting a new
token, so the sync can be started over.
If the discovery takes longer than the oauth2 validity, this means that
the sync can never proceed, as it would be always restarted from scratch.
With this patch, we try to transparently renew the OAuth2 token and restart
the jobs that failed because the access token was invalid.
Note that some changes were required in the GETFile job because it handled
the error itself and so it was erroring the jobs before its too late.
Issue #6814
> OAuth2: Refresh the token without aborting the sync

- src/gui/owncloudsetupwizard.cpp
Because a previous call with another demain might have set some
config for another server.
Issue #6832
> Wizard: Reset the QSslConfiguration before checking the server

- src/libsync/propagateremotemove.cpp
QDir::cleanPath does not remove starting slashes on windows.
So use account::davUrl which is already cleaned
Issue: #6824
> Move: Fix too many starting slashes in the destination header

- src/gui/application.cpp
This can happen if the directory already exist because, say, it was
created by another program which save its file in the same directory
> Migration from 2.4: fallback to move file by file if directory move failled

- src/gui/sharee.cpp
> Sharing: add the `shareWithAdditionalInfo` string in autocompletion results

- src/cmd/cmd.cpp
This is required to get the new endpoint working when the server
uses ldap or that the dav user is not the same as the login.
Issue #6830
> owncloudcmd: fetch the dav user

- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderman.cpp
- src/gui/folderman.h
If virtual files are disabled on a folder it might still have db entries
or local virtual files that would confuse older client versions.
> Settings: Make FoldersWithPlaceholders group sticky

- src/libsync/discoveryphase.cpp
> Errors: Include path in discovery error message

- src/common/syncjournaldb.cpp
- src/gui/folder.cpp
- src/gui/folder.h
The 2.6 client will introduce an index that depends on a custom
function.
This causes insersion onto the metadata database to fail if the database
it opened with older version of the client. (Which will cause the client
to abort)
Delete this index in this version in order to allow downgrade.
OF course this commit need not to be in the 2.6 release
> Database: future-proof to allow downgrade from future version

- src/libsync/owncloudpropagator.cpp
TODO: Does `ENFORCE()` trigger the crash reporter properly?
> Propagator: Add assert against duplicate done() calls

- src/gui/folderman.cpp
- src/gui/lockwatcher.cpp
- src/gui/lockwatcher.h
- test/CMakeLists.txt
- test/testlockedfiles.cpp
Otherwise the local discovery list might not get filled as needed.
Possibly for #6822, maybe for 2.5.1 too?
FYI @guruz  @mmattel
> Folder: Treat file unlock similar to external change

- doc/troubleshooting.rst
- src/gui/settingsdialog.cpp
F12 is taken on OSX and there's no other way of showing it.
> Add Ctrl-Alt-Shift-L as log window shortcut

- src/libsync/discovery.cpp
- test/testlocaldiscovery.cpp
This also fix the currently failling LockedFilesTest
> Discovery: Fix downloading files when database is used for local discovery

- src/gui/sslbutton.cpp
Always show the menu, no matter if HTTPS is used or not.
And add the server version in the menu
Issue #6628
> SslButton: Add Server version information

- shell_integration/dolphin/CMakeLists.txt
This bugged me for quite some time :-D
> Fix KDEInstallDirs deprecation warnings

- src/libsync/propagateuploadng.cpp
Commit 6ca724f fixed it for the move case. But the upload MOVE did the same
Issue #6904
> Chunking Move: Fix too many starting slashes in the destination header

- src/gui/creds/httpcredentialsgui.cpp
https://sentry.io/owncloud/desktop-win-and-mac/issues/777907931/
mention a crash in OCC::HttpCredentialsGui::showDialog
One possible explaination is that this is caused by re-entring the event loop.
So don't do that.
> HttpCredentials: Do not re-enter the event loop

- src/gui/socketapi.cpp
MacOSX's file system watcher does not deliver events for files modified by
our own process.
Issue: #6844
> SocketApi: make sure to discover the file we want to make virtual

- src/libsync/owncloudpropagator_p.h
- src/libsync/propagatedownload.cpp
- src/libsync/propagateupload.cpp
- test/testdownload.cpp
- test/testsyncengine.cpp
Only do it when it is actually a maintenance mode
Issues #5088, #5859, https://github.com/owncloud/enterprise/issues/2637
> Propagator: Don't abort sync on error 503

- src/common/vfs.cpp
A plugin that can't be loaded due to dependency issues should not be
considered as available.
> Vfs plugins: Available plugins must load

- src/gui/folder.cpp
- src/gui/folder.h
Previously there'd likely be a mess if a 2.6 winvfs folder was attempted
to be used with a 2.5 client. Now the older clients will ignore these
folders.
> Vfs: Ensure older versions gracefully ignore winvfs folders

- src/libsync/vfs/CMakeLists.txt
Fixes in-source builds and other cases where more non-plugin directories
are created in src/libsync/vfs.
@mrow4a Should fix the smashbox build failure you saw.
> Vfs: Have a static list of potential plugins for now

- doc/troubleshooting.rst
- src/common/syncjournaldb.cpp
- src/gui/folder.cpp
- src/gui/folderman.cpp
- test/scripts/txpl/ownCloud/Test.pm
- test/scripts/txpl/t2.pl
- test/scripts/txpl/t6.pl
- test/syncenginetestutils.h
This is to avoid issues on OSX, where the ._ prefix has special meaning.
Originally (before 2.3.2) ._ was necessary to guarantee exclusion. But
since then the .sync_ prefix is excluded as well.
This does not affect existing database files.
For  #5904
> Database: Change path for new dbs to .sync_*

- src/common/syncjournaldb.cpp
- src/common/syncjournaldb.h
- src/gui/socketapi.cpp
- src/libsync/discovery.cpp
- src/libsync/discovery.h
- test/testsyncjournaldb.cpp
- test/testsyncvirtualfiles.cpp
For #6815
This is targeted for 2.5 in the ticket but I'd like to avoid that if possible since it's a new feature.
Warts:
- Maybe `PinState` should be `NewFilesAreVirtualFlag` or something? With options `NewFilesAreVirtual` and `NewFilesAreDownloaded`? I have some hopes of replacing the action-flag like "ItemTypeVirtualFileDehydration" and "ItemTypeVirtualFileDownload" with something orthogonal to the item type.
- The root folder's state isn't stored in the db (the root has no entry). It's stored in `SyncOptions` instead.
- SocketAPI actions can't control the root's state.
- The root "newFilesAreVirtual" state controls whether selective sync is shown or not. That's now weird, since the flag may be set even though all subfolders are `AlwaysLocal`. Or it's not set even though all subfolders …
> Directory level control of whether new files are virtual or not

- src/libsync/progressdispatcher.h
Treat virtual file creation as a size-less action, similar to
propagating renames or deletions.
For  #6933
> Progress: Virtual file creation needs no transfer progress

- src/common/syncjournaldb.cpp
- src/common/syncjournaldb.h
- src/gui/accountsettings.cpp
- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderman.cpp
- src/gui/owncloudsetupwizard.cpp
- src/libsync/discovery.cpp
- src/libsync/discovery.h
- src/libsync/discoveryphase.cpp
- src/libsync/syncoptions.h
- test/testsyncjournaldb.cpp
- test/testsyncvirtualfiles.cpp
This unifies how to deal with pin states.
Also enable reading a folders direct pin state vs its effective pin
state.
> vfs: Remove newFilesAreVirtual - use root PinState instead

- src/gui/CMakeLists.txt
The updated code in qtmacgoodies uses private headers.
> Update qtmacgoodies for an OSX crash fix #6930

- docs/README.md
- site.local.yml
This commit adds two Antora Playbook files, so that the docs can be built, stand-alone, from the remote repository and from the local working copy. It also documents how to build the docs locally.
> Add Antora Playbook files and update docs documentation

- src/libsync/configfile.cpp
ConfigFile sets the application name to `appNameGUI()`, so we should also use that for looking up settings in the registry. 
It's also what is used in NSIS to write the `skipUpdateCheck` setting in the registry. [1] For the unbranded ownCloud client it doesn't matter, but if application name and application shortname differ, the current code fails to retrieve the setting correctly. 
Worst of all: it's completely inconsistent: for user policies the shortname is used `appName()` but for machine policies the full application name is used via `APPLICATION_NAME`. Replaced that also with `appNameGUI()` to be more consistent.
[1] https://github.com/owncloud/client/blob/master/cmake/modules/NSIS.template.in#L819
> Fix lookup of system wide settings

- src/common/syncjournaldb.cpp
Please double check that this is safe to do for a patch release. I think it is.
For #6881
> sqlite: Set exclusive locking_mode to avoid WAL issues

- src/common/result.h
- src/common/syncjournaldb.cpp
- src/common/syncjournaldb.h
- src/gui/accountsettings.cpp
- src/gui/accountsettings.h
- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderstatusmodel.cpp
- test/testsyncjournaldb.cpp
There is now a local/online availability switch on folder context menus in the settings as well as a menu entry to switch into vfs mode and away from it.
I looked at migrating between the two analogous settings (selective sync excluded <-> vfs online-only) but it's complex and will probably not produce exactly what users want. So instead I just start with blank vfs and selective sync settings after switching.
Details: When switching on vfs it seems natual to make all excluded paths online-only, the rest available-locally. But then switching on vfs has no visible effect for users that didn't use selective sync unless they manually also switch folders to online-only.
Migrating from vfs to selective sync is just hard since vfs can have arbitrary switches back and forth between online/local …
> Vfs <=> selective sync switching

- src/libsync/discovery.cpp
- test/testsyncvirtualfiles.cpp
Depends on #6954 - that must merge first.
For #6953
> Fix discovery crash when non-virtual but suffixed files exist on server or in db

- docs/modules/ROOT/pages/building.adoc
I'm not sure why I added the attribute previously, in 0afd511b9cbc30e9586d388c32c72d4d25ddddaf, but it's not necessary and has caused some confusion. Given that, this commit's removing it.
> Remove unrequired start attribute

- src/libsync/propagatedownload.cpp
It contains the compressed size.
See https://bugreports.qt.io/browse/QTBUG-73364
> Download: Ignore content-length for compressed HTTP2/SPDY replies #6885

- src/libsync/creds/httpcredentials.cpp
- src/libsync/creds/httpcredentials.h
Also, calling deleteLater() on jobs is unnecessary (they autodelete
after finished()) and deleting the attached QSettings is also
unnecessary because the settings object is parented to the job.
See  #6776
> HttpCreds: Warn in log if keychain-write jobs fail

- .drone.yml
- CMakeLists.txt
- src/csync/DefineOptions.cmake
Compare https://cmake.org/cmake/help/v3.0/module/CTest.html
Craft automatically handles BUILD_TESTING, so we don't need to handle it
in our own blueprint.
> Switch to standard opt-out BUILD_TESTING instead of opt-in UNIT_TESTING

- src/cmd/cmd.cpp
- src/libsync/propagateupload.cpp
- src/libsync/syncengine.cpp
- src/libsync/syncengine.h
- test/syncenginetestutils.h
On Linux and Windows the file watcher can't distinguish between changes
that were caused by the process itself, like during a sync operation,
and external changes. To work around that the client keeps a list of
files it has touched and blocks notifications on these files for a bit.
The duration of this block was originally and arbitrarily set at 15
seconds. During manual tests I regularly thought there was a bug when
syncs didn't trigger, when the only problem was that my changes happened
too close to a previous sync operation.
This change reduces the duration to three seconds. I imagine that this
is still enough.
> File watcher: Reduce touch ignore duration

- test/testsyncengine.cpp
It was using the wrong path to the conflict file.
> Tests: Fix permission propagation check

- src/cmd/cmd.cpp
- src/common/syncjournaldb.cpp
- src/common/syncjournaldb.h
- src/common/vfs.h
- src/gui/folderstatusmodel.cpp
- src/gui/owncloudgui.cpp
- src/gui/protocolwidget.h
- src/libsync/configfile.cpp
- src/libsync/configfile.h
- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- src/libsync/progressdispatcher.cpp
- src/libsync/progressdispatcher.h
- src/libsync/propagatedownload.cpp
- src/libsync/propagatedownload.h
- src/libsync/propagatedownloadzsync.cpp
- src/libsync/propagateupload.cpp
- src/libsync/propagateupload.h
- src/libsync/propagateuploadng.cpp
- src/libsync/propagateuploadv1.cpp
- src/libsync/syncengine.cpp
- src/libsync/syncengine.h
- src/libsync/syncfileitem.h
- src/libsync/syncoptions.h
- src/libsync/vfs/suffix/vfs_suffix.cpp
- src/libsync/vfs/suffix/vfs_suffix.h
- test/testchunkingng.cpp
- test/testdownload.cpp
- test/testsyncengine.cpp
- test/testuploadreset.cpp
Many warnings originated in the fact that the code wasn't consistent about whether it used `qint64` or `quint64` for file sizes. It now consistently uses `qint64`.
> Fix compiler warnings

- src/cmd/cmd.cpp
- src/common/syncjournaldb.cpp
- src/common/syncjournaldb.h
- src/gui/accountsettings.cpp
- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderstatusmodel.cpp
- src/gui/selectivesyncdialog.cpp
- src/gui/sharemanager.cpp
- src/libsync/propagatedownload.cpp
- src/libsync/propagateupload.cpp
- src/libsync/syncengine.cpp
- test/testselectivesync.cpp
- test/testsyncengine.cpp
- test/testsyncjournaldb.cpp
- test/testsyncmove.cpp
- test/testsyncvirtualfiles.cpp
As far as I'm aware local discovery can be skipped on folders that are
selective-sync blacklisted, so a local discovery is required when an
entry is removed from the blacklist.
Also rename
avoidReadFromDbOnNextSync() -> schedulePathForRemoteDiscovery()
since the old name might also imply it's not read from db in the local
discovery - which is not the case. Use Folder::
schedulePathForLocalDiscovery() for that.
> Ensure local discovery on selective sync changes

- src/gui/wizard/owncloudsetuppage.cpp
This could lead to odd behavior when slotCertificateAccepted
was called multiple times.
> Wizard: Avoid cert dialog multiple connection

- src/gui/socketapi.cpp
With the recent bugfix to avoid sending messages on dead connections
0bfe7ac250c54f5415c0a794c7b271428e83c3cf
the client now crashed if readyRead() was received after disconnected()
for the socket as the listener for that connection was already removed.
This code fixes it by still invoking the handler from readyRead() but
passing a SocketListener that won't attempt to send messages.
> SocketApi: Fix crash with readyRead() after disconnected() #7044

- src/libsync/accessmanager.cpp
Due to QTBUG-73947 and #7020.
Use OWNCLOUD_HTTP2_ENABLED=1 to enable anyway.
> Disable HTTP2 by default

- src/gui/socketapi.cpp
For #6977, already fixed in master.
Since the rename is triggered by the client process the folder watcher
didn't pick up on it on OSX.
> Vfs: Fix folder dehydration requests on OSX

- src/gui/accountsettings.cpp
doExpand() is called when the selective sync editing mode is enabled in
the folder settings view. Previously it'd set the expansion to be
exactly the root items. Now, it just expands any root items that are
currently collapsed, leaving all other item expansion unchanged.
For  #7055
> Selective sync: Don't collapse tree when entering mode

- src/libsync/discovery.cpp
- test/testsyncmove.cpp
Previously they were detected as DELETE+NEW because if "a" is renamed to
"A" then QFile::exists("a") will still return true on Windows.
> Discovery on Windows: Fix detection of case-only renames

- src/csync/csync_exclude.cpp
- test/csync/csync_tests/check_csync_exclude.cpp
> Windows: Forbid chars 0-31 in filenames 

- ChangeLog
- src/common/ownsql.cpp
- src/common/ownsql.h
- src/common/syncjournaldb.cpp
- test/testownsql.cpp
- test/testpermissions.cpp
For #6677, fyi @Phlos
This could fix a problem where the client incorrectly decides to delete
local data.
Previously any sqlite3_step() return value that wasn't SQLITE_ROW would
be interpreted as "there's no more data here". Thus an sqlite error at a
bad time could cause the remote discovery to fail to read an unchanged
subtree from the database. These files would then be deleted locally.
With this change sqlite errors from sqlite3_step are detected and
logged. For the particular case of SyncJournalDb::getFilesBelowPath()
the error will now be propagated and the sync run will fail instead of
performing spurious deletes.
Note that many other database functions still don't distinguish
not-found from error cases. Most of them won't have as severe effects on
affected sync runs though.
> OwnSql: Distinguish no-data from error 

- src/libsync/owncloudpropagator.h
- src/libsync/propagatedownload.cpp
- src/libsync/syncengine.h
- test/testdownload.cpp
From issue #7015, the code is wrong because the path is the file system path and
not the path on the DB.
But since this is a conflict, this means the reconcile will still want to download
the file from the server next sync, so we need not to worry about this case
> Download: Remove useless code and add a test

- src/gui/sharelinkwidget.cpp
- src/gui/socketapi.cpp
- src/libsync/capabilities.cpp
- src/libsync/capabilities.h
Previously it gave up if "expiry required" was enabled. Now it'll create
a link share per day with the default expiry for these setups.
For  #7061
@michaelstingl I think this is safe enough that we could include it in 2.5.4 if desired.
> Shares: "copy link" action can create shares with expiry

- src/gui/folderwatcher.cpp
This makes sure that the conflict list can be updated if a user resolves
a conflict by deleting the local conflict file. Previously one had to
wait for the next sync run.
For  #7073
> FolderWatcher: Always notify about conflict files

- src/gui/application.cpp
- src/gui/application.h
- src/gui/main.cpp
- src/gui/owncloudgui.cpp
- src/gui/owncloudgui.h
When owncloud is started during desktop startup the tray may not yet
be running when the client starts. This will make the client attempt
to create a tray icon again after 10 seconds if there's no tray
during initial startup.
For  #6518
> Tray: Try to establish tray after 10s if failed initially

- src/gui/folder.cpp
- src/gui/folderwatcher.cpp
- src/gui/folderwatcher.h
- src/gui/folderwatcher_linux.cpp
- src/gui/folderwatcher_linux.h
- src/gui/folderwatcher_mac.h
- src/gui/folderwatcher_win.h
- test/testfolderwatcher.cpp
Previously it depended on addFolder() / removeFolder() calls to adjust
watchers when new folders were added or removed. There also needed to be
complex move handling.
Now, any folder creation/move-in notifications automatically trigger
watcher additions and folder deletion/move-out triggers removal.
For  #7068 and a replacement of the 2.5 workaround #7069. I think this is too high risk for 2.5.4.
> FolderWatcher linux: Make automatically recursive

- src/gui/addcertificatedialog.ui
- src/gui/creds/httpcredentialsgui.h
- src/gui/wizard/owncloudhttpcredspage.cpp
- src/gui/wizard/owncloudoauthcredspage.cpp
- src/gui/wizard/owncloudsetuppage.cpp
- src/gui/wizard/owncloudwizard.h
- src/libsync/account.cpp
- src/libsync/creds/httpcredentials.cpp
- src/libsync/creds/httpcredentials.h
It still reads and writes the old format too, but all newly stored
client certs will be in the new form.
For #6776 because Windows limits credential data to 512 bytes in older
versions.
> Client certs: Store pkcs12 in config, password in keychain

- ChangeLog
Some of these are rather major (discovery, deltasync, vfs) and encompass dozens of commits each. I filtered for what's user-relevant somewhat.
> Add basic 2.6.0 changelog

- src/common/utility_unix.cpp
It seems that sometimes the tray implementation isn't ready on system
startup. Retrying later seems to not help. Delaying the start of the
client is the workaround that people have reported as effective.
For  #6518 since the internal retry seems to be uneffective.
> Linux: Add autostart delay to avoid tray issues

- src/gui/folderman.cpp
- test/testfolderman.cpp
When the user typed "x:" where the drive x didn't exist, the validation
function would loop forever. Now it shows a "path doesn't exist" error.
For  #7041
> FolderWizard: Don't crash when typing invalid drive

- src/libsync/discovery.cpp
- src/libsync/propagateremotemove.cpp
- test/testsyncvirtualfiles.cpp
Users can rename a file *and* add/remove the vfs suffix at the same time
leading to very complex sync actions. This patch doesn't add support for
them, but adds tests and makes sure these cases do not cause unintened
behavior.
The rename will be propagated, but the users's hydrate/dehydrate request
will be ignored.
For  #7001. I still need to test it with winvfs, and will also drop the commented-out code once it's clear it's not needed.
> VFS: Unbreak behavior for rename+hydrate

- src/gui/folder.cpp
- src/gui/protocolwidget.cpp
- src/gui/syncrunfilelog.cpp
- src/libsync/localdiscoverytracker.cpp
- src/libsync/owncloudpropagator.cpp
- src/libsync/propagatedownload.cpp
- src/libsync/propagatorjobs.cpp
- test/testsyncmove.cpp
- test/testsyncvirtualfiles.cpp
Previously sometimes _file = _renameTarget, and sometimes not. Now information in _file is always preserved.
It's not entirely consistent yet: SYNC(ItemTypeVirtualFileDehydration) has _file and _renameTarget differ, but SYNC(ItemTypeVirtualFileDownload) has an empty _renameTarget. I started adjusting that, but it felt very awkward since the whole existing download job assumes using _file is fine.
> Make handling of _renameTarget consistent

- src/cmd/cmd.cpp
- src/gui/folder.cpp
- src/libsync/CMakeLists.txt
- src/libsync/syncoptions.cpp
- src/libsync/syncoptions.h
Moves a bunch of env var reading from Folder into SyncOptions.
For  #7078
> owncloudcmd: Use env vars for chunk sizes

- src/libsync/discovery.cpp
- test/testsyncvirtualfiles.cpp
Previously removing the vfs suffix of a file always triggered a
conflict. Now it may just cause a file download.
This was done because users expected symmetry in the rename actions and
renaming foo -> foo.owncloud already triggers the "make the file
virtual" action. Now foo.owncloud -> foo triggers the "download the
contents" action.
> Vfs: Better handling and more tests for suffix file renames

- src/libsync/discovery.cpp
- src/libsync/discoveryphase.cpp
- test/testremotediscovery.cpp
This has two positive effects:
- We can put the error on the particular file that has missing data
- We can sync all other files
For  #7112
> Detect missing server data during discovery

- src/libsync/owncloudpropagator.cpp
- test/testsyncengine.cpp
For #7119. Also remove some unused code while reviewing the function.
> When creating local dirs, set mtime to server one

- src/common/pinstate.h
- src/csync/csync.h
- src/gui/accountsettings.cpp
- src/gui/application.cpp
- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/socketapi.cpp
- src/libsync/discovery.cpp
- src/libsync/discovery.h
- test/testsyncvirtualfiles.cpp
The pin state is a per-item attribute that has an effect on _type:
AlwaysLocal dehydrated files will be marked for hydration and OnlineOnly
hydrated files will be marked for dehydration.
Where exactly this effect materializes depends on how the pin states are
stored. If they're stored in the db (suffix) the dbEntry._type is
changed during the discovery.
If the pin state is stored in the filesystem, the localEntry._type must
be adjusted by the plugin's stat callback.
This patch makes pin states behave more consistently between plugins.
Previously with suffix-vfs pin states only had an effect on new remote
files. Now the effect of pinning or unpinning files or directories is as
documented and similar to other plugins.
Note: This requires an extra db lookup per file. If you have suggestions …
> Vfs: Clear up relationship between _type and pin state

- src/common/pinstate.h
- src/common/syncjournaldb.cpp
- src/common/syncjournaldb.h
- src/common/vfs.cpp
- src/common/vfs.h
- src/gui/accountsettings.cpp
- src/gui/socketapi.cpp
- src/libsync/vfs/suffix/vfs_suffix.cpp
- src/libsync/vfs/suffix/vfs_suffix.h
- test/testsyncjournaldb.cpp
- test/testsyncvirtualfiles.cpp
For #7111
The idea is that the user's question is "is this folder's data available
offline?" and not "does this folder have AlwaysLocal pin state?".
The the answers to the two questions can differ: an always-local
folder can have subitems that are not always-local and are dehydrated.
The new availability enum intends to describe the answer to the user's
actual question and can be derived from pin states. If pin states aren't
stored in the database the way of calculating availability will depend
on the vfs plugin.
Needs changes to plugins and depends on PR #7131. Also still needs tests! (EDIT: Tests are done)
> Vfs: Add 'availability', a simplified, user-facing pin state

- src/libsync/discovery.cpp
- src/libsync/owncloudpropagator.h
- src/libsync/syncengine.cpp
- test/testremotediscovery.cpp
PRing the cleanups/test additions from #7134
> Fix discovery getting stuck on 403/503 reply on root item

- src/libsync/discovery.cpp
- test/testallfilesdeleted.cpp
Previously the property wasn't queried, meaning the fingerprint logic
couldn't get triggered.
> Discovery: Query data-fingerprint on root item

- src/common/syncjournaldb.cpp
According to the documentation DELETE+NORMAL isn't safe from corruption
on older file systems.
This would be a correctness change, but it's subject to discussion. We only use DELETE journals on exfat an on user request. But when I recently read https://www.sqlite.org/pragma.html#pragma_synchronous it sounded like FULL would be the sync mode one should use alongside it.
> Sqlite: Use FULL synchronous mode with non-WAL journal

- src/libsync/syncengine.cpp
The db-close operation is likely a leftover from when the SyncEngine
owned its own db connection and serves no purpose anymore.
Closing the db causes the removal of the temporary wal and shm files.
These files are recreated when the db is opened again, which happens
almost immediately.
This is a problem for winvfs because the delete-recreate step wipes the
exclusion state on these files just after the sync is done. That meant
that the db temporaries permanently had a "needs sync" icon marker shown
in the explorer. See  #7141
Avoiding reopening the db also reduces the number of log messages per
sync.
> SyncEngine: Don't close db when done

- src/gui/folder.cpp
- src/gui/socketapi.cpp
For #7124, and a related issue discovered during testing.
I think these are already fixed on `master`, but I'll definitely double-check. EDIT: Yes, same thing works already on master.
It'd be very nice if these actions could be unittested, but they require a `Folder`, not just a `SyncEngine`. Could be worth investigating though.
> Fix vfs hydration and dehydration actions

- src/csync/csync_exclude.cpp
QStringRef::operator[] was introduced in 5.7. QStringRef::at() is
equivalent.
> Fix issues with Qt 5.6

- src/gui/ocssharejob.cpp
- src/gui/ocssharejob.h
- src/gui/sharelinkwidget.cpp
- src/gui/sharelinkwidget.h
- src/gui/sharelinkwidget.ui
- src/gui/sharemanager.cpp
- src/gui/sharemanager.h
- src/gui/socketapi.cpp
The important thing is that, similar to the web link share creation
flow, the share properties can be set before creation is done. This
allows better handling of error conditions. One such condition is the
password policy app restricting valid expire dates.
See owncloud/enterprise#3271
This significantly adjusts how the link share creation flows, will post images below.
> Link shares: Adjust creation flow

- src/gui/accountstate.cpp
This got inverted accidentally when std::chrono was introduced.
For #7160
> Fix logic for duration that an etag reply indicates connectivity

- src/common/vfs.cpp
- src/common/vfs.h
- src/gui/socketapi.cpp
- src/libsync/vfs/suffix/vfs_suffix.cpp
- src/libsync/vfs/suffix/vfs_suffix.h
Previously "no-availability" meant db-error and querying the
availability of a nonexistant path returned AllHydrated.
Now, the availability has a DbError and a NoSuchItem error case.
For #7143
Plugin API change, let me merge.
> Vfs: Distinguish availability error kinds 

- src/common/syncjournaldb.cpp
- src/common/syncjournaldb.h
- src/gui/folder.cpp
- src/gui/folderman.cpp
- src/libsync/syncengine.cpp
The previous patch ensured that the sqlite temporaries weren't deleted
and recreated for every sync run, but there was still time between
client startup and the first sync run where they would have the
"needs-sync" icon.
For  #7141
> Vfs: Mark sqlite temporaries excluded on db-open

- docs/antora.yml
This change is required to correctly display the version within the ownCloud docs component selection.
> [2.6] Change docs version to right value

- docs/antora.yml
This PR fixes the following error, which has been breaking the documentation builds:
```
Error: Duplicate nav: 2.6@desktop:ROOT:nav.adoc
at ContentCatalog.addFile (/Users/settermjd/Workspace/clients/ownCloud/docs/node_modules/@antora/content-classifier/lib/content-catalog.js:91:13)
at files.forEach (/Users/settermjd/Workspace/clients/ownCloud/docs/node_modules/@antora/content-classifier/lib/classify-content.js:23:78)
at Array.forEach (<anonymous>)
at aggregate.reduce (/Users/settermjd/Workspace/clients/ownCloud/docs/node_modules/@antora/content-classifier/lib/classify-content.js:23:13)
at Array.reduce (<anonymous>)
at classifyContent (/Users/settermjd/Workspace/clients/ownCloud/docs/node_modules/@antora/content-classifier/lib/classify-content.js:21:36)
at aggregateContent.then …
```
> Fix ROOT component version in master branch

- src/gui/notificationwidget.cpp
Happens when the activity is updated
QDialogButtonBox::removeButton does not delete the button, it just reparent
it to nullptr.
Issue #7185
> NotificationWidget: Fix buttons being leaked and show top level

- src/gui/socketapi.cpp
- src/gui/socketapi.h
- src/libsync/capabilities.cpp
- src/libsync/capabilities.h
The new menu entry depends on the privateLinksDetailsParam
capability of the server.
For  #7196
> SocketAPI: Add "show versions" to shell context menu

- src/libsync/syncengine.cpp
- test/testallfilesdeleted.cpp
Possibly a regression, since the new discovery discovers rist the renamed
files as removed
Issue #7204
> SyncEngine: Fix renaming a single file cause the "delete all file" popup

- src/libsync/syncengine.cpp
- test/testpermissions.cpp
it seems likely to decrease the severety of #6877: if the database isn't closed and reopened as frequently users are less likely to run into crashes when the sqlite connection switches to wal journaling mode.
> Backport change to stop closing the db connection when a sync finishes

- src/libsync/abstractnetworkjob.cpp
- src/libsync/abstractnetworkjob.h
- src/libsync/propagatedownload.cpp
- test/syncenginetestutils.h
- test/testdownload.cpp
Since Qt does not yet transparently resend HTTP2 requests in some cases
we do it manually.
The test showed a problem where the initial non-200 reply would close
the target temporary file and the follow-up request couldn't store any
data. Removing that close() call is safe because there also is a
_saveBodyToFile flag that guards writes to the target file.
For #7174
> Http2: Resend requests on ContentReSend error 

- src/libsync/propagateupload.cpp
- src/libsync/propagateupload.h
- src/libsync/propagateuploadng.cpp
- src/libsync/propagateuploadv1.cpp
Instead of all at once, to reduce peak memory use.
Changing UploadDevice in this way requires keeping the file open for the
duration of the upload. It also means changes to open(), seek(), close()
to ensure that uses of the device work right when a request needs to
be resent.
Let's consider whether this is safe for 2.5 or should be a 2.6 change!
For #7226
> Upload: Read file chunks gradually 

- src/gui/updater/ocupdater.cpp
- src/gui/updater/ocupdater.h
For #7217 and https://github.com/owncloud/enterprise/issues/3278
Since this is for the updater it needs particuarly thorough review and QA. See below for details.
Need to find a way to make autoupdating fail for tesing.
Expected behaviors:
- Skip this version: Not asked again on restart. Shows as "up to date" in updater info view.
- Ask again later: Asks again on client restart.
- Restart and update: Attempts the updating process again.
- Update manually: Like "skip this version" but also opens browser on updating page.
> WinUpdater: More useful options on update failure

- src/gui/folder.cpp
- src/gui/folderwatcher.cpp
- src/gui/folderwatcher.h
- src/gui/folderwatcher_linux.cpp
Necessary for some filesystems on windows that don't have full file
watching capabilities.
#7241 https://github.com/owncloud/enterprise/issues/3303
> FolderWatcher: Become unreliable if test notification fails

- src/gui/socketapi.cpp
- src/libsync/capabilities.cpp
- src/libsync/capabilities.h
- Don't show it for directories.
- Don't show it when versioning is disabled.
For  #7196
> Shell extension: Show "show versions" only when available

- src/gui/accountsettings.cpp
Currently it's confusing because without user changes "Sync None" and
"Apply manual changes" have the same meaning. Now the "Apply" action
only becomes available if changes were made.
For #7230
> BigFolders: Enable "apply manual changes" only if dirty

- src/gui/sharelinkwidget.cpp
Since the check boxes are disabled users can't check them themselves.
For #7246
> Sharing: Pre-check pw/expiry if the server requires it

- src/gui/socketapi.cpp
Fixes the "Copy public link to clipboard" context menu action for newer
servers.
Previously the server would fill the expiration date for us, since
version 10.2.0 it reports an error. To workaround that the action now
always sends an expiration date if default expiration is enabled in
the settings.
For #7245
> Sharing: Fix fast share creation with enforced expiry and 10.2.0

- src/common/vfs.cpp
- src/libsync/propagateremotemove.cpp
- src/libsync/propagateupload.cpp
- src/libsync/propagatorjobs.cpp
- test/testsyncvirtualfiles.cpp
That means new and renamed files and folders in online-only directories will no longer become dehydrated.
For #7250
> Set pin state of new and renamed virtual files

- src/libsync/propagateupload.cpp
- src/libsync/propagateupload.h
- Close the UploadDevice to close the QFile after the PUT job is done.
This allows winvfs to get an oplock on the file later.
- Don't rely on QFile::fileName() to be valid after
openAndSeekFileSharedRead() was called. The way it is openend on
Windows makes it have an empty filename.
For #7264
> UploadDevice: Fix windows issues 

- ChangeLog
Is it acceptable to break the huge changelog into two sections and include links to the wiki for complex new features?
> Update 2.6.0 changelog

- src/libsync/networkjobs.cpp
- src/libsync/networkjobs.h
- src/libsync/owncloudpropagator_p.h
- test/syncenginetestutils.h
Previously RequestEtagJob did return the etag verbatim (including extra
quotes) while the db had the parsed form. That caused the etag
comparison during discovery move detection to always fail. The test
didn't catch it because the etags there didn't have quotes.
Now:
- RequestEtagJob will parse the etag, leading to a consistent format
- Tests have etags with quotes, detecting the problem
For #7271
> RequestEtagJob: Consistently parse etags 

- src/common/syncjournaldb.cpp
- src/common/syncjournaldb.h
- src/common/vfs.cpp
- src/common/vfs.h
- src/gui/folder.cpp
- src/gui/socketapi.cpp
- src/libsync/discovery.cpp
- src/libsync/propagatedownload.cpp
- src/libsync/syncengine.cpp
- src/libsync/vfs/suffix/vfs_suffix.cpp
- test/testsyncvirtualfiles.cpp
Previously the pin states of deleted files stayed in the 'flags'
database and could be inadvertently reused when a new file with the same
name appeared. Now they are deleted.
To make this work right, the meaning of the 'path' column in the 'flags'
table was changed: Previously it never had the .owncloud file suffix.
Now it's the same as in metadata.path.
This takes the safe parts from #7274 for inclusion in 2.6. The more
elaborate database schema changes (why use 'path' the join the two
tables in the first place?) shall go into master.
For #7273
> VfsSuffix: Wipe stale pin states

- src/gui/sharemanager.cpp
- src/gui/shareusergroupwidget.cpp
If user A shares something with user B and allows resharing but removes
some other permission then user B should be able to share the item or
any of its contents with user C and the new share permissions should
automatically be <= the permissions of the original share.
Currently this works correctly when resharing the original item but
fails for any subitem, preventing the reshare entirely.
With this patch the reshare will always be created with appropriately
limited permissions.
For #7275
> Sharing: Create shares with appropriate permissions

- src/gui/accountsettings.cpp
- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderman.cpp
- src/gui/owncloudsetupwizard.cpp
Previously all local data was deleted because the root folder was marked
as OnlineOnly.
See #7302
> Vfs: Retain existing data when enabling vfs

- src/gui/folderwatcher.cpp
- src/gui/folderwatcher.h
- src/gui/folderwatcher_linux.h
- src/gui/folderwatcher_mac.h
- src/gui/folderwatcher_win.cpp
- src/gui/folderwatcher_win.h
Before on Windows sometimes the file touching was done before the WatcherThread of the FolderWatcher was ready to track events.
For  #7305
> FolderWatcher: Wait for ready before testing

- .drone.yml
- test/CMakeLists.txt
It seems reliable when run manually, but frequently breaks when executed
by drone.
> Drone: Skip DatabaseErrorTest

- src/gui/guiutility.cpp
"Currently always" read very oddly.
> Vfs: Improve strings for availability states

- src/csync/csync_update.cpp
When a file is tagged ItemTypeVirtualFileDownload in the database the
REMOTE pass in csync_update would not find the matching item in the
database. It worked anyway since the rename detection finds it, sees
the type tag and does the right thing. But the logging was confusing.
This change allows the pass to find the matching entry in the database
and proceed to the "db-entry-found" case without going through rename
detection.
Seen in #7231
> SuffixVfs: Simplify logs by avoiding EVAL_RENAME for downloads

- src/libsync/propagateupload.cpp
This will avoid a rare-but-regular crash in low-memory situations.
Note that this is a workaround: In 2.6 this code should be adjusted to
not read a full file chunk into memory immediately and instead load more
data on demand.
For  #6880
> Upload: Catch out-of-memory error

- src/common/vfs.h
- src/libsync/discovery.cpp
- src/libsync/syncengine.cpp
- src/libsync/vfs/suffix/vfs_suffix.h
Allows winvfs to convert files to placeholders when vfs is enabled. This
is required to mark files as in-sync #7329.
Needs matching winvfs change.
> Vfs: Add hook to allow update-metadata for unchanged files

- src/libsync/propagatedownload.cpp
- src/libsync/vfs/suffix/vfs_suffix.cpp
- test/testsyncvirtualfiles.cpp
Previously an implicit hydration of a file in an online-only folder
would not change the pin state and cause a dehydration on the next
sync.
@HanaGemela FYI
> Vfs: Ensure pins change with (de-)hydration

- src/libsync/discovery.cpp
Previously a checksum computation could be done on a suffix-placeholder
file, making discovery believe that no move took place.
For #7001
> Vfs: Make move detection work with virtual files 

- src/libsync/discovery.cpp
- test/testsyncvirtualfiles.cpp
> Vfs: Remove old db record when dehydrating via rename

- src/gui/accountsettings.cpp
Without it local files aren't guaranteed to be downloaded #6936.
> Vfs: Require local discovery after disabling vfs

- src/libsync/discoveryphase.cpp
This avoids unnecessary sync runs.
For #7345
> Discovery: Parse etag to be consistent with RequestEtagJob

- src/libsync/syncengine.cpp
Previously fatal error texts were duplicated: Once they entered the
SyncResult via the SyncFileItem and once via syncError().
syncError is intended for folder-wide sync issues that are not pinned
to particular files. Thus that duplicated path is removed.
For #5088
> SyncEngine: Don't duplicate fatal errors

- src/gui/folderstatusmodel.cpp
That helps avoid empty lists after account creation #7336
> AccountSettings: Fetch subitems after wiping them

- src/common/checksums.cpp
- src/common/checksums.h
- test/testchecksumvalidator.cpp
The checksum computation thread was potentially using a QFile that was
deleted in the gui thread.
For #7368
> Checksums: Fix crash due to threading issue

- src/common/checksums.cpp
- src/libsync/propagatedownload.cpp
Previously the job would only become "active" when the downloads
started. That meant that arbitrarily many hash computations could be
queued at the same time.
Since the the file was opened during future creation this could lead to
a "too many open files" problem if there were lots of new-new conflicts.
To change this:
- Make PropagateDownload become active when computing a hash
asynchronously.
- Make the computation future open the file only once it gets run. This
will make it less likely for this problem to occur even if thousands
of these futures are queued.
For #7372
> Download: Don't trigger too many concurrent hash computations

- src/common/checksums.cpp
- src/common/checksums.h
Because the winvfs plugin needs it. But be more careful about the
device's lifetime this time.
This will need matching winvfs changes. I'll also merge 2.6 into master and update both winvfs branches.
> Checksums: Add back QIODevice api

- src/CMakeLists.txt
The settings are enabled by default with msvc
> Don't set gnu style flags with msvc

- src/gui/folderwizard.cpp
- src/gui/wizard/owncloudwizard.cpp
Related issue: https://github.com/owncloud/client/issues/7406
> OwncloudWizard: Mark vfs as tech preview instead of experimental

- src/libsync/owncloudpropagator_p.h
This is an unreliable workaround. The real fix will need to be deferred
to another release.
For #5088
> Don't fatal on "Storage temporarily unavailable"

- src/libsync/propagatedownload.cpp
This situation could arrise when receiving a read-only share and the
temporary rename failed for some reason.
See #7419
> PropagateDownload: Don't try to open readonly temporaries

- src/libsync/owncloudpropagator.cpp
- src/libsync/owncloudpropagator.h
- test/syncenginetestutils.h
- test/testpermissions.cpp
- test/testsyncmove.cpp
By introducing a PropagateRootDirectory job that explicitly
separates the directory deletion jobs from all the other jobs.
For #7441
> Propagation: Fix delete-before-rename bug

- src/gui/sharelinkwidget.cpp
- src/gui/sharelinkwidget.ui
For #7429
The only reason I'd have this in 2.6.0 is because there was a bug where the new sharing permission labels weren't hidden along with the radio button options.
> ShareLinks: Always show at least readonly permissions

- docs/modules/ROOT/pages/building.adoc
In a code sample, two variables were being incorrectly interpreted as AsciiDoc variables, and throwing build warnings. This PR corrects these two references.
> Fix incorrect AsciiDoc attribute references in docs

- src/gui/connectionvalidator.h
When the gui thread blocks for several seconds it's possible for the
ConnectionValidator to timeout and decide that the account is
unreachable. It will then terminate all sync runs.
Increasing the timeout makes this less likely to happen. The tradeoff is
that real disconnects will not be detected as quickly.
This does not address the root cause but makes the symptom less likely
to appear.
For #7456
> ConnectionValidator: increase timeout to 57s

- src/libsync/discovery.cpp
- src/libsync/discovery.h
There were crashes in the QPointer assignment. Possibly the thread pool
is done with the job and deletes it before the assignment is done.
Thanks for the backtrace @jnweiger
> Don't store pointer to local job

- src/libsync/discovery.h
Old gcc doesn't allow aggregate initialisation of strcuts initialised in class
Fixes: #7451
> Fix build with old gcc

- src/libsync/discovery.cpp
- test/testpermissions.cpp
Adding parallelism broke the test because it depended on the order of
discovery.
> Test: Disable local discovery parallelism in permission test

- src/common/checksums.cpp
To ensure it's no longer open when the finished signal fires.
For #7468
> Checksums: Explicitly close file before reporting result

- docs/modules/ROOT/pages/building.adoc
In a code sample, two variables were being incorrectly interpreted as AsciiDoc variables, and throwing build warnings. This PR corrects these two references.
> Fix incorrect attribute definitions in the docs

- src/libsync/propagateremotemkdir.cpp
- test/testsyncengine.cpp
It must always only be written once all children are successfully
propagated.
For #7481
> Propagate dir: Never write the etag on remote mkdir 

- shell_integration/windows/OCUtil/CommunicationSocket.cpp
- src/gui/socketapi.cpp
This reverts commit ed1e534d24f871a0ab6ea02e4c88eefe3126bf59.
Doesn't make sense to spend effort on this, we keep it as it is.
> Revert "Windows: Use better name for SocketAPI socket #6983"

- src/libsync/discoveryphase.cpp
- test/syncenginetestutils.h
Turns out the drone failures are because of seemingly random errno 11 failures during readdir. These changes should provide better diagnostics and make the source of the failure clearer.
> Investigation around drone test failures

- src/libsync/propagateupload.h
- test/syncenginetestutils.h
- test/testchunkingng.cpp
Issue #7506
This is a regression introduced by the delta sync feature (as the chunk offset
changed from being the chunk number to be the byte offset, it needs to be a
qint64 now)
> Fix Upload of large (> 2GiB) files

- src/gui/owncloudsetupwizard.cpp
It makes no sense to display arbitrary html in a message box.
It is ugly and unfriendly.
The wizard itself already show the error in red.
In case of invalid certificate/ missing clientside certificate, there
is already a dialog that suggest using client side certificates.
Issue #6157
> Wizard: do not display HTML error page from the server in a message box

- docs/modules/ROOT/pages/architecture.adoc
- docs/modules/ROOT/pages/navigating.adoc
- docs/modules/ROOT/pages/troubleshooting.adoc
- docs/modules/ROOT/pages/visualtour.adoc
Fix several broken links in the documentation. Some of the links were incorrectly migrated from the previous Sphinx-Doc implementation. This fixes #7518.
> Fix several broken links

- src/gui/folderstatusdelegate.cpp
To avoid confusion with the color of "success"
Issue #7403
> Account Settings: change the color of info message from green to blue

- .drone.yml
This step has been shown to dramatically lengthen build times. As it's
just an output of the generated documentation, it's not strictly necessary, so
is being removed.
> Remove the build-artifacts Drone step

- src/gui/updater/ocupdater.cpp
There was one argument too many in the string.
Bug was introduced in commit 21ac396b
Issue: #7288
> Updater: Fix Version numer not shown in the user visible string

- src/gui/updater/updateinfo.cpp
The problem was accessing the lines with an off by one error, while printing
the log.
Other problem included the fact that QDebug added spaces, quotes, and other
things which made the error lot look right in the console.
Issue #7545
> Updater: Fix crash when there is an XML error

- src/libsync/discovery.cpp
- src/libsync/discovery.h
- src/libsync/vfs/suffix/vfs_suffix.cpp
- src/libsync/vfs/suffix/vfs_suffix.h
- test/testsyncvirtualfiles.cpp
Avoid or deal with problems that happen when suffixed files exist on the
server or suffix and non-suffixed files exist locally.
See #7350, #7261.
> Vfs: Lots of tests and corrections for suffix edge cases

- src/libsync/discovery.cpp
On windows we do a test to know if we should change the case of the files,
but that conflict with the test that checks if the file was still there
when the filename is actually the same. Which can happen with virtual files
as they have two representation (the one with and without suffix).
> Discovery: fix TestSyncVirtualFiles::testExtraFilesLocalDehydrated on windows

- src/libsync/filesystem.h
This fixes Windows builds that are broken since #7562 was merged
> [libsync] Export verifyFileUnchanged

- src/libsync/discovery.cpp
The original code from csync was stopping at any error.
But we have been whitelisting soeme http error code one by one
to ignore the directory instead of aborting the sync.
However, as there are more requests to continue the sync in case
of error, just ignore most HTTP errors
Issue #7586
> Discovery: Allow more HTTP error code to be treated as ignored dir

- src/gui/networksettings.cpp
- src/gui/networksettings.h
- src/gui/networksettings.ui
Only show this if at least one account is detected to have an url that looks
like localhost, because this could otherwise be confusing
Issue #7169
> Network Settings: Show a warning that proxy settings do not apply to localhost

- src/gui/accountsettings.cpp
> AccountSettings: limit the clickable region of the 'add folder' button

- src/gui/socketapi.cpp
> SocketApi: Don't assume read-only folder when permissions are not known

- src/libsync/discovery.cpp
- src/libsync/syncengine.cpp
- src/libsync/syncfileitem.h
- test/testallfilesdeleted.cpp
> Don't show the "All files deleted" popup when unselecting everything with selective sync

- docs/modules/ROOT/pages/advanced_usage/configuration_file.adoc
- docs/modules/ROOT/pages/navigating.adoc
This PR updates the documentation, adding a link from the GUI config window to the config.ini file documentation. The main reason for doing so is to help ensure that the user knows that they can show and hide the crash reporter from the config file, just in case they need to hide it so that they can debug on-startup crashes. It fixes https://github.com/owncloud/docs/issues/318.
> [318] Document how to show/hide the Crash Reporter from the config.ini

- docs/modules/ROOT/pages/architecture.adoc
- docs/modules/ROOT/pages/navigating.adoc
- docs/modules/ROOT/pages/troubleshooting.adoc
- docs/modules/ROOT/pages/visualtour.adoc
> Fix broken documentation links in the docs for version 2.6

- src/gui/folder.cpp
- src/gui/folder.h
- src/gui/folderman.cpp
For a usual file sync event we check for actual changes in the local file,
after an unlock the local file might be unchanged so we need to sync it anyhow.
Fixes: owncloud/enterprise#3609
> Don't ignore file sync notification after an unlock

- .drone.star
Fixes the changelog pipeline for forked repositories
> Fix for forked repos

- changelog/unreleased/7722
- src/libsync/discoveryphase.cpp
- test/testsyncmove.cpp
Issue #7722
I was not able to reproduce the problem (the new tests don't reproduce it)
But this is just the most plausible explanation for this crash.
> Fix a potential crash in moves

- changelog/unreleased/7744
- src/gui/settingsdialog.cpp
> [GUI] Dynamically elide actions

- changelog/unreleased/7760
- src/libsync/discoveryphase.h
@ogoffart do you think too that could be the cause?
https://sentry.io/organizations/owncloud/issues/1529161263/events/02509984b5ca42ffb3960d9c9e161414/?project=79001&statsPeriod=14d
> Fix potential null pointer access

- changelog/unreleased/7762
- src/gui/creds/oauth.cpp
The server understands '+' as a space.
Issue #7762
> OAuth: make sure to encode the '+' in query string

- changelog/unreleased/7018
- mirall.desktop.in
- src/gui/application.cpp
- src/gui/application.h
> Bugfix: Client sometimes does not show up when started by a user

- src/CMakeLists.txt
Stack protections still breaks mingw builds
> Fix build with mingw

- src/common/vfs.cpp
If the plugin could not be loaded the client calls qFatal
Make the loading warnings critical so they get printed before we crash
> Improve logging of issues during plugin loading

- changelog/unreleased/7759
- src/libsync/syncfilestatustracker.cpp
- test/testsyncfilestatustracker.cpp
> SocketAPI: fix status after a failure to move

- docs/books/ownCloud_Desktop_Client_Manual.adoc
This commit adds the remainder of the client documentation to the PDF configuration file, which were previously missing. I found this while investigating #7653.
> Add the missing documentation content to the PDF configuration file

- docs/books/ownCloud_Desktop_Client_Manual.adoc
This backports #7821 to the 2.6 branch. It adds the remainder of the client documentation to the PDF configuration file, which were previously missing. I found this while investigating #7653.
> Add the missing content to the PDF configuration file

- changelog/unreleased/7831
- src/libsync/accessmanager.cpp
- src/libsync/accessmanager.h
- src/libsync/networkjobs.cpp
This code was actually not breaking most cookie handling by accident.
As the raw cookies where not split properly we added cookies with values like
"key: val; key2 = val2; key3 = val3"
When the code was corrected we overwrote the newer values in the jar with
the old ones from a request.
> Cookies: Don't override cookies with outdated values

- CMakeLists.txt
- cmake/modules/OCConfigPluginDir.cmake
- config.h.in
- src/gui/application.cpp
This fixes installations where the client is not installed in the same prefix as Qt
The idea is to only conditionally add the plugin search path and only if its inside our installation.
On Windows and mac we create distributables that contain everything in the right place.
On Linux not...
Fixes: #7801
> Plugins: Add a relative plugin search path on Linux

- src/gui/wizard/owncloudwizard.cpp
On close the result is the same as accept role (0)...
Issue: #7710
> VFS Dialog: Don't enable on close button clicked

- changelog/unreleased/7856
- src/gui/wizard/owncloudwizard.cpp
The OAuth authentication brings the broweser to the front, once thats done the wizard continues.
But the wizard ist now most probably hidden behind the browser
> Raise the Wizard

- changelog/unreleased/7862
- src/libsync/capabilities.cpp
- src/libsync/capabilities.h
- src/libsync/propagateuploadv1.cpp
The current implementation disables chunking v1 and uses the basic upload.
Is support for unchunked v1 support required?
> Uploads: correctly handle the bigfilechunking capability

- changelog/unreleased/7878
- src/gui/folderman.cpp
> Fix crash on settings migration

- changelog/unreleased/7873
- src/libsync/CMakeLists.txt
- src/libsync/abstractnetworkjob.cpp
- src/libsync/abstractnetworkjob.h
- src/libsync/accessmanager.cpp
- src/libsync/httplogger.cpp
- src/libsync/httplogger.h
Logging is disabled by default, it can be enabled by using:
`QT_LOGGING_RULES = "sync.httplogger=true"`
See https://github.com/owncloud/client/issues/7873
> Log HTTP requests and responses

- changelog/unreleased/7925
- src/gui/accountsettings.cpp
This fixes a strange flickering when the client is started with the gui visible.
> Gui: hide the selective sync pop up by default

- docs/modules/ROOT/pages/troubleshooting.adoc
I always forget `QT_LOGGING_RULES`, so I decided to add some examples to the docs.
Especially HTTP Logging might by handy: https://github.com/owncloud/client/pull/7891
> Add example QT_LOGGING_RULES to troubleshooting.adoc

- src/gui/accountmanager.cpp
Don't log that there was no error...
We might even want to remove it...
> Log: Only print 'Saved account settings' in debug mode

- src/gui/folderwatcher.cpp
- src/gui/socketapi.cpp
- test/owncloud_add_test.cmake
Since we link the core into the tests the define has no effect.
> Remove OWNCLOUD_TEST define handling

- src/gui/CMakeLists.txt
CMake Warning (dev) in src/gui/CMakeLists.txt:
A logical block opening on the line
D:/a/client/client/src/gui/CMakeLists.txt:230 (IF)
closes on the line
D:/a/client/client/src/gui/CMakeLists.txt:246 (endif)
with mis-matching arguments.
> CMake: Fix warning
