owncloud/client

src/gui/application.cpp
warning C4573: the usage of 'QObject::disconnect' requires the compiler to capture 'this' but the current default capture mode does not allow it
=> Fix warning

src/gui/generalsettings.cpp, src/gui/openfilemanager.cpp
D:\a\client\client\src\gui\generalsettings.cpp(74): warning C4996: 'QSysInfo::windowsVersion': Use QOperatingSystemVersion::current()
C:\CraftMaster\windows-msvc2017_32-cl\include\qt5\QtCore/qsysinfo.h(217): note: see declaration of 'QSysInfo::windowsVersion'
=> Fix deprecation warning

changelog/unreleased/7962, src/gui/generalsettings.ui, src/gui/settingsdialog.cpp
=> Gui: Rename "General" -> "Settings" and move "Network" -> "Settings"

changelog/unreleased/7989, src/common/checksums.cpp, src/common/checksums.h, src/libsync/capabilities.cpp, src/libsync/propagatedownload.cpp, src/libsync/propagateupload.cpp
Local computation of sha1 checksum
Comparison with the checksum the remote provided after upload (sha256), therefore re computation of local checksum with sha256. 
Related: https://gitea.owncloud.services/client/client-plugin-vfs-win/pulls/11
=> Use the servers checksum type by default

src/common/syncjournaldb.cpp
We also don't have a version entry in the db if thne db is new.
As I don't expect regular updates from 1.5 this message can just be removed.
Fixes: #8004
=> Remove pointless warning

docs/modules/ROOT/pages/troubleshooting.adoc
Realized the rendering for the example was off on https://doc.owncloud.com/desktop/troubleshooting.html#saving-files-directly
Also, moved the '--logdebug' one line down as the next section deals precisely with it.
=> Fix syntax highlighting for --logexpire example

changelog/unreleased/8019, src/gui/accountsettings.cpp, src/gui/folderwizard.cpp, src/gui/wizard/owncloudadvancedsetuppage.cpp, src/gui/wizard/owncloudwizard.cpp
Depends on https://github.com/owncloud/client/pull/8018
Requires changelog entry
=> Make cfapi vfs the default

src/gui/connectionvalidator.cpp
Seen in https://github.com/owncloud/product/issues/181#issuecomment-680223599
Please check which one is correct.
=> allow displayname instead of display-name

changelog/unreleased/8064, src/gui/folderwizard.cpp, src/gui/wizard/owncloudadvancedsetuppage.cpp, src/libsync/theme.cpp, src/libsync/theme.h
We recommend `newBigFolderSizeLimit` together with `wizardHideFolderSizeLimitCheckbox`
as an alternative
=> Remove the theming option `wizardSelectiveSyncDefaultNothing`

.craft.ini, .github/workflows/main.yml
Now we have public test builds for all platforms https://github.com/owncloud/client/actions/runs/249605262
The pkg packages gets stuck on github so use the dmg packager for now...
=> Ci: enable packaging on mac

src/libsync/creds/oauth.cpp
The cookies are required by the load balancer and there for a reason.
Since #6574 we fixed the back button in https://github.com/owncloud/client/pull/8056 .
=> Don't clear cookies during oauth

changelog/unreleased/7724, src/gui/folderwizard.cpp, src/gui/folderwizard.h
=> Don't show 404 errors when manually creating folder sync pair.

src/gui/folderwatcher_mac.cpp
Hey,
working on the Mac code recently, I just stumbled upon a missing release call.
Greetings & thx for your work :)
=> macOS: Fix memory leak in FolderWatcherPrivate::startWatching

src/gui/accountsettings.cpp, src/gui/folderwizard.cpp, src/gui/wizard/owncloudadvancedsetuppage.cpp
This change kind of decouples the vfs modes a bit.
If enableExperimentalFeatures == false, we will hide the suffix implementation.
showVirtualFilesOption can still be used to completely disable vfs support.
We need to set showVirtualFilesOption to true per default in ownbrander.
WIP because its Friday evening and those conditions are complex....
=> Evaluate enableExperimentalFeatures when handling suffix vfs

src/libsync/theme.cpp
Fixes: https://github.com/owncloud/ownbrander/issues/715
There are also two other cases where the system style might be used:
```
git grep fromTheme
src/gui/sharelinkwidget.cpp:    auto deleteIcon = QIcon::fromTheme(QStringLiteral("user-trash"),
src/gui/shareusergroupwidget.cpp:    _ui->deleteShareButton->setIcon(QIcon::fromTheme(QStringLiteral("user-trash"),
=> Use platform icon theme only on the unbranded client

src/gui/folderstatusdelegate.cpp
Pass a widget to the progressbar in the folder delegate to draw the correct active state
=> Draw active progressbar

src/gui/accountmanager.cpp, src/gui/connectionvalidator.cpp, src/gui/owncloudsetupwizard.cpp, src/libsync/account.cpp, src/libsync/account.h, src/libsync/creds/oauth.cpp, src/libsync/theme.cpp, src/libsync/theme.h
The idp will now provide a selection dialog.
This fixes the issue where the login is done with the wrong account.
Also provide `login_hint` so that providers supporting it can skip that dialog.
=> Oauth use `prompt=select_account` instead of `consent`

src/gui/accountmanager.cpp, src/gui/connectionvalidator.cpp, src/gui/owncloudsetupwizard.cpp, src/libsync/account.cpp, src/libsync/account.h, src/libsync/creds/oauth.cpp
This reverts commit b9a0df55ad0677c354f84c6f9d0fa01a471f4713.
The issue of getting ocis internal identifier instead of the user name
was fixed in ocis.
=> Revert "Add idp username, used for oidc authentication"

changelog/unreleased/8263, src/gui/folder.cpp
=> Pause sync when remove all dialog is displayed

changelog/unreleased/8248, src/libsync/propagatedownload.cpp
The issue was caused by gziped responses not providing a
content lenght header.
Fixes: #8248
=> Owncloud - virtual files smaller <1KB - problems with syncing

changelog/unreleased/8317, src/gui/wizard/owncloudadvancedsetuppage.ui
I'm targeting master to not break the translations
=> Don't recoomend non default sync option

changelog/unreleased/8323, src/libsync/owncloudpropagator.cpp, src/libsync/propagatedownload.cpp
Bugfix: Detect file name clash with VirtualFiles enabled
We fixed an issue where the file name clash detection was not run with
VirtualFiles enabled.
https://github.com/owncloud/client/issues/8323
=> Fix filename clash detection with virtual files

changelog/unreleased/8299, src/csync/csync_exclude.cpp, test/testexcludedfiles.cpp
See https://github.com/owncloud/client/issues/8298  for reasons.
=> Ignore the desktop.ini file in every directory, not only in top dir.

src/csync/CMakeLists.txt
The define is not referenced anywhere in the code
=> CMake: Remove unsupported build option

changelog/unreleased/8467, src/libsync/logger.cpp, src/libsync/logger.h
I'll also modify the crash reporter once this is discussed.
=> Dump the last 20 lines of logs to a file when we crash

src/libsync/logger.cpp, src/libsync/logger.h
The only overhead added is the call to qFormatMessage... and we lock one time less if one is attached.
Depends on #8470
=> Always call doLog even if we don't have a file stream

CMakeLists.txt, changelog/unreleased/8482, src/cmd/CMakeLists.txt, src/csync/CMakeLists.txt, src/gui/CMakeLists.txt, src/libsync/CMakeLists.txt, src/libsync/vfs/suffix/CMakeLists.txt, test/csync/CMakeLists.txt, test/owncloud_add_test.cmake
This fixes brandings with spaces in the name
Do we need a changelog entry for that?
=> Instead of renaming the targets, we rename their output 

src/gui/socketapi/socketapi.cpp, src/gui/socketapi/socketapi_p.h
I guess it makes sense that the warning is not part of the result arguments but error on the other side is the only argument...
=> Allwo socket api2 to issue warnings

test/gui/shared/scripts/names.py, test/gui/shared/steps/steps.py, test/gui/tst_sharing/test.feature
This PR adds UI tests to select and unselect the password protection box while public sharing to see the status of the progress indicator.
- https://github.com/owncloud/client/issues/7459
- locally
=> [tests-only] Adds tests for selecting and unselecting password protection checkbox

src/gui/folderwizard.cpp, src/gui/selectivesyncdialog.cpp
Once the slash is gone, an assert is triggered, making the software terminate unexpectedly:
```
[...] [ fatal default ]: ASSERT: "relativePath.startsWith(QLatin1Char('/'))" in file .../client/src/libsync/abstractnetworkjob.cpp, line 196
```
This happens when trying to add a directory synchronization, in the second step where the remote directory is selected, once you click on the next button.
Related to #8459.
=> Remove unnecessary stripping of leading slashes

changelog/unreleased/8466, docs/modules/ROOT/pages/advanced_usage/command_line_options.adoc, src/gui/CMakeLists.txt, src/gui/application.cpp, src/gui/application.h, src/gui/generalsettings.cpp, src/gui/generalsettings.h, src/gui/generalsettings.ui, src/gui/translations.cpp, src/gui/translations.h, src/libsync/configfile.cpp, src/libsync/configfile.h
Closes #8466.
This PR adds two new methods to select the language within the GUI application: a config option in the general settings page, and a `--language` parameter.
The current implementation of listing all available locales relies on the translation file's filenames. It extracts the locale part and tries to resolve the native language name using `QLocale::nativeLanguageName`. This seems to work relatively well, except for one file called `TW`. I suspect we have to rename that file to `tw`.
=> Make language configurable

changelog/unreleased/8437, src/gui/folder.cpp, src/gui/protocolwidget.cpp, src/gui/socketapi/socketuploadjob.cpp, src/gui/socketapi/socketuploadjob.h, src/libsync/progressdispatcher.cpp, src/libsync/progressdispatcher.h, src/libsync/syncfileitem.h
=> Log when we begin and end a backup requested on a socket

test/gui/shared/steps/steps.py
multiple small issues fixed in the GUI tests:
- move path sanitization to own function
- don't rely on `openPublicLinkDialog` to sanitize path - that function should only do its own thing
- wait till the public share is created
- avoid that multiple matching step definitions
=> [tests-only] multiple small fixes in UI tests

changelog/unreleased/8130, src/CMakeLists.txt
Closes #8130.
Updates libcrashreporter-qt submodule to the latest commit to include https://github.com/dschmidt/libcrashreporter-qt/pull/25.
Also makes building `all` targets a little faster by excluding all targets from libcrashreporter-qt which are not explicitly linked by any other target. (They can still be buillt manually.)
=> Make crash report IDs easy to copy

changelog/unreleased/8367, src/gui/application.cpp
Some widgets, e.g., `QDateEdit`, use locale-dependent formatting to display its results. Setting the default locale correctly makes sure these widgets respect the user-selected language.
Fixes #8367.
=> Set up default locale correctly

changelog/unreleased/7549, src/gui/sharelinkwidget.cpp
Removing the name of a share link does not yield an error, but causes the server to automatically assign the link ID. The UI so far didn't show this, however. Rather than disallowing empty link names in the UI, we'll follow a "server makes it right" approach and trust it to either return an error or accept the request. In the latter case (which is what is experienced when emptying the name), to show up-to-date information client side, we have to re-fetch the share names from the server to show accurate information.
Fixes #7549.
=> Make sure share names are in sync with server

test/gui/shared/scripts/names.py, test/gui/shared/steps/steps.py, test/gui/tst_sharing/test.feature
This PR adds tests for sharing folder using public link:
- with password protection
- without password protection
https://github.com/owncloud/client/issues/8501
=> [tests-only]password protection public link share for folder

changelog/unreleased/8179, src/gui/accountsettings.cpp, src/gui/folderwizard.cpp, src/gui/generalsettings.cpp, src/gui/wizard/owncloudadvancedsetuppage.cpp, src/gui/wizard/owncloudadvancedsetuppage.ui, src/libsync/theme.cpp, src/libsync/theme.h
=> Add branding option to enforce VFS on Windows

changelog/unreleased/5644, src/gui/folderman.cpp, src/gui/folderman.h, src/gui/owncloudgui.cpp
=> Show last sync date in tray menu

test/gui/shared/steps/steps.py, test/gui/tst_syncing/test.feature
This PR refactors the following test which creates a conflict and tests the conflict while syncing.  https://github.com/owncloud/client/blob/196c641dbd3a12c441723c6b801cdce7490ca51e/test/gui/tst_syncing/test.feature#L27-L50
The file used to create sync is not in the skeleton directory so we have to create a new file of name `conflict.txt` on the server. Also the file `uploaded-lorem.txt` is not needed here so I have deleted steps related to it.
Finally I have substitute `mouseClick` with `openContextMenu` in step for pausing and resuming the sync because the `mouseClick` doesn't open the menu option for "Pause sync"
=> [tests-only]refactor tests for file sync conflict

test/gui/tst_addAccount/test.feature, test/gui/tst_sharing/test.feature, test/gui/tst_syncing/test.feature
This PR refactors all tests for client-UI to stop using skeleton files.
- Fixes https://github.com/owncloud/client/issues/8543
=> [tests-only]refactor tests to stop using skeleton files

test/gui/envvars, test/gui/shared/steps/steps.py
the current client of the master branch does not get its language settings from env variable but from a commandline switch
=> start the client with correct language setting

test/gui/shared/steps/steps.py
The client takes language arguments like `en_US` not `en_US.utf8` see https://github.com/owncloud/client/pull/8572#pullrequestreview-644470076 .
=> fix language setting in GUI tests

shell_integration/dolphin/ownclouddolphinactionplugin.cpp, shell_integration/nautilus/syncstate.py, src/gui/socketapi/socketapi.cpp
This PR introduces a separator between VFS and non-VFS entries in the context menu for Dolphin based file browsers.
For Nautilus based ones, this is unfortunately not possible, as the API doesn't provide any functionality to add such separators. Unfortunately, I only noticed this after cleaning up a bunch of things that would've allowed me to add such separators at all. I think these improvements are worth merging anyway, though.
The changes in the socket API should be backwards compatible. The old clients should just ignore the new entry type.
Partial fix for #7083.
The PR should also fix #8334 by increasing the socket timeout to 500ms, as suggested there.
Fixes #7614.
=> Improve VFS context menu of Linux shell integration

docs/antora.yml
@TheOneRing is this correct?
I hope, this cause https://doc.owncloud.com/desktop/2.8 to appear? Or do we need some ansible magic too?
=> bump antora to 2.8 here

test/gui/shared/scripts/helpers/SetupClientHelper.py, test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py, test/gui/shared/steps/steps.py
This PR is a POC for implementing Page Object Model in client test. Currently the PO is only implemented for tests related to adding accounts which is in `tst_addAccount.py`
For this implementation  the folder structure looks like this:
```
test
|
|------>gui	
|
|------>shared
|	|
|	|------>scripts
|	|	|
|	|	|----->helpers
|	|	|	|
|	|	|	|---->SetupClientHelper.py
|	|	|	
|	|	|------>pageObjects
|	|	|	|	
|	|	|	|----->AccountConnectionWizard.py
|	|	|	
|	|	|	
|	|	|------->bdd_hooks.py
|	|	|	
|	|	|------->names.py
|	|
|	|
|	|------>steps
|		|
|		|
|		|----->steps.py
|			
|
|------>tst_addAccount
|
|------>tst_sharing
|
|------>tst_syncing
```
- The `helper` folder contains `SetupClientHelper.py` which contains general helpers functions.
-  The `pageObjects` contains all the stepObject model. …
=> [tests-only]implement pageObject model

changelog/unreleased/8158, src/gui/activitylistmodel.cpp, src/gui/activitywidget.cpp, src/gui/activitywidget.h, src/gui/activitywidget.ui, src/gui/protocolitemmodel.cpp, src/gui/protocolwidget.cpp
=> Add context menu to activity list

test/gui/shared/steps/steps.py
This PR adds new method `openShareDialog` for opening sharing dialog box and make creation of public link creation DRY.
- fixes https://github.com/owncloud/client/issues/8624
=> [tests-only] DRY public link creation

changelog/unreleased/8272, src/common/vfs.cpp
We can't rely on the file system detection because Windows is reporting the underlying file system.
Fixes: #8272
=> Fix network drive detection

changelog/unreleased/8464, shell_integration/dolphin/CMakeLists.txt, shell_integration/dolphin/ownclouddolphinactionplugin.cpp, shell_integration/dolphin/ownclouddolphinpluginhelper.cpp, shell_integration/dolphin/ownclouddolphinpluginhelper.h, src/gui/socketapi/socketapi.cpp, src/gui/socketapi/socketapi.h
=> support V2/GET_CLIENT_ICON in socketapi, add icon to dolphin right click menu

changelog/unreleased/8158, src/gui/activitywidget.cpp, src/gui/models/models.cpp, src/gui/models/models.h
Depends on https://github.com/owncloud/client/pull/8627
Would be great if this could be reviewed by someone with an understanding of rtl formatted texts.
```
Activity                                                                                                                ,Account             ,Time                ,Local path                    ,
You created Photos/Lake-Constance.jpg, Photos/Portugal.jpg, Photos/Teotihuacan.jpg, Photos, Documents/Example.odt and Documents,admin@demo.owncloud.com,2021-05-11T09:04:38.000Z,C:/Users/hanna/ownCloud8/Photos/Lake-Constance.jpg,
You created ownCloud Manual.pdf and /                                                                                   ,admin@demo.owncloud.com,2021-05-11T09:04:38.000Z,C:/Users/hanna/ownCloud8/ownCloud Manual.pdf, …
```
=> RTL support in copy to clipboard

test/gui/shared/scripts/helpers/SetupClientHelper.py
The master branch have  `--language en_US` to setting language setting in GUI tests due which CI is failing. This PR temporarily fixes CI run for GUI tests. Until https://github.com/owncloud/client/issues/8680 is fixed
=> [test-only]fix CI for GUI test run

test/gui/shared/scripts/pageObjects/Toolbar.py, test/gui/shared/steps/steps.py, test/gui/suite.conf, test/gui/tst_loginLogout/test.feature, test/gui/tst_loginLogout/test.py
This PR adds tests for:
- logout user from client
- https://github.com/owncloud/client/issues/8651
=> [tests-only]logout user from client

test/gui/shared/scripts/names.py, test/gui/shared/scripts/pageObjects/AccountStatus.py, test/gui/shared/scripts/pageObjects/Toolbar.py, test/gui/shared/steps/steps.py, test/gui/suite.conf, test/gui/tst_removeAccountConnection/test.feature, test/gui/tst_removeAccountConnection/test.py
This PR adds tests for removing connection after a user has been added to the desktop-client
- https://github.com/owncloud/client/issues/8651
=> [tests-only] remove connection

src/csync/csync_exclude.cpp
Compilation on void linux (qt 5.15.3+20210429) fails due to implicit cast to QChar
```
[18/326] Building CXX object src/csync/CMakeFiles/csync.dir/csync_exclude.cpp.o
FAILED: src/csync/CMakeFiles/csync.dir/csync_exclude.cpp.o 
/usr/lib/ccache/bin/g++ -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_MESSAGELOGCONTEXT -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_URL_CAST_FROM_STRING -DQT_USE_QSTRINGBUILDER -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600 -Dcsync_EXPORTS -Isrc/csync -I../src/csync -Isrc/csync/csync_autogen/include -I. -I../src -Isrc -I../src/csync/std -I /usr/include/qt5 -I /usr/include/qt5/QtCore -I /usr/lib/qt5/mkspecs/linux-g++ -I /usr/include/qt5/QtConcurrent -fstack-clash-protection …
```
=> Fix use of deleted function

src/libsync/propagateuploadtus.cpp
Memory leak occurs when new UploadDevice hasn't been opened in ReadOnly mode.
=> Destroy UploadDevice instance in case it has not been opened in ReadOnly mode

src/common/checksums.cpp
https://doc.qt.io/qt-5/qtglobal.html#qEnvironmentVariableIsEmpty
It's potentially much faster, and can't throw exceptions.
=> Use qEnvironmentVariableIsEmpty instead of qgetenv().isEmpty()

shell_integration/windows/OCContextMenu/OCClientInterface.cpp, shell_integration/windows/OCContextMenu/dllmain.cpp
Microsoft doc:
Do not call GdiplusStartup or GdiplusShutdown in DllMain or in any function that is called by DllMain
=> Fix deadlock introduced in 8fcc9adcc41f2b46a74b9c0d806d2f4721081f8a

.drone.star
After https://github.com/owncloud/owncloud-test-middleware/pull/44 has been merged  `HOST` has been changed to `MIDDLEWARE_HOST` due to which CI has been failing while running GUI tests.
This PR fixes GUI tests failing on CI
=> [Tests-Only]fix gui tests fail in CI

src/gui/accountsettings.cpp, src/gui/folderman.cpp, src/gui/owncloudgui.cpp
With QMap and QHash, foreach accesses the value component of the (key, value) pairs automatically, so you should not call values() on the container (it would generate an unnecessary copy, see below).
https://doc.qt.io/qt-5/containers.html#foreach
=> Removed unnecessary temporary containers during iteration over QMap values

src/gui/accountmanager.cpp, src/gui/folderwizard.cpp, src/gui/ocsjob.cpp, src/libsync/bandwidthmanager.cpp
Note: Since Qt 5.7, the use of this macro is discouraged. It will be removed in a future version of Qt. Please use C++11 range-for, possibly with qAsConst(), as needed.
https://doc.qt.io/qt-5/qtglobal.html#Q_FOREACH
=> Removed obsolete Q_FOREACH macro

.drone.star, .github/workflows/run-in-docker.sh, .github/workflows/translate.yml, translations/Makefile
Cherry-picked version of #8709 on the `2.8` branch. The original PR operated on the dev branch, but translations shall be updated on the stable branch only.
Original PR reverted in #8712.
Note that we have to update the branch name in this workflow whenever a new minor or major release is published.
=>  Update translations on stable branch in GitHub actions

.drone.star, test/gui/tst_sharing/test.feature
Currently we run all GUI tests in same pipeline name `GUI-tests`. This is a POC PR for running smokeTest in CI.
Here, we have separated GUI tests run into two pipeline `GUI-tests-@smokeTest` where all tests with tag `@smokeTest`  will run and `GUI-tests-~@smokeTest` where other remaining tests will run. These pipelines does not run parallelly. First `GUI-tests-@smokeTest` will run and on passing  `GUI-tests-~@smokeTest` will run. 
All the normal tests depends on smokeTest. This way we also will be achieving early failure.
- https://github.com/owncloud/client/issues/8705
=> [Tests-Only]Run smokeTest on CI

test/gui/tst_sharing/test.feature, test/gui/tst_syncing/test.feature
After https://github.com/owncloud/client/pull/8719 has been merged this PR adds `@smokeTest` tag for already existing tests like for:
- Sync a file to the server
- Create a public link for file/folder
- https://github.com/owncloud/client/issues/8705
Also see: https://github.com/owncloud/client/issues/8651#issuecomment-857373491
=> [Tests-Only] add smokeTest tag

src/gui/application.cpp, src/gui/application.h, src/gui/main.cpp
Closes #8603.
The big chain of `if`s could be reduced by using a map and a loop, but it works well.
I could continue to use `showHint`/`displayHelpText` for user feedback, Qt is relatively flexible there. 
Note that #8604 should be rebased once this PR has been merged.
=> Replace custom argument parsing with QCommandLineParser

changelog/unreleased/4597, src/gui/application.cpp, src/gui/folderman.cpp, src/gui/proxyauthhandler.cpp, src/gui/updater/ocupdater.cpp, src/libsync/configfile.cpp, src/libsync/configfile.h
Don't initialize a settings object just to check whether the file exists.
Fixes: https://github.com/owncloud/enterprise/issues/4597
This is intended to fix one issue, further work is planned in https://github.com/owncloud/client/issues/6213
=> Fix migration of settings

.drone.star, test/gui/tst_sharing/test.feature
When a user creates a public link with expiration date and opens the sharing dialog in desktop-client for that file then the Set expiration date checkbox is unchecked and the expiration date field have public link creation date(6/16/21). Due to this some tests are failing in CI. So this PR skips these tests for now. 
- https://github.com/owncloud/client/issues/8733
=> [Tests-Only] Skip public link test

src/gui/folderman.cpp, src/libsync/syncengine.cpp, test/testsyncengine.cpp
https://doc.qt.io/qt-5/qfileinfo.html#exists
Note: Using this function is faster than using QFileInfo(file).exists() for file system access.
=> Replaced QFileInfo(file).exists() with a static QFileInfo::exists(file)

.drone.star
Currently we do not run GUI tests on nightly. So, this PR will run all the GUI tests against the `daily-master-qa` server and  run PRs against a stable server tarball `10.7.0`.
After this PR gets merged we need to change the server version from `10.7.0` to latest stable release when new stable version of core is released.
=> [Tests-Only] Run GUI tests on nightly

test/gui/shared/scripts/names.py, test/gui/shared/steps/steps.py, test/gui/suite.conf, test/gui/tst_checkAlltabs/test.feature, test/gui/tst_checkAlltabs/test.py, test/gui/tst_checkAlltabs/verificationPoints/Activity, test/gui/tst_checkAlltabs/verificationPoints/AddAccount, test/gui/tst_checkAlltabs/verificationPoints/QuitOwncloud, test/gui/tst_checkAlltabs/verificationPoints/Settings
This PR adds test to check if all the tabs in toolbar section is visible by property verification point creation and suing squish api `test.vp` 
- https://github.com/owncloud/client/issues/8705
Also see: https://github.com/owncloud/client/issues/8651#issuecomment-857373491
=> [Tests-Only] Visually check all tabs

changelog/unreleased/8761, src/common/filesystembase.cpp, src/common/filesystembase.h, src/gui/folderman.cpp, src/gui/folderman.h, src/gui/lockwatcher.cpp, src/gui/lockwatcher.h, src/libsync/owncloudpropagator.cpp, src/libsync/owncloudpropagator.h, src/libsync/propagatedownload.cpp, src/libsync/propagateuploadng.cpp, src/libsync/propagateuploadtus.cpp, src/libsync/propagateuploadv1.cpp, src/libsync/syncengine.h, src/libsync/syncoptions.h, test/testlockedfiles.cpp
=> Require exclusive locks for vfs and renames

src/cmd/cmd.cpp, src/common/vfs.cpp, src/csync/csync_exclude.cpp, src/gui/folder.cpp, src/gui/generalsettings.cpp, src/gui/generalsettings.h, src/gui/models/activitylistmodel.cpp, src/gui/models/protocolitemmodel.cpp, src/gui/wizard/owncloudsetuppage.cpp, src/gui/wizard/owncloudsetuppage.h, src/gui/wizard/owncloudwizard.cpp, src/libsync/creds/httpcredentials.cpp, src/libsync/creds/httpcredentials_p.h, src/libsync/logger.cpp, src/libsync/owncloudpropagator.h, test/syncenginetestutils.h, test/testcredentialmanager.cpp, test/testjobqueue.cpp
Fixed the warning messages appeared during build except following:
1) Q_DECL_DEPRECATED_X("Use uuid") QString id() const;
Not sure whether I can simply replace id() to uuid().
2) Qt deprecation warnings
If there is a plan to move to Qt6 it would be very useful to fix all warnings in Qt 5.15 to make a migration smoother - can provide a separate PR for that.
=> Fix build warnings

changelog/unreleased/8787, src/common/syncjournaldb.cpp, src/common/syncjournaldb.h, src/common/utility.cpp, src/common/vfs.h, src/libsync/owncloudpropagator.cpp, src/libsync/owncloudpropagator.h, src/libsync/propagatedownload.cpp, src/libsync/propagateremotemkdir.cpp, src/libsync/propagateremotemove.cpp, src/libsync/propagateupload.cpp, src/libsync/propagatorjobs.cpp, src/libsync/vfs/suffix/vfs_suffix.cpp, src/libsync/vfs/suffix/vfs_suffix.h
~Depends on https://github.com/owncloud/client/pull/8786~
=> Improve the handling of errors in convertToPlacholder and updateMetaData

src/libsync/propagatedownload.cpp, src/libsync/propagateupload.cpp
There were mixed const and non-const iterators.
It is generally good practice to use const_iterator on a non-const container as well, unless you need to change the one through the iterator. Const iterators are slightly faster, and can improve code readability.
=> Use const iterators

test/gui/shared/scripts/names.py, test/gui/shared/scripts/pageObjects/SharingDialog.py, test/gui/shared/steps/steps.py, test/gui/tst_sharing/test.feature
This PR adds test for changing collaborator permissions got files/folder.
https://github.com/owncloud/client/issues/8651
=> [tests-only] change collaborator permissions

test/gui/shared/steps/steps.py, test/gui/tst_sharing/test.feature
There are many `Given` steps  which contains `on the server`  in them, that we call using owncloud-middleware. It seems to be random where we put `on the server` in these steps. 
This PR refactor all the `Given` steps that has `on the server` in them and change them to add `on the server` at the end of the step or wherever it seems more suitable.
- Fixes #8795
=> [tests-only]refactoring steps with on the server in them

test/gui/shared/scripts/pageObjects/SharingDialog.py, test/gui/shared/steps/steps.py, test/gui/tst_sharing/test.feature
The following test scenarios have been added:
- Collaborator should not see to whom a file is shared.
- Group sharing
- User (non-author) can not share to a group to which the file is already shared
- part of https://github.com/owncloud/client/issues/8651
=> [tests-only] Group share tests added

test/gui/shared/steps/steps.py, test/gui/tst_sharing/test.feature
This PR adds gui test for overwrite content of a file shared by sharer
https://github.com/owncloud/client/issues/8651
=> [tests-only] overwrite content of shared file

CMakeLists.txt, cmake/modules/OCBundleResources.cmake, src/gui/CMakeLists.txt, src/gui/application.cpp, src/gui/translations.cpp, src/gui/translations.h
Contributes to #8822.
This PR replaces the existing translations deployment in "guessable" directories. They are now bundled in the binary using the [Qt resources system](https://doc.qt.io/qt-5/resources.html). This is going to be a lot more reliable and also faster than the old system. The only disadvantage is that the binaries will become a little larger.
=> Bundle translations using Qt resources system

changelog/unreleased/8672, src/libsync/owncloudpropagator.cpp, src/libsync/syncfileitem.h, test/testpermissions.cpp
This fixes the issue that a CaseClash caused a resync every 30s.
=> Use ignore list for all NormalErrors

test/gui/shared/steps/steps.py
5s seems to be the default snooze time and it seems to fix the test (that now fails since 3 weeks)
=> Wait longer before we assume the client to be ready

changelog/unreleased/7715, src/gui/folderman.cpp, src/gui/folderman.h, src/gui/folderstatusmodel.cpp, src/gui/libcloudproviders/libcloudproviders.cpp, src/gui/owncloudgui.cpp, src/libsync/syncresult.cpp, src/libsync/syncresult.h, src/libsync/theme.cpp, src/libsync/theme.h
With this change we will display the problem state if we have blacklisted errors.
This change also aligns the icon in the tray icon with the icon displayed for the folder state.
=> Align sync status and icon

changelog/unreleased/8824, src/common/utility.cpp, src/gui/application.cpp, src/gui/settingsdialog.cpp, src/gui/socketapi/socketuploadjob.cpp, src/libsync/configfile.cpp, src/libsync/creds/abstractcredentials.cpp, src/libsync/creds/abstractcredentials.h, src/libsync/creds/httpcredentials_p.h
=> Fix config data migration from 2.8 to 2.9

test/gui/shared/scripts/names.py, test/gui/shared/steps/steps.py, test/gui/suite.conf, test/gui/tst_vfs/test.feature, test/gui/tst_vfs/test.py
This PR adds gui tests for enabling and diabling VFS
Find a way to verify if VFS has been enabled/disabled
- https://github.com/owncloud/client/issues/8651
=> [Tests Only] add test for enable/disable vfs

src/gui/wizard/owncloudadvancedsetuppage.cpp, src/gui/wizard/owncloudadvancedsetuppage.h, src/gui/wizard/owncloudadvancedsetuppage.ui, src/gui/wizard/owncloudhttpcredspage.cpp, src/gui/wizard/owncloudhttpcredspage.h, src/gui/wizard/owncloudhttpcredspage.ui
The commit also removes some unused labels and uses a stack widget instead of hiding/showing widgets during runtime which messed up the layout.
Old:
=> Wizard: Display sync root issues as dialog

CMakeLists.txt
I saw these hooks in other projects, and I think they are pretty useful. Right now only CMake's "Unix" platforms (i.e., Linux, BSD, ...) seem to be supported.
I did not want to bump the ECM version requirement, thus the hook is only enabled if ECM happens to be recent enough. Otherwise, a warning is printed.
=> Set up Git pre-commit hook for clang-format

src/gui/folderstatusdelegate.cpp, src/gui/folderstatusmodel.cpp
We are a sync client mentioning that we sync is pointless.
Also remove `Synchronizing VirtualFiles` with placeholders we still display a banner.
On Windows VirtualFiles are the standard.
New:
Old:
Fixes: #8871
=> Folder delegate: Don't display `Synchronizing with`

changelog/unreleased/8780, src/gui/accountstate.cpp, src/gui/folder.cpp, src/gui/folder.h, src/gui/folderman.cpp, src/libsync/capabilities.cpp, src/libsync/capabilities.h, src/libsync/configfile.cpp, src/libsync/configfile.h
With this, admins can configure the remote poll interval via the capabilities of the server.
```
% curl -u admin:admin 'https://demo.owncloud.com/ocs/v1.php/cloud/capabilities?format=json' \
| jq | grep -i -e  poll
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1954  100  1954    0     0   4897      0 --:--:-- --:--:-- --:--:--  4897
"pollinterval": 60,
```
If the client has no custom interval in the [client config file](https://doc.owncloud.com/desktop/advanced_usage/configuration_file.html) and if the capability is different than the default, the remote poll interval is changed. 
Note: To use 60 seconds, the capability needs to contain the string "60!" for the reason that 60 was the default in the capas, …
=> Poll interval from capabilities

src/gui/folder.cpp
08-17 11:30:56:139 [ info gui.folder ]:	dueToSync: "1" 9626  <  30000
08-17 11:30:56:139 [ info gui.folder ]:	dueToSync: "2" 9483  <  30000
08-17 11:30:57:140 [ info gui.folder ]:	dueToSync: "1" 10626  <  30000
08-17 11:30:57:140 [ info gui.folder ]:	dueToSync: "2" 10484  <  30000
08-17 11:30:58:140 [ info gui.folder ]:	dueToSync: "1" 11627  <  30000
08-17 11:30:58:141 [ info gui.folder ]:	dueToSync: "2" 11484  <  30000
08-17 11:30:59:139 [ info gui.folder ]:	dueToSync: "1" 12626  <  30000
08-17 11:30:59:140 [ info gui.folder ]:	dueToSync: "2" 12484  <  30000
=> Remove leftover debug line

src/libsync/discovery.cpp
If the file $RECYCLE.BIN is on the local file system there is no reason
we should not mark the sync as success.
If for some reason there is a file with such a name on the server we do need to warn,
as we can't download that file. Thus the sync is incomplete.
=> Don't tread local system reserved file names as an issue

src/gui/folder.h, src/gui/folderman.cpp, src/gui/folderman.h, src/gui/owncloudgui.cpp, src/libsync/syncresult.h
This also fixes an issue where the pause state took higher precedence over success.
Fixes: #8904
=> Fix sync status

src/libsync/syncresult.h
Fixes: #8933
https://github.com/owncloud/client/blob/2.8/src/gui/folderman.cpp#L1312
=> Running sync takes precedence over Success in overall state

changelog/unreleased/8938, src/gui/sharedialog.cpp, src/gui/sharedialog.h, src/gui/thumbnailjob.cpp, src/gui/thumbnailjob.h
The api currently does respond with non png icons, determine the image type based on the content.
Don't override the system icon if we got a null icon.
Fixes: #8938
=> Sharedialog preview be more resilient

.drone.star, test/gui/TestLogParser.py
Improve the log of GUI tests to print the name, location, and the details of the failing tests at the end of the execution.
Fixes https://github.com/owncloud/client/issues/8799
The errors in tests are displayed as follows:
For more information, https://drone.owncloud.com/owncloud/client/8733/5/13 
The parsed test result can be found in the `show-gui-test-result` under the `GUI-tests-...` pipelines
The data related to failing tests are displayed as a list of dictionary with following keys.
```json
{
"Error Details": "Actual error message, cause of the error",
"Feature": "NAME OF FEATURE IN WHICH THE FAILING TEST IS",
"Feature File": "NAME OF THE FILE IN WHICH THE FAILING TEST IS",
"Scenario": "FAILING TEST SCENARIO",
"Test Step": "STEP AT WHICH THE ERROR PERSIST"
}
```
=> [Tests-Only]Improve CI log

changelog/unreleased/8806, src/gui/application.cpp
Can you see side effects of the patch?
The issue does not occur with Qt 5.15 so maybe I should ifdef it
Fixes: #8806
=> Explicitly set the layout direction if changing the locale

.drone.star
Currently pushing into a branch triggers a build that only runs gui test linting which is not really necessary as same pipeline runs after creating the PR.
=> [CI] fix push trigger for CI

changelog/unreleased/9006, src/gui/models/protocolitemmodel.cpp, src/gui/protocolitem.cpp, src/gui/protocolitem.h
Copying to clipboard will still display utc time (raw data)
Fixes: #9006
=> Display the local time not utc time

src/common/filesystembase.cpp, src/common/utility.cpp, src/csync/csync_exclude.cpp, src/libsync/propagateremotemkdir.cpp, test/testoauth.cpp
- comparison of integers of different signs
- usused parameter
- loop variable creates a copy
- unused variable (due to #ifdef)
=> Fix some compiler warnings

src/common/utility.h, src/gui/models/protocolitemmodel.cpp, src/libsync/syncfileitem.cpp, src/libsync/syncfileitem.h
The previous use of template specialisation triggered a compiler bug on
Debian 9 and CentOS 7, which use gcc 5.4 or earlier. As there is just
one specialisation, the work-around is to change the function to be a
static member function of the wrapping class of the enum.
See also: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56480
=> Work around compiler bug in old GCC versions

src/libsync/creds/credentialmanager.cpp, src/libsync/creds/credentialmanager.h
The underlying object is managed by a std::unique_ptr. So accidentally
setting a parent, or managing it somewhere else, will result in a
double-free. Returning a reference is slightly more safe, and has the
added benefit that it communicates the fact that it will never be a
nullptr.
=> Turn raw QSettings pointer into a reference in the CredentialManager

src/common/vfs.cpp, src/gui/accountmanager.cpp, src/libsync/configfile.cpp, src/libsync/configfile.h, src/libsync/propagateuploadng.cpp, src/libsync/propagateuploadv1.cpp, test/testoauth.cpp
Use make_unique to create an object that isn’t shared (at least not yet), unless you need a custom deleter or are adopting a raw pointer from elsewhere.
=> Used make_unique instead of direct unique_ptr construction

changelog/unreleased/9048, src/gui/shareusergroupwidget.cpp, src/gui/shareusergroupwidget.ui
Due to the prominent string change this goes to 2.10
Fixes: #9048
=> Fix copy private link url

src/common/fixedsizeringbuffer.h, src/gui/issueswidget.cpp, src/gui/models/protocolitemmodel.cpp, src/gui/models/protocolitemmodel.h, src/gui/protocolwidget.cpp, src/libsync/syncengine.cpp, test/modeltests/testprotocolmodel.cpp
People might have a suboptimal setup with lots of ignored files.
The historic maximum we displayed was 2000 issues, we now allow 20000, while we keep the old value for the protocol view.
The underlying data structure was selected with the protocol widget in mind, so many continual inserts.
The issue widget however resets the model on every single sync, deletes all issues associated with an account, to then fill in the new issues. We should try to create a more clever approach....
=> Allow up to 20000 sync issues

src/gui/updater/ocupdater.cpp
Contributes to #8923. Not the nicest solution, but I didn't want to add another entry to the enum.
=> Improve "update available" message in AppImages

src/gui/folder.cpp
Only set ready status after all signal/slot connections are hooked up.
=> Fix sync-start regression

changelog/unreleased/9093, src/common/filesystembase.cpp, src/libsync/propagatedownload.cpp, src/libsync/syncengine.cpp
This enables us to dehydrate read only files.
Side note the read only flag won't be re applied after the dehydration...
Please also review https://gitea.owncloud.services/client/client-plugin-vfs-win/pulls/33
Issue: https://github.com/owncloud/client/issues/9093
=>  Fix dehydration of read only files

src/gui/activitywidget.cpp, src/gui/activitywidget.ui, src/gui/issueswidget.cpp, src/gui/issueswidget.h, src/gui/issueswidget.ui, src/gui/models/expandingheaderview.cpp, src/gui/models/expandingheaderview.h, src/gui/models/models.cpp, src/gui/models/models.h, src/gui/models/protocolitemmodel.cpp, src/gui/protocolwidget.cpp, src/gui/protocolwidget.h, src/gui/protocolwidget.ui, src/libsync/localdiscoverytracker.cpp, src/libsync/owncloudpropagator.cpp, src/libsync/syncfileitem.cpp, src/libsync/syncfileitem.h
Fixes: https://github.com/owncloud/client/issues/9000
=> Allow to filter issue table by issue type

test/gui/shared/scripts/helpers/SetupClientHelper.py
I also tried to set `os.environ["QT_LOGGING_RULES"] = "sync.httplogger=true"`
But that seemed to have no effect on the test.
See https://doc.owncloud.com/desktop/2.9/appendices/troubleshooting.html for context.
=> Ci: Better logging in squish test

changelog/unreleased/9099, src/gui/accountsettings.cpp
Allows to remove broken folders without removal of the whole account.
Should go to rc2
=> Allow to remove broken sync folder connections

.drone.env
This PR bumps middleware commit id for tests (but not to the latest commit id)
=> [tests-only] Bump middleware commit id for tests

changelog/unreleased/9114, src/gui/folder.cpp, src/gui/folder.h, src/gui/folderman.cpp
=> Prevent downgrade of vfs folder

.drone.star
Camke will fail if the dependency is missing
=> Always build with cloudproviders

changelog/unreleased/9202, src/gui/accountstate.cpp
When the client detects a change of the url we ask the user to accept
the change or if it was only representational change we directly accept the change.
Due to a bug the we aborted the sync only after we updated the url.
This caused the client to idle for one minute.
=> Ensure we only update the clients url after the sync was stopped

changelog/unreleased/7348, src/libsync/propagateuploadng.cpp
Always set the request time, response value and request Id in the SyncFileItem.
These values are written to the .owncloudsync.log file which is useful for debugging. For some operations, some data is missing. This PR fixes that. 
Fixes: #7348
=> Fix values in sync item

shell_integration/MacOSX/CMakeLists.txt
Propagate the cmake build type to xcode-build too. Previously, a release
build would always be done. Now, a debug build will be done when the
cmake build type is Debug.
=> macOS: allow for debug builds in xcode-build

changelog/unreleased/9216, src/gui/folderman.cpp, src/gui/folderman.h, src/libsync/theme.cpp, src/libsync/theme.h
Also cache error message to prevent unnecessary listing of sync root.
=> Branding option to disable the multiple db files warning

test/gui/shared/scripts/pageObjects/SharingDialog.py, test/gui/shared/steps/steps.py, test/gui/tst_sharing/test.feature
Gui test scenario: `change collaborator permissions of a file & folder` was failing intermittently because the expected share field `file_target` was different for some unknown reason.
Expected `file_target: '/Shares/simple-folder'` but sometime it was `file_target: '/simple-folder'`
I have added some fixes for that and I am not getting any previous errors now.
For other failing tests, I didn't find anything. I suspect these fails are caused by the above test fail.
Fixes #9206
=> [gui-tests-only] Fix intermittent test fails

src/gui/accountmanager.cpp
Makes it easier to distinguish between the regular migration code and the legacy code's logging.
=> Add prefix to legacy migration log messages

.drone.star
Future releases are going to be built against Qt 5.15. For 2.9, we prepared a new tag that still ships Qt 5.12.
Depends on https://github.com/owncloud-ci/client/pull/13
=> Change Docker image used in CI

.drone.env, test/gui/shared/scripts/names.py, test/gui/shared/scripts/pageObjects/PublicLinkDialog.py, test/gui/shared/steps/steps.py, test/gui/tst_sharing/test.feature
add tests for public link 
- Public link to a file and set a password with special characters
- Public link to a file and disable it after | use the sharing menu to delete the public link
- Public link to a file and set a password. Modify Password Policies and retry
https://github.com/owncloud/client/issues/8971#issuecomment-909885070
=> [tests-only] add tests for public share

src/libsync/logger.cpp
Now the question remains, will this post routine be called first or https://github.com/owncloud/client/blob/master/src/gui/guiutility.cpp#L114
The log file could also be parented with qApp.
=> Ensure we prooperly close the log file

changelog/unreleased/9241, src/cmd/cmd.cpp
owncloudcmd now checks if the file specified by --unsyncedfolders exists
and can be read, before starting the sync. If it does not exist, show an
error message and quit immediately.
https://github.com/owncloud/client/issues/9165
=> Bugfix: Do not sync when unsyncedfolders file cannot be read

README.md
the link seems to have got out of date
=> fix link to the building instructions

test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
the test code waits for the password box, which is not comming most of the time, because the password is stored in the keyring after the first test.
We can save a lot of test time by reducing that waiting
=> reduce time waiting for password box

.drone.star
there are now different versions of squish availiable with different qt versions. for the client v2.10 we need QT 5.12
=> use qt5.12 squish for UI tests

.github/patch_release_template.md
After first build of a new release the extended linux keys have to be uploaded to the key server (esp. for rpm-based linux distributions)
=> add "Upload linux keys to key server"

test/gui/tst_syncing/test.feature
This PR adds tests for Creating a new folder with space at the end and sync it.
https://github.com/owncloud/client/issues/8971#issuecomment-909884918
=> [Tests-Only] add test for folder sync

changelog/unreleased/9196, src/gui/creds/httpcredentialsgui.cpp, src/gui/wizard/owncloudoauthcredspage.cpp, src/gui/wizard/owncloudoauthcredspage.h, src/libsync/creds/oauth.cpp, test/testoauth.cpp, test/testutils/testutilsloader.cpp
=> Restart oauth on error

test/gui/tst_syncing/test.feature
Added automated tests for folder creation and syncing
- Part of https://github.com/owncloud/client/issues/8971#issuecomment-909884257
=> [tests-only]Added tests for folder creation and syncing (part 2)

test/gui/tst_sharing/test.feature
This PR adds following tests:
- Share a file with user B with Can Edit permissions enabled. Login as User B and delete it
https://github.com/owncloud/client/issues/8971#issuecomment-909885166
=> [tests-only]Add sharing test

changelog/unreleased/9071, src/libsync/filesystem.cpp, src/libsync/owncloudpropagator.cpp, src/libsync/syncengine.cpp, src/libsync/syncfileitem.cpp, src/libsync/syncfileitem.h, test/testsyncconflict.cpp, test/testsyncfilestatustracker.cpp, test/testsyncvirtualfiles.cpp
Completed was emitted before the database entry was created in PropagateDirectory::slotSubJobsFinished.
=> Fix wrong status displayed for files moved on the server

changelog/unreleased/9194, src/libsync/propagateupload.cpp, src/libsync/propagateuploadv1.cpp
I tried to fix this before, but in the wrong uploader.
Looking at the code I assume that legacy chunking with parallel chunking was completely  broken in 2.9
=> Only check whether a file is locked before we start the upload

changelog/unreleased/9291, src/gui/accountsettings.cpp
@swoichha @Talank the pr removes the "Availability" entry from the context menu which causes the tests to fail.
=> Remove Availability menu from the ui

test/gui/tst_vfs/test.feature
Fixing the failing VFS tests is in progress in the PR https://github.com/owncloud/client/pull/9307. And until the tests are fixed, I am skipping these consistently failing tests so that the `2.10` CI goes green.
=> [Tests-only]skipped VFS tests

test/gui/shared/scripts/pageObjects/PublicLinkDialog.py, test/gui/shared/scripts/pageObjects/SharingDialog.py, test/gui/shared/steps/steps.py, test/gui/tst_sharing/test.feature
Added more automated tests for different sharing scenarios
- Part of https://github.com/owncloud/client/issues/8971#issuecomment-909884257
=> [tests-only] Added more gui tests for sharing with user and group (Part 01)

src/gui/accountsettings.cpp
This partly reverts commit 934da5b219e4774fe0f4ec422ed067437ac44e3c which removed the vfs mode selection by accident.
Fixes: #9314
=> Partly Revert "Remove Availability menu from the ui"

test/gui/tst_sharing/test.feature
Skipped the expiration date changing related tests. An issue has been opened to fix it https://github.com/owncloud/client/issues/9321.
=> [Tests-Only]Skipped failing expiration tests

test/gui/shared/steps/steps.py, test/gui/tst_vfs/test.feature
The steps that were removed in https://github.com/owncloud/client/pull/9307 has been reestablished. It is because, the removal of `Enable/Disable VFS` button was unintentional.
- fixes https://github.com/owncloud/client/issues/9303
=> [Tests-Only] Reverted removed steps of VFS tests

src/libsync/creds/oauth.cpp
Introduced in ba37025f4b5ac4a2a6cde6aac7d4a5896cfbac1.
Closes #9324.
=> Fix OpenID Connect authentication regression

.gitmodules
submodules step failed with 
```
fatal: clone of 'git://github.com/dschmidt/libcrashreporter-qt.git' into submodule path '/drone/src/src/3rdparty/libcrashreporter-qt' failed
Failed to clone 'src/3rdparty/libcrashreporter-qt'. Retry scheduled
```
GitHub changed stuff for security reasons and without username we have to use HTTPS see https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> use https to clone submodules

test/gui/shared/steps/steps.py
After deleting the public link, wait till the delete button disappears to make sure the action is finished
fixes #9346
=> Fix public link delete test

changelog/unreleased/9341, src/gui/accountsettings.cpp
=> Ensure to performe a local discovery on force or after a paused sync

.drone.star
Added job to send drone notification to `desktop-internal` channel in rocketchat for all the cron jobs such as nightly builds.
Part of https://github.com/owncloud/client/issues/9327
=> [Tests-Only]Execute drone notification in cron pipelines

.drone.star
Removing the call to nofication from the normal pipeline so that it will notify only when the `cron_pipelines` is running.
Related to https://github.com/owncloud/client/issues/9327
=> [Tests-Only]Notify to rocketchat for only the nightly builds

test/gui/shared/steps/steps.py, test/gui/tst_syncing/test.feature
If a file fails, we mark it as ignored for 5s. If it fails again within the 25s, 525, if again 55*25...
If you want to test the "changed during upload" scenario, you should wait for the error to be resolved, or force sync.
If you don't want to test it, don't modify the src file to often and not after the sync was started.
Besides the mentioned ignore list there are other random timeouts in the client which are hard to predict.
REF: https://github.com/owncloud/client/issues/9325#issuecomment-1016179775
Hence, it looks like waiting for 5 sec in the beginning is a good solution.
Fixes https://github.com/owncloud/client/issues/9325
=> [Tests-Only]Fixed file creation and syncing tests

changelog/unreleased/9382, src/gui/issueswidget.cpp, src/libsync/localdiscoverytracker.cpp, src/libsync/owncloudpropagator.cpp, src/libsync/propagateupload.cpp, src/libsync/syncfileitem.cpp, src/libsync/syncfileitem.h
Fixes: #9382
The filter menu will now be sorted by the localised string.
=> Introduce new error category that is not handled by the ignore list

.github/workflows/stale.yml
If we label an issue with QA:team then we don't want the stale bot to keep marking it stale.
Example: #9247 was marked stale yesterday.
This PR is to the 2.10 branch, because CI is red in `master`.
The change is really needed in `master` to change the stale bot behavior, what to do?
=> Do not mark QA:team issues stale

.clang-format
The option was in there twice, causing confusion for some tools that can parse `.clang-format` files.
Also, the value was invalid, see https://clang.llvm.org/docs/ClangFormatStyleOptions.html. It must be one of `Never`, `CaseSensitive` or `CaseInsensitive`. I think `CaseSensitive` is a sensible choice.
=> Fix duplicate option in clang-format config

changelog/9417, src/gui/guiutility.cpp, src/gui/guiutility.h, src/gui/main.cpp
We also ensure that qApp is completely set up when we create the icon.
Fixes: #9417
=> Move the creation of the icon to the main thread to prevent crash

src/gui/application.cpp, src/libsync/abstractnetworkjob.cpp, src/libsync/abstractnetworkjob.h, src/libsync/account.cpp, src/libsync/networkjobs.cpp, src/libsync/networkjobs.h, src/libsync/propagatedownload.cpp, src/libsync/propagatedownload.h, test/testutils/syncenginetestutils.cpp
One of the effects is that the time now runs on the reply, and gets reset as long as the reply is active and not on the parent job.
=> Use buildin timeout handling provided by Qt

src/gui/generalsettings.ui
Because, well, the client isn't started on startup, but only when
logging in.
=> Change "Start on System Startup" to "Start on Login"

changelog/unreleased/9387, src/common/utility_mac.cpp
When checking if the client is auto-started, the list of all login-items
is retrieved, and each item is compared to the path of the .app bundle.
This comparison needs to be done ignoring the case, as most macOS file
systems are case-insensitive.
https://github.com/owncloud/client/issues/9387
=> macOS: Fix path comparison in launch-on-startup code

.drone.star
Set up QT logging rules using environment variable to disable socketapi log and enable http log.
- closes https://github.com/owncloud/client/issues/9109
=> [Tests-Only]Enabled http log on GUI tests

test/gui/shared/steps/steps.py, test/gui/tst_syncing/test.feature
part of https://github.com/owncloud/client/issues/9396
The following test from the testplan has been automated in this PR
```
Test scenario: User adds the various types of files 
Steps to reproduce:
1. Microsoft word documents, Microsoft Excel, Microsoft Powerpoint, .JPG, .PDF, .MP3
Result: The Sync files tab show all type of files added in the Desktop Client folder from desktop, All files snyced and shown in Activities Tab under synchronization protocol
```
I have automated test for syncing files from client to server and vice-versa
=> [tests-only] Added files tests from testplan

test/gui/tst_syncing/test.feature
#9334 
Refactored the invalid folder name and tested for sync
=> [tests-only]refactored invalid system name tests

.drone.star
bump middleware version to v1.4.0
https://github.com/owncloud/owncloud-test-middleware/issues/104
=> [tests-only] Bumped test middleware version to v1.4.0

src/common/utility_mac.mm
Case-sensitive compares will give problems when a launchd plist file
exists, but the executable gets upated, and the name only has a
different case (e.g.: owncloud -> ownCloud).
=> macOS: Do case-insensitive compare in auto-launch code

changelog/unreleased/9238, src/libsync/progressdispatcher.cpp
Fixed: https://github.com/owncloud/client/issues/9238
=> Bugfix: mention source file in activity tab when renaming

src/libsync/CMakeLists.txt, src/libsync/abstractcorejob.h, src/libsync/creds/jobs/determineuserjobfactory.cpp, src/libsync/creds/oauth.cpp, src/libsync/determineauthtypejobfactory.cpp
Forgot to add proper handling in my previous PR, #9426. This reliably fixes the `OAuthTest` (tested with a sample size of 1000 against the previous implementation, where about 9% of the test runs failed).
=> Fix timeouts in OAuth

src/gui/folderman.cpp, src/libsync/configfile.cpp
PR #8777 made the client responsive to the "pollinterval" setting reporting  by the server in the capabilities.
The value of pollintervalis now interpreted as milliseconds.
This PR clarifies some comments. Hopefully I have made it clearer for future readers.
=> Improve poll-interval comments

changelog/unreleased/9472, src/libsync/networkjobs.cpp
Close the body device when we finished.
This fixes:
```
02-25 14:27:42:887 [ debug sync.propagator.upload.tus ]	[ OCC::PropagateUploadFileTUS::finalize ]:	"" "a1c61d6e3a2dbc99d8c78fc9d20f0edf" "f7fbf8c8-139b-4376-b307-cf0a8c2d0d9c!c246992e-fc43-4ea1-8353-cf1740d90d3a"
02-25 14:27:42:887 [ warning sync.vfs.win ]:	"CfOpenWithOplock error C:/Users/hanna/ownCloud44/Marie Curie/CableTie1.1 - Copy.stl WindowsError: ffffffff80070020: The process cannot access the file because it is being used by another process."
```
=> Enusre we close the file in time

changelog/unreleased/9155, src/gui/application.cpp
=> Set up VFS integration before parsing options

changelog/unreleased/9367, src/gui/accountmanager.cpp, src/gui/accountmanager.h, src/gui/activitywidget.cpp, src/gui/activitywidget.h, src/gui/application.cpp, src/gui/application.h, src/gui/folderman.cpp, src/gui/folderman.h, src/gui/models/activitylistmodel.cpp, src/gui/models/activitylistmodel.h, src/gui/settingsdialog.cpp, src/gui/settingsdialog.h, test/modeltests/testactivitymodel.cpp
The fix involves some guesses.
imho: we should not use shared pointers at all and rather call deleteLater but the code is what it is.
Fixes: #9367
=> Fix shared pointer deletion before the slot was invoked

.craft.shelf, src/gui/connectionvalidator.cpp, src/gui/owncloudsetupwizard.cpp, src/gui/quotainfo.cpp, src/libsync/CMakeLists.txt, src/libsync/graphapi/CMakeLists.txt, src/libsync/graphapi/drives.cpp, src/libsync/graphapi/drives.h
When adding a server that provides spaces, add those as sync roots.
=> Implement spaces

changelog/unreleased/enterprise-5052, src/common/filesystembase.cpp, src/common/filesystembase.h, src/common/utility.h, src/common/utility_win.cpp, src/libsync/propagateupload.cpp, src/libsync/propagateupload.h, src/libsync/propagateuploadng.cpp
| Client| Server| State|
|---|---|---|
| A | A |Same version on both sides
| B | A | Versions differ, client starts upload
| B | A | During the upload, B gets locked
| B | B | B is uploaded, Local B is locked so we don't enter the state to the db
| C | B | The local db was not updated, we don't know about B on the server, local file gets updated and becomes C
| C | B | We have C locally and B on the server -> clash
=> Lock upload during finalization

src/gui/proxyauthhandler.cpp, src/gui/updater/ocupdater.cpp, src/libsync/configfile.cpp, src/libsync/configfile.h
Extracted from #9376, as requested by @TheOneRing.
Fun fact: I accidentally cherry-picked the commit on 2.10 first and then spent a lot of time trying to figure out why it wouldn't build. Turns out the issue was that the old branch uses `-std=gnu++14` vs. `-std=gnu++17 -fsyntax-only` on `master` (not sure about the latter, though). In C++14, return-by-value in the `makeQSettings` factory calls the copy constructor for some reason I don't know, which `QSettings` disabled, and I found no way to use move-construction instead.
The pointer factory is there for `ProxyAuthHandler`, by the way. I didn't want to rewrite that class. Perhaps we can avoid `makeQSettingsPtr` by creating a new object on the heap and then move-assigning the old one to the one on the heap?
=> Use factories to construct QSettings objects

changelog/unreleased/9147, src/common/ownsql.cpp, src/gui/folder.cpp, src/gui/folder.h, src/gui/folderman.cpp
=> Don't load folder if we encounter a db error

src/gui/sharelinkwidget.cpp
Contributes to #9336.
New behavior:
I think we shouldn't disable the close button, because that'll bloat the (already relatively complex) code within the dialog, and requires the user to uncheck the checkbox first (in that case, we'd actually have to disable the close button generally when information is missing to make the UX consistent). Just removing the password and asking for a new one in the line edit combined with displaying the error message gives the user sufficient feedback to continue. Keeping the password makes little sense either, we should not store secrets for longer than necessary.
Upon success, a generic placeholder will be inserted in the line edit, as before.
=> Leave password line edit enabled on errors

changelog/unreleased/9425, src/gui/activitywidget.cpp, src/gui/protocolwidget.cpp, src/gui/protocolwidget.h
Fixes: https://github.com/owncloud/client/issues/9425
=> Fix account filtering in Server Activity tab

changelog/unreleased/9513, src/gui/activitywidget.cpp, src/gui/activitywidget.h, src/gui/commonstrings.cpp, src/gui/commonstrings.h, src/gui/issueswidget.cpp, src/gui/issueswidget.h, src/gui/models/models.cpp, src/gui/models/models.h, src/gui/protocolwidget.cpp, src/gui/protocolwidget.h
- replaced "No filter" option text with "All", to avoid the "No filter
is not enabled" situation
- replace the "Filter" label on the button with "1 Filter"/"2 Filters"
when a filter is active, so a user can immediately see that without
having to open the filter pop-up
=> Fix filter menus

test/gui/shared/scripts/pageObjects/SharingDialog.py, test/gui/shared/steps/steps.py
This PR adds a check for whether the share is complete or not before closing the share dialog.
Fixes https://github.com/owncloud/client/issues/9429
=> [tests-only] Fix share with multiple users GUI test

test/gui/shared/scripts/bdd_hooks.py, test/gui/shared/scripts/names.py, test/gui/shared/scripts/pageObjects/AccountStatus.py, test/gui/shared/steps/steps.py, test/gui/tst_deletFilesFolders/test.feature, test/gui/tst_sharing/test.feature
Whenever the last file/folder is deleted from the sync directory, client will show a pop like in the issue.
This PR fixes that scenario and unskipped the tests.
Fixes https://github.com/owncloud/client/issues/9439
=> [tests-only] Fix and unskip delete tests

src/gui/updater/ocupdater.cpp, src/gui/updater/ocupdater.h, test/testupdater.cpp
I guess I should implement a fake server and not rely on our mirror....
Fixes: #7390
=> Improve windows update downloader 

changelog/unreleased/9525, src/gui/updater/ocupdater.cpp, src/gui/updater/ocupdater.h
=> Retry update after 10 minutes

changelog/unreleased/9523, src/gui/folderwizard.cpp, src/gui/folderwizard.h, src/libsync/theme.cpp, src/libsync/theme.h
Default:
With branding:
Fixes: #9523
=> Branding parameter to prevent duplicated folder sync pair

src/gui/updater/appimageupdater.cpp, src/gui/updater/ocupdater.cpp, src/gui/updater/ocupdater.h, src/gui/updater/updater_private.h
Seems like while renaming some variables, the `if` condition was messed up.
The second commit renames a variable, making the related code easier to read and understand.
=> Fix skipped update check

.drone.star
Run uploadGuiTestLogs steps during nightly runs also so that the notification can have logs whenever there is a tests failure.
=> [CI] Run uploadGuiTestLogs step in nightly cron job

.drone.star, test/gui/drone/comment.sh, test/gui/drone/notification_template.sh, test/gui/shared/scripts/bdd_hooks.py, test/gui/shared/scripts/helpers/SetupClientHelper.py, test/gui/shared/scripts/helpers/StacktraceHelper.py
Stacktracing the AUT crash
Whenever there is a crash, coredump will be generated into `tmp/` folder with pattern `core-%t-%p-%s-%E`.
This PR reads those files and creates a readable stacktrace file, `${GUI_TEST_REPORT_DIR}/stacktrace`
Fixes https://github.com/owncloud/client/issues/9259
=> [tests-only] Stacktracing AUT crash while running gui tests

changelog/unreleased/9482, src/gui/CMakeLists.txt, src/gui/accountsettings.cpp, src/gui/askexperimentalvirtualfilesfeaturemessagebox.cpp, src/gui/askexperimentalvirtualfilesfeaturemessagebox.h, src/gui/folderman.cpp, src/gui/folderman.h, src/gui/folderwizard/folderwizard.cpp, src/gui/newwizard/CMakeLists.txt, src/gui/newwizard/pages/accountconfiguredwizardpage.cpp, src/gui/newwizard/pages/accountconfiguredwizardpage.h, src/gui/newwizard/pages/accountconfiguredwizardpage.ui, src/gui/newwizard/setupwizardcontroller.cpp, src/gui/newwizard/setupwizardcontroller.h, src/gui/newwizard/syncmode.cpp, src/gui/newwizard/syncmode.h, src/gui/ocwizard_deprecated.h, src/gui/owncloudgui.cpp, src/gui/selectivesyncdialog.cpp, src/gui/selectivesyncdialog.h
Contributes to #9249.
This PR implements the remaining configuration options missing in the new wizard. It adds an hidden-by-default advanced options group box to the final wizard page.
I think we can just squash this PR entirely before merging it.
=> Advanced account configuration for new wizard

src/gui/newwizard/jobs/resolveurljobfactory.cpp, src/gui/newwizard/setupwizardwindow.cpp, src/gui/newwizard/setupwizardwindow.h
Depends on #9566.
This pull request
- fixes the back button/pagination behavior by fixing the root cause within `ResolveUrlJobFactory`
- removes some dead code
- fixes segfaults when users hit `Enter` while a transition is active (also fixes potential emission of duplicate signals)
=> Fix wizard navigation

test/gui/shared/scripts/bdd_hooks.py, test/gui/shared/scripts/pageObjects/Activity.py, test/gui/shared/steps/steps.py, test/gui/tst_syncing/test.feature
#9396 
The file name with length(>=233 character) is not synced and is blacklisted.
=> added test for long file name

test/gui/drone/comment.sh
Fixes an issue introduced in #9582. With this fix, the links should work again.
=> Fix screenshot links

src/gui/newwizard/setupwizardwindow.cpp
The check also triggers on the comment within the stylesheet. It is not really needed anyway.
=> Remove overly sensitive check

.drone.star
Overall test result shows the test has failed even if there is any pass in retry situation. Hence, the `retry` function is not working as expected, and there is no point on using it because it raises more confusions. So, I removed that option here.
=> [Tests-Only]Removed GUI test retry option as it is errorsome in Squish

src/gui/accountstate.cpp, src/gui/connectionvalidator.cpp, src/gui/folderman.cpp, src/gui/newwizard/setupwizardcontroller.cpp, src/gui/newwizard/setupwizardcontroller.h, src/gui/proxyauthhandler.cpp, src/libsync/accessmanager.cpp, src/libsync/accessmanager.h, src/libsync/account.cpp, src/libsync/account.h, src/libsync/creds/abstractcredentials.h, src/libsync/creds/dummycredentials.cpp, src/libsync/creds/dummycredentials.h, src/libsync/creds/httpcredentials.cpp, src/libsync/creds/httpcredentials.h, src/libsync/creds/oauth.cpp, src/libsync/creds/tokencredentials.cpp, src/libsync/creds/tokencredentials.h, test/testoauth.cpp, test/testutils/syncenginetestutils.cpp, test/testutils/syncenginetestutils.h
Preparation for an upcoming PR that implements a TLS error dialog in the wizard.
This PR extends the existing `AccessManager` subclass of `QNetworkAccessManager` with TLS certificates management. Unfortunately, the default Qt class does not support this.
This PR replaces all the hacks that altered the global state in order to make requests to servers using (previously untrusted) certificates work.
=> Handle custom trusted CA certificates in our access manager

.drone.star, test/gui/shared/scripts/bdd_hooks.py
Closes https://github.com/owncloud/client/issues/9609
Previously, the stack trace used to be generated before the application gets closed so there was some issue with the generated stack trace. That issue is fixed in this PR and now the stack trace is done only after the application gets closed.
=> Stracktrace done after application gets closed

src/gui/CMakeLists.txt, src/gui/newwizard/jobs/resolveurljobfactory.cpp, src/gui/newwizard/setupwizardaccountbuilder.cpp, src/gui/newwizard/setupwizardaccountbuilder.h, src/gui/newwizard/setupwizardcontroller.cpp, src/gui/tlserrordialog.cpp, src/gui/tlserrordialog.h, src/gui/tlserrordialog.ui, src/libsync/abstractcorejob.h, src/libsync/determineauthtypejobfactory.cpp
Depends on #9642.
This PR implements a new TLS error dialog similar to the old SSL error dialog (which had a dependency on an account object and didn't implement separation of concerns) 
There are some TODOs/FIXMEs left, please leave your opinion there.
Contributes to https://github.com/owncloud/client/issues/9249.
=> TLS error dialog for new setup wizard

src/gui/newwizard/jobs/resolveurljobfactory.cpp, src/libsync/abstractcorejob.cpp, src/libsync/abstractcorejob.h, src/libsync/creds/jobs/determineuserjobfactory.cpp, src/libsync/determineauthtypejobfactory.cpp
Needed for an upcoming refactoring of the `CheckServerJob`.
Note that by default the corresponding nam is set as parent. I presume this will work for us. Moving ownership to the `CoreJob` causes a segfault in the destructor.
=> Make reply available for core jobs

.drone.star
In this PR, I have added some helper functions to add pipeline dependencies for pipelines. Also, made some steps to run in parallel and some dependent to others.
For e.g;
`submodules`, `install-core` and `generate` steps can run in parallel.
Closes https://github.com/owncloud/client/issues/9557
=> [tests-only] Run pipeline steps in parallel

src/gui/folderwizard/CMakeLists.txt, src/gui/newwizard/CMakeLists.txt, src/gui/spaces/CMakeLists.txt
In recent CMake versions (> 3.19.2 at least), using OBJECT libraries with Qt fails because CMake does not link AUTOMOC targets properly into users of the OBJECT libraries. This should have been fixed in 3.20, but apparently in our case this still is not working. Suggested workarounds like linking Qt5::Core into the OBJECT libraries also did not yield success.
=> Use static libraries again

src/gui/newwizard/CMakeLists.txt, src/gui/newwizard/jobs/checkbasicauthjobfactory.cpp, src/gui/newwizard/jobs/checkbasicauthjobfactory.h, src/gui/newwizard/setupwizardaccountbuilder.cpp, src/gui/newwizard/setupwizardaccountbuilder.h, src/gui/newwizard/setupwizardcontroller.cpp, src/libsync/determineauthtypejobfactory.cpp
This way, users don't unexpectedly have to re-login after the wizard completes if they entered the wrong credentials.
Fixes #9623.
Please note that there is one issue which I haven't been able to fully resolve. When moving back from the last page to the second one, the wizard re-checks the auth type (which should not be necessary but also shouldn't hurt). For some reason, this time, the lookup fails. You can move forward from the first page just fine, though, and the lookup works again.
=> Check basic auth credentials in wizard

src/gui/libcloudproviders/libcloudproviders.cpp
Fixes #9683.
I don't think we need a changelog item, since we just enabled cloudproviders integration with the upcoming 3.0 release.
=> Fix object path passed to DBus by libcloudproviders

src/gui/updater/appimageupdateavailabledialog.cpp
Dialogs inherit the icon from their parent, so we do not have to set it manually.
Closes #9704.
=> Make sure AppImage update dialog uses application icon

src/gui/newwizard/pages/serverurlsetupwizardpage.ui
=> Improve URL placeholder in first wizard page

src/gui/newwizard/pages/accountconfiguredwizardpage.cpp
I just re-reviewed #9688, and noticed a comment would be very useful, since this behavior is not clearly documented by Qt.
=> Document how native file dialog must be initialized

src/libsync/account.cpp
While we have our version info in `data`->`capabilities`->`core`->`status`  theirs is in `data`->`version`.
As putting effort in better detection support for an unsupported server feels wrong, just remove the check.
Users will now only see the 
banner.
```
"data": {
"version": {
"major": 23,
"minor": 0,
"micro": 2,
"string": "23.0.2",
"edition": "",
"extendedSupport": false
}
```
=> Remove now broken nextcloud detection

changelog/unreleased/9731, src/gui/application.cpp, src/gui/application.h, src/gui/logbrowser.cpp, src/gui/logbrowser.h, src/gui/logbrowser.ui, src/gui/owncloudgui.cpp, src/libsync/configfile.cpp, src/libsync/configfile.h, src/libsync/logger.cpp, src/libsync/logger.h
We now only rotate the logs when the client is started or the log gets bigger than 100mb
An inititial sync with cloud.owncloud.com creates archives of 4-7mb .
Keeping only 5 log files is however not enough for servers like that.
=> Change the way the continous log files are created

changelog/unreleased/9752, src/common/utility_unix.cpp
Gtk+ 3 based desktops store bookmarks information in another location. The old path was valid for Gtk+ 2 only.
Tested on xUbuntu 20.04, 22.04, Fedora 36, openSUSE Leap 15.3.
=> Fix bookmark creation in GNOME, XFCE etc.

src/libsync/CMakeLists.txt, src/libsync/logger.cpp, src/libsync/logger.h
I removed the install target for probably not working headers and added the logger.h file instead.
Ideally we would also provide a cmake export target but at the moment I would not recommend anybody to use the logger besides for testing purposes.
=> Allow to use our logger code in external libraries

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
This pull request changes the way users report new issues. It makes use of the [issue forms beta feature](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms). This should increase the quality of new issues significantly, since the new forms guide reporters much better. They also no longer have to manually remove/replace Markdown text (in fact, reporting without knowing any Markdown is possible).
Since the issue forms need to be committed before they can be tested, I set up a demo/development project. You can see these templates in action here: https://github.com/fmoc/issue-forms-demo/issues/new/choose. Please do not hesitate to open issues for testing!
Feedback is highly appreciated!
=> Make use of new issue forms feature

test/gui/shared/scripts/bdd_hooks.py
Since the last 2 days, an error occurred in the after scenario in the nightly builds saying `can only concatenate str (not "FileNotFoundError") to str`
Test Result: https://cache.owncloud.com/public//owncloud/client/11991/guiReportUpload/index.html
Solution Ref: https://stackoverflow.com/questions/63223226/python-try-except-include-the-custom-message-in-the-error-variable 
In the test log, we can see that there is no error until the users are deleted. And only place where error might occur is while generating the stacktrace. So, this solution should work.
=> [Tests-Only] Converted stacktrace error into str while logging

test/gui/tst_sharing/test.feature
The test is passing without any change. https://drone.owncloud.com/owncloud/client/12018/6/14
However, while running locally, squish is not being able to properly parse the example table.
=> [Tests-Only]Unskipped sharing test with example table

test/testdownload.cpp, test/testutils/syncenginetestutils.cpp, test/testutils/syncenginetestutils.h
The old code didn't take into account the case where a file was removed
on the server. It just Q_ASSERT-ed that it should always exist. However,
the CI does release builds, so the assert never triggered.
The problem is that in TestSyncVirtualFiles::testVirtualFileDownload the
file "A/a3" *is* removed from the server while a download is scheduled.
The fix is to handle this case separately as a valid response.
=> Fix FakeGetReply for non-existing files

test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py, test/gui/shared/steps/steps.py, test/gui/tst_syncing/test.feature
In the [previous PR](https://github.com/owncloud/client/pull/9770), I had forgotten to replace the default sync path with the temporary one. So, this PR is created for the purpose of replacing the default sync directory with `/tmp/client-bdd/Alice`.
=> changed local sync directory

changelog/unreleased/9772, src/common/utility.cpp, src/libsync/creds/oauth.cpp, src/resources/client.qrc, src/resources/oauth/oauth.html.in, test/testoauth.cpp
Depends on: https://github.com/owncloud/client/pull/9815
With the ownCloud 10 app we used to be redirected to a theme "you can now close the browser window" page.
With oidc we will display our own page which looks kind of unprofessional.
This change starts theming the web page we display.
Old:
New:
@fmoc thx for the css :D
=> Improve oauth error handling

CMakeLists.txt, changelog/unreleased/9082, src/gui/CMakeLists.txt, src/gui/application.cpp, src/gui/generalsettings.cpp, src/gui/main.cpp
=> CMake: Implement WITH_AUTO_UPDATER

changelog/unreleased/5174, src/libsync/creds/oauth.cpp
The issue occurred as we compare the user input (webfinger) with the string returned by the server.
This only happens during the initial authentication as we later use the string returned by the server.
I don't think this would still be needed in 3.0 but it most probably also won't hurt.
@DeepDiver1975 any thoughts?
=> Oauth: case insensitive username compare

changelog/unreleased/9832, src/libsync/abstractnetworkjob.cpp, src/libsync/abstractnetworkjob.h, src/libsync/networkjobs.cpp, src/libsync/propagatedownload.cpp, src/libsync/propagateupload.cpp
=> Allow to set the priority on a job level

test/gui/shared/scripts/bdd_hooks.py
This PR includes changes that log tests scenario title at the `server log file`
[make GUI test result easy to read #9826](https://github.com/owncloud/client/issues/9826)
=> Log tests scenario title at `serverlog file`

src/resources/CMakeLists.txt
Makes sure the new installed library file has a version suffix like all the other libraries. Most important for Linux distro packaging.
Fixes a minor issue introduced in #9815. We can't provide working Linux packages before this has been merged.
=> Fix installation of new resources library

test/gui/shared/scripts/bdd_hooks.py
This PR 
- refactor appending scenario title to serverlog.log  so that it runs only in CI 
- https://github.com/owncloud/client/issues/9826
=> [Tests-only] Run `append scenario title to serverlog` code  only in CI

src/gui/newwizard/pages/accountconfiguredwizardpage.cpp, src/gui/newwizard/pages/accountconfiguredwizardpage.ui
Same as #9862, but this time in the advanced section of the account
wizard page.
Fixes #9718
=> Fix another group box label truncation

src/gui/folder.cpp, src/gui/folder.h
As older clients don't know spaces yet, loading a spaces profiles
would result in all spaces being synced to the legacy dav point.
=> Prevent loading of 3.0 profiles with older clients

src/csync/csync.h, src/gui/protocolitem.h, src/libsync/propagateupload.h, src/libsync/syncfileitem.h
Fixes:
```
/__w/client/client/src/csync/csync.h:181:26: warning: 'csync_file_stat_s::type' is too small to hold all values of 'enum CSyncEnums::ItemType'
ItemType type BITFIELD(4);
```
I don't expect much impact on the level of memory consumption.
Minor performance improvement could be expected.
=> Remove bitfield macro

test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
This PR fixes the fail in `  And the user "Alice" clicks on the next button in sync connection wizard` step
due to selector change
[Scenario: Sync all is selected by default started to fail ](https://github.com/owncloud/client/issues/9879)
=> Refactor selector of choose local sync

src/gui/accountmanager.cpp, src/libsync/theme.h
This option seems to have been useful in the past, but is no longer in use.
=> Deprecate Theme::forceConfigAuthType

test/gui/shared/steps/steps.py
Closes: #9872
Related issue: #9811
This PR aims to fix an issue reported on https://github.com/owncloud/client/issues/9811. The scenario `reshare a file/folder` was failing on CI and by observing the PR https://github.com/owncloud/client/pull/9872, we concluded that the failure was due to a lack of the desired wait time for files to sync. So, to sync a resource from server to client an implicit wait has been added in this PR. 
In [debugging PR](https://github.com/owncloud/client/pull/9872), we ran 50 copies of the same scenario. Before adding the wait, 42 scenarios of them were failing. But none of the scenarios are failing after adding the wait for files to sync.
Previous build: https://drone.owncloud.com/owncloud/client/12368/6/1
After build: …
=> added implicit wait for resource to sync

test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py, test/gui/shared/steps/steps.py, test/gui/tst_syncing/test.feature
This PR refactors the test related to the `account connection wizard`. The wizard of client version 3.0 is somewhat different than version 2.10. In version 3.0, the `choose_what_to_sync` button appears only when we select the `Configure synchronization manually` option in the advanced section. Also, the folders to be synced don't appear in a single tree selector. So here we're fixing the test for `Scenario: Sync only one folder from the server` in the `tst_syncing` suite to match the selectors in the new client version.
Related issue:
#9762
=> fixed test for `Sync only one folder from the server`

changelog/unreleased/9919, src/gui/folder.cpp, src/gui/folder.h, src/gui/folderstatusmodel.cpp
In #9863 we started throtteling the the ui updates during sync, this throttles the updates even more.
=> Throttle folder status updates in general

src/gui/askforoauthlogindialog.cpp, src/gui/askforoauthlogindialog.ui
=> Use more generic message when asking the user to authenticate

changelog/unreleased/9725, src/gui/thumbnailjob.cpp, src/gui/thumbnailjob.h, src/libsync/abstractnetworkjob.cpp, src/libsync/abstractnetworkjob.h, src/libsync/bandwidthmanager.cpp, src/libsync/bandwidthmanager.h, src/libsync/networkjobs.cpp, src/libsync/networkjobs.h, src/libsync/networkjobs/jsonjob.cpp, src/libsync/networkjobs/jsonjob.h, src/libsync/propagatedownload.cpp, src/libsync/propagatedownload.h, src/libsync/propagateremotedelete.cpp, src/libsync/propagateremotedelete.h, src/libsync/propagateremotemove.cpp, src/libsync/propagateremotemove.h, src/libsync/propagateupload.cpp, src/libsync/propagateupload.h, src/libsync/propagateuploadng.cpp, src/libsync/propagateuploadtus.cpp, src/libsync/propagateuploadv1.cpp, test/testjobqueue.cpp, test/testutils/syncenginetestutils.cpp
A delete job that triggered slotComputeContentChecksum could reach slotComputeTransmissionChecksum before the delete job was removed from _jobs.
The upload job would then not start the first chunk upload and be stalled for ever.
Fixes: #9725
=> Ensure we remove a child job from before we trigger the next

changelog/unreleased/9918, src/common/syncjournaldb.cpp
In context of #6049 a check for the existance of the db file was introduced.
That check is performed before every db access... so serveral 100 times per second.
=> Don't check for db exists

changelog/unreleased/9956, src/common/vfs.h, src/gui/folder.cpp, src/gui/folder.h, src/libsync/vfs/suffix/vfs_suffix.cpp, src/libsync/vfs/suffix/vfs_suffix.h
Notes for testing:
- Lots of files online
- Initial sync
- While the sync is running, double click on a placeholder already created
- The file should be downloaded in reasonable time
- The sync progress bar should behave sensible
-  No warnings are expected
- The initial sync continues
=> Don't abort sync to dehydrate files

changelog/unreleased/9966, src/common/syncjournaldb.cpp, src/gui/accountsettings.cpp, src/gui/accountsettings.h, src/gui/folder.cpp, src/gui/folder.h, src/gui/folderman.cpp, src/gui/owncloudsetupwizard.cpp
For suffix vfs the code returned always local by default and thus needed the setRootPinState.
Obviously that wrong with anything but he suffix plugin.
For testing:
- Nothing for Windows VFS
- Suffix VFS: test how pinning behaves for child items of pinned directories.
- What happens on enable disable VFS.
- Adding a folder with files
The expected behavior is:
- Remote new remote files are online only by default.
- Existing local files stay available
- Pin states persist.
=> Don't set the pin state of the root folder but assume unspecified

test/gui/tst_syncing/test.feature
Looks like there has been a regression in desktop client (master branch). These tests are hard failures and I am skipping them in this PR until the issue is fixed.
See https://github.com/owncloud/client/issues/9971
=> [GUI-tests] Skip selective sync tests until the issue #9971 is fixed

test/gui/drone/notification_template.sh
With Rocket.chat version 5, `**:x: Failure**` doesn't yield expected :x: **Failure**
This PR has fix for such an issue.
=> [CI] Fix build notification: apply bold to text only

test/modeltests/testprotocolmodel.cpp, test/testchecksumvalidator.cpp, test/testexcludedfiles.cpp, test/testfolderman.cpp, test/testfoldermigration.cpp, test/testfolderwatcher.cpp, test/testlockedfiles.cpp, test/testlongpath.cpp, test/testownsql.cpp, test/testutils/syncenginetestutils.h, test/testutils/testutils.cpp, test/testutils/testutils.h, test/testutils/testutilsloader.cpp
Startig all QTemporaryDirs in unit tests with ownCloud-unit-test-...
simplifies the cleanup after a unit test crashed
=> Use pattern for QTemporaryDir in unit tests

src/gui/newwizard/enums.cpp, src/gui/newwizard/navigation.cpp, src/gui/newwizard/pages/serverurlsetupwizardpage.cpp, src/gui/newwizard/setupwizardcontroller.cpp, src/gui/newwizard/setupwizardwindow.cpp, src/gui/newwizard/setupwizardwindow.h
One of the last remaining branding options to be implemented in the new wizard.
I wasn't sure where to put `getNavigationEntries`, feedback appreciated. Opening as a draft to make sure we discuss this first.
=> Support overrideServerUrlV2 branding in wizard

src/gui/accountsettings.cpp, src/gui/accountstate.cpp, src/gui/askexperimentalvirtualfilesfeaturemessagebox.h, src/gui/folderwizard/folderwizardselectivesync.cpp
This PR should ensure all dialogs and message boxes opened within the client are raised to front to improve the UX, especially on macOS.
=> Raise dialogs and message boxes

.drone.star
We are having trouble running GUI tests with the latest squish docker image. Therefore, We are skipping GUI tests until this issue is resolved (issue: https://github.com/owncloud-ci/squish/issues/34)
=> [CI] Skip GUI test pipeline

src/libsync/creds/httpcredentials.cpp, src/libsync/creds/httpcredentials.h, src/libsync/creds/oauth.cpp, src/libsync/creds/oauth.h
Moves the relevant code into our account-based subclass.
Fixes #9975.
=> Fix OAuth2 refresh

src/gui/askforoauthlogindialog.cpp, src/gui/newwizard/pages/accountconfiguredwizardpage.cpp, src/gui/newwizard/pages/oauthcredentialssetupwizardpage.cpp
I kept the icons within the Qt Designer files because it helps visualize changes.
=> Use correctly themed icons

src/gui/newwizard/jobs/resolveurljobfactory.cpp
Fixes https://github.com/owncloud/client/issues/9540.
This also removes the app name from the string since we do not know (and do not care) what branding the server uses.
=> Make URL resolving error more user friendly

.craft.ini
Packaging and uploading the symbols takes ages.
Our nightlies have an integrated crash reporter and local full debug builds are rather easy with craft.
=> Ci: Don't package debug symbols

changelog/unreleased/9790, src/gui/accountsettings.cpp
Are there errors we really should display?
Fixes: #9790
=> Don't display error if server is unavailable

src/common/ownsql.cpp, src/common/ownsql.h
New:
```
08-18 12:09:09:012 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentChecksum, contentChecksumTypeId) VALUES ('-7718185600186795398' , '53', 'New folder/ownCloud-3.0.0-daily20220525.7687.AppImage' , '169157' , '0' , '0' , '0',  '1653476593' , 'CSyncEnums::ItemTypeVirtualFile' , '-7718185600186795398'0, '-7718185600186795398'1, '-7718185600186795398'2, '-7718185600186795398'3, '-7718185600186795398'4, '-7718185600186795398'5, '-7718185600186795398'6);" Try: 0
````
Old:
```
08-18 11:17:21:279 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 -8239167585704120375
08-18 11:17:21:279 [ debug …
```
=> Pretty print sqlite log

src/libsync/theme.cpp
We have the date in the build number, no need for the unpopular __DATE__ macro.
=> Remove build time from about

changelog/unreleased/10058, src/gui/accountsettings.cpp, src/gui/folderstatusdelegate.h, src/gui/folderstatusmodel.cpp
=> Fix expansion of selective sync tree

src/gui/accountsettings.cpp, src/gui/folderstatusdelegate.h, src/gui/folderstatusmodel.cpp
This commit restores the use of FolderStatusDelegate::data(...) to check whether a folder is ready. The two additions fix two different ways in which the client could crash.
Using data(...) makes sure we use the right data structure to look up the ready state for the subfolders. Using folder(...) rightfully causes an index out of range error.
This commit partially reverts #10058 and restores a previous version of said PR.
=> Fix crash in selective sync configuration

src/resources/client.qrc
We most likely overlooked this while adding some of the new icons. The files have correct colors, we just reference them incorrectly from within the `.qrc` file.
=> Fix light icons

test/gui/shared/steps/steps.py
We want to have the current scenario's state of the server not the state stored in global by the previous scenario. Storing state in global causes this issue #9866 if the scenarios are to be shuffled. Because if the first scenario only creates user Alice then in the second scenario where Alice and Brian are created, `KeyError` will be thrown if we want to add user Brain to desktop client.
UPDATE: user information is stored in a global variable and information of new user is added to the list
Fixes https://github.com/owncloud/client/issues/9866
=> [gui-tests] Update/Add users in the global user store

test/gui/shared/steps/steps.py, test/gui/tst_vfs/test.feature
Previously, the vfs tests failed because of trying to enable vfs feature before the user account was set up. In this PR, I have added wait for files to sync step so that the enabling vfs action will be successful.
This PR unskips the vfs tests.
part of https://github.com/owncloud/client/issues/10072
=> [gui-tests-only] Unskip vfs tests

test/gui/shared/scripts/bdd_hooks.py, test/gui/shared/steps/steps.py
In the GUI tests, the function `hasSyncStatus` opens a new socket connection every time it is called. The main issue is with `waitForFileOrFolderToHaveSyncStatus` function which calls `hasSyncStatus` function rapidly until the condition is met. So, there will be many socket connection requests in a single test scenario (which may or may not be an issue for the Unix socket server).
IMO, I think we must open only a single socket connection per test scenario. So, in this PR,  I have refactored the test code to only create a new socket connection if there is none and reuse the existing connection until a test scenario finishes and close the connection afterward. This way, we will open only one socket connection per scenario.
I tried to reuse a single connection for a whole test suite but that …
=> [GUI-tests] Open only one socket connection per test scenario

shell_integration/nautilus/syncstate.py
Quoting from [devhelp](https://tracker.debian.org/pkg/devhelp) (sorry, couldn't find a web document to link to), migrating Nautilus section:
>    The get_file_items, get_file_items_full, get_background_items a get_background_items_full methods of Nautilus.MenuProvider no longer take the window argument. Remove it from your implementations.
If you need to keep supporting older versions of Nautilus, you can use variadic arguments:
```
def get_file_items(self, *args):
files = args[-1]
```
=> Compatibility with older python3-nautilus

src/common/utility_mac.mm
When the crash is due to a library load failure while starting, having this turned on would result in an endless loop of crash-restarts.
Fixes: #9800
=> Mac: do not restart after crash

src/gui/newwizard/setupwizardaccountbuilder.cpp, src/gui/newwizard/setupwizardaccountbuilder.h, src/gui/newwizard/setupwizardcontroller.cpp, src/gui/newwizard/setupwizardcontroller.h, src/gui/newwizard/states/oauthcredentialssetupwizardstate.cpp, src/gui/owncloudgui.cpp, src/libsync/creds/credentialmanager.cpp, src/libsync/creds/oauth.cpp, src/libsync/creds/oauth.h
So far, dynamic registration data (i.e., data the IdP uses to identify dynamically registered clients, the method of choice when, e.g., using Keycloak with oCIS) has not been stored by the setup wizard, causing users to be logged out and requiring them to log in again after the client restarts.
=> Make wizard store dynamic registration data

src/libsync/abstractnetworkjob.cpp, src/libsync/account.cpp, src/libsync/account.h
````
09-14 13:06:06:958 [ info sync.networkjob ]:	Created OCC::PropfindJob(OCC::Account("Einstein@foo.de"), "https://foo.de/remote.php/webdav/", "PROPFIND", Original-Request-ID: "550809ee-8b92-4dd0-bd69-67c89956ffbd", X-Request-ID: "550809ee-8b92-4dd0-bd69-67c89956ffbd")
=> Improve network job logging

changelog/unreleased/10104, src/libsync/networkjobs.cpp
Implements RFC 8144, which reduces the amount of transferred data by leaving out the 404 not found attributes of items.
see https://github.com/cs3org/reva/pull/3222
=> Add a prefer minimal header to PROPFINDs.

.github/workflows/main.yml, .github/workflows/stale.yml, .github/workflows/translate.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

src/libsync/propagateuploadng.cpp, test/testchunkingng.cpp
The header was a leftover from delta sync and is not used by the server
https://github.com/owncloud/client/commit/12aeb890c9a6ad329e3612ebb96d843d70e413c9
=> Remove OC-Chunk-Offset header

.github/workflows/translate.yml
This will give the translators some time to prepare for the huge amount of string changes.
=> Ci: Switch translations branch to master

test/testallfilesdeleted.cpp, test/testblacklist.cpp, test/testchunkingng.cpp, test/testdownload.cpp, test/testpermissions.cpp, test/testsyncconflict.cpp, test/testsyncengine.cpp, test/testsyncmove.cpp, test/testutils/syncenginetestutils.cpp, test/testutils/syncenginetestutils.h
- make the default values into static constexpr member fields
- remove unused method `modifyByte`
- don't rely on on-disk info like file sizes (so it can be used in dehydrated VFS modes)
=> Tests: Clean up FileModifier API

.github/workflows/main.yml
```
[qt/stdout] Copying file /lib64/libavahi-client.so.3 to /github/home/craft/CraftMaster/linux-64-gcc/build/owncloud/owncloud-client/archive/usr/lib/libavahi-client.so.3
[qt/stdout] ERROR: Failed to copy file /lib64/libavahi-client.so.3 to /github/home/craft/CraftMaster/linux-64-gcc/build/owncloud/owncloud-client/archive/usr/lib/libavahi-client.so.3: boost::filesystem::copy_file: Invalid cross-device link: /lib64/libavahi-client.so.3, /github/home/craft/CraftMaster/linux-64-gcc/build/owncloud/owncloud-client/archive/usr/lib/libavahi-client.so.3
```
=> Ci: Disable packaging on linux for now

test/gui/shared/scripts/names.py, test/gui/shared/steps/steps.py
Sometimes when starting the client `No connection configured` message appears and the tests would fail. It appears that sometimes it takes few waits to connect to the account.
In this PR, I have added the wait until the connection is confgured.
Fixes https://github.com/owncloud/client/issues/10140
=> [gui-tests] Wait until the connection is configured after starting client

changelog/unreleased/5382, src/libsync/owncloudpropagator_p.h
This should fix the issue where huge file uploads failed because the uploaded file could not be moved as it was still locked by the AV.
@dragotin What do you think?
=> Don't trigger ignore list when files are locked on the server

src/libsync/bandwidthmanager.cpp, src/libsync/bandwidthmanager.h, src/libsync/owncloudpropagator.cpp, src/libsync/owncloudpropagator.h, src/libsync/propagatedownload.cpp, src/libsync/propagateupload.cpp, src/libsync/propagateuploadng.cpp, src/libsync/propagateuploadtus.cpp, src/libsync/propagateuploadv1.cpp, src/libsync/syncengine.cpp
This might not fix the referenced issue, however there is no point in calling all those functions and run all those timers for no reason at all.
Downside:
If we have a huge download running, it will not be affected by changes to the limit.
Issue: #10031
=> Only use bandwidth manager if needed

src/libsync/discoveryphase.cpp, src/libsync/propagatedownload.cpp, src/libsync/propagateremotedelete.cpp, src/libsync/propagateremotemkdir.cpp, src/libsync/propagateremotemove.cpp
That way we will correctly detect the reason and not assume a timeout
=> Use job, abort instead of reply()-abort()

src/gui/accountsettings.cpp, src/gui/creds/httpcredentialsgui.cpp, src/gui/loginrequireddialog/loginrequireddialog.cpp, src/gui/loginrequireddialog/loginrequireddialog.h
The widgets are pre-initialized by the .ui file already, there is no need for initializing them manually.
=> Don't create redundant content widgets

test/gui/shared/scripts/bdd_hooks.py, test/gui/shared/scripts/helpers/SyncHelper.py, test/gui/shared/steps/steps.py, test/gui/tst_addAccount/test.feature, test/gui/tst_deletFilesFolders/test.feature, test/gui/tst_editFiles/test.feature, test/gui/tst_sharing/test.feature, test/gui/tst_syncing/test.feature, test/gui/tst_vfs/test.feature
Making sync wait more reliable using pattern matching. Meaning, certain patterns can be found in the socket messages while the desktop-client is syncing files/folder. This PR utilizes those patterns in order to determine the different sync statuses of the file/folder.
For example; while a file/folder undergoes sync and sync is completed, we can see the following pattern (in order):
```
STATUS:SYNC
STATUS:OK
```
Thus, this PR uses such status messages order (pattern) to determine the sync status of file/folder.
Previously, in order to determine whether the file/folder is synced or not, we were searching for `STATUS:OK` status in the socket messages. This was not so reliable as there can be multiple OK statuses for the same file/folder in the socket messages. Also, we might get a false …
=> [tests-only] Make sync wait more reliable using sync status pattern matching

.drone.star
This PR bumps the middleware version to `1.8.2` 
https://github.com/owncloud/owncloud-test-middleware/issues/126
=> [tests-only]Bump middleware version to 1.8.2

test/gui/shared/scripts/bdd_hooks.py, test/gui/shared/scripts/helpers/SetupClientHelper.py, test/gui/shared/steps/steps.py
This PR has the following changes:
- Remove waits where there is no need
- Wisely wait for some actions to finish (if needed)
Previously, there were waits before any action (`create`, `delete`, `rename`, and `move` file/folder). The wait was needed but only before the first action so there was no need for other waits after the first wait. Those waits accumulate and cause test cases to run for a long. Thus, this PR has refactored the test code so that there is a wait only before performing the first sync operation and other operations can be performed without waits.
Similarly, we have explicitly waited for `minSyncTimeout` i.e. `5 secs` for the AUT to be terminated thus causing unnecessary waits and long tests run. In this PR, I have checked the availability of the AUT process, determined …
=> [gui-tests] Remove unnecessary waits

src/gui/activitywidget.cpp, src/gui/activitywidget.h, src/gui/folder.cpp, src/gui/folder.h, src/gui/folderman.cpp, src/gui/folderwizard/folderwizard.cpp, src/gui/folderwizard/folderwizard.h, src/gui/folderwizard/folderwizard_p.h, src/gui/issueswidget.cpp, src/gui/issueswidget.h, src/gui/models/models.cpp, src/gui/models/models.h, src/gui/owncloudgui.cpp, src/gui/protocolwidget.cpp, src/gui/protocolwidget.h, src/gui/spaces/spacesbrowser.cpp, src/gui/spaces/spacesmodel.cpp, src/gui/spaces/spacesmodel.h, src/libsync/graphapi/drives.cpp, src/libsync/graphapi/drives.h
This will ensure that the personal folder and the shares folder are always on top.
The implementation in the folder status view on the accounts view will need a follow up as it requires refactoring.
=> Sort spaces by priority

changelog/unreleased/49
It turned out to be just one changelog entry, one was a 3.0 regression.
Fixes: #10233
=> Add vfs changelog

changelog/unreleased/10193, changelog/unreleased/10239, src/cmd/cmd.cpp, src/common/utility.cpp, test/testutility.cpp
```
Usage: C:\CraftRoot\build\_\30b36579\owncloud-client\out\build\x64-Debug\bin\owncloudcmd.exe [options] source_dir server_url remote_folder
owncloudcmd version 3.1.0.0-git - command line client tool
Options:
-s, --silten                      Don't be so verbose.
--httpproxy <http://server:port>  Specify a http proxy to use.
--trust                           Trust the SSL certification
--exclude <file>                  Path to an exclude list [file]
--unsyncedfolders <file>          File containing the list of unsynced remote
folders (selective sync)
--server <url>                    Use [url] as the location of the server.
OCIS only (server location and spaces url
can differ)
-u, --user <name>                 Use [name] as the login name
-p, --password <password>         Use [pass] as …
```
=> CMD accept remote folder explicitly

changelog/unreleased/10206, src/gui/owncloudgui.cpp, src/libsync/capabilities.cpp, src/libsync/capabilities.h
When using role based sharing we no longer display the sharing dialog.
Fixes: #10206
=> Open the browser instead of the share dialog

changelog/unreleased/10193, changelog/unreleased/10239, src/cmd/cmd.cpp, src/common/utility.cpp, test/testutility.cpp
These commits were merged by accident into `master`, they were meant to go into `3.0`.
=> Backport some commits from master to 3.0

src/gui/updater/updater.cpp
We changed the updater server's behavior to properly distinguish between different kinds of packaging/bundling, which is novel to the current setup. In future releases, we are going to add this parameter for the other platforms, too, and also stop encoding the architecture into the platform string for Windows.
=> Fix AppImages' update check

src/libsync/propagateuploadtus.cpp
Upload jobs where always done with a low priority
=> Set upload priority for tus jobs

src/libsync/platform_mac.mm
... by actually calling the migration function. This got lost during the `Platform` class refactoring.
=> macOS: Fix start-on-login migration

src/common/utility_unix.cpp
This should fix #10280. I could not find any other encoding issues other than spaces while testing on a variety of distributions an desktops. 
Unfortunately, there is little to no documentation on how this file should really be structured. We have not seen any issues other than with spaces in paths so far, though. We can add additional escaping in the future if needed.
=> Fix encoding of Gtk bookmarks

changelog/unreleased/10310, src/libsync/httplogger.cpp, src/libsync/logger.cpp
Changes the log format to:
```
22-11-23 18:38:34:438 [ info sync.httplogger ]: "5dca3f29-99a7-488b-a35d-8113302e4ba8: Response: PROPFIND 207 (duration(0h, 0min, 0s, 214ms)=214ms) ht...
```
Note 
1. The year at the beginning of the line to make the time stamp standard compatible and parseable
2. The duration in milliseconds appended to the "verbose" duration for humans...
=> Log parseables

test/testutils/syncenginetestutils.cpp, test/testutils/syncenginetestutils.h
Applying local modifications will run the event loop, so any callbacks from cfapi (and QNAM replies) will be handled.
This change prevents the sync to interfere with e.g. hydration requests and possibly soft-fail for that reason.
=> Run the sync only once after applying all local modifications

src/cmd/cmd.cpp
=> typo in cmd client usage

translations/.tx/config, translations/Makefile
The way we maintain the commands (in a `Makefile` that is tracked in the branch we want to update rather than the main branch), we need to backport these changes to our 3.1 branch.
Note for self: do it right next time.
=> Backport translation changes to 3.1

translations/Makefile
The flag in question doesn't exist any more.
=> Fix tx push command

src/gui/application.cpp, src/gui/logbrowser.cpp, src/libsync/configfile.cpp, src/libsync/configfile.h, src/libsync/logger.cpp
This commit makes sure that when starting the application, the value is populated from the config file. Previously, the value was only changed when the user set a different value in the log settings dialog.
The static initialization was removed from the constructor to prevent a cyclic dependency between the config file and logger classes (the latter uses the former to populate the value mentioned above).
Fixes #10345.
=> Load log file count limit properly from config file

test/gui/shared/scripts/names.py, test/gui/shared/scripts/pageObjects/AccountStatus.py, test/gui/shared/scripts/pageObjects/Toolbar.py, test/gui/shared/steps/steps.py, test/gui/tst_addAccount/test.feature, test/gui/tst_removeAccountConnection/test.feature
We want to avoid using `names` (UI component selector) directly in the step def files. This will help us to maintain the selectors in the page objects. Using page object methods for UI actions is the preferred way and it helps to maintain the DRY code
Part of https://github.com/owncloud/client/issues/10353
=> [gui-tests] Avoid use of names in step defs but use methods from page objects (part 1)

src/gui/loginrequireddialog/abstractloginwidget.h, src/gui/loginrequireddialog/basicloginwidget.cpp, src/gui/newwizard/pages/abstractsetupwizardpage.h, src/gui/newwizard/pages/basiccredentialssetupwizardpage.cpp, src/gui/newwizard/pages/serverurlsetupwizardpage.cpp, src/gui/newwizard/setupwizardwindow.cpp
This removes the now-obsolete handling via the event filter, which doesn't need to run that often anyway.
Closes #10321.
=> Enable next button when pasting data using context menu, too

changelog/unreleased/10387, src/libsync/appprovider.cpp
Due to a bug opening in browser only worked when logs where active
=> Fix opening the browser

.drone.star
=> [tests-only] Bump oCIS version to 2.0.0

changelog/unreleased/10390, src/cmd/cmd.cpp
There used to be an option to enable the synchronization of hidden files using the `-h` parameter which collided with the `--help` option and subsequently was removed.
A new ~`-H`~ parameter was introduced to fill in the missing feature (long form: `--sync-hidden-files`).
Closes #10390.
=> (Re)introduce "sync hidden files" parameter in owncloudcmd

test/gui/shared/scripts/helpers/SyncHelper.py, test/gui/shared/scripts/pageObjects/SharingDialog.py, test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py
`test` module was not imported int SyncHelper, so this PR imports that module.
Also, removes unused imports
Fixes https://github.com/owncloud/client/issues/10386
=> [gui-tests] Import test module

src/gui/aboutdialog.ui, src/gui/activitywidget.ui, src/gui/folderwizard/folderwizardtargetpage.ui, src/gui/notificationwidget.ui, src/gui/proxyauthdialog.ui, src/gui/sharedialog.ui, src/gui/sharelinkwidget.ui, src/gui/shareuserline.ui, src/gui/updater/appimageupdateavailabledialog.ui
These are unnecessary, as they are programmatically replaced by the wanted text. They do end up in translations though, so they produce confusion there.
=> Remove "TextLabel" texts from `QLabel`s in .ui files

test/testsyncconflict.cpp
This test was already partially skipped due to order-of-operations problems (see issue #10223), but on the CI the very first sync already fails. This is probably due to the same problem, so now we skip the test completely (for dehydrated files).
=> Skip `testLocalFileRemoteDirConflict()` for dehydrated files

test/gui/shared/steps/file_context.py, test/gui/tst_moveFilesFolders/test.feature, test/gui/tst_moveFilesFolders/test.py
This pr adds test cases related to :
- Move a folder and a file up from sub-folder to the root
- Move two folders and a file down to sub-folder
- https://github.com/owncloud/QA/issues/789
=> [tests-only] Add GUI tests related to moving files and folders

src/libsync/creds/oauth.cpp
It usually just means none was set.
Fixes: #10409
=> Reduce warning level if no dynamic registration key was fetched

src/libsync/creds/webfinger.cpp
The WebFinger class expects a resource ID already. It's the caller's job to assemble the `acct:` URL, not WebFinger's.
Fixes #10471.
=> Fix duplicate acct: in Webfinger resource ID

src/gui/loginrequireddialog/basicloginwidget.cpp, src/gui/newwizard/pages/webfingersetupwizardpage.cpp, src/gui/newwizard/pages/webfingersetupwizardpage.ui
Fixes #10440.
Do we need changelog entries for these changes?
=> Fix custom user ID and hint handling

test/gui/shared/scripts/helpers/SpaceHelper.py, test/gui/shared/steps/file_context.py, test/gui/shared/steps/spaces_context.py, test/gui/tst_spaces/test.feature
Add test cases for project space member with Editor and Manager roles
Scenarios:
```feature
Scenario: User with Editor role can edit the file
Scenario: User with Manager role can add files and folders
``` 
Part of https://github.com/owncloud/QA/issues/789
Closes https://github.com/owncloud/client/issues/10428
=> [gui-tests] Add tests for space member with Editor and Manager roles

.drone.star, test/gui/drone/notification_template.sh
For tag/release events, we want to get the Squish GUI tests reports regardless of the status of the tests (pass or fail). This helps the QA team to evaluate the test reports on releases.
=> [ci] Notify chat with gui reports on tag events

changelog/unreleased/10231, src/gui/accountsettings.cpp, src/gui/owncloudgui.cpp
This commit further unifies the wording between the context menu entries and the popup.
Fixes #10231.
=> Replace term (un)pause with a more suitable one

test/gui/shared/scripts/pageObjects/AccountSetting.py, test/gui/shared/steps/account_context.py, test/gui/tst_checkAlltabs/test.feature
PR adds test scenario to open log dialog with `Ctrl+l` keys combination
- part of https://github.com/owncloud/QA/issues/789
=> [gui-tests] Added test scenario to open log dialog

.drone.star, test/gui/shared/scripts/helpers/WebUIHelper.py, test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py, test/gui/shared/steps/account_context.py, test/gui/tst_loginLogout/test.feature, test/gui/webUI/login.spec.js, test/gui/webUI/package.json
Added a test scenario to test the successful oauth2 login (only for oC10 server)
- part of https://github.com/owncloud/QA/issues/789
=> [gui-tests] Add oauth2 login test scenario

test/gui/tst_moveFilesFolders/test.feature
This PR adds GUI test for renaming a file and a folder
=> [tests-only] add test for renaming file and folder

changelog/unreleased/9270, src/gui/folderman.cpp, src/libsync/syncresult.h
Please read carefully, I'm not sure what the whole logic here was meant to do (It`s my code).
Fixes: #9270
=> Fix overall status computation

src/libsync/creds/httpcredentials.cpp
This removes support for credentials stored in the url like `demo:demo@demo.owncloud.org`.
The 2.11 client allowed to enter such a url in the wizard, however the credentials where properly stored.
So there is no need to keep this hack around.
Do we need a changelog entry?
=> Remove support for credentials encoded in urls

src/common/utility.h
The utily based on https://www.kdab.com/qt-range-based-for-loops-and-structured-bindings/ Enables us to use C++17 structural binding loops with Qt containers like:
```c++
QMap<QString, Error> errorPaths;
for (const auto &[path, error] : Utility::asKeyValueRange(errorPaths)) {}
```
=> Add Utility::asKeyValueRange

src/gui/accountsettings.cpp
After adding an oCIS account, the "add" button on the account settings page will now correctly show "Add Space" instead of "Add Folder".
Fixes: #10502
=> Fix button label in account settings page

changelog/unreleased/10251, src/gui/generalsettings.cpp
Fixes a minor UI bug where the update channel in testpilotcloud is not reset to its original value even if the message box that warns about the beta channel is rejected.
Fixes #10251.
=> Reliably reset update channel

src/libsync/abstractnetworkjob.cpp, src/libsync/abstractnetworkjob.h, src/libsync/account.cpp, src/libsync/account.h, src/libsync/networkjobs.cpp
This pull request adds a local network cache to every account. Using this cache, we can store resources locally to reduce the load on the server and also implement better offline support.
By default, network jobs' target resources are not stored in the cache and we always download the latest version. Therefore, currently, one needs to enable caching on a per-job basis. This might change in the future, since we depend on the server-side caching policy anyway.
Qt supports the common headers. In fact, Qt won't cache resources with `Cache-Control: ... must-revalidate` anyway (we had to check Qt's code base for this). We may have to either implement our own caching logic outside of `QNetworkAccessManager` or adapt the server policy.
Contributes to …
=> Cache specific network resources

src/gui/folderstatusdelegate.cpp, src/gui/guiutility.cpp, src/gui/guiutility.h, src/gui/logbrowser.cpp, src/gui/loginrequireddialog/CMakeLists.txt, src/gui/loginrequireddialog/oauthloginwidget.cpp, src/gui/models/activitylistmodel.cpp, src/gui/newwizard/CMakeLists.txt, src/gui/newwizard/pages/accountconfiguredwizardpage.cpp, src/gui/notificationwidget.cpp, src/gui/owncloudgui.cpp, src/gui/settingsdialog.cpp, src/gui/sharelinkwidget.cpp, src/gui/shareusergroupwidget.cpp, src/gui/spaces/CMakeLists.txt, src/gui/spaces/spacesdelegate.cpp, src/gui/spaces/spacesmodel.cpp, src/gui/updater/appimageupdateavailabledialog.cpp, src/libsync/CMakeLists.txt, src/libsync/theme.cpp, src/libsync/theme.h, src/resources/CMakeLists.txt, src/resources/resources.cpp, src/resources/resources.h
We already require a QGuiApplication so keeping the core free of QGui doesn't make much sense.
This change will allow to use resources in libsync.
=> Move getCoreIcon to the resource module

changelog/unreleased/10621, src/gui/aboutdialog.cpp, src/gui/accountsettings.cpp, src/gui/accountstate.cpp, src/gui/folderwizard/folderwizard.cpp, src/gui/guiutility.cpp, src/gui/guiutility.h, src/gui/ignorelisteditor.cpp, src/gui/logbrowser.cpp, src/gui/loginrequireddialog/basicloginwidget.cpp, src/gui/loginrequireddialog/loginrequireddialog.cpp, src/gui/loginrequireddialog/oauthloginwidget.cpp, src/gui/newwizard/jobs/resolveurljobfactory.cpp, src/gui/newwizard/pages/accountconfiguredwizardpage.cpp, src/gui/newwizard/setupwizardwindow.cpp, src/gui/owncloudgui.cpp, src/gui/owncloudgui.h, src/gui/settingsdialog.cpp, src/gui/sharedialog.cpp, src/gui/tlserrordialog.cpp, src/gui/updater/appimageupdateavailabledialog.cpp, src/gui/updater/appimageupdater.cpp
Eliminate Utility::setModal and rather call ->open() on all dialogs
Utility::setModal was also setting Qt::ApplicationModal however
it appears Qt never cared and always set Qt::WindowModal.
https://github.com/qt/qtbase/blame/4ee4fc18b4067b90efa46ca9baba74f53b54d9ec/src/widgets/dialogs/qdialog.cpp#L543
Setting Qt::Sheet is also handled in open();
Fixes: #10621
=> Fix modal dialogs

src/cmd/cmd.cpp, src/gui/accountmanager.cpp, src/gui/accountmanager.h, src/gui/newwizard/setupwizardaccountbuilder.cpp, src/libsync/account.cpp, src/libsync/account.h, test/testoauth.cpp, test/testutils/testutils.cpp
For the unit tests and the cmd client we will get a different uuid every run, this means we will leave the caches behind.
=> Ensure account uuid doesn't change during lifetime

changelog/unreleased/10251, src/gui/generalsettings.cpp, src/gui/generalsettings.ui
We need to keep our own copy of the old index to be able to reliably reset the selection if the dialog is rejected.
=> Fix update channel reset

src/gui/newwizard/setupwizardaccountbuilder.cpp, src/gui/newwizard/setupwizardaccountbuilder.h, src/gui/newwizard/setupwizardcontroller.cpp
It's not great to add the setter to the common interface, but still much better than casting the pointer and conditionally executing that method.
Fixes #10682.
=> Fix setup of OAuth2 accounts

.drone.star
Disable squish tests pipeline for oc10 server.
The oc10 pipeline finishes in around 30 mins and the CI is somehow delaying developers to act fast on PRs. Even though the tests run in parallel, we have limited Squish license due to which if there are several PRs then some CI build will get stuck waiting for the license.
However, the tests against oc10 server can be enabled for the PRs by simply adding `oc10-gui-tests` in the PR title.
1. Normal PR (without `oc10-gui-tests` in the title): https://drone.owncloud.com/owncloud/client/14915
2. PR with `oc10-gui-tests` in the title: https://drone.owncloud.com/owncloud/client/14916
=> Disbale gui tests against oc10 on PRs

changelog/unreleased/10352, src/common/filesystembase.cpp, src/common/filesystembase.h, src/gui/folder.cpp, src/gui/folderman.cpp
Additionally the length to the db is irrelevant for this check
=> Prevent selection of too long path on Windows

src/libsync/account.cpp, src/libsync/graphapi/spacesmanager.cpp, src/libsync/graphapi/spacesmanager.h
Ensur spaces are fetched even if the server was unavailable during startup
=> Ensure the spaces are always fetched

cmake/modules/OCApplyCommonSettings.cmake, src/csync/CMakeLists.txt
This is so we can use the secure identifier APIs.
=> Bump minimal Win32 API version to Win8

.drone.star
- skip oc10 pipeline on commit push (run only on tags and nightly)
- fix notification pipeline on tag event
- allow changelog pipeline on commit push
=> [CI] Fix pipeline runs

src/gui/application.cpp, src/gui/application.h, src/libsync/accessmanager.cpp
Fixes: #10744
Will be implemented again in #10745.
=> Remove usage of deprecated QNetworkConfigurationManager

src/gui/application.cpp
The used apis are no longer available
=> Qt6: Remove 2.5 migration code

test/gui/shared/steps/sharing_context.py
Falky GUI tests: 
- `Scenario: share a file with many users`
- `Scenario: share file and folder to a group`
Flaky test report here https://github.com/owncloud/client/issues/10074#issuecomment-1288378357
In this PR, I have refactored the test code to do all the collaborator assertions and then only close the share dialog.
=> [GUI test][full-ci] open and close shareDialog once 

test/gui/shared/scripts/helpers/SetupClientHelper.py
Included `0/http_CredentialVersion=1` in the account config. This will disable the migration code.
Hoping not to see this failure with this
https://github.com/owncloud/client/issues/10140
=> [full-ci][gui-tests] Disable legacy migration for the test accounts

src/gui/folder.cpp
When whe changed the argument from single path to a set of paths, this return was overlooked.
Fixes: #10807
=> Fix issue introduced during refactoring

test/gui/shared/scripts/helpers/SpaceHelper.py, test/gui/shared/scripts/helpers/UserHelper.py, test/gui/shared/scripts/helpers/api/HttpHelper.py, test/gui/shared/scripts/helpers/api/Provisioning.py, test/gui/shared/steps/server_context.py, test/gui/tst_loginLogout/test.feature
Removed the use of oc10 app setup step from middleware and added it locally in python.
Renamed step:
```diff
- Given app "oauth2" has been "enabled" on the server
+ Given app "oauth2" has been "enabled" in the server
```
=> [gui-tests][full-ci] Add server app setup steps

.drone.star, test/gui/tst_checkAlltabs/test.feature
Updated squish image to have necessary libs for `master` branch in https://github.com/owncloud-ci/squish/pull/42
Bumped squish image to `owncloudci/squish:fedora-38-...`
=> [ci][full-ci] Use updated fedora-38 squish image for tests

test/gui/shared/scripts/helpers/api/HttpHelper.py, test/gui/shared/scripts/helpers/api/webdav_helper.py, test/gui/shared/steps/server_context.py, test/gui/tst_deletFilesFolders/test.feature, test/gui/tst_moveFilesFolders/test.feature, test/gui/tst_sharing/test.feature, test/gui/tst_syncing/test.feature
These `Then` step implementation asserts whether the given resource(file/folder) is present on the server or not.
Renamed step:
```diff
-Then as "<user>" file "<fileName>" should exist on the server
-Then as "<user>" file "<fileName>" should not exist on the server
-Then as "<user>" folder "<folderName>" should exist on the server
-Then as "<user>" folder "<folderName>" should not exist on the server
+Then as "<user>" file "<fileName>" should exist in the server
+Then as "<user>" file "<fileName>" should not exist in the server
+Then as "<user>" folder "<folderName>" should exist in the server
+Then as "<user>" folder "<folderName>" should not exist in the server
```
=> [tests-only][full-ci] Then step implementation in python for the existence of file on the server

test/gui/shared/scripts/helpers/api/webdav_helper.py, test/gui/shared/steps/server_context.py, test/gui/tst_editFiles/test.feature, test/gui/tst_moveFilesFolders/test.feature, test/gui/tst_sharing/test.feature, test/gui/tst_syncing/test.feature
These `Then` step implementation asserts whether the given resource(file/folder) is present on the server or not.
Renamed step:
```diff
-Then as "<user>" the file "<fileName>" should have the content "<content>  on the server"
+Then as "<user>" the file "<fileName>" should have the content "<content> in the server "
```
=> [tests-only][full-ci] Then step implementation in python for asserting the content of the file in the server

src/libsync/abstractnetworkjob.cpp
Explicitly set attribute(QNetworkRequest::RedirectPolicyAttribute, QNetworkRequest::ManualRedirectPolicy); This used to be the default in Qt5.
Fixes: #10832
=> Qt6: Don't follow redirects

changelog/unreleased/10866
Changelog was missing the link and the changelog pipeline in drone-ci complains about it.
Added the correct link to the changelog
Fixes https://github.com/owncloud/client/issues/10870
=> Add missing PR link to the changelog

.drone.star
Changelog pipeline in other branches such as 4, pulls the master branch but it should pull the branch 4.
See build: https://drone.owncloud.com/owncloud/client/15458/1/2
Removed the clone step from changelog pipeline so that default clone step is used that clones the target branch (clones the respective branch that triggered the build)
=> [CI] Use default clone step in changelog pipeline

.drone.star
Nightly fail: https://drone.owncloud.com/owncloud/client/15538
Currently, changelog pipeline in 4 branch tries to push the diff to the master branch.
As per https://github.com/owncloud/client/pull/10895#issuecomment-1569749623, we only push changelog on master branch only
=> [ci] Make changelog push to the master branch only

src/common/checksums.cpp, src/common/utility.cpp, src/gui/application.cpp, src/gui/folderwatcher_linux.cpp, src/gui/folderwatcher_mac.cpp, src/gui/generalsettings.cpp, src/gui/lockwatcher.h, src/gui/main.cpp, src/gui/socketapi/socketapi.cpp, src/gui/socketapi/socketapi.h, src/gui/systray.cpp, src/gui/translations.cpp, src/libsync/configfile.cpp, src/libsync/filesystem.h, src/libsync/owncloudtheme.cpp, src/libsync/propagatedownload.cpp, src/libsync/propagateupload.cpp, src/libsync/propagateuploadv1.cpp, src/libsync/theme.cpp, src/libsync/theme.h, src/plugins/vfs/suffix/vfs_suffix.cpp, test/testsyncmove.cpp
And also for the application icon name. There is one left in the common sources, but those cannot depend on libsync, so that's left alone.
=> Use theme methods instead of macros for application name

changelog/unreleased/10825, src/gui/folderwatcher.cpp, test/testfolderwatcher.cpp
We currently gather changes for up to 1s and then handle them.
Often we then ignore them as nothing, interesting for us, changed.
This change increases the interval to 10s.
If the file changed 50 times in that interval we will now only check once instead of about 10 times.
Note: When we detect a change it does not mean instant upload, we will evaluate the file and queue it for the next sync run. 
Estimated impact: Less noise in the logs, slight performance improvements.
=> Don't emit folder watcher changes every 1s

test/gui/shared/scripts/helpers/api/sharing_helper.py, test/gui/shared/steps/server_context.py, test/gui/tst_sharing/test.feature
These `Then` step implementation for checking public link in the server
Renamed step:
```diff
-Then as user "<user>" the file "<fileName>" should have a public link on the server
-Then as user "<user>" the folder "<folderName>" should have a public link on the server
-Then as user "<user>" the file "<fileName>" should not have any public link on the server
-Then as user "<user>" the folder "<folderName>" should not have any public link on the server
+Then as user "<user>" the file "<fileName>" should have a public link in the server
+Then as user "<user>" the folder "<folderName>" should have a public link in the server
+Then as user "<user>" the file "<fileName>" should not have any public link in the server
+Then as user …
```
=> [tests-only][full-ci] Then step implementation for checking public link in the server

changelog/unreleased/10905, src/libsync/logger.h
This mainly affects https://github.com/owncloud/client/blob/e6d0be936f43754ccfc7b9a18f0e0ac6358d1b5a/src/libsync/logger.cpp#L153 which tries to load our plugins and qt plugins.
=> Fix possible deadlock during log setup

src/libsync/progressdispatcher.cpp
A verb-used-as-adjective after a verb is very confusing: "copied changed local file", and problematic as it was used when a sync *conflict* occurred. This now reads "renamed local copy".
Fixes: #10568
=> Fix hard to read error message

THEME.cmake
DBus paths may only contain a subset of the characters that are valid for domain names. This commit replaces all offending characters with underscores.
=> Sanitize libcloudproviders DBus path

src/gui/settingsdialog.cpp
Specifically, show it when the wizard was aborted and no account was created. Previously, the button was not shown, and the user could not add an account after aborting the wizard.
Fixes: #10443
=> Show Add Account button for single account clients

src/common/utility.cpp
Fixes `testdownload.cpp` unit tests when using them in a non-UTC environment (e.g., developer workstations).
=> Treat RFC1123 dates as UTC

src/gui/application.cpp, src/libsync/configfile.cpp, src/libsync/configfile.h
The version number stored in the config file now includes the build number. So when the build number changes between RCs, alphas, betas etc, there will be a backup made of the "old" configuration.
Fixes: #10789
=> Create config file backup with every update

changelog/unreleased/10928, src/gui/issueswidget.cpp, src/libsync/configfile.cpp, src/libsync/configfile.h
=> Persist filter settings for Not Synced tab

src/resources/CMakeLists.txt
qt_add_translation also invokes lupdate which might invalidate the generated files.
We don't need to call lupdate as we explicitly call it in the translation sync.
Requires Qt 6.2
=> Possible speedup for recompilation (translations)

.drone.star
This PR bumps ocis server version to 3.0.0, 
previously it was 2.0.0 .
=> Bump ocis server to 3.0.0

src/gui/application.cpp
This was introduced in #4197, but as far as we can tell, it is not needed anymore.
Fixes: #10763
=> Do not set stylesheets globally in application setup code

src/gui/main.cpp
With Qt6 the `appmenu-qt5` is never available, so remove the codition and the else-clause.
=> Remove unused code

src/gui/activitywidget.cpp
Some servers do not provide activities at all. In that case, the label should not read "have activities enabled", because that implies that they could be provided, but are disabled. Which is misleading.
=> Fix misleading message

src/libsync/propagateuploadtus.cpp
=> Include mtime in tus Upload-Metadata

.drone.star
Building client requires qt6. And current squish only supports qt5. So disabling squish gui test pipelines until new version of squish is available.
=> [ci] Disable gui tests until new squish is available

test/gui/shared/scripts/helpers/UserHelper.py, test/gui/shared/scripts/helpers/api/HttpHelper.py, test/gui/shared/scripts/helpers/api/sharing_helper.py, test/gui/shared/steps/server_context.py, test/gui/tst_sharing/test.feature
These `Then` step implementation asserts whether the given resource(file/folder) is present on the server or not.
Renamed step:
```diff
-Then the public should be able to download the file "<fileName>" without password from the last created public link by "<user>" on the server
-Then the public should not be able to download the file "<fileName>" from the last created public link by "<user>" on the server
-Then the public should be able to download the file "<fileName>" with password "<password>" from the last created public link by "<user>" on the server
+Then the public should be able to download the file "<fileName>" without password from the last created public link by "<user>" in the server
+Then the public should not be …
```
=> [tests-only] [full-ci] Implement `Then` step for downloading file from public link

src/gui/folderstatusdelegate.cpp
=> Fix alignment of the 3dots menu on mac

test/gui/shared/scripts/helpers/api/webdav_helper.py, test/gui/shared/steps/server_context.py, test/gui/tst_syncing/test.feature
These `Then` step implementation asserts whether the given resource(file/folder) is present on the server or not.
Renamed step:
```diff
-Then as user "<user>" folder "<folderName>" should contain "<number>" items on the server
+Then as user "<user>" folder "<folderName>" should contain "<number>" items in the server
```
=> [tests-only] [full-ci] Implement `Then` step for verifying number of items in the folder 

src/common/checksumalgorithms.cpp, src/common/checksumalgorithms.h, src/common/checksums.cpp, src/common/pinstate.cpp, src/common/pinstate.h, src/common/syncjournaldb.cpp, src/common/utility.h, src/common/vfs.cpp, src/common/vfs.h, src/gui/folder.cpp, src/gui/folderman.cpp, src/gui/folderstatusmodel.cpp, src/gui/guiutility.cpp, src/gui/guiutility.h, src/gui/libcloudproviders/libcloudproviders.cpp, src/gui/owncloudgui.cpp, src/gui/settingsdialog_mac.mm, src/gui/socketapi/socketapi.cpp, src/libsync/propagateuploadtus.cpp, src/libsync/syncresult.cpp, src/libsync/syncresult.h, src/libsync/theme.cpp, src/libsync/theme.h, test/testutils/testutils.cpp
Fixes #9043 among others.
Unfortunately, formatting of nested function calls and constructions of `QVariantMap`s has degraded. We may have to invest some time into adapting our clang-format config.
=> Unify enum handling with generic utility function templates

src/gui/accountstate.h, src/gui/activitywidget.cpp, src/gui/activitywidget.h, src/gui/models/activitylistmodel.cpp, src/gui/models/activitylistmodel.h, src/gui/owncloudgui.cpp, src/gui/settingsdialog.cpp, src/gui/settingsdialog.h
I debugged a bit more and it turned out that the activitywidget.cpp class was keeping a reference to the shared pointer.
This commit only cleans the internal state which was previously guarded in the sender.
Testing: Please test removal of an account followed with interactions with the activities view.
=> Remove removed accounts from activitywidget.cpp

changelog/unreleased/10939, src/gui/owncloudgui.cpp
=> Don't display resume sync if no account is configured

changelog/unreleased/8360, src/cmd/cmd.cpp, src/gui/folder.cpp, src/gui/folder.h, src/libsync/syncengine.cpp, src/libsync/syncengine.h, test/testallfilesdeleted.cpp, test/testsyncvirtualfiles.cpp, test/testutils/syncenginetestutils.cpp
Instead of pausing the current sync we now abort the sync, ask the user and start a second sync
Fixes: #8360
=> If all files are removed on either sync side abort the sync

src/gui/main.cpp
Fixes: #10996
```
Usage: C:\CraftRoot\download\git\owncloud\owncloud-client\cmake-build-debug\bin\owncloud.exe [options] [<vfs file>]
ownCloud version 5.0.0-git
File synchronization desktop utility.
For more information, see https://www.owncloud.com
Options:
-?, -h, --help         Displays help on commandline options.
--help-all             Displays help including Qt specific options.
-v, --version          Displays version information.
-s, --show             Start with the main window visible, or if it is already running, bring it to the front. By default, the client launches in the background.
-q, --quit             Quit the running instance.
--logfile <filename>   Write log to file (use - to write to stdout).
--logdir <name>        Write each sync log output in a new file in folder. …
```
=> Update the description of the commandline switch `-s`

.drone.star
Similar to https://github.com/owncloud/core/pull/40857
Part of https://github.com/owncloud/enterprise/issues/5832
`cancel-previous-builds` pipeline won't work because PRs won't have `DRONE_TOKEN` exposed to them. So, removing them from the CI.
=> [CI] Remove PR-based special drone actions from CI

.drone.star
Similar to https://github.com/owncloud/core/pull/40857
Part of https://github.com/owncloud/enterprise/issues/5832
`cancel-previous-builds` pipeline won't work because PRs won't have `DRONE_TOKEN` exposed to them. So, removing them from the CI.
=> [CI][4] Remove special PR-based drone actions from CI

src/gui/issueswidget.cpp, src/libsync/configfile.cpp, src/libsync/configfile.h
There were two issues: first, the StatusSet was not initialised, thus containing random values. Second, no difference was made between an empty filter list, and an absent filter list (the latter would cause the filter to be reset). Both are fixed now.
Fixes: #10881
=> Fix persisting filter settings in activity tab

changelog/unreleased/8991, src/gui/CMakeLists.txt, src/gui/application.cpp, src/gui/generalsettings.cpp, src/libsync/CMakeLists.txt, src/libsync/platform.cpp, src/libsync/platform_win.cpp, src/libsync/theme.cpp, src/libsync/theme.h
This change also enables the crash reporter in the cmd client
Fixes: #10998
Issue: #8991
=> Fix crashreporter

changelog/unreleased/10751, src/gui/accountsettings.cpp, src/gui/accountsettings.h, src/gui/accountsettings.ui, src/gui/accountstate.cpp, src/gui/accountstate.h, src/gui/owncloudgui.cpp
=> Implement progress spinner after wizard

src/gui/folderman.cpp
When downgrading the client was supported, the folder setup could fail when a downgrade was detected and the user chose not to downgrade when asked. This is no longer the case, so the this change removes the unused error handling for failed folder setup.
Fixes: #11031
=> Fix folder setup

test/gui/shared/scripts/helpers/api/webdav_helper.py, test/gui/shared/steps/file_context.py, test/gui/shared/steps/server_context.py, test/gui/tst_addAccount/test.feature, test/gui/tst_deletFilesFolders/test.feature, test/gui/tst_moveFilesFolders/test.feature, test/gui/tst_sharing/test.feature, test/gui/tst_syncing/test.feature
This `Given` step implementation creates folder in the server.
Renamed step:
```diff
-Given user "<user>" has created folder "<folderName>" on the server
+Given user "<user>" has created folder "<folderName>" in the server
```
=> [tests-only] [full-ci] Given step implementation for creating folder in the server

test/gui/shared/scripts/helpers/api/webdav_helper.py, test/gui/shared/steps/server_context.py, test/gui/tst_deletFilesFolders/test.feature, test/gui/tst_editFiles/test.feature, test/gui/tst_moveFilesFolders/test.feature, test/gui/tst_sharing/test.feature
This `Given` step implementation uploads file with some contents in the server.
Renamed step:
```diff
-Given user "<user>" has uploaded file with content "<content>" to "<fileName>" on the server
+Given user "<user>" has uploaded file with content "<content>" to "<fileName>" in the server
```
=> [tests-only] [full-ci] Upload file in server

src/libsync/platform_mac.mm
We tried to log when we got a `kIOMessageSystemWillPowerOn`, which could cause errors. This notification is not useful to us, so just don't log anything. The notification `kIOMessageSystemHasPoweredOn` is useful, and we log that, so that should be sufficient.
=> Fix power notification handling on macOS

src/gui/folderwizard/folderwizard.cpp, src/gui/folderwizard/folderwizardselectivesync.cpp, src/gui/selectivesyncwidget.cpp, src/gui/selectivesyncwidget.h
Closes https://github.com/owncloud/client/issues/10596.
=> Allow selective sync of spaces in folder wizard

src/gui/newwizard/enums.h, src/gui/newwizard/pages/accountconfiguredwizardpage.cpp, src/gui/newwizard/pages/accountconfiguredwizardpage.h, src/gui/newwizard/setupwizardaccountbuilder.cpp, src/gui/newwizard/setupwizardaccountbuilder.h, src/gui/newwizard/setupwizardcontroller.cpp, src/gui/newwizard/setupwizardcontroller.h, src/gui/newwizard/setupwizardcontroller_p.h, src/gui/newwizard/states/accountconfiguredsetupwizardstate.cpp
Fixes #10680.
This PR makes sure to "unhide" the advanced settings whenever the selected/default sync root is unavailable (tested with `/dev/null`). It also remembers the user's last input, initializing the sync root with a default value only once, allowing users to easily edit their last value.
Note: this does _not_, in any way, block the Finish button. We never live-check such data anywhere else (e.g., checking "can we login already", asking upon every single button press to enable the button only once it works). It's by design to run more advanced checks when the user clicks on "Next" resp. "Finish".
=> Handle "selected sync destination is unusable" case better in setup wizard

src/gui/folder.cpp, src/gui/folderman.cpp
The feature that this settings group relates to is not supported for quite some time.
Fixes: #9117
=> Remove saving of legacy `Multifolders` settings entry

src/common/utility.cpp, src/gui/updater/ocupdater.cpp, src/gui/updater/ocupdater.h, test/testutility.cpp
In order to notify users of the traditional Linux packages (which are usually updated by the package managers as they are shipped from repositories and therefore lack integrated updater), the updater regularly called itself with `--version` to recognize whether its own version changed (i.e., the package was updated in the background while the client was running).
Due to a change in the commandline parsing, this approach no longer works as `--version` is evaluated only after KDSingleApplication was initialized, causing the client to terminate after a few seconds and therefore rendering it unusable.
The new approach focuses on the application binary's `mtime`. Whenever it changed compared to the timestamp we initially saved when the client started, we assume the binary has changed, i.e., …
=> Fix KDSingleApplication related startup bug

src/gui/settingsdialog.cpp
For single account: the add button is removed, place the account tab as the first item. For multi account: we keep the add button on the left, but place the account(s) right after the add button.
Fixes: #10986
=> Fix tab order in settings window for single account clients

src/gui/main.cpp
The lambda was returning a QStringBuilder and casting it to QString when its content was out of scope.
=> Fix QStringBuilder crash 10976

owncloudcmd.desktop.in
Ubuntu does not show the full application name which leads to confusion, and the application is not interactive either.
=> Hide owncloudcmd from app menu on Linux

.github/workflows/main.yml
The output has limited use for now and slows down the build enormously.
=> Ci: Don't run clang tidy on pr

changelog/unreleased/10351, src/gui/accountstate.cpp
I don't think this was the original looping issue but a new one introduced with the connecting state in 4.0
Fixes: #10351
=> Fix the login dialog appearing for logged out accounts

src/gui/accountsettings.cpp, src/gui/scheduling/syncscheduler.cpp
The current code would schedule the folder before its ready and thus trigger an assert.
=> Folders will shedule themselves after vfs changed

test/testsyncconflict.cpp
This reverts commit ba694ebdef2f764757f2619e363511231d5ce856.
Requires: https://github.com/owncloud/client-desktop-vfs-win/pull/60
For ci see https://github.com/owncloud/client-desktop-vfs-win/actions/runs/5830681201
=> Revert "Fix test for VFS with dehydrated placeholders"

src/gui/issueswidget.cpp, src/libsync/syncfileitem.h
The GUI uses this to display and filter status messages. To make sure we have all displayable status items listed, they are now in `SyncFileItem` together with a static assert to check we covered all items. This should make adding/removing status items less error-prone.
Fixes: #10960
=> Make SyncFileItem::Status more robust to changes

src/gui/folder.cpp, src/gui/folder.h, src/gui/folderman.cpp, src/gui/folderman.h, src/gui/folderstatusmodel.cpp, src/gui/folderwizard/folderwizard.cpp, src/gui/folderwizard/folderwizard.h, src/gui/folderwizard/folderwizard_p.h, src/gui/folderwizard/spacespage.cpp, src/gui/folderwizard/spacespage.h, src/gui/owncloudgui.cpp, src/gui/scheduling/etagwatcher.cpp, src/gui/spaces/spacesbrowser.cpp, src/gui/spaces/spacesmodel.cpp, src/gui/spaces/spacesmodel.h, src/libsync/graphapi/spacesmanager.h, test/testspacesmigration/testspacesmigration.cpp, test/testutils/testutils.cpp
Ideally we would no longer need to store the webdav url for spaces, but while the client is starting up or we are offline when starting the client, we don't have the relevant information available.
Fixes: #10936
=> Add space id to folder and use it

src/gui/folderman.cpp, test/testfolderman.cpp
If the default folder name exists, a different one was offered in the form of "ownCloud2". This is now changed to follow the ownCloud convention, and "ownCloud (2)" is now offered.
=> Change local collision to follow the ownCloud convention

src/gui/folder.cpp
The client used to emit a file changed event for every single change. In order to prevent pointless syncs it delayed the sync by 2s. This created a QTimer for every singe change.
Since 5.0 we gather changes for 10s and only then handle the changes, so no delay should be needed anymore.
=> Don't start a timer per changed file

src/gui/application.cpp, src/gui/application.h, src/gui/folderman.cpp, src/gui/folderman.h, src/gui/main.cpp
The check is done after the application constructor is run. In this constructor, a couple of signals get fired, which in turn queues showing the GUI window (e.g. an account is logged out, and needs new authentication). When the version check fails, it brings up a (modal) dialog, and the event loop is spun, which also brings up the GUI window. Somewhere halfway this, the quit button is clicked, tearing down the application with a half-way set up window. This causes a crash somewhere deep in a child-widget-deletion process.
The fix is to move even more out of the application constructor, so the full check can be done before any other GUI code is run. This comes down to setting up the account manager and the folder manager in the main function.
Fixes: #11135
=> Fix crash when database version check fails

changelog/unreleased/10919, src/gui/folderwizard/folderwizard.cpp, src/gui/newwizard/setupwizardaccountbuilder.cpp, src/libsync/account.cpp
Creating the default sync root is only needed at initial setup. If a user chooses to point all folders for Spaces outside that default sync root, and deletes the default sync root folder, it should not be re-created.
Fixes: #10919
=> Do not create default sync root when loading accounts

src/gui/main.cpp
Flags like -h need to be handled in the new instance not in the main instance.
Fixes: #11151
=> Parse command line before handing single application

.drone.star
Updated the build trigger branch to 5. This will enable tests in nightly which is currently skipped. See https://drone.owncloud.com/owncloud/client/16501
=> [ci] update the trigger branch to 5 for CI

src/gui/settingsdialog.cpp, src/gui/settingsdialog.h
Steps to reproduce:
- single account branding
- once an account is added, the activity page is selected instead of the account.
With this change always the first account will be selected by default.
=> Correctly select the first account when multiAcc is off

test/gui/tst_syncing/test.feature
Changed `Then` step 
```diff
-Then the content of file "<fileName>" for user "Alice" should be "<content>" on the server
+Then as "<user>" the file "<fileName>" should have the content "<content>" in the server 
```
=> [tests-only] [full-ci] Changed remaining `Then` step for checking file content

src/libsync/theme.cpp
```
ownCloud 5.0.0-git [c8c2d9](https://github.com/owncloud/client/commit/c8c2d927da5bb3ce88ce9eee620e5b659f13667d)
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: wincfapi
windows-10.0.22621
```
```
ownCloud 5.0.0-git [c8c2d9](https://github.com/owncloud/client/commit/c8c2d927da5bb3ce88ce9eee620e5b659f13667d)
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: wincfapi
OS: windows-10.0.22621
QPA: windows
```
On linux this will tell us whether wayland or xcb is used.
=> Add qpa info to version info

src/gui/main.cpp
We now do a backup of the config file for any version change of the client, not only when the major version changes.
We do still allow downgrades as long as the major version does not change.
Fixes: #10789
=> Create config file backup for any version change

changelog/unreleased/8216
=> Add changelog for #8216

src/gui/folderman.cpp, src/gui/folderman.h, src/gui/folderwizard/folderwizard.cpp
After changes to `FolderWizardPrivate::initialLocalPath`, the non-spaces case was returning the default sync root, not a new path.
Fixes: #11231
=> Fix "Add sync folder" using an existing invalid location

test/gui/shared/scripts/pageObjects/AccountSetting.py, test/gui/shared/steps/account_context.py
This pr modifies the step for asserting the connection of account to the server by waiting for 5000ms(default) if the element is not found.
`
Then user "Alice" should be connect to the client-UI
`
Fixes https://github.com/owncloud/client/issues/11217
=> [tests-only] [full-ci] Fix test for assertion of account connection by waiting for element if not found 

shell_integration/MacOSX/OwnCloudFinderSync/OwnCloudFinderSync.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
This "update" is adding a file that xcode uses to mark that the 32bit check has been performed. When missing, the file is re-created every time the project is opened.
There is no functional change.
=> macOS: update xcode project

changelog/unreleased/11245, src/gui/application.cpp, src/gui/application.h, src/gui/main.cpp
This option was used before the UI language could be chosen in the settings.
Fixes: #11245
Todo: changelog entry
=> Remove unused command line option `--language`

src/gui/accountsettings.cpp
When the account state was disconnected from an oCIS server, the button would show "Add Folder" instead of "Add Space". This also fixes the tooltip of the button.
Fixes: #11230
=> Fix "Add Space" button text in disconnected state

changelog/unreleased/11288, src/gui/main.cpp, src/gui/socketapi/socketapi.cpp, src/gui/socketapi/socketapi.h
The shell integration was started while the folder manager was being instantiated. It could happen that callbacks came in when this was not yet completed, resulting in a crash when calling back into the (incomplete) folder manager.
Now shell integration is started after all other startup work has been completed.
Fixes: #11280
=> Fix possible crash when starting shell integration

.github/workflows/.craft.ps1
Craft has issues with python3.12 which are fixed upstream, we however pinned the craft revision.
=> Ci: Github actions use python 3.11 for now

test/gui/shared/scripts/helpers/SetupClientHelper.py, test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py, test/gui/shared/steps/file_context.py, test/gui/shared/steps/sync_context.py, test/gui/tst_syncing/test.feature
Added test scenario for configuring synchronization manually between remote folders(with special character in the folder name) with the local folder(also with special character in its folder name).
=> [tests-only] [full-ci] GUI test for manually syncing remote folder with special character

test/gui/envs.txt, test/gui/shared/scripts/helpers/ConfigHelper.py, test/gui/shared/scripts/helpers/SetupClientHelper.py, test/gui/suite.conf
`--confdir` option is deprecated and about to be removed in https://github.com/owncloud/client/pull/11300.
So, squish tests makes use of `XDG_CONFIG_HOME` env to set custom config location (i.e. `/tmp/owncloudtest/`) for owncloud during the test execution
NOTE: env `XDG_CONFIG_HOME` is only available for the AUT context so not available for the squish and test script
~NOTE: we have to come up with something for running tests locally with Squish.~
~**WARN: NOT RECOMMENDED to run gui-tests on local machine (doing so will remove existing client configs)**~
=> [gui-tests][full-ci] use `XDG_CONFIG_HOME` with custom location for AUT during squish tests

test/gui/shared/scripts/names.py, test/gui/shared/scripts/pageObjects/Settings.py, test/gui/shared/scripts/pageObjects/Toolbar.py, test/gui/shared/steps/server_context.py, test/gui/shared/steps/sync_context.py, test/gui/tst_checkAlltabs/test.feature
Added test scenario for verifying options of `Settings Tab`
**General Settings**
Checkboxes:
-   Launch on System Startup
-   Use Monochrome Icons
-   Show Desktop Notifications
-   Language option
**Advanced**
Checkboxes:
- Show sync folders in Explorer's Navigation Pane (Windows) :x: 
- Sync hidden files
- Show crash reporter :x: 
Buttons:
- Edit Ignored Files - opens Ignored files dialog
- Log Settings
Non VFS mode checkboxes:
- Ask for confirmation before synchronizing folders larger than 500 MB
- Ask for confirmation before synchronizing external storages
**Network**
- Proxy Settings
- Download Bandwidth
- Upload Bandwidth sections
**Version**
- Updates section (Channels are only available in testpilotcloud and on Mac we don't have the update info section)
- About button - opens …
=> [tests-only] [full-ci] add test for verifying options of settings tab

changelog/unreleased/11347, src/gui/folder.cpp, src/gui/folderwatcher.cpp, src/gui/folderwatcher.h
Since 5.0 we accumulate changes for 10s, include accumulated changes when starting a sync.
=> Include recent change events in local discover

src/common/utility.cpp, test/testutility.cpp
It is replaced by `QLocale::formattedDataSize`.
=> Remove custom data size formatting

src/common/utility.cpp, src/common/utility.h, src/common/utility_mac.mm, src/gui/updater/updater.cpp, src/libsync/theme.cpp
This PR uses a syscall to properly detect whether the application is running inside of macOS's rosetta2 emulator. It replaces uses of `QSysInfo::currentCpuArchitecture()` with a custom in our code.
It further extends the about dialog to show the detected build and CPU architectures.
This is a preparation for #10757.
Please note that the formatting changes are forced by clang-format. I'm not a fan of them.
=> Fix current CPU architecture detection with rosetta2

test/gui/tst_addAccount/test.feature, test/gui/tst_vfs/test.feature
In this pr GUI tests related to suffix vfs are skipped but not removed as those tests might work for Windows.
Related pr: https://github.com/owncloud/client/pull/11365
Part of https://github.com/owncloud/client/issues/11393
=> [tests-only] [full-ci] skip GUI tests related to suffix vfs

src/libsync/discovery.cpp
Also slightly improve the message by removing "handling" (as the adjective "unhandled" is also used).
=> Fix typo in error string

src/gui/folderwizard/folderwizardsourcepage.ui
The styling caused unreadable warning/error messages when the OS theme was set to dark: the text color would be white, but the background was styled to be white too.
The message is still noticable: normally there is no text in the label, so an error or warning message showing up will be noticed.
Fixes: https://github.com/owncloud/client/issues/11243
=> Remove styling from the warning label in the "Add Folder" dialog

src/gui/accountsettings.cpp, src/gui/folder.cpp, src/gui/folder.h
With the previous implementation it was possible that we started to swap the back end while a sync was running.
This change ensures that 
- the current sync is aborted
- the sync is paused
- the backend is switched
- the sync is unpaused
- we sync
For testing please start a sync (an upload with throttling enabled) and disable/enable vfs.
Things to watch out for.
- Selective sync
- dehydrated files
=> Fix switching vfs during a sync

test/gui/shared/scripts/helpers/api/webdav_helper.py, test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py, test/gui/shared/steps/server_context.py, test/gui/shared/steps/sync_context.py, test/gui/tst_syncing/test.feature
Refactored test scenario to cover the test cases related to selective sync with oc10 server:
1. Verify that the subfolders that you unselect are not synced
2. Upload some files from the server in a folder which is selected to be synced
3. Upload some files from the file explorer in the synced folder
4. Upload some files from the server in a folder which is not synced
5. Delete a synced folder from the file explorer
6. Delete a synced folder from the server
7. Verify that when you unselect all the folders, the root files continue to sync
Related Issue: https://github.com/owncloud/QA/issues/789
=> [tests-only] [full-ci] test for uploading file in remote folder with selective sync

src/gui/updater/updater.cpp
This will allow us implementing some additional logic in the update server to prevent updates on now-incompatible products and give users better feedback in such situations.
Fixes #11328.
=> Send kernel and OS version information to update server

src/gui/folder.cpp, src/gui/folder.h
=> Make account saving as atomic as possible

src/gui/MacOSXBundleInfo.plist
We sign our updates with both EdDSA and classic DSA now to
1. allow seamless upgrades for 5.x and before to the new versions (they should already support EdDSA but don't know the key, hence using DSA along with EdDSA allows them to build a chain of trust; once on 6.x, they will be using EdDSA anyway)
1. allow 6.x+ to update to newer versions (Sparkle in there rejects DSA and demands EdDSA, so that's fixed by now)
Sparkle looks up the key in the bundle's `Info.plist`, so we need to add it to that file. Then, upgrades on 6.x should work smoothly.
To test:
1. test an upgrade from 5.x and before (I suggest 5.2.0 and the latest 4.x release) to 6.x using our force-update server
1. test an upgrade from 6.x using our force-update server
=> Add new EdDSA pubkey to Info.plist

.drone.star
`skipOnOC10` tag was also append to the ocis pipeline which is not right and that skipped the spaces test suite in ocis. This PR fixes the skip tags. And the space suite is running for ocis pipeline
=> [full-ci] fix: skipOnOC10 tag also appended in ocis pipeline

test/gui/shared/scripts/helpers/FilesHelper.py, test/gui/shared/steps/vfs_context.py, test/gui/tst_vfs/test.feature
This PR extends the scenario for `Disable/Enable VFS` in windows to verify that the dehydrated file are present after disabling VFS. 
Added test coverage for https://github.com/owncloud/client/issues/11331
=> [gui-tests][full-ci] Assert the presence of dehydrated file after VFS disabled

test/gui/shared/scripts/helpers/FilesHelper.py, test/gui/shared/scripts/pageObjects/SyncConnection.py, test/gui/shared/steps/sync_context.py, test/gui/shared/steps/vfs_context.py, test/gui/tst_vfs/test.feature
Refactored the test scenario to cover the test cases related to VFS and selective sync in Windows:
1. Verify when VFS is on, user cannot select folders for selective sync
2. Unselect a folder in selective sync and Turn on VFS
3. Turn off VFS
=> [gui-tests][full-ci] Vfs and selective sync

changelog/unreleased/11467, src/gui/connectionvalidator.cpp, src/gui/fetchserversettings.cpp, src/gui/fetchserversettings.h
Properly handle errors during the update of the server settings. Due to an unhandled result, the client could get stuck in a ` reconnecting` state.
=> Properly handle ConnectionValidator error

src/gui/networksettings.cpp
On platforms where metered connection detection is not available, hide the checkbox instead of disabling it.
Fixes: #11471
=> Hide pause-sync-when-metered ceckbox when not supported

test/testutils/syncenginetestutils.cpp, test/testutils/syncenginetestutils.h
This is something that came up while I wrote https://github.com/owncloud/client/pull/11469.
I used a delayed response with a fake job that did not properly implement abort and was a bit suprised.
=> Properly abort Fake jobs in tests

changelog/unreleased/11478, src/gui/accountsettings.cpp, src/gui/accountsettings.h, src/gui/creds/httpcredentialsgui.cpp, src/gui/creds/httpcredentialsgui.h
This fixes a bug where askFromUser did not display a ui and the client got stuck in reconnecting
=> Move OAuth dialog to HttpCredentialsGui

src/gui/folder.cpp
In a few error scenarios (out-of-memory or out-of-space), the folder watcher on Linux shows a dialog with an error message. If this occurs during start-up before the GUI is initialised, this will lead to a crash.
This is fixed by delaying the VFS start until after event loop is started, guaranteeing that the GUI is up and running.
Fixes: #11460
=> Fix early-use crash in folder watcher on Linux

src/gui/accountsettings.cpp, src/gui/accountsettings.ui, src/gui/folderwizard/folderwizardremotepath.cpp, src/gui/folderwizard/folderwizardtargetpage.ui, src/gui/logbrowser.cpp, src/gui/logbrowser.ui
Some error messages were styled in a way that is not compatible with dark mode. These have now been replaced by unstyled labels, but the warning icon is shown to the left of the message.
Fixes: #11412
=> Fix badly styled warning/error messages

test/gui/shared/steps/file_context.py, test/gui/tst_vfs/test.feature
Added test scenario to cover test cases: 
| Test case | Expected Result |
---|---
| Create a new file | New file has been added and synced but is not virtual |
| Copy and paste a file | Placeholder file gets downloaded and it has been copied |
=> [tests-only] [full-ci] File operations on virtual file

.drone.star
>(and we could disable the changelog generation from the nightly build, it runs on every commit to master)
Changelog pipeline runs on every commit to master so disabling changelog pipeline for nightly builds.
=> ci: disable changelog pipeline for cron builds

test/gui/shared/scripts/bdd_hooks.py, test/gui/shared/scripts/helpers/SetupClientHelper.py, test/gui/shared/scripts/pageObjects/AccountSetting.py, test/gui/shared/steps/account_context.py, test/gui/shared/steps/sharing_context.py, test/gui/tst_sharing/test.feature, test/gui/tst_syncing/test.feature
Updated the account cleanup script to work for client versions ^5 and ^6
Tested in:
- Linux (5 and 6) :heavy_check_mark: 
- Windows (5 and 6) :heavy_check_mark: 
- CI (5) https://drone.owncloud.com/owncloud/client/17650 :heavy_check_mark:
=> [gui-tests][full-ci] Update account cleanup via UI for client 5 and 6

test/gui/shared/steps/file_context.py, test/gui/tst_vfs/test.feature
Added test scenario to cover test cases: 
| Test case | Expected Result |
---|---
| 1. Copy and paste a file inside a folder | Placeholder file gets downloaded and it has been copied both in file system and in the server |
| 1. Move a virtual file to temp folder <br> 2. Move a virtual file inside a folder | Virtual as well as the physical file on the server have been moved |
=> [tests-only] [full-ci] Test coverage for files operations on virtual file

test/gui/shared/steps/account_context.py
Added a wait for sync task completion after an account has been added via UI
- Closes https://github.com/owncloud/client/issues/11503
=> [gui-tests][full-ci] wait for sync completion after adding account

test/gui/tst_checkAlltabs/test.feature
Removed gui tests related advanced settings which were removed in https://github.com/owncloud/client/pull/11517
Closes https://github.com/owncloud/client/issues/11520
=> [gui-tests][full-ci remove test for sync related advanced settings

changelog/unreleased/11497, src/gui/newwizard/states/serverurlsetupwizardstate.cpp
Authentication is done through the web browser, so no user information is needed for that URL.
Fixes: #11497
=> Strip user info from URL in New Connection Wizard

test/gui/tst_vfs/test.feature
Added test scenario related to VFS and Selective sync:
| Switch between VFS and selective sync quickly | It works, no errors |
--|--
=> [tests-only] [full-ci] Switch between VFS and selective sync quickly

test/gui/shared/steps/file_context.py, test/gui/tst_vfs/test.feature
Added step to copy and paste a virtual file in the same location by creating its copy with ` - Copy` suffix in file name.
| Copy a virtual file and Paste it at the same location | File browser asks or creates a copy |
---|---
=> [tests-only] [full-ci] Add test coverage to copy and paste virtual file in same location

.drone.star
Changed notification channel from `desktop-internal` of `chat.owncloud.com` to `desktop-ci` of `talk.owncloud.com`. 
Closes https://github.com/owncloud/client/issues/11536
=> [tests-only] Move notification to desktop-ci channel of talk.owncloud

changelog/unreleased/11531, src/gui/tlserrordialog.cpp
=> Make 'No' button default in Unknown Certificate dialog

test/gui/tst_sharing/test.feature
Dates are different locally and CI environment so, we have to come up with better ways to assert the dates in different environment, For now skipping this tests.
=> [gui-test] [full-ci] Skip sharing with expiration tests

test/gui/shared/scripts/helpers/SpaceHelper.py, test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py, test/gui/shared/steps/file_context.py, test/gui/shared/steps/sync_context.py, test/gui/tst_sharing/test.feature, test/gui/tst_syncing/test.feature
Fix the scenario and test code, and unskip tests
=> [gui-tests][full-ci] unskip GUI tests

src/gui/folderman.cpp, src/gui/folderman.h, src/gui/folderwizard/folderwizard.cpp, src/gui/folderwizard/folderwizardlocalpath.cpp, src/gui/guiutility.cpp, src/gui/guiutility.h, src/gui/newwizard/setupwizardaccountbuilder.cpp, src/gui/newwizard/states/accountconfiguredsetupwizardstate.cpp, src/gui/owncloudgui.cpp, test/testfolderman.cpp
=> Fix check for creation of a spaces folder in a spaces root

changelog/unreleased/enterprise-6390, src/gui/folderman.cpp
This partly reverts 97192194bd38e1be0824bb5db73842b4387f8f1b and the behavor introduced in 3.0
=> Revert sync folder name back to appName

changelog/unreleased/11581, src/libsync/httplogger.cpp
During a debugging session, I discovered that the client can send the same request multiple times if the redirect is directly handled by Qt.
This wasn't discovered previously as we disallow redirects for most requests.
```
24-04-08 16:59:13:604 [ info sync.httplogger ]:	REQUEST 697f9664-e926-4569-be6c-5c2c228010cf {"request":{"body":{"length":0},"header":{"Accept":"*/*","Accept-Language":"en_DE","Authorization":"Basic [redacted]","Original-Request-ID":"697f9664-e926-4569-be6c-5c2c228010cf","User-Agent":"Mozilla/5.0 (Windows) mirall/6.0.0-git (ownCloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","X-Request-ID":"697f9664-e926-4569-be6c-5c2c228010cf"},"info":{"cached":false,"id":"697f9664-e926-4569-be6c-5c2c228010cf","method":"GET","url":"https://download.owncloud. …
```
=> HttpLogger: Log redirects

src/gui/accountsettings.cpp, src/gui/accountsettings.h, src/gui/settingsdialog.cpp
Since we don't display the selective sync in the folder view we don't need to reset it on tiny changes.
=> Remove folderChanged signal

src/gui/owncloudgui.cpp
When a new account has been created, make sure that the settrings page is showing the page for this new account.
Fixes: #11642
=> Focus settings page for new accounts

src/gui/generalsettings.ui, src/gui/networksettings.cpp, src/gui/networksettings.ui
- buddies
- accessibility names
- tab order
- fix label text so screen readers produce something useful
Fixes: #11636
=> Fix accessibility issues in settings tab

src/gui/activitywidget.cpp, src/gui/protocolwidget.ui
This makes the purpose more clear to users, and removes the need for the label above the table. In case of oc10, it also makes the difference clear between this tab and the "Server Activity" tab.
The table itself now also has an a11y name.
Fixes: #11637
=> Rename "Local sync protocol" tab in activity view to "Local Activity"

src/gui/updater/CMakeLists.txt, src/gui/updater/newversionavailabledialog.cpp, src/gui/updater/newversionavailabledialog.h, src/gui/updater/newversionavailabledialog.ui, src/gui/updater/ocupdater.cpp, src/gui/updater/ocupdater.h, src/gui/updater/updatedownloadeddialog.cpp, src/gui/updater/updatedownloadeddialog.ui
=> Adopt Update dialogs to the new modal widget experience

changelog/unreleased/11646, src/libsync/creds/oauth.cpp, src/libsync/creds/oauth.h, test/testoauth.cpp
Historically the client used both basic auth and the post body to provide the client id and secret. Some idp's however are picky and only accept one.
=> OAuth: Only use one auth methode

src/gui/newwizard/setupwizardwindow.cpp, src/gui/newwizard/setupwizardwindow.h
Wizards on all platforms do not react to enter keys when buttons do not have focus.
=> Remove event handler from setup wizard

src/gui/qmlutils.h, src/gui/settingsdialog.cpp, src/gui/settingsdialog.h
This macro exposes focusNext and focusPrevious, which can be called from qml
=> Introduce OC_DECLARE_WIDGET_FOCUS

src/gui/activitywidget.cpp, src/gui/activitywidget.ui
The notifications are now shown in a group box named "Notifications", and the server activities are shown in another group box named "Server Activities". The labels have been removed, as the group box titles take their role.
The tab order has also been fixed.
=> Fix a11y issues in "Server Activities" tab

test/gui/shared/scripts/helpers/SetupClientHelper.py, test/gui/shared/scripts/names.py, test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py, test/gui/shared/steps/sync_context.py, test/gui/tst_syncing/test.feature
Added test for adding a folder in remote destination to sync.
- https://github.com/owncloud/client/issues/11653
=> [gui-tests][full-ci] added tests for adding folder to sync

test/gui/shared/scripts/pageObjects/Activity.py
Added a short wait for all activity tabs to render correctly.
Fixes CI flakineses:
- https://drone.owncloud.com/owncloud/client/18582/2/16
- https://drone.owncloud.com/owncloud/client/18584/2/16
=> [gui-tests][full-ci] wait for tabs to render completely

test/gui/webUI/pnpm-lock.yaml
The pnpm-lock file was not updated which caused pnpm to look for different browser version during GUI test
Updated the lock file so that GUI test code can find the correct browser version.
Fixes https://github.com/owncloud/client/issues/11716
=> [gui-test][full-ci] update pnpm lock file

test/gui/shared/scripts/names.py, test/gui/shared/scripts/pageObjects/SyncConnection.py, test/gui/shared/steps/account_context.py, test/gui/shared/steps/sync_context.py, test/gui/tst_syncing/test.feature
This PR, adds GUI tests to remove the synced folder connection.
- https://github.com/owncloud/client/issues/11653
=> [gui-tests][full-ci] add gui test to remove folder sync connection

.drone.star
Updated drone config for new smaller squish image.
REQUIRES https://github.com/owncloud-ci/squish/pull/58
=> [ci][full-ci] update config to use new smaller squish image

test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py, test/gui/shared/steps/sync_context.py, test/gui/tst_syncing/test.feature
This PR updates the step
```feature
Then the folder "test-folder" should be present and selected in the remote destination wizard
```
to
```feature
Then the folder "test-folder" should be present in the remote destination wizard
```
Checking whether the folder is selected or not seemed to be flaky because of the timing issue for folder to be selected, so only checking the presence of the folder in the remote destination wizard.
=> [gui-tests][full-ci]update step to only check if the local folder is present in the remote destination wizard

test/gui/shared/steps/sync_context.py, test/gui/tst_syncing/test.feature
This PR adds the step to navigate and check the contents in `Sync Protocol` tab in Activity tab.
- https://github.com/owncloud/client/issues/11653
=> [gui-tests][full-ci]add test to check the sync activity in Sync Protocal tab

test/gui/shared/scripts/helpers/SetupClientHelper.py, test/gui/shared/scripts/helpers/SpaceHelper.py, test/gui/shared/scripts/pageObjects/EnterPassword.py, test/gui/shared/steps/account_context.py, test/gui/shared/steps/spaces_context.py, test/gui/tst_removeAccountConnection/test.feature
Added a step that adds multiple user accounts (of current server).
```feature
And the user has set up the following accounts with default settings:
| Alice |
| Brian |
```
=> [gui-tests][full-ci] Add multiple accounts in a single step

src/gui/updater/CMakeLists.txt, src/gui/updater/newversionavailablewidget.cpp, src/gui/updater/newversionavailablewidget.h, src/gui/updater/newversionavailablewidget.ui, src/gui/updater/ocupdater.cpp, src/gui/updater/ocupdater.h, src/gui/updater/updatedownloadedwidget.cpp, src/gui/updater/updatedownloadedwidget.h, src/gui/updater/updatedownloadedwidget.ui
Both are not based on QDialog anymore, but on QWidget. This rename removes confusion about the nature of the classes.
=> Rename two sets of files from ...Dialog to ...Widget

src/common/preparedsqlquerymanager.h
The file is included indirectly in many places, so this one semmicolon produced lots of warnings.
=> Fix GCC warning about "extra ‘;’"

test/gui/envs.txt, test/gui/shared/scripts/bdd_hooks.py, test/gui/shared/scripts/helpers/ConfigHelper.py, test/gui/shared/scripts/helpers/FilesHelper.py, test/gui/shared/scripts/helpers/SetupClientHelper.py, test/gui/shared/scripts/names.py, test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py, test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py, test/gui/shared/steps/account_context.py, test/gui/shared/steps/file_context.py, test/gui/shared/steps/sync_context.py, test/gui/tst_addAccount/test.feature
This PR adds the test coverage for adding the new existing account or folder and checking the addition of bracket with incremented number in it.
- https://github.com/owncloud/client/issues/11653
=> [gui-tests][full-ci] Added test for checking incremented number with bracket while adding new account and folder

owncloud.desktop.in
Fixed by setting the StartupWMClass in the `.desktop` file.
Fixes: #11625
=> Fix missing desktop/application icon with Wayland

changelog/unreleased/11752, src/gui/CMakeLists.txt, src/gui/qml/FolderDelegate.qml, src/gui/spaces/CMakeLists.txt, src/gui/spaces/qml/SpacesView.qml, src/gui/spaces/spaceimageprovider.h, src/gui/spaces/spacesbrowser.cpp, src/gui/spaces/spacesbrowser.h, src/gui/spaces/spacesmodel.cpp, src/gui/spaces/spacesmodel.h
Fixes: #11752
Depends on https://github.com/owncloud/client/pull/11758
=> 2: Hide synced spaces in spaces browser

test/gui/tst_addAccount/test.feature
Added test to check for synced spaces to be not listed in the sync connection wizard.
Test coverage for: https://github.com/owncloud/client/pull/11758 and https://github.com/owncloud/client/pull/11759
Fixes: https://github.com/owncloud/client/issues/11764
=> [gui-tests][full-ci] test for checking already synced spaces should not be listed in sync connection wizard

test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py, test/gui/shared/steps/sync_context.py, test/gui/tst_addAccount/test.feature, test/gui/tst_loginLogout/test.feature
This PR checks for the button to open sync connection wizard to be disabled when all the available spaces are already synced.
Test for: https://github.com/owncloud/client/pull/11760
Skipped the scenario: `Scenario: login, logout and restart with oauth2 authentication`
`@skip` tag will be removed after the fix in PR https://github.com/owncloud/client/pull/11761
=> [gui-tests][full-ci]add test to check for open connection sync button to be disabled

test/gui/Makefile
Fix the `pnpm-install-chromium` make target to install the correct browser
=> [gui-tests] install the correct browser

.drone.star
Skip failing `DatabaseErrorTest` ctest because the fix is yet to come. and we want unblock the gui test PRs.
Open issue: https://github.com/owncloud/client/issues/11784
> [!IMPORTANT]
> Revert this with the fix for #11784
=> ci: skip failing ctest

src/gui/generalsettings.ui
A few checkboxes and buttons still had keyboard shortcuts, while the majority didn't. This removes the last remaining ones: none of the settings is important enough to need shortcuts, and they can still be reached by keyboard using tab-navigation.
=> Remove remaining keyboard shortcuts from settings screen

src/gui/qml/FolderDelegate.qml, src/gui/spaces/qml/SpacesView.qml
VoiceOver on macOS will read both the accessible name *and* the accessible description. Setting both to the same value results in having the same text read twice. This is fixed by removing the accessible description.
Fixes: #11775
=> [a11y] Fix repeated text read by VoiceOver

src/gui/activitywidget.ui, src/gui/issueswidget.ui, src/gui/protocolwidget.ui
This allows users to tab out of the table views. Navigation inside the table can still be done with the arrow keys.
Fixes: #11789
=> Disable tabKeyNavigation in activity tables

test/gui/shared/scripts/helpers/api/Provisioning.py, test/gui/shared/scripts/helpers/api/oc10.py, test/gui/shared/scripts/helpers/api/ocis.py, test/gui/shared/steps/server_context.py, test/gui/tst_sharing/test.feature
This `Given` step implementation adds user to the group in the server.
Renamed step:
```diff
-Given user <user> has been added to group <group> on the server
+Given user <user> has been added to group <group> in the server
```
=> [test-only][full-ci] Given step implementation of adding user to the group in the server

changelog/unreleased/11774, src/gui/accountsettings.cpp, src/gui/accountsettings.h, src/gui/folderman.cpp, src/gui/folderman.h, src/gui/folderwizard/folderwizard.cpp, src/gui/folderwizard/folderwizard.h, src/libsync/theme.cpp, src/libsync/theme.h
For now, this can only be enabled through theming.
Fixes: #11751
=> Automatically add sync connections for new discovered spaces

changelog/unreleased/11533, changelog/unreleased/11567, src/gui/CMakeLists.txt, src/gui/accountsettings.cpp, src/gui/accountstate.cpp, src/gui/accountstate.h, src/gui/application.cpp, src/gui/connectionvalidator.cpp, src/gui/connectionvalidator.h, src/gui/folderman.cpp, src/gui/folderstatusmodel.cpp, src/gui/guiutility.cpp, src/gui/guiutility.h, src/gui/main.cpp, src/gui/networkinformation.cpp, src/gui/networkinformation.h, src/gui/networksettings.cpp, src/gui/owncloudgui.cpp, src/gui/scheduling/syncscheduler.cpp, src/libsync/jobqueue.h, test/testfoldermigration.cpp, test/testutils/testutils.cpp, test/testutils/testutilsloader.cpp
=> Stop synchronisation when behind a captive portal

src/libsync/account.cpp
If you have the same display name on multiple servers, you will now get different avatars.
=> Include server in avatar gradient computation

test/gui/shared/scripts/bdd_hooks.py, test/gui/shared/scripts/helpers/UserHelper.py, test/gui/shared/scripts/helpers/api/Provisioning.py, test/gui/shared/scripts/helpers/api/oc10.py, test/gui/shared/scripts/helpers/api/ocis.py, test/gui/shared/steps/server_context.py, test/gui/tst_activity/test.feature, test/gui/tst_addAccount/test.feature, test/gui/tst_checkAlltabs/test.feature, test/gui/tst_deletFilesFolders/test.feature, test/gui/tst_editFiles/test.feature, test/gui/tst_loginLogout/test.feature, test/gui/tst_moveFilesFolders/test.feature, test/gui/tst_removeAccountConnection/test.feature, test/gui/tst_sharing/test.feature, test/gui/tst_spaces/test.feature, test/gui/tst_syncing/test.feature, test/gui/tst_vfs/test.feature
This `Given` step implementation creates user in the server with default attributes and without skeleton files.
Renamed step:
```diff
-Given user <user> has been created on the server with default attributes and without skeleton files
+Given user <user> has been created in the server with default attributes and without skeleton files
```
=> [test-only][full-ci] given step implementation of creating user in the server

src/gui/generalsettings.ui, src/gui/networksettings.cpp
The network settings are now tab-selected before the about button.
Fixes: #11782
=> Fix tab order in settings page

changelog/unreleased/11810, src/gui/accountsettings.cpp, src/gui/accountsettings.ui
The URL in the status label of the account settings page was not always accessible by keyboard. The label will now only show the connection status, and the "Manage Account" button has a new entry for "Open in Web Browser".
=> [a11y] Move server URL from status label to Account button

src/gui/qml/FolderDelegate.qml, src/gui/spaces/qml/SpacesView.qml
On the desktop, list views do not bounce when reaching the top/bottom.
=> Disable bounce behaviour in list views

.drone.star
- Allow abort on failure for Squish tests in PRs (using `--abortOnFail` arg) - skips the next testcases if current fails
- With `full-ci` in the PR title, the above behavior is disabled
The `--abortOnFail` option is available only when using `--testsuite` option but does not work with `--testcase`.
>[--abortOnFail](https://doc.qt.io/squish/cli-squishrunner.html#playback-option-op-op-op-op-abortonfail)
>If the --abortOnFail option is specified, squishrunner will terminate the suite execution as soon as a failed test case is detected.
This means that if we have test cases 1, 2, 3 and 4, and test case no.2 failed then test cases 3 and 4 will not run. Also if the fail was in the first scenario of test case no.2, other scenarios of test case no.2 still continue to run.
Fixes: …
=> [gui-tests] abort testcase execution on first failure

test/gui/.pylintrc, test/gui/shared/scripts/helpers/api/sharing_helper.py, test/gui/shared/steps/server_context.py, test/gui/tst_sharing/test.feature
This `Given` step implementation shares file or folder in the server.
Renamed step:
```diff
-Given user "<user>" has shared file|folder <file|folder> on the server with user "<user>" with "<permission>" permission(s)
+Given user "<user>" has shared file|folder <file|folder> in the server with user "<user>" with "<permission>" permission(s)
```
=> [test-only][full-ci] Given step implementation of sharing file or folder in the server

src/gui/qml/FolderDelegate.qml, src/gui/spaces/qml/SpacesView.qml
When entering a ListView through tab navigation (both forward and backward), the selection should stay the same. The selection itself can be changed with the arrow keys.
=> Fix (back-)tabbing into ListViews

test/gui/.pylintrc, test/gui/Makefile, test/gui/shared/scripts/bdd_hooks.py, test/gui/shared/scripts/helpers/ConfigHelper.py, test/gui/shared/scripts/helpers/FilesHelper.py, test/gui/shared/scripts/helpers/ObjectHelper.py, test/gui/shared/scripts/helpers/SetupClientHelper.py, test/gui/shared/scripts/helpers/SpaceHelper.py, test/gui/shared/scripts/helpers/StacktraceHelper.py, test/gui/shared/scripts/helpers/SyncHelper.py, test/gui/shared/scripts/helpers/UserHelper.py, test/gui/shared/scripts/helpers/WebUIHelper.py, test/gui/shared/scripts/helpers/WinPipeHelper.py, test/gui/shared/scripts/helpers/api/http_helper.py, test/gui/shared/scripts/helpers/api/oc10.py, test/gui/shared/scripts/helpers/api/ocis.py, test/gui/shared/scripts/helpers/api/provisioning.py, test/gui/shared/scripts/helpers/api/sharing_helper.py, test/gui/shared/scripts/helpers/api/utils.py, test/gui/shared/scripts/helpers/api/webdav_helper.py, test/gui/shared/steps/file_context.py, test/gui/shared/steps/server_context.py
=> [gui-tests][full-ci] lint helper files

test/gui/shared/scripts/helpers/api/sharing_helper.py, test/gui/shared/steps/server_context.py, test/gui/tst_sharing/test.feature
This `Given` step implementation creates public link in the server.
Renamed step:
```diff
-Given user "<user>" has created a public link on the server with following settings
+Given user "<user>" has created a public link in the server with following settings
```
=> [test-only][full-ci] Given step implementation of creating public link in the server

test/gui/shared/scripts/helpers/api/sharing_helper.py, test/gui/shared/steps/server_context.py, test/gui/tst_sharing/test.feature
This `Given` step implementation shares file or folder with group in the server.
Renamed step:
```diff
-Given user "<user>" has shared file|folder <file|folder> on the server with group "<group>" with "<permission>" permission(s)
+Given user "<user>" has shared file|folder <file|folder> in the server with group "<group>" with "<permission>" permission(s)
```
=> [test-only][full-ci] Given step implementation of sharing resource with group in the server

test/gui/tst_sharing/test.feature
These `Then` step implementation asserts whether the given folder can be downloaded with or without password from the last created public link. Since the folder can not be downloaded, these steps are removed.
Removed step:
```diff
- Then the public should be able to download the folder "<folderName>" with password "<password>" from the last created public link by "<user>" on the server
- Then the public should be able to download the folder "<folderName>" without password from the last created public link by "<user>" on the server
```
=> [tests-only][full-ci] Then step implementation for downloading resource with(out) password 

src/gui/accountsettings.cpp
When a new account is added, the settings page for the account is created with the account in the disconnected state. At that point, it is not yet known if the server supports spaces, so there is no space manager yet, and the update signal is not connected. Moving the signal connect to `slotAccountStateChanged` for the `Connected` state fixes the issue.
Fixes: #11889
=> Fix count of synced spaces

src/gui/qmlutils.cpp
The `ocContext` in referenced from the QML side is deleted before the QML items (and their binding), resulting in access to a `null` context:
```
TypeError: Cannot read property 'currentPage' of null
```
Fixes: #11805
=> Fix QML warnings on application exit

src/gui/qml/AccountBar.qml, src/gui/qml/AccountButton.qml, src/gui/qmlutils.cpp, src/gui/qmlutils.h
This also fixes the display of disabled avatars
=> Properly use opacity instead of enabled icons

.drone.star, test/gui/shared/scripts/bdd_hooks.py, test/gui/shared/scripts/helpers/SetupClientHelper.py, test/gui/tst_loginLogout/test.feature
Check the keyring locked status and try to unlock it if locked during the test execution.
Fixes https://github.com/owncloud/client/issues/11883
Depends on: https://github.com/owncloud-ci/squish/pull/63
:x: Test fails because keyring can be locked during the test execution: https://drone.owncloud.com/owncloud/client/19470/1/10
```
--------------Scenario 1 (PASS)
LOG:   Start Scenario	login after logging out normal Account
LOG:   CompletedProcess(args=['busctl', '--user', 'get-property', 'org.freedesktop.secrets', '/org/freedesktop/secrets/collection/login', 'org.freedesktop.Secret.Collection', 'Locked'], returncode=0, stdout=b'b false\\n', stderr=b'')	
LOG:   b false\n
...
LOG:   End Scenario	login after logging out normal Account
--------------Scenario 2 (FAIL)
LOG:   Start Scenario	login …
```
=> [gui-tests][full-ci] check the keyring and try to unlock if locked

src/gui/owncloudgui.cpp, src/gui/owncloudgui.h, src/gui/sharedialog.h
=> Fix crash when multiple share dialogs were shown

test/gui/shared/scripts/helpers/api/sharing_helper.py, test/gui/shared/steps/server_context.py, test/gui/tst_sharing/test.feature
This `Then` step implementation checks if the public link share details is same
Renamed step:
```diff
-Then user "<user>" on the server should have a share with these details:
+Then user "<user>" should have a share with these details in the server :
```
=> [test-only][full-ci] Then step implementation of checking public link share details

src/gui/qml/credentials/OAuthCredentials.qml
When an item is in a layout, the width property is ignored, and the implicitWidth is used. So the copy-to-clipboard button's preferredWidth should be bound the implicitWidth property of the open-browser button.
Fixes: #11915
=> Fix button alignment in oauth screen

src/gui/qml/credentials/BasicAuthCredentials.qml
=> Fix textfield layout on basic auth credentials page

src/gui/qml/credentials/OAuthCredentials.qml
The DPI rate of pixmaps seems to be ignored by QML, resulting in double-sized icons when shown on a high-DPI screen. This limits the height of the buttons on the oauth login page, so the icon is not excessively large.
Fixes: #11928
=> Fix button sizes on high-DPI screens

src/gui/qml/AccountBar.qml
This fixes the issue where a (non-native) tooltip could be shown where the mouse cursor is positioned, which would block any clicks to go through to the button underneath.
Fixes: #11951
=> Use native tooltips for Navigation bar

src/gui/accountsettings.cpp, src/gui/folderman.cpp, src/gui/folderman.h, src/gui/folderwizard/folderwizard.cpp, src/gui/newwizard/states/accountconfiguredsetupwizardstate.cpp, src/gui/owncloudgui.cpp, test/testfolderman.cpp
The account UUID was not passed in, which resulted in a failed check when adding a space folder to a spaces root.
=> Fix `findGoodPathForNewSyncFolder`

src/gui/folder.cpp
Sometimes a `Folder` is created for a local path that we cannot sync (e.g. it's not writable). This folder will not have a sync engine. If the engine of this `Folder` is accessed, this will lead to a crash.
The fix is to check for the existance of a sync engine in the `Folder::canSync()` method.
Fixes: #11981
=> Fix crash when checking the sync file status

src/gui/main.cpp
During startup, sync was enabled before the UI was completely set up. This could lead to a crash when a sync error occurred, which would try to show it in the UI.
Fixes: #11988
=> Fix possible crash when a sync error early in startup

src/gui/folder.cpp
Sometimes a `Folder` is created for a local path that we cannot sync (e.g. it's not writable). This folder will not have a sync engine. If the engine of this `Folder` is accessed, this will lead to a crash.
The fix is to check for the existance of a sync engine in the `Folder::canSync()` method.
Fixes: #11981
=> [backport] Fix crash when checking the sync file status (#11982)

src/libsync/discovery.cpp, src/libsync/httplogger.cpp
This can be used to debug Unicode normalization/encoding issues.
=> Log percent-encoded URL/filename

src/libsync/creds/httpcredentials.cpp
Prevent the user being logged out when the network disappears during OAuth token refresh.
=> OAuth: Prevent logout when refreshing token

.craft.shelf
fix: https://github.com/DeepDiver1975/craft-blueprints-kde/commit/9be073decbb06b7425655806c4e57ccc85ea2117
=> fix: dbus to not install systemd files

.drone.star, test/gui/shared/scripts/helpers/SpaceHelper.py
Part of https://github.com/owncloud/ocis/issues/10373
=> [full-ci] ci: bump ocis version to 7

test/gui/shared/scripts/bdd_hooks.py, test/gui/shared/scripts/helpers/SetupClientHelper.py
Added keyring check before starting client. The check is done with multiple retries until a timeout is reached.
Fixes https://github.com/owncloud/client/issues/11883
THe problem with the mentioned issue was that sometimes the keyring service gets killed or disconnected in the middle of the test execution.
=> [gui-tests][full-ci] check keyring before starting client

src/common/utility_win.cpp, src/common/utility_win.h, src/csync/std/c_time.cpp
`Int32x32To64` macro internally truncates the arguments to int32, while `time_t` is 64-bit on most/all modern platforms. Therefore, usage of this macro creates a Year 2038 bug.
I detailed this issue a while ago in a writeup, and spotted the same issue in this repository when updating the list of affected repositories:
<https://cookieplmonster.github.io/2022/02/17/year-2038-problem/>
Note: I don't know if `src/csync/std/c_time.cpp` should be edited as part of this repository, or another upstream source. At the moment I included the necessary changes in this PR, but if this part of the PR needs to be directed elsewhere I'm happy to do so instead.
=> Fix a Y2038 bug by replacing `Int32x32To64` with regular multiplication

test/testutility.cpp
test in preparation for #12027
=> test: Utility::UnixTimeToLargeIntegerFiletime

test/CMakeLists.txt, test/testfilesystem.cpp
In preparation for adding more tests for `OCC::FileSystem`.
=> Rename `LongPathTest` to `FileSystemTest`

src/common/filesystembase.cpp, src/common/filesystembase.h, src/csync/std/c_time.cpp, src/csync/vio/csync_vio_local_unix.cpp, src/gui/socketapi/socketapi.cpp, src/libsync/propagatorjobs.cpp, test/testfilesystem.cpp, test/testlocaldiscovery.cpp, test/testutils/syncenginetestutils.cpp, test/testutils/syncenginetestutils.h
=> fix: bypass Qt's QFile::encodeName() in csync

CMakeLists.txt
Don't forget to manually remove the existing hook!
=> Stop installing clang-format as pre-commit hook

src/common/vfs.h
This is to inform/warn VFS implementors of the fact that starting the VFS implementation is assumed to possibly start in the background. But more importantly: the client will not "wait" for one VFS instance to be started before calling `start` on a second instance. Meaning: synchronization (when needed) has to be done by the VFS impementation itself.
=> Add important documentation on the async nature of `Vfs::startImpl()`

src/gui/qml/FolderError.qml, src/gui/spaces/qml/SpacesView.qml
This was the least destructive approach I could find.
also fixed the error message when it's "show less"
finally reverted the size change since we don't know if it fits, but kept the fix for collapsed error messages
=> Fixed the Folder/Space error message when in collapsed state

src/gui/accountsettings.cpp, src/gui/accountsettings.h
When a server override path is set for a branded client, this should only be used for the WebDAV end-point, not for "normal" browsing.
=> Fix "Open in web browser" action in "Manage account" menu

changelog/unreleased/12044.md, src/csync/INSTALL, src/gui/folderman.cpp, src/gui/updater/ocupdater.h
Fixes: #12090 (Translation source string has a wrong capitalisation)
This PR updates some relevant occurrences where the string `macOS` has the wrong capitalsiation.
There are many more occurrences but these are mainly:
* changelog entries for releases already published
* parts of the code where directories are accesses.
This would need dir naming changes too which is not worth it (except one decides to)
=> Update MacOS --> macOS where necessary, especially for the translation

test/testutils/syncenginetestutils.cpp
=> fix(test framework): a finished signal could be emitted twice

.github/release_template.md
Update release template
Part of: https://github.com/owncloud/client/issues/12010
=> docs: update release template

.github/workflows/main.yml
=> Revert "ci: drop macos debug build"

src/libsync/theme.cpp
In case the cmake variable APPLICATION_UPDATE_URL is undefined the code shall still compile ;-)
Before:
```
***\src\libsync\theme.cpp(246): error C2146: syntax error: missing ')' before identifier 'APPLICATION_UPDATE_URL'
***\src\libsync\theme.cpp(246): error C2059: syntax error: ')'
***\src\libsync\theme.cpp(246): error C2059: syntax error: ')'
=> fix: test undefined APPLICATION_UPDATE_URL

src/gui/accountmanager.cpp, src/gui/accountmanager.h, src/gui/accountstate.cpp, src/gui/models/activitylistmodel.cpp, src/gui/settingsdialog.cpp
slot to saveAccount was connected before AccountState was effectively added. saveAccount uses the AccountStatePtr so it was null in some cases and crashed.
I added checks for null on the account state in these areas and also re-ordered the behavior in AccountManager::addAccountState
also renamed AccountManager::account to accountState as that's actually what you get from it.
=> fix crash when adding an accountState to the AccountManager

src/libsync/httplogger.cpp
The assumption that the content "device" is a `QBuffer` when it is closed, is wrong: it can very well be a `QNetworkReply`, plus that shouldn't matter just for logging.
Fixes: #12098
=> Remove invalid assert in the HTTP logger

src/gui/networksettings.cpp, src/gui/networksettings.ui, test/gui/tst_checkAlltabs/test.feature
Implement deprecation of bandwidth limits:
- when none are set, hide the UI
- when a limit is set, show the UI, including a warning icon and a text label warning about the deprecation
=> Deprecate bandwidth limits

src/gui/folderwizard/folderwizard.cpp
When VFS is forced on, all elements on this page are disabled: the checkbox to turn VFS off is disabled, and the selective sync chooser is also disabled. This can be very confusing to the user, so completely skip this page.
This also prevents a bug in this page from showing: if VFS is forced, the checkbox for disabling VFS is not shown. And when this checkbox is not shown, the selective sync widget is not disabled, allowing to do selective sync with VFS (forced) on.
Fixes: #12135
(cherry picked from commit 02544983b88ff27828bab30398928ee473e97dce)
=> Skip the selective sync page when VFS is forced

test/gui/shared/scripts/helpers/SetupClientHelper.py, test/gui/shared/scripts/helpers/SyncHelper.py, test/gui/shared/scripts/pageObjects/SyncConnection.py, test/gui/shared/steps/account_context.py, test/gui/shared/steps/spaces_context.py, test/gui/shared/steps/sync_context.py, test/gui/tst_activity/test.feature, test/gui/tst_sharing/test.feature, test/gui/tst_spaces/test.feature, test/gui/tst_syncing/test.feature
This PR uses the full account setup in all the test scenarios and removes the use of incomplete config file when setting up account.
Fixes https://github.com/owncloud/client/issues/12136
=> [test-only][full-ci] Refactor tests to use normal account setup flow

src/gui/folderman.cpp, src/gui/folderman.h
as suspected, there was a stray signal that triggered folder save after it was removed from settings when removing the folder sync.
fix is to disconnect the auto-save signals in FolderMan::removeFromSettings to avoid the problem.
=> fixes https://kiteworks.atlassian.net/browse/DC-31

.drone.star
Do not use cache server and bucket name from secrets
Part of https://github.com/owncloud/QA/issues/883
=> ci: add cache server and bucket varaibles

src/gui/accountmanager.cpp, src/gui/accountmanager.h, src/gui/newwizard/setupwizardcontroller.cpp
block creation of account if an account with the same url and davUser already exists in the account manager
=> [DC-10] fix: block creation of duplicate new account

src/gui/folderman.cpp, src/gui/folderman.h, src/libsync/determineauthtypejobfactory.cpp
remove folder migration which only supported incomplete/faked config used by squish tests in the past
also added a future todo to determineauthtypejobfactory.cpp
=> [DC-37] chore: remove qa safety net for fake configs

test/gui/shared/scripts/bdd_hooks.py, test/gui/shared/scripts/pageObjects/Toolbar.py
The accounts tab in the desktop client does not contain the display name. In windows during clean up of users, account connection need to be removed, and the selector used the display name which resulted in failure to remove the users. This PR fixes this problem in windows.
=> [tests-only][full-ci] fix remove account connection for windows

test/gui/shared/scripts/bdd_hooks.py
Fixes the selector while selecting the account from toolbar during user account cleanup in windows.
Follow up of PR: https://github.com/owncloud/client/pull/12160
=> [tests-only][full-ci] fix cleanup user account in windows

test/gui/shared/scripts/helpers/SyncHelper.py
Exclude socket message with `STATUS:NOP` during sync status check filtering.
=> [tests-only][full-ci] exclude STATUS:NOP during sync status check filtering

.drone.star
This PR https://github.com/owncloud/client/pull/12173, missed the environment releated to cache due to which the notification missed the failed logs in the message notification. This PR adds the missing envs.
=> [tests-only][full-ci] add missing cache envs - fix notification

.craft.shelf
They are not used for builds, and are rebuild every time on macOS.
=> ci: remove gammaray and kdstatemachineeditor from the shelf

src/libsync/account.cpp
Some versions of the client failed to remove the temporary cache
directory on exit, and after a crash the directory would not be removed
either. This can result in multiple GB of cached space images. So clean
this up before creating a new cache.
=> [DC-83] Fix: remove any existing ResourceCache directories for accounts

src/gui/creds/httpcredentialsgui.cpp, src/gui/creds/oauth.cpp, src/gui/creds/oauth.h, src/gui/newaccountwizard/oauthpagecontroller.cpp, src/gui/newwizard/states/oauthcredentialssetupwizardstate.cpp, test/testoauth.cpp
As desktop client 7 drops oc10 - OAuth2 support for oc10 is also being removed.
In fact the client now supports OpenID-Connect only starting 7 - we might want to reflect this in the code elements as well at some point in time.
=> fix: remove oc10 OAuth2 fallback

changelog/unreleased/12224.md, src/gui/accountmanager.cpp, src/libsync/account.cpp, src/libsync/account.h, src/libsync/graphapi/space.cpp, src/libsync/networkjobs/resources.cpp, src/libsync/networkjobs/resources.h
This includes the cache for space images, as well as certain cached network jobs.
=> [DC-82] Fix: delete account-specific caches when an account is removed

src/gui/accountmanager.cpp, src/gui/folder.cpp, src/gui/folder.h, src/gui/folderman.cpp, src/gui/folderman.h, src/libsync/configfile.cpp, src/libsync/configfile.h
These keys were not written out anymore, but would still stay in the configuration file if no configuration change was made. Now they are removed when detected.
=> [DC-111] Actively delete version keys

test/gui/shared/scripts/helpers/SyncHelper.py
This Pr fixes the 503 http error at the start of the test. Use `requests` instead of `urllib request`.
fixes: https://github.com/owncloud/client/issues/12316
=> [tests-only][full-ci] use requests instead of urllib request

test/gui/shared/scripts/helpers/SyncHelper.py
Update url and use `raw.githubusercontent.com` instead of `raw.github.com` to download syncstate.py.
Follow up of: https://github.com/owncloud/client/pull/12322
Part of: https://github.com/owncloud/client/issues/12316
=> [tests-only][full-ci] update url to raw.githubusercontent.com while downloading syncstate.py

changelog/unreleased/12305.md, src/gui/folderwizard/folderwizardselectivesync.cpp, src/gui/folderwizard/folderwizardselectivesync.h
* [DC-146] Fix VFS checkbox in folder wizard
On the last page of the folder wizard, there is a checkbox to select/deselect VFS. By default this is checked. The bug was that after unchecking this checkbox, it could not be checked again. This has now been fixed.
* Move checkbox handling to a slot
* [DC-166] Disable selective-sync when VFS is forced
Previously the checkbox to deselect VFS was not shown when VFS was forced. This also caused the selective sync widget to be enabled. This is now fixed: the checkbox is shown (and checked) when VFS is availabled, but disabled when VFS is forced. This leaves it in the checked state, but the user cannot deselect it.
---------
(cherry picked from commit 73493d0087fc1280004bd9d46e760637179498df)
=> [DC-146, DC-166] Fix VFS checkbox in folder wizard (#12305)
