owncloud/client

test/gui/shared/scripts/bdd_hooks.py

This PR adds init and sends a http `POST` request in `OnScenarioStart`. This change in the hooks is done as https://github.com/owncloud/owncloud-test-middleware/pull/34 has been merged now.

[tests-only]Add init in bdd hooks

---

.drone.star

install and start the test middleware as mentioned in the documentation

fix start of middleware

---

changelog/unreleased/8367
src/gui/application.cpp

Overwrite locale only when a language is enforced

---

test/gui/shared/steps/steps.py
test/gui/tst_sharing/test.feature
test/gui/tst_syncing/test.feature

This PR removes polling interval from test step and sets it to 5000ms by default 
fixes https://github.com/owncloud/client/issues/8641

[tests-only] Set polling interval by default

---

test/gui/Makefile

This PR adds Makefile for UI test formatting 
fixes https://github.com/owncloud/client/issues/8642

[tests-only] Add makefile for UI test formatting

---

test/gui/shared/scripts/helpers/SetupClientHelper.py
test/gui/shared/steps/steps.py
test/gui/tst_addAccount/test.feature
test/gui/tst_sharing/test.feature
test/gui/tst_syncing/test.feature

This PR refactors all the steps with password in them
- fixes https://github.com/owncloud/client/issues/8652

[tests-only] refactor steps with password in them

---

src/gui/accountstate.cpp
src/gui/connectionvalidator.cpp
src/gui/connectionvalidator.h
src/libsync/theme.cpp
src/libsync/theme.h

Depends on https://github.com/owncloud/client/pull/8653

Change when to clear cookies

---

changelog/unreleased/4627
shell_integration/windows/3rdparty/nlohmann-json/LICENSE.MIT
shell_integration/windows/3rdparty/nlohmann-json/json.hpp
shell_integration/windows/OCContextMenu/CMakeLists.txt
shell_integration/windows/OCContextMenu/OCClientInterface.cpp
shell_integration/windows/OCContextMenu/OCClientInterface.h
shell_integration/windows/OCContextMenu/OCContextMenu.cpp
shell_integration/windows/OCContextMenu/dllmain.cpp
shell_integration/windows/OCUtil/CommunicationSocket.cpp
shell_integration/windows/OCUtil/CommunicationSocket.h
shell_integration/windows/OCUtil/RemotePathChecker.cpp
shell_integration/windows/OCUtil/StringUtil.cpp
shell_integration/windows/OCUtil/StringUtil.h

Fixes: https://github.com/owncloud/client/issues/4627

Add an icon to the windows explorer context menu

---

src/gui/application.cpp
src/gui/application.h
src/gui/main.cpp

Implement `--list-languages` CLI parameter

---

.drone.star

Workaround for https://github.com/appleboy/drone-git-push/issues/43 respectively https://github.com/appleboy/drone-git-push/issues/49.

Push translations over SSH

---

test/gui/shared/steps/steps.py

This PR adds a function called `getMiddlewareState` which will get user information from middleware using `state` endpoint of middleware. Previously we were using a global variable `defaultUsers` which now is not needed and thus removed.
- Fixes https://github.com/owncloud/client/issues/8677

[Tests-Only] get userinformation through middleware

---

.drone.star
.github/workflows/run-in-docker.sh
.github/workflows/translate.yml
translations/Makefile

Right now, translations are updated on Drone. This PR moves the task to GitHub actions.

Update translations in GitHub actions

---

src/libsync/creds/oauth.cpp

This PR implements validation for the OAuth 2.0 authorization URLs returned by the ownCloud/oCIS server. The specification requires the use of HTTPS to ensure confidentiality of the credentials. This PR makes sure that no sensitive information is leaked when, for instance, due to a configuration issue, an HTTP URL would be returned.

Validate OAuth authorization URLs

---

src/csync/csync_exclude.cpp
src/csync/csync_exclude.h
src/gui/selectivesyncdialog.cpp

Fix exclude filtering in selective sync dialog

---

changelog/unreleased/8729
src/gui/syncrunfilelog.cpp
src/gui/syncrunfilelog.h

Use QDebug stream operators for .owncloudsync.log

---

src/gui/CMakeLists.txt
src/gui/activitywidget.cpp
src/gui/issueswidget.cpp
src/gui/models/expandingheaderview.cpp
src/gui/models/expandingheaderview.h
src/gui/models/models.cpp
src/gui/models/models.h
src/gui/protocolwidget.cpp
src/gui/protocolwidget.h

Fixes: https://github.com/owncloud/client/issues/8660

Change the resize behaviour of the header view

---

src/gui/translations.cpp

Don't use deprecated DataLocation

---

test/gui/tst_sharing/test.feature

After https://github.com/owncloud/client/pull/8739 has been merged GUI will run on latest stable server tarball. So, we can now undo all the changes done in PR https://github.com/owncloud/client/pull/8735.

[Tests-Only] Revert changes done in PR-8735

---

src/gui/accountmanager.h
src/gui/owncloudsetupwizard.cpp

Fix crash on rediredct during setup

---

CMakeLists.txt

~Depends on #8727~
@alexeylysenko :)

Add QT_NO_FOREACH

---

changelog/unreleased/4639
src/common/vfs.cpp

Fixes: https://github.com/owncloud/enterprise/issues/4639

Fix a bug preventing sync root on drive roots

---

src/gui/accountmanager.cpp
src/gui/owncloudsetupwizard.cpp
src/gui/wizard/owncloudsetuppage.cpp
src/libsync/theme.cpp
src/libsync/theme.h

Depends on: https://github.com/owncloud/client/pull/8771

Allow to override the server url with $OWNCLOUD_OVERRIDE_SERVER_URL

---

src/libsync/owncloudpropagator.cpp

Fix file name in clash warning

---

changelog/unreleased/8804
src/cmd/cmd.cpp
src/gui/folder.cpp
src/gui/folder.h
src/libsync/syncengine.h

Cmd: Implement aboutToRemoveAllFiles

---

src/libsync/propagatedownload.cpp

Avoid the verb "dehydrate" in message

---

test/testsyncvirtualfiles.cpp

if the test fails now we see why....

use QCOMPARE

---

changelog/unreleased/8811
src/libsync/owncloudpropagator_p.h

Treat a 502 as SoftError and retry the sync

---

src/common/preparedsqlquerymanager.h
src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/common/vfs.h
src/csync/csync.h
src/libsync/discovery.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
src/libsync/propagatedownload.cpp
src/libsync/syncengine.cpp
src/libsync/vfs/suffix/vfs_suffix.cpp
src/libsync/vfs/suffix/vfs_suffix.h
test/testchunkingng.cpp
test/testdatabaseerror.cpp
test/testsyncfilestatustracker.cpp

The first commit can be reviewed in https://github.com/owncloud/client/pull/8830

Properly handle metadata updates

---

src/common/filesystembase.cpp
src/common/filesystembase.h
src/csync/csync_exclude.cpp
test/testutility.cpp

Depends on https://github.com/owncloud/client/pull/8851

Fix isExcludedRemote

---

test/gui/shared/steps/steps.py
test/gui/tst_sharing/test.feature

Refactor `Given` steps as per https://github.com/owncloud/client/issues/8795
https://github.com/owncloud/client/issues/8840

[tests-only] refactor steps

---

test/CMakeLists.txt
test/owncloud_add_test.cmake
test/testutils/CMakeLists.txt
test/testutils/syncenginetestutils.cpp
test/testutils/testutilsloader.cpp

Q_COREAPP_STARTUP_FUNCTION doesn't work reliably in a static lib

Ensure the tests are properly set up

---

changelog/unreleased/8849
src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/gui/folder.cpp
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/folderwizard.cpp
src/gui/wizard/owncloudadvancedsetuppage.cpp
src/gui/wizard/owncloudadvancedsetuppage.h
test/testfolderman.cpp

Prevent sync root sharing

---

src/gui/issueswidget.cpp
src/gui/models/protocolitemmodel.cpp
src/libsync/discovery.cpp
src/libsync/syncfileitem.h
src/libsync/syncresult.cpp

Don't treat exclude as error

---

src/libsync/abstractnetworkjob.cpp
src/libsync/account.cpp
src/libsync/account.h
src/libsync/creds/httpcredentials.cpp
src/libsync/creds/oauth.cpp
src/libsync/creds/oauth.h

Don't forget oauth token if refresh failed due to network issues

---

src/libsync/abstractnetworkjob.cpp

Don't start connection validation during authentication

---

changelog/unreleased/8901
src/gui/accountstate.cpp

Correctly handle credential invalidation on start up

---

src/csync/csync_exclude.cpp
sync-exclude.lst

~The code also checked whether the strings started with COM8. and returned true in that cas.
While COM8 is reserved COM8.png is ok.~
@michaelstingl maybe only for 2.10?

Refactor reserved name code

---

src/gui/models/expandingheaderview.cpp
src/gui/models/expandingheaderview.h

Use a more intuitive resize behaviour

---

.craft.shelf
src/libsync/creds/httpcredentials.cpp
src/libsync/creds/httpcredentials.h
src/libsync/creds/httpcredentials_p.h

Fix credential loading

---

src/gui/application.cpp

Fixes: https://github.com/owncloud/client/issues/8932

Set OC_PLUGIN_DIR before we set the about text

---

src/gui/accountsettings.cpp
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/folderstatusmodel.cpp

Warn on unsupported legacy configuration

---

.drone.env
.drone.star

pin middleware commit id for GUI tests in CI

[Tests-Only][CI] pin middleware commit id for running tests in CI

---

changelog/unreleased/9000
src/common/utility.h
src/csync/csync.cpp
src/csync/csync.h
src/gui/models/protocolitemmodel.cpp
src/gui/models/protocolitemmodel.h
src/gui/protocolwidget.cpp
src/libsync/syncfileitem.cpp
src/libsync/syncfileitem.h

This is only part one, the filtering is still missing.
Please try to improve the wording for the enum values.
Issue: #9000

Add SyncStatus to the tables

---

changelog/unreleased/9019
src/common/syncjournaldb.h
src/gui/folder.cpp
src/gui/folder.h
src/gui/folderman.cpp

Migrate existing db files and save their journal path

---

changelog/unreleased/9014
src/libsync/syncengine.cpp
src/libsync/syncengine.h

Fix crash on shutdown

---

changelog/unreleased/9016
src/common/vfs.cpp
src/common/vfs.h
src/gui/accountsettings.cpp
src/gui/folder.cpp
src/gui/folder.h
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/folderstatusmodel.cpp
src/gui/folderwizard.cpp
src/gui/socketapi/socketapi.cpp
src/gui/wizard/owncloudadvancedsetuppage.cpp
src/libsync/syncengine.cpp

The change means that vfs is not initialised so I need to implement a dummy vfs or better add checks for every use of vfs()....
Fixes: #9016

Fix crash on missing sync root

---

changelog/unreleased/9019

The missing url broke the changelog generation

Fix changelog entry

---

src/common/utility.h
src/gui/models/protocolitemmodel.cpp
src/libsync/syncfileitem.cpp
src/libsync/syncfileitem.h

We rather update the compiler on debian 9
This reverts commit 4acec7bfdeeb798cdc7f32d6286dc7de07e17ef1.
@fmoc you had a look into updating those?

Revert "Work around compiler bug in old GCC versions"

---

test/gui/shared/scripts/pageObjects/Activity.py
test/gui/shared/steps/steps.py
test/gui/tst_syncing/test.feature

This PR fixes failing test for file sync with conflict after the recent redesign of desktop-client.
- fixes https://github.com/owncloud/client/issues/9031

[tests-only] Fix "sync conflict" test scenario

---

src/gui/application.cpp

Makes debugging translations loading issues easier.
CC #9022

Extend translations setup logging

---

test/gui/TestLogParser.py

This fixes GUI test log parser to display the log from middleware steps fails as well.

[Tests-Only]Fixed GUI test log parser

---

.craft.shelf
changelog/unreleased/9022

The other change is in the msi code

Update craft-core to fix mac translation  deployment

---

.github/patch_release_template.md

see https://github.com/owncloud/client/issues/8869

Apply changes from 2.9 release ticket

---

CMakeLists.txt

I couldn't find any reference to the defin

Remove non existing option

---

src/gui/libcloudproviders/libcloudproviders.cpp

Rebase of https://github.com/owncloud/client/pull/9025

Fix build with libcloudproviders, reported in #8996

---

.github/workflows/main.yml
test/testdownload.cpp
test/testfolderman.cpp

The change also skips two checks in order to fix running tests on docker

CI: Use a docker container for centos

---

test/gui/shared/steps/steps.py
test/gui/suite.conf
test/gui/tst_deletFilesFolders/test.feature
test/gui/tst_deletFilesFolders/test.py

Added automated tests for deleting files and folders.
- Part of https://github.com/owncloud/client/issues/8971#issuecomment-909884844

[tests-only]add tests for deleting files and folder

---

changelog/unreleased/8924
src/gui/accountstate.cpp
src/gui/accountstate.h

Fix re-authenticating at startup when logged out before

---

.github/workflows/translate.yml

Switch to powershell as the other scripts are using it too.
Only haggle with ssh and push if we have a change.
(I'm getting a mail every day https://github.com/owncloud/client/runs/4220100543?check_suite_focus=true)

Ci: Translations, only push if we have a change

---

changelog/unreleased/9170
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateremotemkdir.h

Fix crash in PropagateRemoteMkdir

---

changelog/unreleased/4896
src/csync/std/c_time.cpp

Fixes: https://github.com/owncloud/enterprise/issues/4896

Fix another occurence of the wrong path format used on Windows

---

test/gui/TestLogParser.py
test/gui/tst_syncing/test.feature

This PR fixes gui-tests log that reports passing Scenario Outline tests as failed whenever one or more tests fail.
fixes https://github.com/owncloud/client/issues/9222

Fix TestLogParser for scenario outline tests

---

changelog/unreleased/9266
src/gui/models/activitylistmodel.cpp

Fix hiding of activity tab in case app is disabled or not installed

---

changelog/unreleased/9257
src/common/vfs.h
src/libsync/owncloudpropagator.cpp
src/libsync/propagatedownload.cpp
src/libsync/vfs/suffix/vfs_suffix.cpp
src/libsync/vfs/suffix/vfs_suffix.h
test/testsyncvirtualfiles.cpp

Related: https://github.com/owncloud/client-desktop-vfs-win/pull/9

Move dehydration in to updateMetaData

---

changelog/unreleased/9194
src/libsync/propagateuploadng.cpp

Only check for locked files before we start the upload

---

.drone.env

Bumping middleware commit id for the tests.

[tests-only] Bump middleware commit id to the latest

---

test/gui/shared/scripts/pageObjects/SharingDialog.py
test/gui/shared/steps/steps.py
test/gui/tst_sharing/test.feature

This PR adds test for sharing a file with multiple users(3-users)
https://github.com/owncloud/client/issues/8971#issuecomment-909885070

[tests-only] added tests for  multiuser share

---

changelog/unreleased/9208
src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/common/syncjournalfilerecord.h
src/gui/folder.cpp
src/gui/folder.h
src/libsync/owncloudpropagator.cpp
src/libsync/syncengine.cpp
test/testblacklist.cpp
test/testchunkingng.cpp
test/testdownload.cpp
test/testlockedfiles.cpp
test/testsyncengine.cpp

Fixes: #9208, #9133
Might also fix https://github.com/owncloud/client/issues/9076

Handle local errors with the ignore list

---

.drone.star
test/gui/tst_syncing/test.feature

3 tests are failing a lot in drone, which has been skipped in this PR. 
Ref: https://github.com/owncloud/client/issues/9281#issuecomment-993317582

[tests-only]Skipped 3 failed tests

---

test/testdatabaseerror.cpp
test/testsyncengine.cpp
test/testsyncmove.cpp
test/testutils/syncenginetestutils.cpp
test/testutils/syncenginetestutils.h

Always take the hydration state into account, and always check the
mtime.

Tests: simplify equality check for state

---

changelog/unreleased/client-desktop-vfs-win-12
changelog/unreleased/client-desktop-vfs-win-13

Add changelog entry for win-vfs

---

src/common/syncjournaldb.cpp

Fix unlock of files

---

test/gui/shared/scripts/bdd_hooks.py

Cleanup test server state after each scenario
Code taken from #8792
Fixes #8831

[tests-only] Cleanup test server in after scenario hook

---

changelog/unreleased/9342
src/libsync/syncfilestatustracker.cpp

https://github.com/owncloud/client-desktop-vfs-win/pull/14

Don't set origin file of moves to in sync

---

.drone.star

make the drone starlark file same as in 2.10

fix starlark

---

test/gui/TestLogParser.py
test/gui/tst_vfs/test.feature

This PR also adds the tests that fail with `result: FAIL` to the failed log.
Fixes https://github.com/owncloud/client/issues/9371

[gui][tests-only Fix gui test logParser

---

.github/release_template.md

Fixes https://github.com/owncloud/client/issues/9327

[Tests-only]Added note in release template to update the branch for nightly runs

---

changelog/unreleased/9383

Add change log for #9383

---

test/gui/shared/scripts/bdd_hooks.py
test/gui/shared/steps/steps.py
test/gui/tst_sharing/test.feature

Added more automated tests for different sharing scenarios
Splitted from https://github.com/owncloud/client/pull/9323

[tests-only] Added more GUI tests for sharing with user (part 02)

---

test/gui/shared/scripts/pageObjects/PublicLinkDialog.py
test/gui/shared/steps/steps.py
test/gui/tst_sharing/test.feature

Added more automated tests for different sharing scenarios
Splitted from https://github.com/owncloud/client/pull/9323

[tests-only] Added more GUI tests for sharing with user (part 03)

---

changelog/unreleased/9460
translations/.tx/config

Map de -> de-informal

---

.drone.star

fixes https://github.com/owncloud/client/issues/9469

[CI] update public s3 cache credentials

---

src/gui/folderstatusdelegate.h

Using this pattern with the role does not work

Remove DataRoleCount from datarole

---

src/gui/application.cpp

Only log after the logger is set up

---

changelog/unreleased/9236
src/libsync/discovery.cpp

Remove db entry for no longer existing ignored files

---

changelog/unreleased/9460
src/gui/generalsettings.cpp
src/gui/generalsettings.h

Include locale in language dropdown

---

src/gui/CMakeLists.txt
src/gui/accountsettings.cpp
src/gui/activitywidget.cpp
src/gui/commonstrings.cpp
src/gui/commonstrings.h
src/gui/protocolwidget.cpp

Unify common translatable strings

---

src/gui/commonstrings.cpp

Fix plural translation

---

src/gui/application.cpp

Init library path before we call setApplicationVersion

---

.drone.star
test/gui/drone/notification_template.sh

Uses the custom template for build notification
Example:
Fixes https://github.com/owncloud/client/issues/9479

[tests-only] Notify with logs whenever there is a nightly fail

---

changelog/unreleased/9545
src/gui/accountstate.cpp
src/gui/creds/httpcredentialsgui.cpp
src/libsync/creds/abstractcredentials.h

Fix basic auth logout

---

.github/issue_template.md
CONTRIBUTING.md
README.md
src/gui/application.cpp

Update outdated URLs

---

src/gui/accountmanager.cpp
src/libsync/account.cpp
src/libsync/account.h
src/libsync/capabilities.cpp
src/libsync/capabilities.h
src/libsync/syncengine.cpp
test/testchunkingng.cpp
test/testlocaldiscovery.cpp
test/testsyncconflict.cpp
test/testsyncengine.cpp
test/testuploadreset.cpp
test/testutils/syncenginetestutils.cpp
test/testutils/testutils.cpp
test/testutils/testutils.h

This allows us to use them during startup or when offline.
The capability will be saved in the settings:
```
1\capabilities="@Variant(\0\0\0\b\0\0\0\b\0\0\0\x1e\0p\0\x61\0s\0s\0w\0o\0r\0\x64\0_\0p\0o\0l\0i\0\x63\0y\0\0\0\b\0\0\0\x1\0\0\0*\0p\0\x61\0s\0s\0w\0o\0r\0\x64\0_\0r\0\x65\0q\0u\0i\0r\0\x65\0m\0\x65\0n\0t\0s\0\0\0\b\0\0\0\x1\0\0\0\x1a\0\x63\0o\0n\0\x66\0i\0g\0u\0r\0\x61\0t\0i\0o\0n\0\0\0\b\0\0\0\x4\0\0\0\x14\0u\0p\0p\0\x65\0r\0_\0\x63\0\x61\0s\0\x65\0\0\0\b\0\0\0\x1\0\0\0\x1a\0g\0\x65\0n\0\x65\0r\0\x61\0t\0\x65\0_\0\x66\0r\0o\0m\0\0\0\b\0\0\0\x1\0\0\0\x14\0\x63\0h\0\x61\0r\0\x61\0\x63\0t\0\x65\0r\0s\0\0\0\n\0\0\0\x34\0\x41\0\x42\0\x43\0\x44\0\x45\0\x46\0G\0H\0I\0J\0K\0L\0M\0N\0O\0P\0Q\0R\0S\0T\0U\0V\0W\0X\0Y\0Z\0\0\0$\0s\0p\0\x65\0\x63\0i\0\x61\0l\0_\0\x63\0h\0\x61\0r\0\x61\0\x63\0t …
```

Cache capabilities

---

.drone.star

This is an update on .drone.star file 
- using drone-cancel-previous-builds
- using thegeeklab/drone-github-comment instead of jmccann/drone-github-comment for github comments 
- moving docker image references to constants
- using caches images
Part of issue: 
- https://github.com/owncloud/QA/issues/700
- https://github.com/owncloud/QA/issues/717
- https://github.com/owncloud/QA/issues/729
- https://github.com/owncloud/QA/issues/728

[CI]updated drone.star file 

---

src/gui/newwizard/pages/serverurlsetupwizardpage.cpp
src/gui/newwizard/pages/serverurlsetupwizardpage.h
src/gui/newwizard/setupwizardcontroller.cpp

Automatically prepend user-provided server URLs with https://

---

src/gui/quotainfo.cpp
src/libsync/account.cpp
src/libsync/account.h

Quota stuff needs a rewrite anyhow (spaces)

Don't assert if capabilities are not ready yet

---

src/gui/folderman.cpp

Do we need a changelog entry for this?
Its neither an enhancement nor a bugfix..

Remove config migration < 2.0

---

src/gui/accountsettings.cpp
src/gui/accountstate.cpp
src/gui/folder.cpp
src/gui/folder.h
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/folderstatusmodel.cpp
src/gui/folderwizard/folderwizard.cpp
src/gui/folderwizard/folderwizard.h
src/gui/navigationpanehelper.cpp
src/gui/owncloudgui.cpp

This depends on quite a lot of other open reviews.

Add display name to folders

---

.drone.star

This is an update on .drone.star file 
- skip pipeline based on changed code 
Closes https://github.com/owncloud/QA/issues/732
Closes https://github.com/owncloud/QA/issues/730
1. Changes only in:
```
"^.github/.*"
"^.vscode/.*",
"^changelog/.*",
"README.md",
".gitignore",
"CHANGELOG.md",
"CONTRIBUTING.md",
"COPYING",
"COPYING.documentation",
```
DO NOT RUN: `ctest` and `gui-test`

[CI]Implemented skip-if-unchanged

---

src/gui/newwizard/setupwizardwindow.cpp

Bring wizard window to front after page change

---

src/gui/accountsettings.cpp
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/newwizard/pages/accountconfiguredwizardpage.cpp
src/gui/newwizard/pages/accountconfiguredwizardpage.ui
src/gui/newwizard/setupwizardcontroller.cpp
src/gui/newwizard/syncmode.h
src/gui/owncloudgui.cpp

Extracted from #9606. Fixed the mistake mentioned in the reviews there, and further removed some now-obsolete code.

Use folder wizard for manual sync config

---

changelog/9598
src/libsync/owncloudpropagator.cpp
src/libsync/propagatedownload.cpp
src/libsync/vfs/off/vfs_off.cpp
src/libsync/vfs/suffix/vfs_suffix.cpp

Depends on https://github.com/owncloud/client/pull/9603

Move setFileReadOnlyWeak to updateMetadata

---

changelog/unreleased/9618
src/common/utility_win.cpp

https://blogs.windows.com/windows-insider/2015/06/08/get-your-work-done-faster-with-quick-access/

No longer create < Windows 10 link

---

src/gui/newwizard/jobs/resolveurljobfactory.cpp
src/gui/newwizard/jobs/resolveurljobfactory.h
src/gui/newwizard/pages/abstractsetupwizardpage.cpp
src/gui/newwizard/pages/abstractsetupwizardpage.h
src/gui/newwizard/pages/accountconfiguredwizardpage.cpp
src/gui/newwizard/pages/accountconfiguredwizardpage.h
src/gui/newwizard/pages/basiccredentialssetupwizardpage.cpp
src/gui/newwizard/pages/basiccredentialssetupwizardpage.h
src/gui/newwizard/pages/oauthcredentialssetupwizardpage.cpp
src/gui/newwizard/pages/oauthcredentialssetupwizardpage.h
src/gui/newwizard/pages/serverurlsetupwizardpage.cpp
src/gui/newwizard/pages/serverurlsetupwizardpage.h
src/gui/newwizard/pagination.cpp
src/gui/newwizard/pagination.h
src/gui/newwizard/setupwizardaccountbuilder.cpp
src/gui/newwizard/setupwizardaccountbuilder.h
src/gui/newwizard/setupwizardcontroller.cpp
src/gui/newwizard/setupwizardcontroller.h
src/gui/newwizard/setupwizardwindow.cpp
src/gui/newwizard/setupwizardwindow.h
src/gui/newwizard/syncmode.cpp
src/gui/newwizard/syncmode.h

A second commit adds the missing copyright headers to the wizard.

Reorder and sort includes in new wizard

---

src/gui/newwizard/setupwizardwindow.cpp
src/gui/newwizard/setupwizardwindow.ui

Center the transistion spinner

---

src/gui/newwizard/setupwizardcontroller.cpp

Display URL in "insecure URL" message box

---

src/gui/proxyauthhandler.cpp
src/libsync/account.cpp
src/libsync/account.h

Remove sharedAccessManager

---

test/gui/shared/scripts/pageObjects/PublicLinkDialog.py
test/gui/tst_sharing/test.feature

Fixes https://github.com/owncloud/client/issues/9321

[Tests-Only] Fixed tests related to expiration date set/change

---

src/gui/owncloudgui.cpp

Unpause sync before we schedule a sync

---

.github/workflows/main.yml

Add build job with libcloudproviders enabled

---

src/gui/newwizard/setupwizardwindow.cpp

Hide ? icon on Windows

---

src/libsync/theme.cpp

Fix missing git revision

---

src/gui/folder.cpp
src/gui/folderman.cpp

Fix scheduling of newly added folders

---

src/gui/connectionvalidator.cpp
src/gui/owncloudgui.cpp

Allow to connect to unsupported servers

---

test/gui/tst_addAccount/test.feature
test/gui/tst_checkAlltabs/test.feature
test/gui/tst_deletFilesFolders/test.feature
test/gui/tst_editFiles/test.feature
test/gui/tst_loginLogout/test.feature
test/gui/tst_removeAccountConnection/test.feature
test/gui/tst_sharing/test.feature
test/gui/tst_syncing/test.feature
test/gui/tst_vfs/test.feature

Currently, most of the tests are failing either because of the changed GUI components or because they have not been maintained for a long time. So all tests has been skipped, which will be shall be unskipped in upcoming PRs when they are fixed.
- fixes https://github.com/owncloud/client/issues/9733

[Tests-Only]Skipped all failing GUI tests

---

resources/wizard/style.qss
src/gui/newwizard/CMakeLists.txt
src/gui/newwizard/pages/basiccredentialssetupwizardpage.cpp
src/gui/newwizard/pages/basiccredentialssetupwizardpage.ui
src/gui/newwizard/pages/serverurlsetupwizardpage.cpp
src/gui/newwizard/pages/serverurlsetupwizardpage.ui
src/gui/newwizard/postfixlineedit.cpp
src/gui/newwizard/postfixlineedit.h

Closes https://github.com/owncloud/client/issues/9701.

Implement remaining wizard branding options

---

.craft.ini

I'll then add llvm to our craft cache

[ci] don't skip llvm, we need it in a dev env

---

test/gui/tst_syncing/test.feature

This PR is to ensure, that the test cases[related to the file-syncing suite] that are passing locally pass in CI too.

[test-only]unskipped file syncing related tests that are passing locally

---

.github/release_template.md

https://github.com/owncloud/client/issues/9488

Apply improvements from 2.10.1 ticket

---

test/gui/tst_sharing/test.feature

A lot of sharing tests are already passing. So, I am unskipping those tests.

[Tests-Only]Unskipped sharing tests that are now passing now

---

resources/wizard/style.qss
src/common/utility.cpp
src/common/utility.h
src/gui/newwizard/setupwizardwindow.cpp

The function alows to fill template files

Implement renderTemplate

---

src/gui/folderman.cpp
src/gui/folderwizard/folderwizard.cpp
src/gui/owncloudgui.cpp
src/gui/spaces/spacesbrowser.cpp
src/gui/spaces/spacesmodel.cpp
src/gui/spaces/spacesmodel.h
src/libsync/graphapi/drives.cpp
src/libsync/graphapi/drives.h

This reverts commit 0c4f977615fcd19ca46962b45ce15fcc912f51b6.
Fixes: #9821

Revert "Sync spaces to Spaces subfolder"

---

changelog/unreleased/9791
src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
test/testpermissions.cpp

Don't recreate db after it was closed

---

changelog/unreleased/8998
src/gui/sharedialog.cpp
src/gui/socketapi/socketapi.cpp
src/libsync/networkjobs.cpp

Don't query private links if disabled on the server

---

src/gui/newwizard/pages/basiccredentialssetupwizardpage.ui

Open external links in wizard in browser

---

src/gui/owncloudgui.cpp

Fix condition

---

src/gui/accountstate.cpp
src/gui/folderman.h
src/gui/socketapi/socketapi.cpp
src/gui/socketapi/socketapi.h

The socked api won't populate the conext menu for the directory
but in every other regard it will behave like an ownCloud managed dir.
Fixes: #9838

Register defaultSyncRoot with the socket api

---

src/gui/folderman.cpp

Normalise path

---

src/gui/folderman.cpp
src/gui/folderman.h

Check return value

---

src/gui/CMakeLists.txt
src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/accountsettings.ui
src/gui/askforoauthlogindialog.cpp
src/gui/askforoauthlogindialog.h
src/gui/askforoauthlogindialog.ui
src/gui/creds/httpcredentialsgui.cpp
src/gui/creds/httpcredentialsgui.h
src/gui/newwizard/pages/oauthcredentialssetupwizardpage.cpp
src/gui/newwizard/pages/oauthcredentialssetupwizardpage.h
src/gui/newwizard/pages/oauthcredentialssetupwizardpage.ui
src/gui/newwizard/states/oauthcredentialssetupwizardstate.cpp
src/libsync/creds/oauth.cpp
src/libsync/creds/oauth.h

Ask user to reauthenticate against OAuth2 server using modal dialog

---

changelog/unreleased/8234
src/gui/owncloudgui.cpp

Rename Settings action to Show ownCloud

---

src/gui/accountsettings.cpp
src/gui/folder.cpp
src/gui/folder.h
src/gui/folderstatusmodel.cpp
src/gui/folderstatusmodel.h

Implement flag for deployed folders

---

src/gui/folder.h

Init member

---

test/gui/shared/scripts/bdd_hooks.py
test/gui/shared/steps/steps.py

This PR implement code to screenshot failed tests scenario only
[Sometime fail to store screenshot](https://github.com/owncloud/client/issues/9852)

[CI]Implement code to screenshot failed scenario only

---

src/libsync/discoveryphase.cpp

Depends on #9920
The impact of this change is open for discussion.
If the server provides us with exactly the values we expect the iteration might be more performant.
If the server provides X more entries the map access would be more performant.

Map access vs iteration

---

changelog/unreleased/9924
src/libsync/propagateupload.cpp
src/libsync/propagateupload.h
src/libsync/propagateuploadng.cpp
src/libsync/propagateuploadtus.cpp
src/libsync/propagateuploadv1.cpp

Fix changed during upload timeout

---

src/gui/newwizard/pages/serverurlsetupwizardpage.cpp

Trim user entered url

---

changelog/unreleased/9923
src/gui/accountsettings.cpp

Remove app name from server messages

---

src/libsync/propagateuploadtus.cpp

Several tus fixes

---

src/common/checksumalgorithms.h
src/common/checksums.cpp
src/common/checksums.h
test/testchecksumvalidator.cpp
test/testsyncengine.cpp
test/testsyncmove.cpp
test/testutils/testutils.cpp
test/testutils/testutils.h

Looks like this change requires gcc > 10

Cleanup checksum handling

---

src/gui/newwizard/CMakeLists.txt
src/gui/newwizard/enums.cpp
src/gui/newwizard/pages/basiccredentialssetupwizardpage.cpp
src/gui/newwizard/pages/basiccredentialssetupwizardpage.h
src/gui/newwizard/pages/webfingersetupwizardpage.cpp
src/gui/newwizard/pages/webfingersetupwizardpage.h
src/gui/newwizard/pages/webfingersetupwizardpage.ui
src/gui/newwizard/setupwizardaccountbuilder.cpp
src/gui/newwizard/setupwizardaccountbuilder.h
src/gui/newwizard/setupwizardcontroller.cpp
src/gui/newwizard/states/basiccredentialssetupwizardstate.cpp
src/gui/newwizard/states/oauthcredentialssetupwizardstate.cpp
src/gui/newwizard/states/serverurlsetupwizardstate.cpp
src/gui/newwizard/states/webfingersetupwizardstate.cpp
src/gui/newwizard/states/webfingersetupwizardstate.h
src/libsync/CMakeLists.txt
src/libsync/creds/webfinger.cpp
src/libsync/creds/webfinger.h
src/libsync/theme.cpp
src/libsync/theme.h
src/resources/wizard/style.qss

Based on #9779. Uses the protocol implementation from https://github.com/owncloud/client/pull/9366. Contributes to #9249.
Opened as a draft because this requires some more cleanup and the error handling could be a little more user friendly.
Tested against the customer's production system.

Implement Webfinger protocol in setup wizard

---

src/gui/accountsettings.cpp
src/gui/accountsettings.ui

Remove ancient connection message

---

src/gui/newwizard/pages/serverurlsetupwizardpage.cpp
src/gui/newwizard/pages/serverurlsetupwizardpage.ui
src/libsync/theme.h

Remove wizard hint

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h

Hide quota bar with spaces

---

changelog/unreleased/9995
src/gui/aboutdialog.cpp
src/gui/askforoauthlogindialog.cpp
src/gui/askforoauthlogindialog.ui
src/gui/authenticationdialog.cpp
src/gui/folderwizard/folderwizard.cpp
src/gui/folderwizard/folderwizard.h
src/gui/guiutility.cpp
src/gui/guiutility.h
src/gui/ignorelisteditor.cpp
src/gui/logbrowser.cpp
src/gui/newwizard/setupwizardcontext.cpp
src/gui/newwizard/setupwizardcontext.h
src/gui/newwizard/setupwizardcontroller.cpp
src/gui/newwizard/setupwizardcontroller.h
src/gui/newwizard/setupwizardwindow.cpp
src/gui/newwizard/setupwizardwindow.h
src/gui/settingsdialog.cpp
src/gui/sharedialog.cpp

Use Qt::Sheet for dialogs

---

src/gui/newwizard/navigation.cpp

Enable current state button

---

src/gui/folderwizard/folderwizard.cpp
src/gui/folderwizard/folderwizard_p.h
src/gui/folderwizard/folderwizardselectivesync.cpp
src/gui/selectivesyncdialog.cpp
test/gui/tst_syncing/test.feature

Fix regression introduced in db73340fb33ecfe081ecb4764e6ff939b870e8bc

---

src/libsync/theme.cpp

Found a typo in a log message…

Fix typo in log message

---

src/gui/aboutdialog.cpp
src/gui/authenticationdialog.cpp
src/gui/folderwizard/folderwizard.cpp
src/gui/generalsettings.cpp
src/gui/guiutility.cpp
src/gui/ignorelisteditor.cpp
src/gui/logbrowser.cpp
src/gui/loginrequireddialog/loginrequireddialog.cpp
src/gui/newwizard/pages/accountconfiguredwizardpage.cpp
src/gui/newwizard/setupwizardwindow.cpp
src/gui/sharedialog.cpp

Fixes: https://github.com/owncloud/client/issues/10006

Fix dialog raising

---

src/gui/folderman.cpp
src/gui/folderman.h
src/gui/newwizard/pages/oauthcredentialssetupwizardpage.cpp
src/gui/newwizard/pages/oauthcredentialssetupwizardpage.ui
src/gui/newwizard/pages/serverurlsetupwizardpage.ui
src/gui/newwizard/states/accountconfiguredsetupwizardstate.cpp

Polish wizard

---

src/gui/spaces/spacesmodel.cpp

Don't display image url in spaces browser

---

src/common/syncjournaldb.h
src/gui/accountstate.h
src/gui/connectionvalidator.h
src/gui/folderstatusdelegate.h
src/gui/folderstatusmodel.h
src/gui/folderwizard/folderwizard.h
src/gui/models/activitylistmodel.h
src/gui/models/models.h
src/gui/models/protocolitemmodel.h
src/gui/sharemanager.h
src/gui/updater/ocupdater.h
src/libsync/configfile.h
src/libsync/owncloudpropagator.h
src/libsync/theme.h

Improves logging of their values.

Use Q_ENUM where applicable

---

src/gui/creds/httpcredentialsgui.cpp
src/gui/loginrequireddialog/basicloginwidget.cpp
src/gui/loginrequireddialog/basicloginwidget.h
src/gui/loginrequireddialog/basicloginwidget.ui
src/gui/newwizard/pages/basiccredentialssetupwizardpage.cpp
src/resources/wizard/style.qss

Remove app password hints

---

src/gui/newwizard/pages/accountconfiguredwizardpage.cpp
src/gui/newwizard/states/accountconfiguredsetupwizardstate.cpp

Always disable VFS when experimental features are disabled

---

src/plugins/vfs/suffix/vfs_suffix.cpp

Suffix VFS: only apply local modtime changes on download

---

shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/FinderSync.m

Fixes: #10056
Downside sometimes the menu is empty

Mac: enable context menu on root folders

---

src/gui/application.cpp
src/gui/application_p.h
src/gui/main.cpp

Log when we get invoked by QSingleApplication

---

test/testoauth.cpp

Implement test cases for oidc dynamic client registration

---

.github/workflows/main.yml

Revert "Ci: Run unit tests a as non root"

---

changelog/unreleased/10101
src/gui/folderstatusmodel.cpp
src/gui/folderstatusmodel.h

Directly display sync status changes

---

test/testsyncengine.cpp
test/testsyncmove.cpp
test/testutils/syncenginetestutils.h

So it can be re-used in other tests.

Move OperationCounter into the utils

---

src/libsync/networkjobs.cpp

With the async upload some entries might have a status code 425 which is a valid code.

Handle propfind replies with status 425 as valid.

---

src/gui/shareusergroupwidget.cpp

Hide private links in share dialog if disabled on the server

---

src/gui/newwizard/pages/accountconfiguredwizardpage.cpp

... unless `enableExperimentalFeatures()` is set.

Make sure VFS is not forced if it is experimental

---

src/gui/accountsettings.cpp
src/gui/creds/httpcredentialsgui.cpp
src/gui/creds/httpcredentialsgui.h
src/gui/loginrequireddialog/basicloginwidget.ui
src/gui/loginrequireddialog/loginrequireddialog.cpp
src/gui/loginrequireddialog/loginrequireddialog.ui
src/gui/loginrequireddialog/oauthloginwidget.cpp
src/gui/loginrequireddialog/oauthloginwidget.h
src/gui/loginrequireddialog/oauthloginwidget.ui

I'm sure this could and should be polished. We are going to work on these widgets soon again when integrating them into the wizard, which is a good chance to improve the UX.

Allow user to retry OAuth2/OIDC login

---

src/common/asserts.h
src/gui/folder.cpp
src/gui/folder.h
src/libsync/abstractnetworkjob.cpp
src/libsync/abstractnetworkjob.h
src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp
src/libsync/networkjobs.cpp
src/libsync/networkjobs.h
src/libsync/owncloudpropagator_p.h
src/libsync/propagatedownload.cpp
test/testowncloudpropagator.cpp

Depends on https://github.com/owncloud/client/pull/10181

Port RequestEtagJob -> to PropFindJob

---

src/gui/newwizard/states/serverurlsetupwizardstate.cpp

Restore server URL in wizard when errors occur

---

test/gui/shared/steps/steps.py

We want to gracefully wait for the sync pattern to match whenever there are changes in the file/folder. This means, after a certain operation is done to the file/folder, we wait for the sync pattern to match (to determine that the sync has been completed) but sometimes the test code might run slow or we might do other operations before waiting for sync complete. This can cause the sync pattern to not match at the time of waiting for the sync to complete.
Thus, in order to avoid such scenario (which might be rare as of now), this PR has added last minute check for the sync status.
Means, whenever a matching sync pattern fails, it will now check the last sync status of the resource and passes the step if the status is `STATUS:OK` and throws if other.
Some concerns:
This works best while …

[gui-tests] Check the last sync status if sync pattern doesn't match

---

test/testchunkingng.cpp
test/testutils/syncenginetestutils.h

The unit test is supposed to fail

 Implement a test for chunking ng fail due to a lock

---

.drone.star

In PR https://github.com/owncloud/client/pull/9644, some independent pipeline steps were run in parallel in the hopes of reducing pipeline runtime. This came with one side effect: those parallel steps ran before `skip-if-unchanged` step (see https://github.com/owncloud/client/issues/10202). In order to prevent this behavior, dependency could be added to those parallel steps and some conditional logic to cope with cron builds.
This implementation seems to cluster the drone config with more dependencies and the config might look complex and could be brittle in the future. So this PR has removed dependencies to run all the steps sequentially. The pipeline runtimes with parallel and sequential builds are very close to each other.
Fixes https://github.com/owncloud/client/issues/10202

[CI] Run pipeline steps sequentially

---

src/libsync/creds/oauth.cpp

This commit also improves the code structure a little.

Improve OAuth related logging

---

changelog/unreleased/10031

https://github.com/owncloud/client-desktop-vfs-win/commit/495f8aac5725702abcc8e0c4cbb9e4710347c830

Add changelog entry for vfs change

---

src/gui/accountsettings.cpp
src/gui/creds/httpcredentialsgui.cpp
src/gui/creds/httpcredentialsgui.h

Fixes #10212 among some other potential bugs.

Fix issues around "login required dialog"

---

.drone.star

Make directory paths reusable using global path dictionary.
Part of https://github.com/owncloud/QA/issues/734

[tests-only] Use global dir path variables

---

test/gui/shared/scripts/bdd_hooks.py
test/gui/shared/scripts/pageObjects/SharingDialog.py
test/gui/shared/steps/steps.py

With this PR, the env variable configs get the highest priority and override any other config for GUI tests. Removing unused variables, libs, functions, and steps are also done in this PR to remove code smells.

[tests-only] Refactor GUI test code (p1)

---

changelog/unreleased/10184
src/gui/folder.cpp
src/gui/folder.h
src/gui/folderman.cpp
src/gui/owncloudgui.cpp

Update the folder icon on every run

---

src/gui/newwizard/setupwizardwindow.cpp
src/gui/newwizard/setupwizardwindow.h

Ask before closing the wizard

---

src/libsync/appprovider.cpp

Handle http error on open in web

---

src/gui/thumbnailjob.cpp

Fix thumbnail job after the introduction of spaces

---

src/gui/folderstatusmodel.cpp

Fix progress string

---

src/common/utility_mac.mm

Instead of using a dictionary for the value of KeepAlive, setting it to @NO will keep launchd from relaunching the client.

macOS: Fix restart-after-quit

---

src/common/ownsql.h

Clear the debug string, don't append to previous values.
Fixes: #10288

Fix sqlite log

---

src/libsync/propagatedownload.cpp

readyRead might not be connected at the time

Remove broken assert

---

src/gui/accountsettings.cpp
src/gui/creds/httpcredentialsgui.cpp
src/gui/creds/httpcredentialsgui.h

Alternative approach for #10301.
Fixes https://github.com/owncloud/client/issues/10300.

Fix OAuth retry

---

src/cmd/cmd.cpp
src/gui/accountsettings.cpp
src/gui/connectionvalidator.cpp
src/gui/folderman.cpp
src/gui/owncloudgui.cpp
src/libsync/account.cpp
src/libsync/account.h

Don't prevent sync on unknown servers

---

.drone.star

Updated oCIS server version to 2.0.0-rc.2

[tests-only] Update oCIS version

---

src/gui/activitywidget.cpp
src/gui/notificationconfirmjob.cpp
src/gui/notificationconfirmjob.h
src/libsync/networkjobs/jsonjob.cpp
src/libsync/networkjobs/jsonjob.h

Fix notification actions

---

.github/workflows/translate.yml

Should be merged once we know for sure we won't need a 3.0.

Update translations to 3.1

---

src/libsync/logger.cpp

Enforce max log files limit properly

---

translations/.tx/config
translations/Makefile

Blocked by https://github.com/owncloud-ci/transifex/pull/52.
Should fix #10348.

Update to new transifex CLI written in Go

---

src/libsync/logger.cpp

Ensure to use abs path for log file

---

changelog/unreleased/10294
src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/libsync/discoveryphase.cpp
test/testremotediscovery.cpp

Add an option to trigger a reconnect

---

.drone.star

Bump middleware version to v1.8.3

[gui-tests] Bump middleware version to v1.8.3

---

test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
test/gui/shared/scripts/pageObjects/AccountSetting.py
test/gui/shared/scripts/pageObjects/Activity.py
test/gui/shared/scripts/pageObjects/EnterPassword.py
test/gui/shared/scripts/pageObjects/PublicLinkDialog.py
test/gui/shared/scripts/pageObjects/SharingDialog.py
test/gui/shared/scripts/pageObjects/SyncConnection.py
test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py
test/gui/shared/steps/steps.py

- Removed assertions from POs and When steps
- Make POs static
Part of https://github.com/owncloud/client/issues/10353

[gui-tests] Remove assertions from POs and When steps

---

test/gui/shared/scripts/pageObjects/PublicLinkDialog.py

Remove manual formatting of date but instead parse it using the `datetime` module
Fixes https://github.com/owncloud/client/issues/10383

[gui-tests] Fix date parsing

---

changelog/unreleased/10398
src/common/utility.cpp
src/common/utility.h
src/common/utility_unix.cpp

Fix build on non linux unix

---

src/gui/accountsettings.cpp

Fix reconnect button enabled when logged out

---

test/gui/tst_deletFilesFolders/test.feature

This pr adds test related to deleting a file and a folder out of all created files and folders

[tests-only] Add GUI test related to deleting a file and a folder

---

.drone.star
test/gui/drone/notification_template.sh

With this PR, the chat notification can be sent to multiple chat channels. And the GUI tests reports are uploaded both on build success and failure.
Part of https://github.com/owncloud/QA/issues/794

[gui-tests] Notify with gui tests reports on success

---

changelog/unreleased/10408
src/libsync/creds/httpcredentials.cpp

If the keychain does not provide valid credentials log out

---

src/libsync/graphapi/drives.cpp

Identify the 'Shares' space by its uuid

---

test/gui/shared/scripts/helpers/FilesHelper.py
test/gui/shared/scripts/helpers/SpaceHelper.py
test/gui/shared/steps/spaces_context.py
test/gui/tst_spaces/test.feature
test/gui/tst_spaces/test.py

Add test cases for project space member with Viewer role
Scenarios:
```feature
Scenario: User with viewer role can open the file
Scenario: User with viewer role cannot edit the file
``` 
Part of https://github.com/owncloud/QA/issues/789

[gui-tests] Add tests for space member with Viewer role

---

changelog/unreleased/9829
src/common/filesystembase.cpp
src/common/filesystembase.h
src/common/ownsql.cpp
src/common/ownsql.h
src/common/preparedsqlquerymanager.h
src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/common/syncjournalfilerecord.h
src/common/vfs.h
src/libsync/creds/httpcredentials.cpp
src/libsync/discoveryphase.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/propagateremotemkdir.cpp
src/libsync/propagateupload.cpp
src/libsync/propagateupload.h
src/libsync/propagateuploadng.cpp
src/libsync/propagateuploadtus.cpp
src/libsync/propagateuploadv1.cpp
src/libsync/syncengine.cpp
src/libsync/syncoptions.h

Upload locked files

---

src/libsync/creds/webfinger.cpp

This reverts commit 2499b5ffdd1eb3f555fba23043392df050529377.

Revert "Fix duplicate acct: in Webfinger resource ID"

---

changelog/unreleased/10441
src/gui/newwizard/pages/webfingersetupwizardpage.cpp

Fix next button on Webfinger setup wizard page

---

changelog/unreleased/10468
src/gui/folderman.cpp

Use selective sync result

---

src/libsync/platform_mac_deprecated.mm

Remove log message that is printed before the logger is initialised

---

.drone.star
test/gui/drone/notification_template.sh

Port changes from https://github.com/owncloud/client/pull/10424/files and enable drone ci for 3.* branch

Enable drone ci for 3.2 branch

---

.drone.star
test/gui/drone/notification_template.sh

Upload squish gui reports on test failure only.

[ci] Upload GUI reports on failure only

---

src/libsync/platform_unix.cpp
src/libsync/theme.cpp

Document plugin dir in version string

---

src/gui/newwizard/enums.cpp

Improve wizard pages' names

---

changelog/unreleased/10500
src/libsync/creds/credentialmanager.cpp
src/libsync/creds/httpcredentials.cpp

Don't save empty credentials

---

.gitmodules
src/CMakeLists.txt
src/crashreporter/CMakeLists.txt
src/gui/CMakeLists.txt

Depends on https://github.com/dschmidt/libcrashreporter-qt/pull/36

Use system libcrashreporter

---

src/common/syncjournaldb.h

Fix assert

---

.drone.star
test/gui/drone/notification_template.sh

Forward port drone config changes (#10508) from 3.2 to the master

[ci] Notify chat with gui reports on tag events (#10508)

---

test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
test/gui/shared/steps/account_context.py
test/gui/tst_addAccount/test.feature

This pr adds test scenario related to:
* checking availability of local sync directory option in advanced configuration.
* checking  default sync option

[tests-only] Added GUI test scenario to check local sync and default sync options

---

src/gui/newwizard/jobs/checkbasicauthjobfactory.cpp
src/gui/newwizard/jobs/checkbasicauthjobfactory.h
src/gui/newwizard/jobs/resolveurljobfactory.cpp
src/gui/newwizard/jobs/resolveurljobfactory.h
src/libsync/abstractcorejob.cpp
src/libsync/abstractcorejob.h
src/libsync/determineauthtypejobfactory.cpp
src/libsync/determineauthtypejobfactory.h
src/libsync/networkjobs/checkserverjobfactory.cpp
src/libsync/networkjobs/checkserverjobfactory.h
src/libsync/networkjobs/fetchuserinfojobfactory.cpp
src/libsync/networkjobs/fetchuserinfojobfactory.h

AbstractCoreJobFactory: Don't inherit from QObject

---

changelog/unreleased/10406
src/libsync/platform_win.cpp

Depends on https://github.com/owncloud/client/pull/10532
Fixes: #10406

Set dpi scale factor to PassThrough

---

changelog/unreleased/10552

Add changelog for issue 10552

---

changelog/unreleased/10494
src/libsync/abstractnetworkjob.cpp
src/libsync/account.cpp
src/libsync/account.h
src/libsync/creds/httpcredentials.cpp

Emit proper signal on oauth error

---

changelog/unreleased/10564
src/gui/newwizard/jobs/checkbasicauthjobfactory.cpp
src/libsync/networkjobs/fetchuserinfojobfactory.cpp

Fix auth encoding issue

---

changelog/unreleased/10453
src/gui/folderstatusdelegate.cpp
src/gui/folderstatusmodel.cpp
src/gui/folderstatusmodel.h

I'd suggest to remove the progress bar we display with oc10

Display quota in status delegate

---

src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h

In addition the path can be used for #9311

Add path to PropagatorJobs for debugging

---

src/libsync/owncloudpropagator.cpp

If you know what exactly we do in 
https://github.com/owncloud/client/blob/3e65a1214c6b27cff824a5d1fcff020e1d378263/src/libsync/owncloudpropagator.cpp#L446-L448
Please elaborate, we really need to document the algorithm.

Cleanup algorithm for deletion of directories

---

changelog/unreleased/10577
src/gui/folderstatusdelegate.cpp
src/gui/folderstatusmodel.cpp

Display spaces subtitle

---

src/gui/folderstatusmodel.cpp
src/libsync/graphapi/spacesmanager.cpp
src/libsync/graphapi/spacesmanager.h

Ensure delegate is redrawn when spaces are refreshed

---

changelog/unreleased/9311
src/libsync/owncloudpropagator.cpp
src/libsync/owncloudpropagator.h
test/testpermissions.cpp
test/testsyncengine.cpp

For the new unit test see https://github.com/owncloud/client/pull/10582

Only abort folder delete jobs in fodlers with errors

---

changelog/unreleased/9700
src/libsync/discovery.cpp
src/libsync/discoveryphase.cpp
src/libsync/discoveryphase.h

Display more user friendly error on deleted space

---

src/gui/socketapi/socketapi.cpp
src/gui/socketapi/socketapi.h

Fix crash #10603

---

changelog/unreleased/10607
src/libsync/discovery.cpp
src/libsync/propagatedownload.cpp

Set content length on download

---

src/libsync/theme.cpp

Replace owncloud.org urls with owncloud.com

---

src/common/filesystembase.cpp

There is one string concatenation in `FileSystem::isChildPathOf`, which is hit quite often: many directory paths will not end with a `/`, for example in `OwncloudPropagator::start`.

Eliminate possible string concatenation

---

changelog/unreleased/10634
src/libsync/theme.cpp

Always point to latest help

---

changelog/unreleased/10254
src/gui/folder.cpp

DeleteAllFiles: Default to keep all files

---

changelog/unreleased/10427
src/common/filesystembase.cpp
src/common/filesystembase.h
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/folderwizard/folderwizard.cpp
src/gui/owncloudgui.cpp
test/testfolderman.cpp

Escape the base folder name

---

src/gui/settingsdialog.cpp

Url button must be non checkable

---

src/gui/folder.cpp

Fix crashed caused by shadowing of a variable

---

src/libsync/creds/oauth.cpp

Fix oc10 oauth redirects

---

changelog/unreleased/10654
src/libsync/creds/httpcredentials.cpp

Don't invalidate oauth refresh token on ConnectionRefusedError

---

src/libsync/CMakeLists.txt
src/libsync/account.cpp
src/libsync/account.h
src/libsync/networkjobs/resources.cpp
src/libsync/networkjobs/resources.h
test/testutils/testutilsloader.cpp

First draft, feel free to finish. Mostly requires documentation.
Prerequisite for #10617.

Resources cache and job

---

src/gui/spaces/spacesdelegate.cpp
src/gui/spaces/spacesmodel.cpp

Depends on https://github.com/owncloud/client/pull/10623

Improve spaces browser layout

---

src/gui/generalsettings.cpp

Connect currentIndexChanged after the data was populated

---

.drone.star

Allow CI builds to run when push to `4` branch is made.

[ci] Add 4 branch as trigger target

---

src/libsync/graphapi/spacesmanager.cpp

Set a timeout for spaces manager requsts

---

src/gui/newwizard/states/accountconfiguredsetupwizardstate.cpp

WebFinger: use final instance for sync folder suggestion

---

src/gui/folder.cpp

Reset the sync result before we start the discovery not after

---

src/libsync/graphapi/spacesmanager.cpp

This fixes spaces listing after a relogin
Fixes: #10721

Connect legacy signal

---

src/gui/generalsettings.cpp
src/gui/generalsettings.h

Cleanup autoupdate setup

---

src/gui/folderstatusdelegate.cpp

Fix alignment of quota with rtl languages

---

test/gui/drone/notification_template.sh

[CI] Notify with meaningful name during tag run

---

src/libsync/propagateupload.cpp
test/testallfilesdeleted.cpp
test/testchunkingng.cpp
test/testcredentialmanager.cpp
test/testremotediscovery.cpp
test/testselectivesync.cpp
test/testutils/syncenginetestutils.cpp
test/testutils/syncenginetestutils.h

We should probably enable strict string handling for the tests

Qt6: Fix unit tests

---

src/common/utility.cpp
src/common/utility.h
src/gui/protocolitem.cpp
src/gui/syncrunfilelog.cpp
src/libsync/abstractnetworkjob.cpp
src/libsync/discoveryphase.cpp
test/testutils/syncenginetestutils.cpp

We accidently used RFC2822Date which with Qt5 also parsed RFC1123. Qt6 howerver failed.

Properly parse RFC1123

---

test/gui/shared/scripts/helpers/ConfigHelper.py
test/gui/shared/steps/file_context.py
test/gui/tst_syncing/test.feature

This pr adds test cases related to ``` Sync works for .zip/.rar files with elaborate internal folder structures ```

[tests-only][full-ci]Add GUI test related to Sync zip file

---

.drone.star

[CI] Build unit tests on fedora image

---

test/gui/webUI/pnpm-lock.yaml

Fixes https://github.com/owncloud/client/issues/10864

Update pnpm-lock file to new format

---

changelog/unreleased/261
src/gui/application.cpp
src/gui/application.h
src/gui/clientproxy.cpp
src/gui/clientproxy.h
src/gui/connectionvalidator.cpp
src/gui/networksettings.cpp
src/gui/networksettings.h
src/libsync/configfile.cpp
src/libsync/configfile.h

Store the proxy password in the keychain

---

changelog/unreleased/enterprise-5743
src/gui/newwizard/states/serverurlsetupwizardstate.cpp

Fixes: https://github.com/owncloud/enterprise/issues/5743

Correctly follow redirects

---

changelog/unreleased/10860
src/gui/folderman.cpp

Fix empty systray message

---

test/gui/tst_addAccount/test.feature

Fixes https://github.com/owncloud/client/issues/10885

[full-ci][gui-tests] Fix test expectation

---

src/gui/accountstate.cpp
src/gui/application.cpp
src/gui/application.h

Use QNetworkInformation to trigger connection checks

---

changelog/unreleased/10313
src/libsync/httplogger.cpp

Use QNetworkReply::requestSent to improve httplog

---

src/gui/issueswidget.cpp

Fix missing include

---

changelog/unreleased/enterprise-5682
src/gui/issueswidget.cpp
src/libsync/discovery.cpp
src/libsync/localdiscoverytracker.cpp
src/libsync/owncloudpropagator.cpp
src/libsync/syncfileitem.cpp
src/libsync/syncfileitem.h

Fixes: https://github.com/owncloud/enterprise/issues/5682

Fix sync issues not cleared

---

changelog/unreleased/10946
src/cmd/cmd.cpp

Fix cmd dav user

---

src/gui/issueswidget.cpp
src/gui/issueswidget.ui
src/libsync/syncfileitem.cpp
src/libsync/syncfileitem.h

And also handle the `SyncFileItem::Status::FilenameReserved` enum value.
Fixes: #10884

Fix filter reloading

---

changelog/unreleased/10939
src/gui/owncloudgui.cpp
src/gui/owncloudgui.h

Cleanup systray menu

---

src/libsync/abstractnetworkjob.cpp

Disable setDecompressedSafetyCheckThreshold

---

src/gui/creds/httpcredentialsgui.h
src/gui/newwizard/setupwizardaccountbuilder.cpp
src/gui/newwizard/setupwizardaccountbuilder.h
src/gui/newwizard/setupwizardcontroller.cpp

Cleanup the use of davUser vs loginUser in wizard code

---

changelog/unreleased/11016
src/gui/owncloudgui.cpp

Delete settings dialog immediately

---

changelog/unreleased/10619
src/libsync/accessmanager.cpp

Always send a language header in all requests

---

src/gui/accountsettings.ui

Fix layout of selective sync widged

---

changelog/unreleased/10976
src/gui/main.cpp

I'm not happy with the change log entry.
Windows support is sub optimal.

Add `--cmd` to gui client

---

src/gui/issueswidget.cpp
src/gui/models/models.cpp

Fixes finding from:
- https://github.com/owncloud/client/issues/10884#issuecomment-1649818735
Also fixes interaction with the caller side of the method populating the menu.

Fix account check marks in filter menu

---

src/gui/creds/httpcredentialsgui.cpp

Tell user which basic auth account they need to log in to

---

src/crashreporter/main.cpp
src/libsync/platform_win.cpp

Use a fuzzy check to decide whether we need fusion style. Aligned with: https://github.com/qt-creator/qt-creator/blob/master/src/app/main.cpp#L631

With Qt6 devicePixelRatio appears to have changed

---

src/crashreporter/main.cpp
src/libsync/platform_win.cpp

This fixes a bug introduced in https://github.com/owncloud/client/pull/11103

Fix logic for fusion theme test

---

src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/gui/application.cpp
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/main.cpp
test/testspacesmigration/testspacesmigration.cpp

Prevent use of older clients with already-upgraded databases

---

src/common/vfs.cpp
src/common/vfs.h
src/gui/folder.cpp
test/testutils/syncenginetestutils.cpp

Preparing: [#9309](https://github.com/owncloud/client/issues/9309)

Make sync engine available to vfs plugins

---

src/gui/scheduling/syncscheduler.cpp

Fixes: #11104
See https://github.com/owncloud/client/blob/9d086119d0457b2fd6e48b41273c6357c2111565/src/gui/folderman.cpp#L744

Restore follow up sync behaviour on errors

---

.github/release_template.md

Discussed here:
- https://github.com/owncloud/enterprise/issues/5898#issuecomment-1678578721

Update desktop client SBOM as part of the release process

---

src/gui/newwizard/pages/accountconfiguredwizardpage.cpp
src/gui/newwizard/pages/accountconfiguredwizardpage.ui

Make sure all elements in row have same height

---

changelog/unreleased/10223
src/common/vfs.h
src/csync/csync.h
src/gui/folder.cpp
src/libsync/discovery.cpp
src/libsync/owncloudpropagator.cpp
test/testsyncconflict.cpp

See https://github.com/owncloud/client-desktop-vfs-win/pull/65
Fixes: #10223

Fix placeholder replaced by folder

---

test/testsyncmove.cpp

Fix unit test after #11144 was merged

---

src/gui/folder.cpp
src/gui/folder.h
src/gui/scheduling/etagwatcher.cpp
src/gui/scheduling/syncscheduler.cpp

Fix multiple remove all files dialog popups

---

changelog/unreleased/11190
src/gui/folderstatusdelegate.cpp
src/gui/folderstatusmodel.cpp
src/gui/folderwizard/CMakeLists.txt
src/gui/folderwizard/folderwizardremotepath.cpp
src/gui/selectivesyncwidget.cpp
src/gui/sharedialog.cpp
src/gui/shareusergroupwidget.cpp

Consistently use folder icon

---

src/libsync/abstractnetworkjob.cpp

https://cache.owncloud.com/public/owncloud/client/16517/ocis/guiReportUpload/stacktrace.log

Fix crash: Parent migt no longer exist

---

changelog/unreleased/11168
src/gui/accountstate.cpp
src/gui/accountstate.h
src/gui/folder.cpp

Only sync once the capabilities where fetched

---

src/gui/settingsdialog.cpp

Fix crash on account removal

---

src/libsync/graphapi/spacesmanager.cpp

Fix crash in network job destructor

---

test/testoauth.cpp

Add unit test for token refresh with dynamic registration

---

src/gui/newwizard/pages/accountconfiguredwizardpage.cpp
src/gui/newwizard/pages/accountconfiguredwizardpage.ui

Partly reverts https://github.com/owncloud/client/pull/11127
Fixes: #11156

Unify addvanced buttons

---

src/gui/accountsettings.cpp
src/gui/creds/httpcredentialsgui.cpp
src/gui/loginrequireddialog/oauthloginwidget.cpp
src/gui/loginrequireddialog/oauthloginwidget.h
src/gui/newwizard/pages/oauthcredentialssetupwizardpage.cpp
src/gui/newwizard/pages/oauthcredentialssetupwizardpage.h
src/gui/newwizard/states/oauthcredentialssetupwizardstate.cpp

Only enable oauth buttons once we got an auth url

---

test/gui/tst_deletFilesFolders/test.feature

This pr adds test for creation and deletion of file with special characters in it's name.

[full-ci] [tests-only] add test for syncing of a file with special characters

---

src/common/utility.cpp
src/common/utility.h
src/gui/selectivesyncwidget.cpp

Fixes a regression introduced in #11237.
Fixes #11255.

Properly display directory size in selective sync widget

---

test/gui/shared/scripts/pageObjects/Activity.py

Perform mouse click to change Activity between tabs
Fixes https://github.com/owncloud/client/issues/11218

[gui-tests][full-ci] Perform mouseClick to open tabs

---

src/libsync/creds/credentialmanager.cpp

Log if the desktop client does not know about the credentials

---

changelog/unreleased/11275
src/crashreporter/main.cpp
src/libsync/platform_win.cpp

Always use fusion style on Windows

---

src/libsync/creds/credentialmanager.cpp

Depends on https://github.com/owncloud/client/pull/11310

Fix timeout

---

test/gui/tst_checkAlltabs/test.feature

Removing `@skip` tag for open log dialog test scenario.

[tests-only] [full-ci] removing skip tag for open log dialog test scenario 

---

changelog/unreleased/11308
src/gui/application.cpp
src/gui/folderman.cpp
src/gui/folderman.h

Schedule sync once we are connected

---

test/gui/shared/scripts/pageObjects/AccountSetting.py
test/gui/shared/steps/account_context.py
test/gui/tst_loginLogout/test.feature

Added test scenario for logging in with incorrect password and again logging in with correct password in oc10 server.

[tests-only] [full-ci] add test scenario for logging in with incorrect password

---

test/gui/shared/scripts/helpers/SetupClientHelper.py
test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
test/gui/shared/steps/account_context.py
test/gui/tst_addAccount/test.feature
test/gui/tst_sharing/test.feature
test/gui/tst_syncing/test.feature

Combine similar steps and remove unused ones. Reword  steps to reduce confusion

[gui-tests][full-ci] update account connection scenario

---

src/common/syncjournaldb.cpp
src/common/syncjournaldb.h
src/gui/folderman.cpp

Remove the migration of sync database files older than 6 years.

Remove migration of old db files

---

src/libsync/creds/credentialmanager.cpp

Deleting a running QtKeychain job can cause a crash

---

src/gui/folderman.cpp

Only enqueue if we can sync

---

changelog/unreleased/11379
src/libsync/discovery.cpp

Fix call to ::abort() instead of sync->abort()

---

test/gui/shared/scripts/bdd_hooks.py
test/gui/shared/scripts/helpers/SetupClientHelper.py
test/gui/shared/scripts/helpers/SyncHelper.py
test/gui/shared/scripts/names.py
test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
test/gui/shared/scripts/pageObjects/AccountSetting.py
test/gui/shared/scripts/pageObjects/EnterPassword.py
test/gui/shared/scripts/pageObjects/Toolbar.py
test/gui/shared/steps/account_context.py
test/gui/shared/steps/spaces_context.py
test/gui/tst_loginLogout/test.feature

[full-ci][gui-tests]  Extend oAuth2 scenario

---

src/libsync/httplogger.cpp

Fixes: #11224
```
23-11-22 11:42:00:314 [ info sync.httplogger ]:	REQUEST 33ea6fe2-2f0e-456a-ad78-811dca54003c {"request":{"body":{},"header":{"Accept":"*/*","Accept-Language":"en_CH","Authorization":"Basic [redacted]","OC-Connection-Validator":"desktop","Original-Request-ID":"33ea6fe2-2f0e-456a-ad78-811dca54003c","User-Agent":"Mozilla/5.0 (Windows) mirall/6.0.0-git (ownCloud, windows-10.0.22631 ClientArchitecture: x86_64 OsArchitecture: x86_64)","X-Request-ID":"33ea6fe2-2f0e-456a-ad78-811dca54003c"},"info":{"id":"33ea6fe2-2f0e-456a-ad78-811dca54003c","method":"GET","url":"http://demo.testlab.owncloud.works/owncloud/status.php"}}}
23-11-22 11:42:00:361 [ info sync.httplogger ]:	RESPONSE 33ea6fe2-2f0e-456a-ad78-811dca54003c {"response":{"body":{"data":"{\"installed\":true,\"maintenance\":fa …
```

Use json to format http logs

---

src/libsync/httplogger.cpp

Log http requests for cached responses

---

.drone.star

Use oCIS version 4
previously it was 3.0.0

Bump oCIS version to 4

---

.drone.star
test/gui/shared/scripts/helpers/SyncHelper.py
test/gui/tst_addAccount/test.feature
test/gui/tst_moveFilesFolders/test.feature

Fix sync pattern matching of a single resource. This will reduce the test execution time.

[gui-tets][full-ci] Fix sync pattern checking for a single resource

---

src/common/utility.cpp
test/testutility.cpp

Also simplify the control flow in `Utility::timeAgoInWords`.

Remove unreachable code

---

changelog/unreleased/11274
src/gui/fetchserversettings.cpp

Fix queuing of the fetch user job

---

changelog/unreleased/11304
src/gui/aboutdialog.cpp
src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/accountsettings.ui
src/gui/accountstate.cpp
src/gui/creds/httpcredentialsgui.cpp
src/gui/folder.cpp
src/gui/generalsettings.cpp
src/gui/newwizard/jobs/resolveurljobfactory.cpp
src/gui/newwizard/setupwizardwindow.cpp
src/gui/owncloudgui.cpp
src/gui/owncloudgui.h
src/gui/settingsdialog.cpp
src/gui/settingsdialog.h
src/gui/settingsdialog.ui
src/gui/sharedialog.cpp
src/gui/sharedialog.h
src/gui/updater/appimageupdater.cpp
src/gui/updater/ocupdater.cpp

-- | --
-- | -- | --
Fixes: https://github.com/owncloud/client/issues/11304
Fixes: https://github.com/owncloud/client/issues/11032
Fixes: https://github.com/owncloud/client/issues/11208
- https://github.com/owncloud/client/issues/11304
- https://github.com/owncloud/client/issues/11032
- https://github.com/owncloud/client/issues/11208

Less modal

---

test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
test/gui/shared/scripts/pageObjects/PublicLinkDialog.py
test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py

Clear input text value before typing anything. If not cleared then the new text will just be appended to the existing one.
Also required for master branch

[gui-tests][full-ci] clear input text before typing

---

changelog/unreleased/11460

This is the fix for the crash in the folder watcher on Linux

Add changelog entry for #11475

---

changelog/unreleased/11320

Add changelog for move-files-to-trash

---

src/common/common.cmake
src/common/restartmanager.cpp
src/common/restartmanager.h
src/gui/generalsettings.cpp
src/gui/main.cpp
src/gui/owncloudgui.cpp
src/gui/updater/ocupdater.cpp

CC #11132.
The second commit cleans up the updater a bit.

Fix restart of AppImage after update has finished

---

cmake/modules/OCBundleResources.cmake

Partly revert 2384695

---

test/gui/shared/steps/account_context.py
test/gui/shared/steps/sharing_context.py
test/gui/tst_addAccount/test.feature
test/gui/tst_sharing/test.feature

oc10 GUI tests is failing in master branch
https://drone.owncloud.com/owncloud/client/17967/2/15

[gui-tests][full-ci] assert text contains

---

CMakeLists.txt
cmake/modules/OCAddVfsPlugin.cmake
src/common/common.cmake
src/common/plugin.cpp
src/csync/CMakeLists.txt
src/libsync/CMakeLists.txt
src/resources/CMakeLists.txt

Nowadays, we don't install multiple client into the same root, so multiple clients won't clash.
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          08/04/2024    15:02                org
-a---          08/04/2024    15:02         103424 ownCloud_vfs_off.dll
-a---          08/04/2024    15:02        1071784 ownCloud_vfs_off.ilk
-a---          08/04/2024    15:02        2658304 ownCloud_vfs_off.pdb
-a---          08/04/2024    15:02         144896 ownCloud_vfs_suffix.dll
-a---          08/04/2024    15:02        1399464 ownCloud_vfs_suffix.ilk
-a---          08/04/2024    15:02        3067904 ownCloud_vfs_suffix.pdb
-a---          08/04/2024    15:02         567808 ownCloud_vfs_wincfapi.dll
-a--- …
```

Don't rename libs depending on the branding

---

.drone.star
test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py

Updated docker images:
`owncloudci/client:fedora-38-amd64` -> `owncloudci/client:fedora-39-amd64`
`owncloudci/squish:fedora-38-7.1.1-qt64x-linux64` -> `owncloudci/squish:fedora-39-7.2.1-qt66x-linux64`
Fixes https://github.com/owncloud/client/issues/11597

[full-ci][gui-tests] update docker images

---

test/gui/shared/scripts/names.py
test/gui/shared/scripts/pageObjects/AccountSetting.py
test/gui/shared/scripts/pageObjects/SyncConnection.py
test/gui/shared/steps/file_context.py
test/gui/tst_addAccount/test.feature
test/gui/tst_vfs/test.feature

Adjust the GUI tests according to the changes in desktop client UI.
PR: https://github.com/owncloud/client/pull/11365 and https://github.com/owncloud/client/pull/11570

[gui-tests][full-ci] fix windows VFS tests

---

changelog/unreleased/11450
src/gui/socketapi/socketapi.cpp

Fix context menu entry Copy public link to clipboard

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/accountsettings.ui

Improve accassability of account menu

---

src/gui/accountsettings.cpp
src/gui/activitywidget.cpp
src/gui/issueswidget.cpp
src/gui/protocolwidget.cpp

Improve accassability of various menus

---

test/gui/shared/scripts/pageObjects/Toolbar.py
test/gui/shared/steps/account_context.py
test/gui/tst_addAccount/test.feature

Added a test to check that the newly added account get the focus (is opened)
Coverage: #11642

[gui-tests][full-ci] add test to check focus on newly added account

---

test/gui/shared/scripts/pageObjects/AccountSetting.py
test/gui/shared/scripts/pageObjects/EnterPassword.py
test/gui/shared/steps/account_context.py

Fixed logout button selector when running tests against oc10 server

[gui-tests][full-ci] fix logout button selector

---

test/gui/webUI/package.json
test/gui/webUI/pnpm-lock.yaml

Update playwright and remove unnecessary library

[gui-tests][full-ci] update playwright

---

src/gui/qml/AccountButton.qml
src/gui/qml/FolderError.qml
src/gui/spaces/qml/SpaceDelegate.qml
src/resources/resources.cpp

Ensure we query the correct icon size

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/accountsettings.ui
src/gui/accountstate.cpp
src/gui/accountstate.h
src/gui/qml/FolderDelegate.qml
src/gui/qmlutils.h
src/gui/settingsdialog.cpp
src/gui/settingsdialog.h
src/libsync/theme.h

Depends on: https://github.com/owncloud/client/pull/11684

Move add acount button to qml

---

src/gui/newwizard/pages/serverurlsetupwizardpage.cpp
src/gui/newwizard/pages/serverurlsetupwizardpage.ui

Improve a11y in setup wizard

---

src/gui/notificationwidget.cpp
src/gui/notificationwidget.ui

Set a11y name on notification icon

---

src/gui/activitywidget.cpp

Once an account with activities is it will be displayed.

Hide activities by default

---

test/gui/shared/scripts/helpers/SetupClientHelper.py
test/gui/shared/scripts/names.py
test/gui/shared/scripts/pageObjects/SyncConnection.py
test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py
test/gui/shared/steps/account_context.py
test/gui/shared/steps/sync_context.py
test/gui/tst_syncing/test.feature

Merge remote-tracking branch 'origin/5' to master

[full-ci] Merge remote-tracking branch 'origin/5'

---

test/gui/shared/scripts/pageObjects/SyncConnectionWizard.py

This PR removes the duplicate selectors from SyncConnectionWizard.py

[gui-tests][full-ci] Remove duplicate selectors

---

src/gui/owncloudgui.cpp

Maximized window reverts to default

---

changelog/unreleased/11743
src/gui/guiutility_unix.cpp
src/gui/guiutility_win.cpp

Remove support for multiple Linux shell extensions

---

src/gui/folderman.cpp
src/gui/folderman.h

1: Add FolderMan::isSpaceSynced

---

changelog/unreleased/enterprise-6761
src/gui/MacOSXBundleInfo.plist

Fixes: https://github.com/owncloud/enterprise/issues/6761

Set CFBundleAllowMixedLocalizations true to fix the language reported by the os

---

changelog/unreleased/11760
src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/qml/FolderDelegate.qml
src/libsync/theme.h

3: Display how many spaces are not synced

---

src/libsync/propagateupload.cpp

No changelog needed, this code path only affects unsupported servers

Handle error case

---

test/gui/shared/scripts/names.py
test/gui/shared/scripts/pageObjects/Activity.py
test/gui/shared/steps/sync_context.py
test/gui/tst_activity/test.feature
test/gui/tst_activity/test.py

This PR adds the test case to filter the activity for specific user.
Added Scenario:
```feature
Scenario: filter synced activities
Scenario: filter not synced activities
```
Related issue:
- https://github.com/owncloud/client/issues/9788

[gui-tests][full-ci] added test to filter activity of specific user

---

src/gui/accountsettings.cpp

Add "debug" logging to help with issue #11673

---

src/gui/accountsettings.ui

[a11y] Make link to server in account settings selectable by keyboard

---

test/gui/shared/scripts/bdd_hooks.py
test/gui/shared/scripts/helpers/api/HttpHelper.py
test/gui/shared/scripts/helpers/api/Provisioning.py
test/gui/shared/scripts/helpers/api/oc10.py
test/gui/shared/scripts/helpers/api/ocis.py
test/gui/shared/scripts/helpers/api/sharing_helper.py
test/gui/shared/steps/server_context.py
test/gui/tst_sharing/test.feature

This `Given` step implementation creates group in the server.
Renamed step:
```diff
-Given group "<group>" has been created on the server
+Given group "<group>" has been created in the server
```

[test-only][full-ci] Given step implementation of creating group in the server

---

src/gui/settingsdialog.cpp
src/gui/spaces/spaceimageprovider.cpp
src/resources/qmlresources.cpp
src/resources/qmlresources.h
src/resources/resources.cpp

Fix null pixmaps

---

changelog/unreleased/11742
src/gui/aboutdialog.cpp
src/libsync/theme.cpp
src/resources/resources.cpp
src/resources/resources.h

Add ocis update channel

---

src/resources/CMakeLists.txt
src/resources/themewatcher.cpp
src/resources/themewatcher.h

Emit a signal for a theme changed event, this will be used with Properties

Implement theme watcher

---

test/gui/shared/scripts/bdd_hooks.py
test/gui/shared/scripts/names.py
test/gui/shared/scripts/pageObjects/Toolbar.py
test/gui/shared/steps/account_context.py
test/gui/tst_syncing/test.feature

Fixes #11837
Skipped test failing due to https://github.com/owncloud/client/issues/11814

[gui-tests][full-ci] fix account locators

---

src/gui/qml/AccountButton.qml

Remove word wrapping from tool button

---

test/gui/shared/scripts/pageObjects/AccountSetting.py

Fixes https://github.com/owncloud/client/issues/11847

[gui-tests][full-ci] fix manage account locators

---

src/gui/folderwizard/spacespage.ui
src/gui/spaces/spacesbrowser.cpp
src/gui/spaces/spacesbrowser.ui

And that the list is also tab-focusable.

Ensure that the Spaces list has focus in the Add Space wizard

---

test/gui/shared/scripts/bdd_hooks.py
test/gui/shared/scripts/helpers/SpaceHelper.py
test/gui/shared/scripts/helpers/UserHelper.py
test/gui/shared/scripts/helpers/api/HttpHelper.py
test/gui/shared/scripts/helpers/api/Provisioning.py
test/gui/shared/scripts/helpers/api/oc10.py
test/gui/shared/scripts/helpers/api/ocis.py
test/gui/shared/scripts/helpers/api/sharing_helper.py
test/gui/shared/steps/server_context.py

- Improved error logging: log error response body
- do not fail hooks if saving screenshot fails

[test-only][full-ci] improve error logging and allow cleanup scripts to run

---

test/gui/requirements.txt

[gui-tests] chore: bump python dependencies

---

.drone.star
test/gui/shared/scripts/helpers/api/ocis.py

This PR runs GUI tests against ocis-rolling release for the master branch
Fixes : https://github.com/owncloud/client/issues/11808

[QA] Run GUI tests against ocis-rolling release for the master branch

---

.github/workflows/main.yml
src/gui/accountsettings.cpp
test/gui/tst_syncing/test.feature

[full-ci] Fix crash when removing an oc10 sync connection

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h
src/gui/accountsettings.ui

Show icon next to the status label in Account Settings page

---

.github/workflows/translate.yml

https://community.transifex.com/t/tx-push-failing/4195/4

fix: add --silent to tx command to get more information .... :shrug:

---

src/gui/accountsettings.ui

Reduce status icon size in Account Settings pages

---

test/gui/shared/scripts/helpers/SetupClientHelper.py
test/gui/shared/scripts/names.py
test/gui/shared/scripts/pageObjects/AccountConnectionWizard.py
test/gui/shared/scripts/pageObjects/AccountSetting.py
test/gui/shared/scripts/pageObjects/Activity.py
test/gui/shared/scripts/pageObjects/EnterPassword.py
test/gui/shared/scripts/pageObjects/Toolbar.py
test/gui/tst_addAccount/test.feature

This PR adjusts the tests as per the new changes in the login wizard.
Fixes https://github.com/owncloud/client/issues/11898

[test-only][full-ci] Adjust GUI tests as per the new changes in login wizard

---

src/gui/qml/credentials/BasicAuthCredentials.qml
src/gui/qml/credentials/Credentials.qml

Fix tab order in basic auth login screen

---

src/gui/qml/credentials/OAuthCredentials.qml

fix: Copy url -> Copy URL

---

test/gui/shared/scripts/helpers/SyncHelper.py

This PR fixes #11927, where all tests are not running in CI

[test-only] Fix CI

---

test/gui/shared/scripts/bdd_hooks.py
test/gui/shared/scripts/helpers/api/http_helper.py
test/gui/shared/scripts/helpers/api/oc10.py
test/gui/shared/scripts/pageObjects/EnterPassword.py
test/gui/shared/steps/sharing_context.py

Fixes https://github.com/owncloud/client/issues/11945

[test-only][full-ci] restore oc10 apps to initial state

---

.github/workflows/main.yml
.github/workflows/stale.yml

to fix ci on prs against 5 like https://github.com/owncloud/client/pull/11955

fix: ci on branch 5

---

src/libsync/capabilities.cpp
src/libsync/capabilities.h
src/libsync/graphapi/space.cpp

feat: add capability support for multiple personal spaces

---

test/gui/shared/scripts/bdd_hooks.py
test/gui/shared/scripts/helpers/ConfigHelper.py
test/gui/shared/scripts/helpers/SetupClientHelper.py
test/gui/shared/steps/account_context.py
test/gui/shared/steps/spaces_context.py
test/gui/tst_addAccount/test.feature
test/gui/tst_syncing/test.feature

The renaming of `Personal` space caused the GUI tests to fail which has been fixed by this PR.
Fixes: #11962

[test-only][full-ci] Fix GUI tests

---

src/gui/CMakeLists.txt
src/gui/aboutdialog.cpp
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/main.cpp
src/gui/updater/appimageupdater.cpp
src/gui/updater/ocupdater.cpp
src/gui/updater/ocupdater.h
src/gui/updater/sparkleupdater.h
src/gui/updater/updater.cpp
src/gui/updater/updater.h

Fix auto update on Windows

---

src/gui/accountsettings.cpp

Note: This has to be tested on Linux and Windows before merging!

Fix "Open in Finder" on mac

---

.github/workflows/main.yml

ci: fix clang tidy

---

src/gui/scheduling/etagwatcher.cpp
src/libsync/abstractnetworkjob.cpp
src/libsync/abstractnetworkjob.h
src/libsync/discoveryphase.cpp

Open question: should we actually assert here? Or only document when the timestamp is missing, and then check all usages?

Remove invalid assert, add documentation, and fix uses

---

src/gui/folderwizard/spacespage.cpp
src/gui/folderwizard/spacespage.ui

There is no need for complex HTML here.

Fix Space/Folder naming

---

src/gui/folder.cpp
src/gui/folderstatusmodel.cpp

fix: XCode 16.3 / clang 17

---

src/gui/folderwizard/folderwizard.cpp

When VFS is forced on, all elements on this page are disabled: the checkbox to turn VFS off is disabled, and the selective sync chooser is also disabled. This can be very confusing to the user, so completely skip this page.
This also prevents a bug in this page from showing: if VFS is forced, the checkbox for disabling VFS is not shown. And when this checkbox is not shown, the selective sync widget is not disabled, allowing to do selective sync with VFS (forced) on.
Fixes: #12135

Skip the selective sync page when VFS is forced

---

src/gui/accountsettings.cpp
src/gui/accountsettings.h

fixes https://kiteworks.atlassian.net/browse/DC-28

[DC-28] fix: menu to pop up on the managed account button

---

changelog/unreleased/11729.md
src/libsync/creds/oauth.cpp
src/libsync/creds/oauth.h

fix: add openid supported prompt value `login` and `create`

---

.drone.star

Support for OC10 has been removed from PR https://github.com/owncloud/client/pull/12167. With this the oc10 pipelines in CI is failing. So, removing the oc10 pipeline from CI.
Failed builds:
- https://drone.owncloud.com/owncloud/client/21206
- https://drone.owncloud.com/owncloud/client/21216

[tests-only][full-ci] remove oc10 pipeline from CI

---

changelog/unreleased/12214.md
src/libsync/account.cpp

Cherry-picked from the master branch

[DC-83] Fix: remove any existing ResourceCache directories for accounts

---

src/gui/accountmanager.cpp
src/gui/accountmanager.h
src/gui/accountsettings.h
src/gui/accountstate.cpp
src/gui/application.cpp
src/gui/application.h
src/gui/connectionvalidator.h
src/gui/folderstatusmodel.cpp
src/gui/owncloudgui.cpp
src/gui/settingsdialog.cpp
test/testconnectionvalidator/testconnectionvalidator.cpp

try to fix some very strange but consistent crashes associated with deleting an account -> auto pop of the account wizard.

fix: strange crashes after deleting account

---

test/gui/shared/scripts/helpers/api/external_api.py
test/gui/shared/scripts/pageObjects/SyncConnection.py
test/gui/shared/steps/file_context.py
test/gui/shared/steps/server_context.py
test/gui/tst_syncing/test.feature

In this PR, tests for syncing is updated for automating branded client.
Related to: https://github.com/owncloud/enterprise/issues/7212

[tests-only][full-ci] update sync related test for automating branded client

---

CMakeLists.txt

(cherry picked from commit bcfc3a7b19beca89d5c3c51b25cd97d1529e0242)

feat: bump minimum macOS version to 13 (#12245)

---

.craft.ini
.craft.shelf

ci: speed-up craft based builds

---

.drone.star

[tests-only][full-ci] remove trigger for branch 5

---

.craft.shelf

unpin dev-utils/icoutils package. this cannot be built in the squish container (as of now)
https://drone.owncloud.com/owncloud-ci/squish/214/1/2

build: unpin dev-utils/icoutils package

---

src/gui/accountmanager.cpp
src/gui/accountmanager.h
src/gui/folder.cpp
src/gui/folder.h
src/gui/folderman.cpp
src/gui/folderman.h
src/gui/generalsettings.cpp
src/gui/selectivesyncwidget.cpp
src/libsync/configfile.cpp
src/libsync/configfile.h

The credentials are done in a separate PR.

[DC-111] Clean up config file keys

---

test/gui/shared/scripts/helpers/SyncHelper.py

fix: GUITests on branch 6

---

test/gui/tst_spaces/test.feature

Backport of PR: https://github.com/owncloud/client/pull/12315

[tests-only][full-ci] Backport add wait for file to sync step

---

test/gui/tst_syncing/test.feature

This PR adds test for syncing file/folder havine European characters.
Test coverage for: https://github.com/owncloud/client/issues/12333

[tests-only][full-ci]add test to sync file/folder having European characters

---

src/gui/socketapi/socketapi.cpp

backport of https://github.com/owncloud/client/pull/12355

[DC-174] fix: SocketAPI cleanup - branch 7.0

---

src/libsync/owncloudpropagator.cpp

backport of https://github.com/owncloud/client/pull/12356 to branch 7.0

[DC-177] fix: sync remotely edited file with NFD chars in name
